# ST#66: Problematic Hadiths Case Study - Part 2 | Sh. Anwar Arafat (2022-09-04)

<iframe loading='lazy' src='https://www.youtube.com/embed/eHsv5BLwGmI'></iframe>

## Description

Problematic Hadiths Case Study - Part 1 | Sh. Anwar Arafat

—
Help us educate and mentor others to share the faith academically.
Donate now: https://sapienceinstitute.org/donate/ 

Free online courses: https://learn.sapienceinstitute.org/

Free books: https://sapienceinstitute.org/books/

Have doubts? Book a mentor: https://sapienceinstitute.org/lighthouse/

Listen (Podcast): https://sapienceinstitute.org/sapientvoices/

Follow:
– Facebook: https://facebook.com/sapienceinstitute.org/ 
– Twitter: https://twitter.com/SapienceOrg/ 
– Instagram: https://instagram.com/sapienceinstitute/ 

Articles, speaker requests & more: https://sapienceinstitute.org/

## Summary of [ST#66: Problematic Hadiths Case Study - Part 2 | Sh. Anwar Arafat](https://www.youtube.com/watch?v=eHsv5BLwGmI)


*<span style="color:red; font-size:125%">This summary is AI generated - there may be inaccuracies</span>. [](/)*

### <a onclick="modifyYTiframeseektime('0')">00:00:00</a> - <a onclick="modifyYTiframeseektime('600')">00:10:00</a>

 Sh. Anwar Arafat discusses how to deal with problematic hadiths. He emphasizes the need for sincerity and patience, noting that these qualities are important in any analysis. He goes on to discuss how these qualities help to avoid bias and ensure that the hadith is taken in context.  provides translations of a problematic hadith into English, Arabic, and Mishkatun, and discusses the different meanings of the phrases.  concludes with a warning that people should be careful when interpreting hadiths, as they may not be accurate.

**<a onclick="modifyYTiframeseektime('0')">00:00:00</a>**  Sh. Anwar Arafat discusses the toolkit for dealing with problematic hadiths. He emphasizes the need for sincerity and patience, noting that these qualities are important in any analysis. He goes on to discuss how these qualities help to avoid bias and ensure that the hadith is taken in context.
* **<a onclick="modifyYTiframeseektime('300')">00:05:00</a>* Discusses a problematic hadith, in which a cautious and sensible man could be led astray by some of the women in the population.  provides translations of the problematic phrase into English, Arabic, and Mishkatun, and discusses the different meanings of the phrases.  concludes with a warning that people should be careful when interpreting hadiths, as they may not be accurate.
* **<a onclick="modifyYTiframeseektime('600')">00:10:00</a>* Discusses a problematic hadith, which states that a woman is more deficient in intellect and religion than a man. He points out that this translation can be misleading because it changes the word "intellect" to "wisdom." This inaccuracy has led to many people misunderstanding the hadith. recommends that people access the original Arabic version to get a more accurate understanding.

<details><summary><h2>Full transcript with timestamps: CLICK TO EXPAND</h2></summary>

<a onclick="modifyYTiframeseektime('14')">0:00:14</a> upon you all  
<a onclick="modifyYTiframeseektime('15')">0:00:15</a> and welcome to sapient thoughts another  
<a onclick="modifyYTiframeseektime('17')">0:00:17</a> episode where here we discuss theo  
<a onclick="modifyYTiframeseektime('20')">0:00:20</a> philosophical issues we answer some of  
<a onclick="modifyYTiframeseektime('21')">0:00:21</a> the contentions that are brought against  
<a onclick="modifyYTiframeseektime('23')">0:00:23</a> islam and we offer  
<a onclick="modifyYTiframeseektime('25')">0:00:25</a> hopefully a robust case for the veracity  
<a onclick="modifyYTiframeseektime('27')">0:00:27</a> and beauty of islam insha'allah as a way  
<a onclick="modifyYTiframeseektime('29')">0:00:29</a> of life my name is anwar arafat and  
<a onclick="modifyYTiframeseektime('32')">0:00:32</a> today we are doing  
<a onclick="modifyYTiframeseektime('34')">0:00:34</a> episode 2 of our case study a  
<a onclick="modifyYTiframeseektime('37')">0:00:37</a> problematic hadith that seems to put  
<a onclick="modifyYTiframeseektime('39')">0:00:39</a> women down or that might seem  
<a onclick="modifyYTiframeseektime('41')">0:00:41</a> disrespectful or demeaning towards women  
<a onclick="modifyYTiframeseektime('43')">0:00:43</a> and a person might read this come across  
<a onclick="modifyYTiframeseektime('46')">0:00:46</a> it in some of the books and say hey wait  
<a onclick="modifyYTiframeseektime('47')">0:00:47</a> a second this is problematic  
<a onclick="modifyYTiframeseektime('50')">0:00:50</a> so how do we deal with this well as we  
<a onclick="modifyYTiframeseektime('52')">0:00:52</a> demonstrated the hadith of course it's a  
<a onclick="modifyYTiframeseektime('54')">0:00:54</a> little longer  
<a onclick="modifyYTiframeseektime('56')">0:00:56</a> if you haven't listened to the hadith  
<a onclick="modifyYTiframeseektime('57')">0:00:57</a> you can go back to that first episode um  
<a onclick="modifyYTiframeseektime('59')">0:00:59</a> in this episode we will apply our hadith  
<a onclick="modifyYTiframeseektime('62')">0:01:02</a> toolkit as we shared it where we we have  
<a onclick="modifyYTiframeseektime('65')">0:01:05</a> 10 tools so for this episode we're going  
<a onclick="modifyYTiframeseektime('67')">0:01:07</a> to go actually through the first five  
<a onclick="modifyYTiframeseektime('70')">0:01:10</a> in applying them to this specific hadith  
<a onclick="modifyYTiframeseektime('73')">0:01:13</a> in sha allah ta'ala  
<a onclick="modifyYTiframeseektime('74')">0:01:14</a> tool number one  
<a onclick="modifyYTiframeseektime('76')">0:01:16</a> is sincerity and remember we said this  
<a onclick="modifyYTiframeseektime('78')">0:01:18</a> is sincerity towards the material  
<a onclick="modifyYTiframeseektime('81')">0:01:21</a> sincerity towards whatever goal it is  
<a onclick="modifyYTiframeseektime('83')">0:01:23</a> sincerity towards your own biases  
<a onclick="modifyYTiframeseektime('86')">0:01:26</a> and obviously as muslims first and  
<a onclick="modifyYTiframeseektime('88')">0:01:28</a> foremost sincerity towards god allah  
<a onclick="modifyYTiframeseektime('90')">0:01:30</a> subhanahu ta'ala  
<a onclick="modifyYTiframeseektime('92')">0:01:32</a> sincerity towards the corpus  
<a onclick="modifyYTiframeseektime('94')">0:01:34</a> means that  
<a onclick="modifyYTiframeseektime('97')">0:01:37</a> when i read a hadith i don't take it by  
<a onclick="modifyYTiframeseektime('100')">0:01:40</a> itself i understand that as part of an  
<a onclick="modifyYTiframeseektime('102')">0:01:42</a> entire corpus a person easily can seize  
<a onclick="modifyYTiframeseektime('105')">0:01:45</a> on one hadith and take it out of context  
<a onclick="modifyYTiframeseektime('109')">0:01:49</a> and show hey look muslims say one two  
<a onclick="modifyYTiframeseektime('111')">0:01:51</a> and three  
<a onclick="modifyYTiframeseektime('112')">0:01:52</a> i can do this to almost any book i can  
<a onclick="modifyYTiframeseektime('114')">0:01:54</a> do this to almost any religion  
<a onclick="modifyYTiframeseektime('115')">0:01:55</a> um not only is it  
<a onclick="modifyYTiframeseektime('118')">0:01:58</a> unwise it's unjust right we're not being  
<a onclick="modifyYTiframeseektime('121')">0:02:01</a> fair to the material not being fair to  
<a onclick="modifyYTiframeseektime('122')">0:02:02</a> anything if i am muslim and i come  
<a onclick="modifyYTiframeseektime('125')">0:02:05</a> across a problematic hadith i have a  
<a onclick="modifyYTiframeseektime('127')">0:02:07</a> bias if i'm not muslim i also have a  
<a onclick="modifyYTiframeseektime('130')">0:02:10</a> bias if i'm an academic  
<a onclick="modifyYTiframeseektime('132')">0:02:12</a> i have a bias there as well what are  
<a onclick="modifyYTiframeseektime('135')">0:02:15</a> some of these biases if i'm muslim and i  
<a onclick="modifyYTiframeseektime('137')">0:02:17</a> read a problematic hadith that seems to  
<a onclick="modifyYTiframeseektime('138')">0:02:18</a> put women down  
<a onclick="modifyYTiframeseektime('140')">0:02:20</a> my sincerity to my paradigm is that wait  
<a onclick="modifyYTiframeseektime('142')">0:02:22</a> a second i know that the prophet sallam  
<a onclick="modifyYTiframeseektime('144')">0:02:24</a> doesn't put women down in fact there are  
<a onclick="modifyYTiframeseektime('145')">0:02:25</a> so many hadith in which he praises women  
<a onclick="modifyYTiframeseektime('148')">0:02:28</a> right he thanks them he's appreciative  
<a onclick="modifyYTiframeseektime('150')">0:02:30</a> he's respecting he's accommodating he's  
<a onclick="modifyYTiframeseektime('152')">0:02:32</a> doing all these things in fact arguably  
<a onclick="modifyYTiframeseektime('154')">0:02:34</a> no one throughout human history has done  
<a onclick="modifyYTiframeseektime('156')">0:02:36</a> more  
<a onclick="modifyYTiframeseektime('157')">0:02:37</a> for women giving them rights etc then  
<a onclick="modifyYTiframeseektime('160')">0:02:40</a> somebody like the prophet saws  
<a onclick="modifyYTiframeseektime('162')">0:02:42</a> especially 1400 years ago when nobody  
<a onclick="modifyYTiframeseektime('164')">0:02:44</a> was doing anything for one whatsoever so  
<a onclick="modifyYTiframeseektime('166')">0:02:46</a> i know that wait a second if i'm reading  
<a onclick="modifyYTiframeseektime('168')">0:02:48</a> this in a way that it could be putting  
<a onclick="modifyYTiframeseektime('170')">0:02:50</a> women down i know this goes against what  
<a onclick="modifyYTiframeseektime('171')">0:02:51</a> i already understand from my paradigm  
<a onclick="modifyYTiframeseektime('174')">0:02:54</a> because i am muslim and i am aware of  
<a onclick="modifyYTiframeseektime('176')">0:02:56</a> all these things  
<a onclick="modifyYTiframeseektime('177')">0:02:57</a> if i am an islamophobe  
<a onclick="modifyYTiframeseektime('179')">0:02:59</a> i already have my bias i'm going to  
<a onclick="modifyYTiframeseektime('180')">0:03:00</a> seize upon something like this and i'm  
<a onclick="modifyYTiframeseektime('183')">0:03:03</a> going to be like hey oh this is more  
<a onclick="modifyYTiframeseektime('184')">0:03:04</a> fuel to my fire but if i'm an academic i  
<a onclick="modifyYTiframeseektime('188')">0:03:08</a> know that i have to take everything  
<a onclick="modifyYTiframeseektime('190')">0:03:10</a> within its context that means i look at  
<a onclick="modifyYTiframeseektime('192')">0:03:12</a> it i analyze it i don't just take  
<a onclick="modifyYTiframeseektime('195')">0:03:15</a> something and run with it without  
<a onclick="modifyYTiframeseektime('196')">0:03:16</a> actually analyzing it correctly this is  
<a onclick="modifyYTiframeseektime('198')">0:03:18</a> why the toolkit is so important for us  
<a onclick="modifyYTiframeseektime('200')">0:03:20</a> and i believe that this toolkit will be  
<a onclick="modifyYTiframeseektime('201')">0:03:21</a> helpful whether you're a muslim or  
<a onclick="modifyYTiframeseektime('203')">0:03:23</a> you're not muslim meaning  
<a onclick="modifyYTiframeseektime('205')">0:03:25</a> how can we actually look at something  
<a onclick="modifyYTiframeseektime('206')">0:03:26</a> like this did the prophet saw salaam  
<a onclick="modifyYTiframeseektime('208')">0:03:28</a> really mean to say that women are less  
<a onclick="modifyYTiframeseektime('211')">0:03:31</a> than men in terms of their religion or  
<a onclick="modifyYTiframeseektime('213')">0:03:33</a> in terms of their intellect  
<a onclick="modifyYTiframeseektime('216')">0:03:36</a> let's analyze this let's test this just  
<a onclick="modifyYTiframeseektime('218')">0:03:38</a> because we have one hadith that seems to  
<a onclick="modifyYTiframeseektime('220')">0:03:40</a> insinuate this is this actually the case  
<a onclick="modifyYTiframeseektime('222')">0:03:42</a> if i'm an academic if i'm actually being  
<a onclick="modifyYTiframeseektime('224')">0:03:44</a> honest this is why sincerity is so  
<a onclick="modifyYTiframeseektime('226')">0:03:46</a> important that it makes us aware of our  
<a onclick="modifyYTiframeseektime('228')">0:03:48</a> own biases and it makes us aware of what  
<a onclick="modifyYTiframeseektime('230')">0:03:50</a> it is that we're actually reading so my  
<a onclick="modifyYTiframeseektime('232')">0:03:52</a> bias as a muslim is that i know that the  
<a onclick="modifyYTiframeseektime('234')">0:03:54</a> prophet sallam respects him so why would  
<a onclick="modifyYTiframeseektime('236')">0:03:56</a> he say this and by the way this bias  
<a onclick="modifyYTiframeseektime('239')">0:03:59</a> informs how we actually read the hadith  
<a onclick="modifyYTiframeseektime('242')">0:04:02</a> and we'll get into it when we do the  
<a onclick="modifyYTiframeseektime('243')">0:04:03</a> reread at the very end we'll go into  
<a onclick="modifyYTiframeseektime('246')">0:04:06</a> why did the prophet say this  
<a onclick="modifyYTiframeseektime('248')">0:04:08</a> what did it mean  
<a onclick="modifyYTiframeseektime('250')">0:04:10</a> and this is why sincerity is very  
<a onclick="modifyYTiframeseektime('252')">0:04:12</a> important so this is applying tool  
<a onclick="modifyYTiframeseektime('254')">0:04:14</a> number one  
<a onclick="modifyYTiframeseektime('256')">0:04:16</a> tool number two  
<a onclick="modifyYTiframeseektime('259')">0:04:19</a> tool number two  
<a onclick="modifyYTiframeseektime('260')">0:04:20</a> is  
<a onclick="modifyYTiframeseektime('261')">0:04:21</a> patience  
<a onclick="modifyYTiframeseektime('264')">0:04:24</a> now what does patience mean here  
<a onclick="modifyYTiframeseektime('268')">0:04:28</a> patience of course is in contrast to i  
<a onclick="modifyYTiframeseektime('270')">0:04:30</a> want an answer now we want everything  
<a onclick="modifyYTiframeseektime('273')">0:04:33</a> instantaneous  
<a onclick="modifyYTiframeseektime('275')">0:04:35</a> um i read it  
<a onclick="modifyYTiframeseektime('277')">0:04:37</a> and i want to run with it  
<a onclick="modifyYTiframeseektime('279')">0:04:39</a> a lot of times people will come and  
<a onclick="modifyYTiframeseektime('280')">0:04:40</a> they'll say  
<a onclick="modifyYTiframeseektime('283')">0:04:43</a> what does islam say about women  
<a onclick="modifyYTiframeseektime('286')">0:04:46</a> okay what does islam say about women are  
<a onclick="modifyYTiframeseektime('289')">0:04:49</a> deficient in their intellect and  
<a onclick="modifyYTiframeseektime('291')">0:04:51</a> and  
<a onclick="modifyYTiframeseektime('292')">0:04:52</a> religion  
<a onclick="modifyYTiframeseektime('294')">0:04:54</a> the thing is this is an incorrect  
<a onclick="modifyYTiframeseektime('295')">0:04:55</a> question  
<a onclick="modifyYTiframeseektime('296')">0:04:56</a> what does islam say  
<a onclick="modifyYTiframeseektime('300')">0:05:00</a> is  
<a onclick="modifyYTiframeseektime('301')">0:05:01</a> a problematic question we can look at  
<a onclick="modifyYTiframeseektime('303')">0:05:03</a> what does the quran say what does the  
<a onclick="modifyYTiframeseektime('305')">0:05:05</a> hadith say what do some scholars say but  
<a onclick="modifyYTiframeseektime('308')">0:05:08</a> islam has a huge concept is such a big  
<a onclick="modifyYTiframeseektime('311')">0:05:11</a> thing that islam  
<a onclick="modifyYTiframeseektime('313')">0:05:13</a> is represented through a lot of these  
<a onclick="modifyYTiframeseektime('316')">0:05:16</a> different avenues but there's  
<a onclick="modifyYTiframeseektime('319')">0:05:19</a> it's not that there's one there's not  
<a onclick="modifyYTiframeseektime('320')">0:05:20</a> one islam  
<a onclick="modifyYTiframeseektime('322')">0:05:22</a> but that the question itself is  
<a onclick="modifyYTiframeseektime('324')">0:05:24</a> inherently wrong this is how for example  
<a onclick="modifyYTiframeseektime('326')">0:05:26</a> the khawarij  
<a onclick="modifyYTiframeseektime('328')">0:05:28</a> the kharajits when they came to alibi  
<a onclick="modifyYTiframeseektime('332')">0:05:32</a> and they said we want the quran to rule  
<a onclick="modifyYTiframeseektime('335')">0:05:35</a> between us  
<a onclick="modifyYTiframeseektime('337')">0:05:37</a> right and so he brought or i think in  
<a onclick="modifyYTiframeseektime('339')">0:05:39</a> this generation it was  
<a onclick="modifyYTiframeseektime('341')">0:05:41</a> he brings a mushaf and he puts it in  
<a onclick="modifyYTiframeseektime('343')">0:05:43</a> between them and he says quran rule  
<a onclick="modifyYTiframeseektime('346')">0:05:46</a> between us  
<a onclick="modifyYTiframeseektime('348')">0:05:48</a> and everybody looks at him like he's  
<a onclick="modifyYTiframeseektime('349')">0:05:49</a> crazy  
<a onclick="modifyYTiframeseektime('350')">0:05:50</a> what they said this is a book it doesn't  
<a onclick="modifyYTiframeseektime('352')">0:05:52</a> speak he said that's what you asked  
<a onclick="modifyYTiframeseektime('354')">0:05:54</a> though  
<a onclick="modifyYTiframeseektime('356')">0:05:56</a> you asked for the quran to rule but the  
<a onclick="modifyYTiframeseektime('358')">0:05:58</a> thing is the quran is always read  
<a onclick="modifyYTiframeseektime('361')">0:06:01</a> through a human being meaning there's an  
<a onclick="modifyYTiframeseektime('362')">0:06:02</a> interpretation happening always  
<a onclick="modifyYTiframeseektime('365')">0:06:05</a> right whether we like it or not now i  
<a onclick="modifyYTiframeseektime('366')">0:06:06</a> can interpret it according to what i  
<a onclick="modifyYTiframeseektime('368')">0:06:08</a> know the prophet saws said i know what  
<a onclick="modifyYTiframeseektime('369')">0:06:09</a> some of the companions said etc which is  
<a onclick="modifyYTiframeseektime('371')">0:06:11</a> what we do all the time  
<a onclick="modifyYTiframeseektime('373')">0:06:13</a> but we're reading it through an  
<a onclick="modifyYTiframeseektime('374')">0:06:14</a> interpretation i saw something wonderful  
<a onclick="modifyYTiframeseektime('377')">0:06:17</a> where there was a lady who came to a  
<a onclick="modifyYTiframeseektime('378')">0:06:18</a> scholar  
<a onclick="modifyYTiframeseektime('380')">0:06:20</a> and she said what is the what is the  
<a onclick="modifyYTiframeseektime('382')">0:06:22</a> ruling in my case i think it was an  
<a onclick="modifyYTiframeseektime('383')">0:06:23</a> issue of divorce  
<a onclick="modifyYTiframeseektime('385')">0:06:25</a> right on a certain ayah  
<a onclick="modifyYTiframeseektime('388')">0:06:28</a> and so the scholar told her well i can  
<a onclick="modifyYTiframeseektime('390')">0:06:30</a> tell you what  
<a onclick="modifyYTiframeseektime('392')">0:06:32</a> allah says or i can tell you what the  
<a onclick="modifyYTiframeseektime('393')">0:06:33</a> quran and sunnah says  
<a onclick="modifyYTiframeseektime('396')">0:06:36</a> she says no tell me what is says and the  
<a onclick="modifyYTiframeseektime('399')">0:06:39</a> man got upset he's like what i am  
<a onclick="modifyYTiframeseektime('401')">0:06:41</a> telling you that i have the quran and  
<a onclick="modifyYTiframeseektime('403')">0:06:43</a> sunnah and you're telling me shafer she  
<a onclick="modifyYTiframeseektime('405')">0:06:45</a> says no  
<a onclick="modifyYTiframeseektime('406')">0:06:46</a> what you're going to tell me is your  
<a onclick="modifyYTiframeseektime('408')">0:06:48</a> interpretation of the quran and sunnah  
<a onclick="modifyYTiframeseektime('410')">0:06:50</a> and when you quote michelle it's his  
<a onclick="modifyYTiframeseektime('412')">0:06:52</a> interpretation of the quran and sunnah  
<a onclick="modifyYTiframeseektime('414')">0:06:54</a> both of you guys are interpreting  
<a onclick="modifyYTiframeseektime('416')">0:06:56</a> as he says i trust his interpretation  
<a onclick="modifyYTiframeseektime('418')">0:06:58</a> over yours  
<a onclick="modifyYTiframeseektime('420')">0:07:00</a> he's a big imam i don't know who you are  
<a onclick="modifyYTiframeseektime('422')">0:07:02</a> basically she's saying  
<a onclick="modifyYTiframeseektime('423')">0:07:03</a> and that's interesting thing because we  
<a onclick="modifyYTiframeseektime('425')">0:07:05</a> have to realize that it's always taken  
<a onclick="modifyYTiframeseektime('426')">0:07:06</a> through that lens so we have to have  
<a onclick="modifyYTiframeseektime('427')">0:07:07</a> patience when it comes to we want  
<a onclick="modifyYTiframeseektime('429')">0:07:09</a> instantaneous answers we want to know  
<a onclick="modifyYTiframeseektime('431')">0:07:11</a> what does islam say about women that's a  
<a onclick="modifyYTiframeseektime('433')">0:07:13</a> big question  
<a onclick="modifyYTiframeseektime('434')">0:07:14</a> right let's look at what are some of the  
<a onclick="modifyYTiframeseektime('436')">0:07:16</a> verses say what are some of the how do  
<a onclick="modifyYTiframeseektime('437')">0:07:17</a> you say what do some of the scholars say  
<a onclick="modifyYTiframeseektime('438')">0:07:18</a> etc so patience when applying this  
<a onclick="modifyYTiframeseektime('440')">0:07:20</a> toolkit we can't automatically just  
<a onclick="modifyYTiframeseektime('443')">0:07:23</a> write off something because we don't  
<a onclick="modifyYTiframeseektime('445')">0:07:25</a> like it or don't agree with it from the  
<a onclick="modifyYTiframeseektime('447')">0:07:27</a> outset there might be something going on  
<a onclick="modifyYTiframeseektime('449')">0:07:29</a> and in fact in this case there is  
<a onclick="modifyYTiframeseektime('450')">0:07:30</a> something else going on  
<a onclick="modifyYTiframeseektime('452')">0:07:32</a> so that's tool number two  
<a onclick="modifyYTiframeseektime('454')">0:07:34</a> tool number three is to talk to someone  
<a onclick="modifyYTiframeseektime('457')">0:07:37</a> of knowledge  
<a onclick="modifyYTiframeseektime('458')">0:07:38</a> and in this case i would encourage  
<a onclick="modifyYTiframeseektime('460')">0:07:40</a> anybody if you come across a problematic  
<a onclick="modifyYTiframeseektime('462')">0:07:42</a> hadith one of the best ways to overcome  
<a onclick="modifyYTiframeseektime('464')">0:07:44</a> it is to ask somebody of knowledge and  
<a onclick="modifyYTiframeseektime('466')">0:07:46</a> in this case we did we consulted many  
<a onclick="modifyYTiframeseektime('467')">0:07:47</a> scholars they offered their  
<a onclick="modifyYTiframeseektime('468')">0:07:48</a> interpretations and their takes which  
<a onclick="modifyYTiframeseektime('470')">0:07:50</a> was great and we'll share them inshallah  
<a onclick="modifyYTiframeseektime('472')">0:07:52</a> at the end  
<a onclick="modifyYTiframeseektime('473')">0:07:53</a> of this whole scenario so we already did  
<a onclick="modifyYTiframeseektime('475')">0:07:55</a> that but we don't want to get ahead of  
<a onclick="modifyYTiframeseektime('476')">0:07:56</a> the gun here tool number four knowledge  
<a onclick="modifyYTiframeseektime('479')">0:07:59</a> of arabic  
<a onclick="modifyYTiframeseektime('481')">0:08:01</a> we said knowledge of the prophetic  
<a onclick="modifyYTiframeseektime('483')">0:08:03</a> language in this case it would save the  
<a onclick="modifyYTiframeseektime('485')">0:08:05</a> person so much headache because as i  
<a onclick="modifyYTiframeseektime('487')">0:08:07</a> said the translation is outright  
<a onclick="modifyYTiframeseektime('489')">0:08:09</a> incorrect so let's pause and go back to  
<a onclick="modifyYTiframeseektime('492')">0:08:12</a> the translation inshaallah  
<a onclick="modifyYTiframeseektime('494')">0:08:14</a> the translation of the problematic so  
<a onclick="modifyYTiframeseektime('496')">0:08:16</a> we're only going to go over the  
<a onclick="modifyYTiframeseektime('497')">0:08:17</a> problematic or one of the problematic  
<a onclick="modifyYTiframeseektime('499')">0:08:19</a> um phrases is where he says  
<a onclick="modifyYTiframeseektime('503')">0:08:23</a> in arabic  
<a onclick="modifyYTiframeseektime('512')">0:08:32</a> now it was incorrectly translated as i  
<a onclick="modifyYTiframeseektime('515')">0:08:35</a> have not seen anyone more deficient in  
<a onclick="modifyYTiframeseektime('516')">0:08:36</a> intelligence i'm sorry i have not seen  
<a onclick="modifyYTiframeseektime('518')">0:08:38</a> anyone more deficient in intelligence  
<a onclick="modifyYTiframeseektime('521')">0:08:41</a> and religion than you  
<a onclick="modifyYTiframeseektime('523')">0:08:43</a> so this is sentence number one and then  
<a onclick="modifyYTiframeseektime('525')">0:08:45</a> sentence number two he says a cautious  
<a onclick="modifyYTiframeseektime('526')">0:08:46</a> sensible man could be led astray by some  
<a onclick="modifyYTiframeseektime('528')">0:08:48</a> of you now it's right off the bat in  
<a onclick="modifyYTiframeseektime('531')">0:08:51</a> arabic it was one complete sentence and  
<a onclick="modifyYTiframeseektime('533')">0:08:53</a> in english they translated it into two  
<a onclick="modifyYTiframeseektime('535')">0:08:55</a> which caused a big problem  
<a onclick="modifyYTiframeseektime('537')">0:08:57</a> meaning it's as a statement and not as a  
<a onclick="modifyYTiframeseektime('539')">0:08:59</a> thing let's look at another translation  
<a onclick="modifyYTiframeseektime('541')">0:09:01</a> this is the translation of mishkatun  
<a onclick="modifyYTiframeseektime('543')">0:09:03</a> that appears for us in the english  
<a onclick="modifyYTiframeseektime('546')">0:09:06</a> translation and what did he  
<a onclick="modifyYTiframeseektime('548')">0:09:08</a> that same phrase how was it translated  
<a onclick="modifyYTiframeseektime('550')">0:09:10</a> here  
<a onclick="modifyYTiframeseektime('551')">0:09:11</a> he said  
<a onclick="modifyYTiframeseektime('552')">0:09:12</a> so look at how different the translation  
<a onclick="modifyYTiframeseektime('554')">0:09:14</a> is among women who are deficient in  
<a onclick="modifyYTiframeseektime('557')">0:09:17</a> intelligence and religion i have not  
<a onclick="modifyYTiframeseektime('560')">0:09:20</a> seen anyone more able to remove the  
<a onclick="modifyYTiframeseektime('561')">0:09:21</a> understanding of a prude man than one of  
<a onclick="modifyYTiframeseektime('564')">0:09:24</a> you  
<a onclick="modifyYTiframeseektime('565')">0:09:25</a> this is a completely different meaning  
<a onclick="modifyYTiframeseektime('568')">0:09:28</a> okay let me repeat this again he says  
<a onclick="modifyYTiframeseektime('570')">0:09:30</a> among women who are deficient in  
<a onclick="modifyYTiframeseektime('573')">0:09:33</a> intelligence and religion i have not  
<a onclick="modifyYTiframeseektime('574')">0:09:34</a> seen anyone more able to remove the  
<a onclick="modifyYTiframeseektime('577')">0:09:37</a> understanding of a prudent man than one  
<a onclick="modifyYTiframeseektime('579')">0:09:39</a> of you  
<a onclick="modifyYTiframeseektime('580')">0:09:40</a> meaning this is sarcasm  
<a onclick="modifyYTiframeseektime('582')">0:09:42</a> here he's being sarcastic in that other  
<a onclick="modifyYTiframeseektime('585')">0:09:45</a> translation he's stating facts  
<a onclick="modifyYTiframeseektime('588')">0:09:48</a> huge difference between sarcasm and  
<a onclick="modifyYTiframeseektime('591')">0:09:51</a> facts and by the way a person might ask  
<a onclick="modifyYTiframeseektime('592')">0:09:52</a> wait was the prophet ever like um  
<a onclick="modifyYTiframeseektime('596')">0:09:56</a> sarcastic or ever he was mentioning it  
<a onclick="modifyYTiframeseektime('598')">0:09:58</a> here trying to highlight the irony  
<a onclick="modifyYTiframeseektime('602')">0:10:02</a> that despite women being deficient  
<a onclick="modifyYTiframeseektime('605')">0:10:05</a> supposedly being deficient in their  
<a onclick="modifyYTiframeseektime('607')">0:10:07</a> intellect and in the religion they can  
<a onclick="modifyYTiframeseektime('609')">0:10:09</a> lead  
<a onclick="modifyYTiframeseektime('610')">0:10:10</a> a wise and intelligent man astray  
<a onclick="modifyYTiframeseektime('615')">0:10:15</a> so he's saying maybe they're not so  
<a onclick="modifyYTiframeseektime('617')">0:10:17</a> deficient if they can lead somebody  
<a onclick="modifyYTiframeseektime('619')">0:10:19</a> who's  
<a onclick="modifyYTiframeseektime('619')">0:10:19</a> more intelligent than them how can they  
<a onclick="modifyYTiframeseektime('622')">0:10:22</a> lead them astray  
<a onclick="modifyYTiframeseektime('624')">0:10:24</a> so that's that's uh something that will  
<a onclick="modifyYTiframeseektime('626')">0:10:26</a> give light inshallah to what is actually  
<a onclick="modifyYTiframeseektime('628')">0:10:28</a> going on here's another translation this  
<a onclick="modifyYTiframeseektime('630')">0:10:30</a> translation i thought this is the  
<a onclick="modifyYTiframeseektime('631')">0:10:31</a> translation of sunan of numaja  
<a onclick="modifyYTiframeseektime('635')">0:10:35</a> and this is narrated by  
<a onclick="modifyYTiframeseektime('637')">0:10:37</a> omar but the same thing it doesn't  
<a onclick="modifyYTiframeseektime('638')">0:10:38</a> mention the first part about the khutba  
<a onclick="modifyYTiframeseektime('640')">0:10:40</a> but it just talks about how he comes to  
<a onclick="modifyYTiframeseektime('643')">0:10:43</a> the women  
<a onclick="modifyYTiframeseektime('644')">0:10:44</a> and then he tells him this is what he  
<a onclick="modifyYTiframeseektime('646')">0:10:46</a> says i have never seen anyone  
<a onclick="modifyYTiframeseektime('649')">0:10:49</a> lacking in discernment and religion more  
<a onclick="modifyYTiframeseektime('651')">0:10:51</a> overwhelming to a man of wisdom than you  
<a onclick="modifyYTiframeseektime('655')">0:10:55</a> very simple straightforward this is the  
<a onclick="modifyYTiframeseektime('656')">0:10:56</a> translation of the same now in arabic  
<a onclick="modifyYTiframeseektime('658')">0:10:58</a> they're all the same  
<a onclick="modifyYTiframeseektime('660')">0:11:00</a> men  
<a onclick="modifyYTiframeseektime('663')">0:11:03</a> very good  
<a onclick="modifyYTiframeseektime('664')">0:11:04</a> so here they translated it as  
<a onclick="modifyYTiframeseektime('667')">0:11:07</a> i have never seen anyone  
<a onclick="modifyYTiframeseektime('669')">0:11:09</a> lacking in discernment instead of  
<a onclick="modifyYTiframeseektime('671')">0:11:11</a> intellect he uses the word discernment  
<a onclick="modifyYTiframeseektime('673')">0:11:13</a> here and religion more overwhelming to a  
<a onclick="modifyYTiframeseektime('675')">0:11:15</a> man of wisdom than you  
<a onclick="modifyYTiframeseektime('678')">0:11:18</a> meaning you're able to over overwhelm a  
<a onclick="modifyYTiframeseektime('680')">0:11:20</a> wise man despite  
<a onclick="modifyYTiframeseektime('683')">0:11:23</a> that deficiency obviously he's saying  
<a onclick="modifyYTiframeseektime('685')">0:11:25</a> that it's technically or in reality it's  
<a onclick="modifyYTiframeseektime('687')">0:11:27</a> not a deficiency even though technically  
<a onclick="modifyYTiframeseektime('690')">0:11:30</a> there is a deficiency and we'll talk  
<a onclick="modifyYTiframeseektime('691')">0:11:31</a> about what it means actually by this so  
<a onclick="modifyYTiframeseektime('693')">0:11:33</a> as you can see translation makes a huge  
<a onclick="modifyYTiframeseektime('695')">0:11:35</a> difference and in some of these like i  
<a onclick="modifyYTiframeseektime('697')">0:11:37</a> said the one of  
<a onclick="modifyYTiframeseektime('699')">0:11:39</a> unfortunately is completely wrong in  
<a onclick="modifyYTiframeseektime('702')">0:11:42</a> some of the other versions like we said  
<a onclick="modifyYTiframeseektime('705')">0:11:45</a> um  
<a onclick="modifyYTiframeseektime('706')">0:11:46</a> is okay  
<a onclick="modifyYTiframeseektime('708')">0:11:48</a> the translation the typical one that's  
<a onclick="modifyYTiframeseektime('709')">0:11:49</a> given  
<a onclick="modifyYTiframeseektime('710')">0:11:50</a> he says  
<a onclick="modifyYTiframeseektime('711')">0:11:51</a> in spite of your lacking in wisdom and  
<a onclick="modifyYTiframeseektime('714')">0:11:54</a> failing in religion you are depriving  
<a onclick="modifyYTiframeseektime('716')">0:11:56</a> the wisest of men of their intelligence  
<a onclick="modifyYTiframeseektime('720')">0:12:00</a> okay so again irony it says in spite of  
<a onclick="modifyYTiframeseektime('723')">0:12:03</a> your lacking in wisdom and failing in  
<a onclick="modifyYTiframeseektime('725')">0:12:05</a> religion now failing and religion is  
<a onclick="modifyYTiframeseektime('726')">0:12:06</a> completely wrong it doesn't use that  
<a onclick="modifyYTiframeseektime('728')">0:12:08</a> word you are depriving the wisest of men  
<a onclick="modifyYTiframeseektime('730')">0:12:10</a> of their intelligence okay  
<a onclick="modifyYTiframeseektime('732')">0:12:12</a> translation matters  
<a onclick="modifyYTiframeseektime('734')">0:12:14</a> and unfortunately the translations are  
<a onclick="modifyYTiframeseektime('736')">0:12:16</a> out there are not perfect these are  
<a onclick="modifyYTiframeseektime('737')">0:12:17</a> human endeavors  
<a onclick="modifyYTiframeseektime('738')">0:12:18</a> sometimes they get it right often they  
<a onclick="modifyYTiframeseektime('740')">0:12:20</a> get it wrong  
<a onclick="modifyYTiframeseektime('742')">0:12:22</a> in this case that  
<a onclick="modifyYTiframeseektime('744')">0:12:24</a> mistake  
<a onclick="modifyYTiframeseektime('745')">0:12:25</a> has led a lot of people to have issues  
<a onclick="modifyYTiframeseektime('748')">0:12:28</a> with this and i completely understand  
<a onclick="modifyYTiframeseektime('749')">0:12:29</a> that and in fact i'm sympathetic and  
<a onclick="modifyYTiframeseektime('750')">0:12:30</a> empathetic towards that  
<a onclick="modifyYTiframeseektime('752')">0:12:32</a> um  
<a onclick="modifyYTiframeseektime('753')">0:12:33</a> and this is why  
<a onclick="modifyYTiframeseektime('755')">0:12:35</a> tool number four when you can access the  
<a onclick="modifyYTiframeseektime('758')">0:12:38</a> original arabic it solves so many  
<a onclick="modifyYTiframeseektime('760')">0:12:40</a> problems you're not reading it through  
<a onclick="modifyYTiframeseektime('761')">0:12:41</a> someone else's translation someone  
<a onclick="modifyYTiframeseektime('762')">0:12:42</a> else's take on the hadith you're reading  
<a onclick="modifyYTiframeseektime('764')">0:12:44</a> it through  
<a onclick="modifyYTiframeseektime('765')">0:12:45</a> what did the prophet saw actually say  
<a onclick="modifyYTiframeseektime('767')">0:12:47</a> this is why it's so important for us to  
<a onclick="modifyYTiframeseektime('769')">0:12:49</a> to kind of realize this inshallah ta'ala  
<a onclick="modifyYTiframeseektime('771')">0:12:51</a> will stop here  
<a onclick="modifyYTiframeseektime('773')">0:12:53</a> and we will go to the  
<a onclick="modifyYTiframeseektime('776')">0:12:56</a> next tools inshallah in the next video  
<a onclick="modifyYTiframeseektime('778')">0:12:58</a> we'll see you guys then assalamualaikum  
</details>