# ST#62: Divine Perfection - The Adamic Conundrum with Dr. Osman Latiff (2022-06-24)

<iframe loading='lazy' src='https://www.youtube.com/embed/3wPFspSeMX0'></iframe>

## Description

ST#62: Divine Perfection - The Adamic Conundrum with Dr. Osman Latiff
—
Help us educate and mentor others to share the faith academically.
Donate now: https://sapienceinstitute.org/donate/ 

Free online courses: https://learn.sapienceinstitute.org/

Free books: https://sapienceinstitute.org/books/

Have doubts? Book a mentor: https://sapienceinstitute.org/lighthouse/

Listen (Podcast): https://sapienceinstitute.org/sapientvoices/

Follow:
– Facebook: https://facebook.com/sapienceinstitute.org/ 
– Twitter: https://twitter.com/SapienceOrg/ 
– Instagram: https://instagram.com/sapienceinstitute/ 

Articles, speaker requests & more: https://sapienceinstitute.org/

## Summary of [ST#62: Divine Perfection - The Adamic Conundrum with Dr. Osman Latiff](https://www.youtube.com/watch?v=3wPFspSeMX0)


*<span style="color:red; font-size:125%">This summary is AI generated - there may be inaccuracies</span>. [](/)*

### <a onclick="modifyYTiframeseektime('0')">00:00:00</a> - <a onclick="modifyYTiframeseektime('900')">00:15:00</a>

 Dr. Osman Latiff discusses the Islamic concept of salvation and how it differs from the Christian perspective. He explains that in Islam, salvation is only found through God himself. The adamic model of salvation is illustrated with a story of three individuals who stayed behind at the battle of Tabuk and were punished by God for their disobedience.

**<a onclick="modifyYTiframeseektime('0')">00:00:00</a>**  Dr. Osman Latiff discusses the Adamic Conundrum, which is the concept that there is a difference between the Islamic and Christian conceptions of salvation. Craig argues that islam does not have a concept of sin, and therefore there is no need for a savior. He also makes the argument that because islam does not have a doctrine of atonement, god's anger cannot be appeased and humanity cannot be forgiven. Latiff disagrees with Craig on both points, and explains that the Islamic view of salvation is different than the Christian view because it takes into account the pre-existing warning Adam was given about the devil.
* **<a onclick="modifyYTiframeseektime('300')">00:05:00</a>* Discusses the biblical and Quranic concept of "Adam" and "the devil."  highlights how Adam and Eve were tempted by the devil, and how this caused them to sin.  also discusses how Adam and Eve were removed from the Garden of Eden and how this caused them to sin further.  concludes by emphasizing the importance of following God's commandments to avoid deviations from our path.
* **<a onclick="modifyYTiframeseektime('600')">00:10:00</a>**  Dr. Osman Latiff discusses the difference between the Christian narrative and the Islamic narrative of the Garden of Eden. He points out that both narratives involve God intervening on behalf of Adam, but the Islamic narrative emphasizes the role of God in guiding and inspiring Adam. He finishes the video by discussing the archetype of Adam and how it can be applied to our own lives.
* **<a onclick="modifyYTiframeseektime('900')">00:15:00</a>**  Dr. Osman Latiff discusses the quranic concept of salvation and how it differs from the Christian perspective. He explains that in Islam, salvation is only found through God himself. The adamic model of salvation is illustrated with a story of three individuals who stayed behind at the battle of Tabuk and were punished by God for their disobedience.

<details><summary><h2>Full transcript with timestamps: CLICK TO EXPAND</h2></summary>

<a onclick="modifyYTiframeseektime('6')">0:00:06</a> assalamualaikum welcome to sapient  
<a onclick="modifyYTiframeseektime('8')">0:00:08</a> thoughts it's dr humanity from going  
<a onclick="modifyYTiframeseektime('9')">0:00:09</a> through my book divine perfection  
<a onclick="modifyYTiframeseektime('11')">0:00:11</a> christianity and islam on sin and  
<a onclick="modifyYTiframeseektime('12')">0:00:12</a> salvation published this year by  
<a onclick="modifyYTiframeseektime('13')">0:00:13</a> sapience institute we have of course  
<a onclick="modifyYTiframeseektime('15')">0:00:15</a> unpacked quite a bit already about  
<a onclick="modifyYTiframeseektime('17')">0:00:17</a> arguments presented by our christian  
<a onclick="modifyYTiframeseektime('19')">0:00:19</a> friends detractors william lane craig  
<a onclick="modifyYTiframeseektime('22')">0:00:22</a> and others before and after him who make  
<a onclick="modifyYTiframeseektime('24')">0:00:24</a> these arguments about islamic theism in  
<a onclick="modifyYTiframeseektime('27')">0:00:27</a> fact craig makes three primary arguments  
<a onclick="modifyYTiframeseektime('30')">0:00:30</a> about allah being not maximally  
<a onclick="modifyYTiframeseektime('32')">0:00:32</a> omniscient therefore making a mistake in  
<a onclick="modifyYTiframeseektime('34')">0:00:34</a> the trinity in the quranic outlook we've  
<a onclick="modifyYTiframeseektime('37')">0:00:37</a> been through that very very cohesively  
<a onclick="modifyYTiframeseektime('40')">0:00:40</a> and  
<a onclick="modifyYTiframeseektime('40')">0:00:40</a> and thoroughly now of course the second  
<a onclick="modifyYTiframeseektime('43')">0:00:43</a> argument perhaps is the most is the most  
<a onclick="modifyYTiframeseektime('45')">0:00:45</a> important of all the arguments that  
<a onclick="modifyYTiframeseektime('46')">0:00:46</a> craig makes  
<a onclick="modifyYTiframeseektime('48')">0:00:48</a> and in fact the biggest one between us  
<a onclick="modifyYTiframeseektime('50')">0:00:50</a> and our christian friends james langford  
<a onclick="modifyYTiframeseektime('52')">0:00:52</a> in his very seminal thesis about some  
<a onclick="modifyYTiframeseektime('56')">0:00:56</a> you know ideas about christian mission  
<a onclick="modifyYTiframeseektime('57')">0:00:57</a> to muslims says that muslims have no  
<a onclick="modifyYTiframeseektime('61')">0:01:01</a> doctrine of sin  
<a onclick="modifyYTiframeseektime('62')">0:01:02</a> that he says that there is no concept of  
<a onclick="modifyYTiframeseektime('64')">0:01:04</a> an estrangement between god and humanity  
<a onclick="modifyYTiframeseektime('67')">0:01:07</a> in islam and therefore there's no need  
<a onclick="modifyYTiframeseektime('69')">0:01:09</a> for reconciliation between god and man  
<a onclick="modifyYTiframeseektime('71')">0:01:11</a> therefore no need for a savior he's not  
<a onclick="modifyYTiframeseektime('73')">0:01:13</a> the first in fact to make that argument  
<a onclick="modifyYTiframeseektime('74')">0:01:14</a> see our marsh in his work says that you  
<a onclick="modifyYTiframeseektime('77')">0:01:17</a> know only and if ever the muslims see  
<a onclick="modifyYTiframeseektime('80')">0:01:20</a> themselves as inherently sinful in the  
<a onclick="modifyYTiframeseektime('83')">0:01:23</a> eyes of god will they ever see the need  
<a onclick="modifyYTiframeseektime('85')">0:01:25</a> for a savior now the the fundamental  
<a onclick="modifyYTiframeseektime('88')">0:01:28</a> thing here is that they're both arguing  
<a onclick="modifyYTiframeseektime('89')">0:01:29</a> similar things about does islam have a  
<a onclick="modifyYTiframeseektime('92')">0:01:32</a> concept of sin what is sin in islam does  
<a onclick="modifyYTiframeseektime('95')">0:01:35</a> sin create the sense of a distance or a  
<a onclick="modifyYTiframeseektime('97')">0:01:37</a> strange assumption between us and god  
<a onclick="modifyYTiframeseektime('100')">0:01:40</a> and is there a need at the end of the  
<a onclick="modifyYTiframeseektime('101')">0:01:41</a> day for a savior now craig of course  
<a onclick="modifyYTiframeseektime('104')">0:01:44</a> makes that same argument they all make  
<a onclick="modifyYTiframeseektime('106')">0:01:46</a> the same argument there is nothing new  
<a onclick="modifyYTiframeseektime('108')">0:01:48</a> it's all the same things that they're  
<a onclick="modifyYTiframeseektime('110')">0:01:50</a> saying  
<a onclick="modifyYTiframeseektime('111')">0:01:51</a> now craig's second argument that he  
<a onclick="modifyYTiframeseektime('112')">0:01:52</a> makes in his website reasonable faith  
<a onclick="modifyYTiframeseektime('114')">0:01:54</a> and his videos and in his debates is the  
<a onclick="modifyYTiframeseektime('116')">0:01:56</a> same one about the fact that the  
<a onclick="modifyYTiframeseektime('119')">0:01:59</a> doctrine of salvation what we call  
<a onclick="modifyYTiframeseektime('121')">0:02:01</a> soteriology in islam is not sufficient  
<a onclick="modifyYTiframeseektime('124')">0:02:04</a> in representing god's maximal holiness  
<a onclick="modifyYTiframeseektime('127')">0:02:07</a> whereas in christianity through that  
<a onclick="modifyYTiframeseektime('130')">0:02:10</a> price paid uh from jesus christ on the  
<a onclick="modifyYTiframeseektime('133')">0:02:13</a> cross that's enough enough and  
<a onclick="modifyYTiframeseektime('135')">0:02:15</a> sufficient for god's wrath to be  
<a onclick="modifyYTiframeseektime('137')">0:02:17</a> appeased and therefore god forgives  
<a onclick="modifyYTiframeseektime('139')">0:02:19</a> humanity and therefore god loves  
<a onclick="modifyYTiframeseektime('141')">0:02:21</a> humanity and so on and so forth now of  
<a onclick="modifyYTiframeseektime('142')">0:02:22</a> course in the last episode we went  
<a onclick="modifyYTiframeseektime('144')">0:02:24</a> through christian atonement theories and  
<a onclick="modifyYTiframeseektime('146')">0:02:26</a> as you remember herring there were many  
<a onclick="modifyYTiframeseektime('148')">0:02:28</a> many of them there was of course that  
<a onclick="modifyYTiframeseektime('150')">0:02:30</a> that primal one of of augustine and the  
<a onclick="modifyYTiframeseektime('154')">0:02:34</a> devil ransom theory christus victor  
<a onclick="modifyYTiframeseektime('156')">0:02:36</a> theory uranuses theories uh origins  
<a onclick="modifyYTiframeseektime('159')">0:02:39</a> theories there was the  
<a onclick="modifyYTiframeseektime('160')">0:02:40</a> uh athanasius's mystical theory there  
<a onclick="modifyYTiframeseektime('163')">0:02:43</a> was uh anselm's satisfaction theory the  
<a onclick="modifyYTiframeseektime('166')">0:02:46</a> one before that of gregory evnessa and  
<a onclick="modifyYTiframeseektime('168')">0:02:48</a> the fish hook theory the one much after  
<a onclick="modifyYTiframeseektime('170')">0:02:50</a> that of calvin and penal substitution  
<a onclick="modifyYTiframeseektime('171')">0:02:51</a> theory and all these theories were in  
<a onclick="modifyYTiframeseektime('173')">0:02:53</a> attempt by christian theologians some of  
<a onclick="modifyYTiframeseektime('175')">0:02:55</a> them church fathers to make sense of  
<a onclick="modifyYTiframeseektime('178')">0:02:58</a> what happened between god and humanity  
<a onclick="modifyYTiframeseektime('181')">0:03:01</a> humanity through jesus christ in the  
<a onclick="modifyYTiframeseektime('183')">0:03:03</a> whole cosmic order of things and the  
<a onclick="modifyYTiframeseektime('185')">0:03:05</a> fundamental position of adam us human  
<a onclick="modifyYTiframeseektime('188')">0:03:08</a> beings as his progeny in light of the  
<a onclick="modifyYTiframeseektime('190')">0:03:10</a> sacrificial model presented by jesus  
<a onclick="modifyYTiframeseektime('193')">0:03:13</a> christ as a way for sins our sins adam's  
<a onclick="modifyYTiframeseektime('196')">0:03:16</a> sins to be atoned for and therefore  
<a onclick="modifyYTiframeseektime('198')">0:03:18</a> god's anger to be appeased and for us  
<a onclick="modifyYTiframeseektime('200')">0:03:20</a> therefore to be forgiven those were  
<a onclick="modifyYTiframeseektime('202')">0:03:22</a> atonement theories and there are of  
<a onclick="modifyYTiframeseektime('204')">0:03:24</a> course some that are being developed and  
<a onclick="modifyYTiframeseektime('206')">0:03:26</a> evolving over time uh over the christian  
<a onclick="modifyYTiframeseektime('210')">0:03:30</a> centuries  
<a onclick="modifyYTiframeseektime('211')">0:03:31</a> uh now  
<a onclick="modifyYTiframeseektime('212')">0:03:32</a> how do we and how do we understand that  
<a onclick="modifyYTiframeseektime('215')">0:03:35</a> or appreciate that in light of the  
<a onclick="modifyYTiframeseektime('217')">0:03:37</a> quranic the islamic the prophetic  
<a onclick="modifyYTiframeseektime('219')">0:03:39</a> discourse about salvation if that's the  
<a onclick="modifyYTiframeseektime('222')">0:03:42</a> way that christians perceive of it how  
<a onclick="modifyYTiframeseektime('223')">0:03:43</a> do we perceive of it remember we said  
<a onclick="modifyYTiframeseektime('225')">0:03:45</a> initially that there is much that we  
<a onclick="modifyYTiframeseektime('227')">0:03:47</a> agree with with our christian friends  
<a onclick="modifyYTiframeseektime('228')">0:03:48</a> that we both believe in similar things  
<a onclick="modifyYTiframeseektime('230')">0:03:50</a> about adam about god about not from the  
<a onclick="modifyYTiframeseektime('232')">0:03:52</a> the particular tree uh to enjoy the  
<a onclick="modifyYTiframeseektime('235')">0:03:55</a> garden him and his wife we both believe  
<a onclick="modifyYTiframeseektime('237')">0:03:57</a> that we both believe in the devil the  
<a onclick="modifyYTiframeseektime('239')">0:03:59</a> devil of course has a plan and and we  
<a onclick="modifyYTiframeseektime('241')">0:04:01</a> all believe in that stuff but the  
<a onclick="modifyYTiframeseektime('243')">0:04:03</a> quranic outline is remarkably  
<a onclick="modifyYTiframeseektime('246')">0:04:06</a> different in fact uniquely different  
<a onclick="modifyYTiframeseektime('249')">0:04:09</a> than our christian friends  
<a onclick="modifyYTiframeseektime('251')">0:04:11</a> outline presented to them in the bible  
<a onclick="modifyYTiframeseektime('253')">0:04:13</a> or at least even not so much from the  
<a onclick="modifyYTiframeseektime('255')">0:04:15</a> bible but in fact in their theoretical  
<a onclick="modifyYTiframeseektime('257')">0:04:17</a> developments in their history and that's  
<a onclick="modifyYTiframeseektime('259')">0:04:19</a> a lot a lot to say about that  
<a onclick="modifyYTiframeseektime('261')">0:04:21</a> so what happens then how is it presented  
<a onclick="modifyYTiframeseektime('263')">0:04:23</a> in the quran what happens with adam in  
<a onclick="modifyYTiframeseektime('265')">0:04:25</a> the quran that is the subject of of this  
<a onclick="modifyYTiframeseektime('268')">0:04:28</a> series here now this is in light of what  
<a onclick="modifyYTiframeseektime('270')">0:04:30</a> i call what the book terms the adamic  
<a onclick="modifyYTiframeseektime('272')">0:04:32</a> conundrum now in the quran is presented  
<a onclick="modifyYTiframeseektime('275')">0:04:35</a> like this  
<a onclick="modifyYTiframeseektime('276')">0:04:36</a> allah of course had forewarned adam and  
<a onclick="modifyYTiframeseektime('279')">0:04:39</a> his wife not to eat from a particular  
<a onclick="modifyYTiframeseektime('281')">0:04:41</a> tree  
<a onclick="modifyYTiframeseektime('282')">0:04:42</a> and allah says  
<a onclick="modifyYTiframeseektime('284')">0:04:44</a> beware of the devil right in the fight  
<a onclick="modifyYTiframeseektime('286')">0:04:46</a> in the quran says  
<a onclick="modifyYTiframeseektime('287')">0:04:47</a> beware of the devil because he is your  
<a onclick="modifyYTiframeseektime('289')">0:04:49</a> enemy  
<a onclick="modifyYTiframeseektime('291')">0:04:51</a> so take him therefore as an enemy adam  
<a onclick="modifyYTiframeseektime('293')">0:04:53</a> was pre-warned we're also warned about  
<a onclick="modifyYTiframeseektime('295')">0:04:55</a> the devil in our lives as well remember  
<a onclick="modifyYTiframeseektime('298')">0:04:58</a> of course in the quranic paradigm human  
<a onclick="modifyYTiframeseektime('300')">0:05:00</a> beings all of us are weak frail prone to  
<a onclick="modifyYTiframeseektime('304')">0:05:04</a> sin  
<a onclick="modifyYTiframeseektime('305')">0:05:05</a> we're not perfect creatures we're  
<a onclick="modifyYTiframeseektime('307')">0:05:07</a> imperfect creatures that means we have a  
<a onclick="modifyYTiframeseektime('309')">0:05:09</a> capacity to do good  
<a onclick="modifyYTiframeseektime('311')">0:05:11</a> and capacity to do sin a beautiful  
<a onclick="modifyYTiframeseektime('314')">0:05:14</a> verses which is outlined in israel  
<a onclick="modifyYTiframeseektime('316')">0:05:16</a> in the quran in which allah says  
<a onclick="modifyYTiframeseektime('321')">0:05:21</a> foreign  
<a onclick="modifyYTiframeseektime('325')">0:05:25</a> beautiful verses what do they say they  
<a onclick="modifyYTiframeseektime('328')">0:05:28</a> say that  
<a onclick="modifyYTiframeseektime('329')">0:05:29</a> consider the self consider yourself  
<a onclick="modifyYTiframeseektime('332')">0:05:32</a> myself yourself  
<a onclick="modifyYTiframeseektime('334')">0:05:34</a> how it's formed  
<a onclick="modifyYTiframeseektime('336')">0:05:36</a> and how it could be inspired by  
<a onclick="modifyYTiframeseektime('339')">0:05:39</a> by depravity by moral depravities but  
<a onclick="modifyYTiframeseektime('342')">0:05:42</a> also inspired by  
<a onclick="modifyYTiframeseektime('344')">0:05:44</a> saintliness  
<a onclick="modifyYTiframeseektime('345')">0:05:45</a> by moral goodness by goodness by good  
<a onclick="modifyYTiframeseektime('349')">0:05:49</a> character right so human beings have  
<a onclick="modifyYTiframeseektime('352')">0:05:52</a> both potentials to do  
<a onclick="modifyYTiframeseektime('354')">0:05:54</a> wondrous dazzling acts of kindness of  
<a onclick="modifyYTiframeseektime('357')">0:05:57</a> mercy of sympathy of empathy of love all  
<a onclick="modifyYTiframeseektime('360')">0:06:00</a> of that but also evil acts hideous acts  
<a onclick="modifyYTiframeseektime('363')">0:06:03</a> reprehensible acts as well in fact the  
<a onclick="modifyYTiframeseektime('366')">0:06:06</a> world of course is a witness to both of  
<a onclick="modifyYTiframeseektime('368')">0:06:08</a> these currents and trends but then the  
<a onclick="modifyYTiframeseektime('371')">0:06:11</a> next verse says  
<a onclick="modifyYTiframeseektime('373')">0:06:13</a> successful is he that purifies it  
<a onclick="modifyYTiframeseektime('376')">0:06:16</a> meaning purifies himself  
<a onclick="modifyYTiframeseektime('378')">0:06:18</a> that that's the undertaking the task  
<a onclick="modifyYTiframeseektime('380')">0:06:20</a> that is set out to man from god  
<a onclick="modifyYTiframeseektime('382')">0:06:22</a> successful is the one that purifies  
<a onclick="modifyYTiframeseektime('384')">0:06:24</a> himself that works labors in that task  
<a onclick="modifyYTiframeseektime('387')">0:06:27</a> day and night all the time that's  
<a onclick="modifyYTiframeseektime('389')">0:06:29</a> success and that loss is the one that  
<a onclick="modifyYTiframeseektime('391')">0:06:31</a> buries it buries himself this allows  
<a onclick="modifyYTiframeseektime('393')">0:06:33</a> himself to reach heights of moral  
<a onclick="modifyYTiframeseektime('396')">0:06:36</a> goodness of moral character of excellent  
<a onclick="modifyYTiframeseektime('398')">0:06:38</a> beautiful behavior beautiful conduct  
<a onclick="modifyYTiframeseektime('400')">0:06:40</a> beautiful acts of worship and so on and  
<a onclick="modifyYTiframeseektime('402')">0:06:42</a> so forth so therefore we have both of  
<a onclick="modifyYTiframeseektime('405')">0:06:45</a> these strands as human beings and so  
<a onclick="modifyYTiframeseektime('407')">0:06:47</a> therefore uh adam therefore when he sins  
<a onclick="modifyYTiframeseektime('411')">0:06:51</a> against allah well the way it's  
<a onclick="modifyYTiframeseektime('413')">0:06:53</a> presented in the quran is not exactly  
<a onclick="modifyYTiframeseektime('414')">0:06:54</a> like that either so we know therefore  
<a onclick="modifyYTiframeseektime('416')">0:06:56</a> that the devil exists and the devil  
<a onclick="modifyYTiframeseektime('419')">0:06:59</a> goes to or we don't know in fact if it  
<a onclick="modifyYTiframeseektime('421')">0:07:01</a> was to eve or adam first except that  
<a onclick="modifyYTiframeseektime('424')">0:07:04</a> they're both blamed for that mistake  
<a onclick="modifyYTiframeseektime('427')">0:07:07</a> that they make  
<a onclick="modifyYTiframeseektime('428')">0:07:08</a> now of course in the quran allah calls  
<a onclick="modifyYTiframeseektime('430')">0:07:10</a> it many things allah calls it an act of  
<a onclick="modifyYTiframeseektime('432')">0:07:12</a> disobedience that's true allah calls  
<a onclick="modifyYTiframeseektime('435')">0:07:15</a> they were misled deceived by the devil  
<a onclick="modifyYTiframeseektime('438')">0:07:18</a> allah says there was a case of  
<a onclick="modifyYTiframeseektime('440')">0:07:20</a> forgetfulness from from adam  
<a onclick="modifyYTiframeseektime('442')">0:07:22</a> forgetfulness perhaps of many things  
<a onclick="modifyYTiframeseektime('443')">0:07:23</a> maybe he forgot therefore the great  
<a onclick="modifyYTiframeseektime('445')">0:07:25</a> undertaking that god gave him in the  
<a onclick="modifyYTiframeseektime('447')">0:07:27</a> first place he forgot his responsibility  
<a onclick="modifyYTiframeseektime('449')">0:07:29</a> between him and god he forgot the great  
<a onclick="modifyYTiframeseektime('453')">0:07:33</a> deceptive character and potential of the  
<a onclick="modifyYTiframeseektime('456')">0:07:36</a> devil he forgot  
<a onclick="modifyYTiframeseektime('457')">0:07:37</a> but in this verse in the in the second  
<a onclick="modifyYTiframeseektime('460')">0:07:40</a> chapter of the quran it's outlined  
<a onclick="modifyYTiframeseektime('461')">0:07:41</a> beautifully in that allah says that the  
<a onclick="modifyYTiframeseektime('464')">0:07:44</a> devil  
<a onclick="modifyYTiframeseektime('467')">0:07:47</a> allah says that the devil caused them  
<a onclick="modifyYTiframeseektime('469')">0:07:49</a> both to slip  
<a onclick="modifyYTiframeseektime('471')">0:07:51</a> the word used here is the word zel which  
<a onclick="modifyYTiframeseektime('473')">0:07:53</a> is stumble or slip now of course in the  
<a onclick="modifyYTiframeseektime('476')">0:07:56</a> book of genesis the bible is called the  
<a onclick="modifyYTiframeseektime('478')">0:07:58</a> fall  
<a onclick="modifyYTiframeseektime('478')">0:07:58</a> fall kind of connotes like something  
<a onclick="modifyYTiframeseektime('481')">0:08:01</a> that is irrecoverable i mean as you've  
<a onclick="modifyYTiframeseektime('483')">0:08:03</a> fallen now but a slip has different  
<a onclick="modifyYTiframeseektime('485')">0:08:05</a> connotations of while you're slipped and  
<a onclick="modifyYTiframeseektime('487')">0:08:07</a> you stumble but perhaps you're still  
<a onclick="modifyYTiframeseektime('489')">0:08:09</a> able to get back up on your feet that's  
<a onclick="modifyYTiframeseektime('490')">0:08:10</a> the first difference that you'll notice  
<a onclick="modifyYTiframeseektime('492')">0:08:12</a> in the quranic narrative  
<a onclick="modifyYTiframeseektime('494')">0:08:14</a> allah says that the shaitaan the devil  
<a onclick="modifyYTiframeseektime('496')">0:08:16</a> caused them both to  
<a onclick="modifyYTiframeseektime('497')">0:08:17</a> slip  
<a onclick="modifyYTiframeseektime('498')">0:08:18</a> and then they were removed from where  
<a onclick="modifyYTiframeseektime('499')">0:08:19</a> they were meaning in the garden they  
<a onclick="modifyYTiframeseektime('501')">0:08:21</a> were taken out from them placed  
<a onclick="modifyYTiframeseektime('503')">0:08:23</a> elsewhere  
<a onclick="modifyYTiframeseektime('504')">0:08:24</a> now that's the first thing now zell of  
<a onclick="modifyYTiframeseektime('508')">0:08:28</a> course has connotations it's like when  
<a onclick="modifyYTiframeseektime('509')">0:08:29</a> we believe that when we uh leave our  
<a onclick="modifyYTiframeseektime('511')">0:08:31</a> homes in the morning or whatever homes  
<a onclick="modifyYTiframeseektime('513')">0:08:33</a> we say a particular prayer that we say  
<a onclick="modifyYTiframeseektime('516')">0:08:36</a> allah  
<a onclick="modifyYTiframeseektime('523')">0:08:43</a> prophetic prayer that we recite oh allah  
<a onclick="modifyYTiframeseektime('525')">0:08:45</a> i seek refuge with you that i go astray  
<a onclick="modifyYTiframeseektime('527')">0:08:47</a> or leaders as a straight or that i slip  
<a onclick="modifyYTiframeseektime('529')">0:08:49</a> and stumble  
<a onclick="modifyYTiframeseektime('530')">0:08:50</a> right or cause others to slip and  
<a onclick="modifyYTiframeseektime('531')">0:08:51</a> stumble so we all in our lives can slip  
<a onclick="modifyYTiframeseektime('535')">0:08:55</a> and stumble we can lose sight of where  
<a onclick="modifyYTiframeseektime('537')">0:08:57</a> we're going sometimes in life that's a  
<a onclick="modifyYTiframeseektime('539')">0:08:59</a> reflection of our imperfect human  
<a onclick="modifyYTiframeseektime('542')">0:09:02</a> character and nature and of course god  
<a onclick="modifyYTiframeseektime('544')">0:09:04</a> creates us with perfect knowledge and  
<a onclick="modifyYTiframeseektime('546')">0:09:06</a> perfect wisdom that's a key fundamental  
<a onclick="modifyYTiframeseektime('549')">0:09:09</a> point for us to emphasize god creates us  
<a onclick="modifyYTiframeseektime('551')">0:09:11</a> with perfect knowledge and perfect  
<a onclick="modifyYTiframeseektime('552')">0:09:12</a> wisdom knowing of course this is who we  
<a onclick="modifyYTiframeseektime('554')">0:09:14</a> are this is our capacity our potential  
<a onclick="modifyYTiframeseektime('557')">0:09:17</a> and these are ways of course we could be  
<a onclick="modifyYTiframeseektime('559')">0:09:19</a> led astray but we have to be on our god  
<a onclick="modifyYTiframeseektime('561')">0:09:21</a> the quran says by the way in the quran  
<a onclick="modifyYTiframeseektime('563')">0:09:23</a> we have the word  
<a onclick="modifyYTiframeseektime('566')">0:09:26</a> which means deviation straying  
<a onclick="modifyYTiframeseektime('569')">0:09:29</a> misleading  
<a onclick="modifyYTiframeseektime('570')">0:09:30</a> repeated more than 200 times in the  
<a onclick="modifyYTiframeseektime('572')">0:09:32</a> quran  
<a onclick="modifyYTiframeseektime('574')">0:09:34</a> straying misleading deviating but we  
<a onclick="modifyYTiframeseektime('576')">0:09:36</a> also have the word wakaya wakka is where  
<a onclick="modifyYTiframeseektime('579')">0:09:39</a> we get the word taqwa from which means  
<a onclick="modifyYTiframeseektime('580')">0:09:40</a> protection which means safeguarding  
<a onclick="modifyYTiframeseektime('583')">0:09:43</a> repeated through and through the quran  
<a onclick="modifyYTiframeseektime('585')">0:09:45</a> as a way of pushing back offsetting the  
<a onclick="modifyYTiframeseektime('588')">0:09:48</a> dangers of dalala of deviation of  
<a onclick="modifyYTiframeseektime('591')">0:09:51</a> straying of of of misleading and going  
<a onclick="modifyYTiframeseektime('594')">0:09:54</a> astray and so the next verse now is is  
<a onclick="modifyYTiframeseektime('597')">0:09:57</a> very essential and key for us in showing  
<a onclick="modifyYTiframeseektime('600')">0:10:00</a> the difference between us  
<a onclick="modifyYTiframeseektime('601')">0:10:01</a> and the christian narrative which ends  
<a onclick="modifyYTiframeseektime('603')">0:10:03</a> up in a lot of confusion a lot of  
<a onclick="modifyYTiframeseektime('605')">0:10:05</a> ambiguity with all of these atonement  
<a onclick="modifyYTiframeseektime('607')">0:10:07</a> theories are proposed and still  
<a onclick="modifyYTiframeseektime('608')">0:10:08</a> developing and evolving and that is this  
<a onclick="modifyYTiframeseektime('611')">0:10:11</a> verse that allah quran says  
<a onclick="modifyYTiframeseektime('618')">0:10:18</a> what does it say it says therefore so  
<a onclick="modifyYTiframeseektime('620')">0:10:20</a> adam slept therefore was removed from  
<a onclick="modifyYTiframeseektime('622')">0:10:22</a> where he was and then allah says adam  
<a onclick="modifyYTiframeseektime('625')">0:10:25</a> was met with some words from his lord  
<a onclick="modifyYTiframeseektime('628')">0:10:28</a> what does it mean to be met with some  
<a onclick="modifyYTiframeseektime('629')">0:10:29</a> words from his lord what does it mean  
<a onclick="modifyYTiframeseektime('631')">0:10:31</a> adam was met with some words from his  
<a onclick="modifyYTiframeseektime('633')">0:10:33</a> lord it means that adam in this state of  
<a onclick="modifyYTiframeseektime('637')">0:10:37</a> vulnerability because of course he has  
<a onclick="modifyYTiframeseektime('639')">0:10:39</a> sinned and done something against god's  
<a onclick="modifyYTiframeseektime('641')">0:10:41</a> wishes is now stuck because he's there  
<a onclick="modifyYTiframeseektime('643')">0:10:43</a> by him so remember adam is there by  
<a onclick="modifyYTiframeseektime('645')">0:10:45</a> himself with his wife that says no other  
<a onclick="modifyYTiframeseektime('646')">0:10:46</a> prophets around to ask to seek help from  
<a onclick="modifyYTiframeseektime('648')">0:10:48</a> nothing that's just them too right but  
<a onclick="modifyYTiframeseektime('650')">0:10:50</a> there of course is allah there is god  
<a onclick="modifyYTiframeseektime('652')">0:10:52</a> and it's god that they beseech but not  
<a onclick="modifyYTiframeseektime('654')">0:10:54</a> just that they beseech god and ask of  
<a onclick="modifyYTiframeseektime('656')">0:10:56</a> god no that is not even the first thing  
<a onclick="modifyYTiframeseektime('658')">0:10:58</a> that happens  
<a onclick="modifyYTiframeseektime('659')">0:10:59</a> allah says adam was received words from  
<a onclick="modifyYTiframeseektime('662')">0:11:02</a> his lord that means  
<a onclick="modifyYTiframeseektime('664')">0:11:04</a> allah god the lord of the heavens and  
<a onclick="modifyYTiframeseektime('667')">0:11:07</a> the earth the most kind the most  
<a onclick="modifyYTiframeseektime('668')">0:11:08</a> merciful the maximally perfect  
<a onclick="modifyYTiframeseektime('671')">0:11:11</a> the most magnificent the most supreme  
<a onclick="modifyYTiframeseektime('674')">0:11:14</a> allah  
<a onclick="modifyYTiframeseektime('675')">0:11:15</a> taught adam words to say that means  
<a onclick="modifyYTiframeseektime('678')">0:11:18</a> allah inspired adam with words to say in  
<a onclick="modifyYTiframeseektime('681')">0:11:21</a> order for adam to know how to ask god  
<a onclick="modifyYTiframeseektime('684')">0:11:24</a> for forgiveness  
<a onclick="modifyYTiframeseektime('686')">0:11:26</a> it's something fundamentally beautiful  
<a onclick="modifyYTiframeseektime('688')">0:11:28</a> here  
<a onclick="modifyYTiframeseektime('688')">0:11:28</a> that is not so much adam then quickly  
<a onclick="modifyYTiframeseektime('690')">0:11:30</a> asked for forgiveness is that allah  
<a onclick="modifyYTiframeseektime('693')">0:11:33</a> aided adam enabled adam facilitated for  
<a onclick="modifyYTiframeseektime('697')">0:11:37</a> adam that path of seeking for seeking  
<a onclick="modifyYTiframeseektime('700')">0:11:40</a> forgiveness which is remarkable right  
<a onclick="modifyYTiframeseektime('702')">0:11:42</a> and so in adam being taught the words  
<a onclick="modifyYTiframeseektime('705')">0:11:45</a> and we know the words from another verse  
<a onclick="modifyYTiframeseektime('707')">0:11:47</a> in the quran when they both said  
<a onclick="modifyYTiframeseektime('708')">0:11:48</a> they both said  
<a onclick="modifyYTiframeseektime('716')">0:11:56</a> our lord our lord  
<a onclick="modifyYTiframeseektime('719')">0:11:59</a> we have wronged our souls  
<a onclick="modifyYTiframeseektime('722')">0:12:02</a> and if you don't forgive us and have  
<a onclick="modifyYTiframeseektime('723')">0:12:03</a> mercy on us we're going to be of the  
<a onclick="modifyYTiframeseektime('725')">0:12:05</a> losers so what's happening here number  
<a onclick="modifyYTiframeseektime('727')">0:12:07</a> one our lord  
<a onclick="modifyYTiframeseektime('729')">0:12:09</a> number two we've wronged ourselves  
<a onclick="modifyYTiframeseektime('731')">0:12:11</a> injustice on ourselves  
<a onclick="modifyYTiframeseektime('733')">0:12:13</a> number three  
<a onclick="modifyYTiframeseektime('736')">0:12:16</a> you forgive  
<a onclick="modifyYTiframeseektime('737')">0:12:17</a> you are the one that forgives number  
<a onclick="modifyYTiframeseektime('739')">0:12:19</a> four you show mercy and number five if  
<a onclick="modifyYTiframeseektime('743')">0:12:23</a> you do we're successful if you don't  
<a onclick="modifyYTiframeseektime('745')">0:12:25</a> wear losers all of that contained in  
<a onclick="modifyYTiframeseektime('747')">0:12:27</a> that beautiful prayer of adam and his  
<a onclick="modifyYTiframeseektime('750')">0:12:30</a> wife that was inspired upon them taught  
<a onclick="modifyYTiframeseektime('752')">0:12:32</a> to them instructed to them by god  
<a onclick="modifyYTiframeseektime('754')">0:12:34</a> himself enabling adam and all of us adam  
<a onclick="modifyYTiframeseektime('758')">0:12:38</a> is archetypal here all of us as his  
<a onclick="modifyYTiframeseektime('760')">0:12:40</a> progeny to remember the way back to god  
<a onclick="modifyYTiframeseektime('763')">0:12:43</a> whenever we slip and whenever we stumble  
<a onclick="modifyYTiframeseektime('765')">0:12:45</a> in life there is a model  
<a onclick="modifyYTiframeseektime('767')">0:12:47</a> paradigmatic model here for us to always  
<a onclick="modifyYTiframeseektime('769')">0:12:49</a> remember and realize that's how it  
<a onclick="modifyYTiframeseektime('771')">0:12:51</a> happened with adam our father where his  
<a onclick="modifyYTiframeseektime('774')">0:12:54</a> progeny that's how god deals with us  
<a onclick="modifyYTiframeseektime('776')">0:12:56</a> remember we ended the last chapter by by  
<a onclick="modifyYTiframeseektime('778')">0:12:58</a> mentioning the verse in the quran when  
<a onclick="modifyYTiframeseektime('779')">0:12:59</a> allah says  
<a onclick="modifyYTiframeseektime('782')">0:13:02</a> what is your impression  
<a onclick="modifyYTiframeseektime('784')">0:13:04</a> of the lord of the worlds how do we  
<a onclick="modifyYTiframeseektime('786')">0:13:06</a> perceive imagine  
<a onclick="modifyYTiframeseektime('788')">0:13:08</a> of god in light of all these tournament  
<a onclick="modifyYTiframeseektime('791')">0:13:11</a> theories and god  
<a onclick="modifyYTiframeseektime('792')">0:13:12</a> and the blood and the sacrifice and the  
<a onclick="modifyYTiframeseektime('794')">0:13:14</a> the wrath and the all of these things  
<a onclick="modifyYTiframeseektime('797')">0:13:17</a> and now how do we  
<a onclick="modifyYTiframeseektime('798')">0:13:18</a> perceive imagine of god  
<a onclick="modifyYTiframeseektime('800')">0:13:20</a> when we know that that's how god treats  
<a onclick="modifyYTiframeseektime('802')">0:13:22</a> and dealt with  
<a onclick="modifyYTiframeseektime('804')">0:13:24</a> the first of us the first of us our  
<a onclick="modifyYTiframeseektime('806')">0:13:26</a> father  
<a onclick="modifyYTiframeseektime('807')">0:13:27</a> adam when he stumbled he stumbled and he  
<a onclick="modifyYTiframeseektime('810')">0:13:30</a> slipped  
<a onclick="modifyYTiframeseektime('812')">0:13:32</a> in the garden there you know when the  
<a onclick="modifyYTiframeseektime('813')">0:13:33</a> devil when he was deceived by the devil  
<a onclick="modifyYTiframeseektime('815')">0:13:35</a> so therefore allah inspired adam with  
<a onclick="modifyYTiframeseektime('817')">0:13:37</a> the words to say but it doesn't end  
<a onclick="modifyYTiframeseektime('819')">0:13:39</a> there  
<a onclick="modifyYTiframeseektime('820')">0:13:40</a> it doesn't end there because then allah  
<a onclick="modifyYTiframeseektime('822')">0:13:42</a> says  
<a onclick="modifyYTiframeseektime('823')">0:13:43</a> now taba it means to lean towards to  
<a onclick="modifyYTiframeseektime('827')">0:13:47</a> relent towards  
<a onclick="modifyYTiframeseektime('828')">0:13:48</a> that means who's doing it all here it's  
<a onclick="modifyYTiframeseektime('831')">0:13:51</a> god doing it towards adam it is not adam  
<a onclick="modifyYTiframeseektime('833')">0:13:53</a> that is the first actor here it is god  
<a onclick="modifyYTiframeseektime('836')">0:13:56</a> enabling assisting adam when allah says  
<a onclick="modifyYTiframeseektime('840')">0:14:00</a> lean to him by showing him repentance by  
<a onclick="modifyYTiframeseektime('843')">0:14:03</a> showing you by accepting repentance  
<a onclick="modifyYTiframeseektime('844')">0:14:04</a> allah did that and allah is of repenting  
<a onclick="modifyYTiframeseektime('848')">0:14:08</a> and allah is merciful that is a  
<a onclick="modifyYTiframeseektime('850')">0:14:10</a> beautiful model here that we we can  
<a onclick="modifyYTiframeseektime('852')">0:14:12</a> clearly see in this adamic paradigm  
<a onclick="modifyYTiframeseektime('855')">0:14:15</a> right conundrum between us and  
<a onclick="modifyYTiframeseektime('856')">0:14:16</a> christians but really when the quran is  
<a onclick="modifyYTiframeseektime('858')">0:14:18</a> an adamic paradigm an archetype showing  
<a onclick="modifyYTiframeseektime('861')">0:14:21</a> illustrating for us the mercy the  
<a onclick="modifyYTiframeseektime('863')">0:14:23</a> closeness the love of god towards his  
<a onclick="modifyYTiframeseektime('866')">0:14:26</a> creation  
<a onclick="modifyYTiframeseektime('867')">0:14:27</a> even though adam made a mistake and  
<a onclick="modifyYTiframeseektime('869')">0:14:29</a> sinned here against god  
<a onclick="modifyYTiframeseektime('871')">0:14:31</a> or he made a mistake some they say it  
<a onclick="modifyYTiframeseektime('873')">0:14:33</a> was a mistake some they say it was act  
<a onclick="modifyYTiframeseektime('875')">0:14:35</a> of disobedience but in any case it was  
<a onclick="modifyYTiframeseektime('877')">0:14:37</a> something that was not what he wasn't  
<a onclick="modifyYTiframeseektime('879')">0:14:39</a> supposed to do but he did and so now  
<a onclick="modifyYTiframeseektime('881')">0:14:41</a> therefore there was a way out for him in  
<a onclick="modifyYTiframeseektime('883')">0:14:43</a> light of that  
<a onclick="modifyYTiframeseektime('885')">0:14:45</a> in light of that mistake or that sin  
<a onclick="modifyYTiframeseektime('887')">0:14:47</a> that he made now i want to show you one  
<a onclick="modifyYTiframeseektime('889')">0:14:49</a> more thing in light of this just so that  
<a onclick="modifyYTiframeseektime('890')">0:14:50</a> you realize this is not restricted to  
<a onclick="modifyYTiframeseektime('893')">0:14:53</a> adam this is not only about adam so we  
<a onclick="modifyYTiframeseektime('896')">0:14:56</a> have of course clarified a big thing  
<a onclick="modifyYTiframeseektime('898')">0:14:58</a> here in light of  
<a onclick="modifyYTiframeseektime('900')">0:15:00</a> salvation what it means from the islamic  
<a onclick="modifyYTiframeseektime('902')">0:15:02</a> perspective and the christian  
<a onclick="modifyYTiframeseektime('903')">0:15:03</a> perspective a big thing but just to show  
<a onclick="modifyYTiframeseektime('906')">0:15:06</a> you something really remarkable this is  
<a onclick="modifyYTiframeseektime('907')">0:15:07</a> not just about adam you might say  
<a onclick="modifyYTiframeseektime('910')">0:15:10</a> christians might say well that's unique  
<a onclick="modifyYTiframeseektime('912')">0:15:12</a> about adam but what else is there in the  
<a onclick="modifyYTiframeseektime('914')">0:15:14</a> quran what else is there in islam how do  
<a onclick="modifyYTiframeseektime('916')">0:15:16</a> we know that god doesn't deals with us  
<a onclick="modifyYTiframeseektime('918')">0:15:18</a> in the same way that with adam for  
<a onclick="modifyYTiframeseektime('919')">0:15:19</a> example let me show you one beautiful  
<a onclick="modifyYTiframeseektime('921')">0:15:21</a> example from the chapter called atoba in  
<a onclick="modifyYTiframeseektime('923')">0:15:23</a> the quran  
<a onclick="modifyYTiframeseektime('925')">0:15:25</a> this chapter which in fact is called  
<a onclick="modifyYTiframeseektime('927')">0:15:27</a> meaning remains repentance but here you  
<a onclick="modifyYTiframeseektime('929')">0:15:29</a> have a beautiful incident concerning  
<a onclick="modifyYTiframeseektime('931')">0:15:31</a> three individuals these individuals were  
<a onclick="modifyYTiframeseektime('933')">0:15:33</a> three people  
<a onclick="modifyYTiframeseektime('934')">0:15:34</a> who made excuses  
<a onclick="modifyYTiframeseektime('936')">0:15:36</a> for not participating in a very  
<a onclick="modifyYTiframeseektime('938')">0:15:38</a> important one called the battle of tabuk  
<a onclick="modifyYTiframeseektime('939')">0:15:39</a> in the life of the prophet sallallahu  
<a onclick="modifyYTiframeseektime('941')">0:15:41</a> alaihi allah please be upon him  
<a onclick="modifyYTiframeseektime('943')">0:15:43</a> they stayed behind and allah says that  
<a onclick="modifyYTiframeseektime('945')">0:15:45</a> you know  
<a onclick="modifyYTiframeseektime('947')">0:15:47</a> about the three who stayed behind  
<a onclick="modifyYTiframeseektime('949')">0:15:49</a> these three therefore they were wracked  
<a onclick="modifyYTiframeseektime('951')">0:15:51</a> with guilt  
<a onclick="modifyYTiframeseektime('952')">0:15:52</a> knowing of course that they've stayed  
<a onclick="modifyYTiframeseektime('954')">0:15:54</a> behind everybody else has gone there by  
<a onclick="modifyYTiframeseektime('956')">0:15:56</a> themselves now what to do they've made  
<a onclick="modifyYTiframeseektime('958')">0:15:58</a> this sin it's a sin this act of  
<a onclick="modifyYTiframeseektime('960')">0:16:00</a> disobedience against god and so allah  
<a onclick="modifyYTiframeseektime('963')">0:16:03</a> then says the three who remained behind  
<a onclick="modifyYTiframeseektime('965')">0:16:05</a> stayed behind held back  
<a onclick="modifyYTiframeseektime('970')">0:16:10</a> until the earth became squeezed and  
<a onclick="modifyYTiframeseektime('973')">0:16:13</a> tight and restricted  
<a onclick="modifyYTiframeseektime('975')">0:16:15</a> for them even though the earth is  
<a onclick="modifyYTiframeseektime('977')">0:16:17</a> spacious and wide  
<a onclick="modifyYTiframeseektime('980')">0:16:20</a> all right  
<a onclick="modifyYTiframeseektime('980')">0:16:20</a> how do you feel when you've sinned  
<a onclick="modifyYTiframeseektime('983')">0:16:23</a> against god that's how you're supposed  
<a onclick="modifyYTiframeseektime('984')">0:16:24</a> to feel you feel you know guilty you  
<a onclick="modifyYTiframeseektime('987')">0:16:27</a> feel as if the earth is closing in  
<a onclick="modifyYTiframeseektime('989')">0:16:29</a> around you you feel like what what are  
<a onclick="modifyYTiframeseektime('991')">0:16:31</a> you supposed to do you've done something  
<a onclick="modifyYTiframeseektime('993')">0:16:33</a> that is a terrible thing in the eyes of  
<a onclick="modifyYTiframeseektime('995')">0:16:35</a> god right and that's how they felt  
<a onclick="modifyYTiframeseektime('998')">0:16:38</a> and then allah says the earth therefore  
<a onclick="modifyYTiframeseektime('1000')">0:16:40</a> it was as if the earth was squeezed and  
<a onclick="modifyYTiframeseektime('1002')">0:16:42</a> restricted for them  
<a onclick="modifyYTiframeseektime('1005')">0:16:45</a> and their own souls their own selves  
<a onclick="modifyYTiframeseektime('1008')">0:16:48</a> were constricted and tight and  
<a onclick="modifyYTiframeseektime('1010')">0:16:50</a> restricted and squeezed for them they  
<a onclick="modifyYTiframeseektime('1012')">0:16:52</a> felt that sense of agitation  
<a onclick="modifyYTiframeseektime('1015')">0:16:55</a> and distance and they felt that sense of  
<a onclick="modifyYTiframeseektime('1018')">0:16:58</a> inner sense of remorse and then allah  
<a onclick="modifyYTiframeseektime('1020')">0:17:00</a> says  
<a onclick="modifyYTiframeseektime('1021')">0:17:01</a> and they realized  
<a onclick="modifyYTiframeseektime('1024')">0:17:04</a> there is no refuge from god except to  
<a onclick="modifyYTiframeseektime('1027')">0:17:07</a> god  
<a onclick="modifyYTiframeseektime('1028')">0:17:08</a> there is no  
<a onclick="modifyYTiframeseektime('1029')">0:17:09</a> escaping from god except going back to  
<a onclick="modifyYTiframeseektime('1032')">0:17:12</a> god  
<a onclick="modifyYTiframeseektime('1033')">0:17:13</a> no refuge except going back to god the  
<a onclick="modifyYTiframeseektime('1036')">0:17:16</a> only  
<a onclick="modifyYTiframeseektime('1037')">0:17:17</a> salvation they will find is with god  
<a onclick="modifyYTiframeseektime('1039')">0:17:19</a> himself they can't run anywhere or find  
<a onclick="modifyYTiframeseektime('1042')">0:17:22</a> help anywhere or seek assistance in  
<a onclick="modifyYTiframeseektime('1045')">0:17:25</a> anything or anyone or anywhere except  
<a onclick="modifyYTiframeseektime('1047')">0:17:27</a> with god himself  
<a onclick="modifyYTiframeseektime('1049')">0:17:29</a> that's the quranic paradigm about human  
<a onclick="modifyYTiframeseektime('1052')">0:17:32</a> salvation your only safety your only  
<a onclick="modifyYTiframeseektime('1054')">0:17:34</a> security your only peace of mind peace  
<a onclick="modifyYTiframeseektime('1057')">0:17:37</a> of heart  
<a onclick="modifyYTiframeseektime('1058')">0:17:38</a> is in god himself there's nothing else  
<a onclick="modifyYTiframeseektime('1061')">0:17:41</a> there's not in a stone or an idol or in  
<a onclick="modifyYTiframeseektime('1063')">0:17:43</a> a or mary or in jesus or in anybody  
<a onclick="modifyYTiframeseektime('1066')">0:17:46</a> except god himself that's the one that  
<a onclick="modifyYTiframeseektime('1068')">0:17:48</a> you've transgressed against that's the  
<a onclick="modifyYTiframeseektime('1070')">0:17:50</a> one you ask from now right and then  
<a onclick="modifyYTiframeseektime('1072')">0:17:52</a> allah says after this allah says now  
<a onclick="modifyYTiframeseektime('1074')">0:17:54</a> look at the comparison here similarity  
<a onclick="modifyYTiframeseektime('1076')">0:17:56</a> with the with the adamic model paradigm  
<a onclick="modifyYTiframeseektime('1079')">0:17:59</a> allah says  
<a onclick="modifyYTiframeseektime('1082')">0:18:02</a> then allah turned to them so that they  
<a onclick="modifyYTiframeseektime('1084')">0:18:04</a> tend to him  
<a onclick="modifyYTiframeseektime('1085')">0:18:05</a> right then allah turned to them so that  
<a onclick="modifyYTiframeseektime('1087')">0:18:07</a> they turned to him remember in adam's  
<a onclick="modifyYTiframeseektime('1089')">0:18:09</a> case it was allah turned to him first  
<a onclick="modifyYTiframeseektime('1092')">0:18:12</a> taught him first 25 so that he would  
<a onclick="modifyYTiframeseektime('1094')">0:18:14</a> turn to allah the same thing exists here  
<a onclick="modifyYTiframeseektime('1097')">0:18:17</a> then allah turned to them allah relented  
<a onclick="modifyYTiframeseektime('1099')">0:18:19</a> to them  
<a onclick="modifyYTiframeseektime('1100')">0:18:20</a> allah inclined to them so that they  
<a onclick="modifyYTiframeseektime('1102')">0:18:22</a> turned to him in repentance and allah is  
<a onclick="modifyYTiframeseektime('1105')">0:18:25</a> all forgiving allah is all merciful a  
<a onclick="modifyYTiframeseektime('1106')">0:18:26</a> beautiful paradigm here illustrating for  
<a onclick="modifyYTiframeseektime('1109')">0:18:29</a> us that concept of salvation in islam in  
<a onclick="modifyYTiframeseektime('1112')">0:18:32</a> light of the adam the adamic conundrum  
<a onclick="modifyYTiframeseektime('1115')">0:18:35</a> that we find you know going through from  
<a onclick="modifyYTiframeseektime('1118')">0:18:38</a> the biblical narrative to through  
<a onclick="modifyYTiframeseektime('1120')">0:18:40</a> centuries of christian theological  
<a onclick="modifyYTiframeseektime('1122')">0:18:42</a> debate about what happened with adam and  
<a onclick="modifyYTiframeseektime('1125')">0:18:45</a> his kind of cosmic significance between  
<a onclick="modifyYTiframeseektime('1127')">0:18:47</a> himself and god and and us as humans as  
<a onclick="modifyYTiframeseektime('1129')">0:18:49</a> his progeny and of jesus himself  
<a onclick="modifyYTiframeseektime('1133')">0:18:53</a> there's a lot of clarity therefore in  
<a onclick="modifyYTiframeseektime('1134')">0:18:54</a> the quranic in the quranic outlook may  
<a onclick="modifyYTiframeseektime('1137')">0:18:57</a> allah bless you all  
</details>