# Cosmic Atheist Comes Closer ... (2021-07-22)

<iframe loading='lazy' src='https://www.youtube.com/embed/ZdugED9KiQ8'></iframe>

## Description



## Summary of [Cosmic Atheist Comes Closer ...](https://www.youtube.com/watch?v=ZdugED9KiQ8)


*<span style="color:red; font-size:125%">This summary is AI generated - there may be inaccuracies</span>. [](/)*

### <a onclick="modifyYTiframeseektime('0')">00:00:00</a> - <a onclick="modifyYTiframeseektime('600')">00:10:00</a>

 discusses the difference between a "god" in human form and a "god" in nature. It argues that the concept of a god in human form is contradictory and irrational, and that only Islam has a rational conception of God.  concludes by urging viewers to be spiritual and critical in their search for truth.

**<a onclick="modifyYTiframeseektime('0')">00:00:00</a>** Cosmic Atheist comes closer to understanding the various arguments for and against the existence of god. He finds the contingency argument to be the most plausible on a surface level, but is still undecided about his position. He appreciates Mick for bringing up the contingency argument, and hopes that he does not change his mind on the matter.
* **<a onclick="modifyYTiframeseektime('300')">00:05:00</a>* Discusses the difference between a "god" in human form and a "god" in nature. It argues that the concept of a god in human form is contradictory and irrational, and that only Islam has a rational conception of God.  concludes by urging viewers to be spiritual and critical in their search for truth.
* **<a onclick="modifyYTiframeseektime('600')">00:10:00</a>** The cosmic atheist argues that the relationship between humans and the necessary existence is one of submission. Everything else in creation is submitting to the will of the necessary existence, so humans must do the same if they want to be at one with nature.

<details><summary><h2>Full transcript with timestamps: CLICK TO EXPAND</h2></summary>

<a onclick="modifyYTiframeseektime('0')">0:00:00</a> boxes that it raises i i think that's  
<a onclick="modifyYTiframeseektime('2')">0:00:02</a> potentially more plausible  
<a onclick="modifyYTiframeseektime('4')">0:00:04</a> um but my i should i should stress that  
<a onclick="modifyYTiframeseektime('6')">0:00:06</a> the agnosticism the agnostic atheism  
<a onclick="modifyYTiframeseektime('8')">0:00:08</a> that i currently  
<a onclick="modifyYTiframeseektime('9')">0:00:09</a> possess is quite unlike the one that i  
<a onclick="modifyYTiframeseektime('12')">0:00:12</a> had maybe four years ago beforehand it  
<a onclick="modifyYTiframeseektime('14')">0:00:14</a> was very much the case  
<a onclick="modifyYTiframeseektime('16')">0:00:16</a> that i essentially would have said like  
<a onclick="modifyYTiframeseektime('18')">0:00:18</a> there aren't really any good reasons to  
<a onclick="modifyYTiframeseektime('20')">0:00:20</a> think that god exists  
<a onclick="modifyYTiframeseektime('21')">0:00:21</a> or at least those reasons that have been  
<a onclick="modifyYTiframeseektime('22')">0:00:22</a> put forward i think don't work  
<a onclick="modifyYTiframeseektime('25')">0:00:25</a> now and that is to say i was sat on the  
<a onclick="modifyYTiframeseektime('27')">0:00:27</a> fence  
<a onclick="modifyYTiframeseektime('28')">0:00:28</a> um because there was just there was just  
<a onclick="modifyYTiframeseektime('30')">0:00:30</a> no breeze there was just no breeze to  
<a onclick="modifyYTiframeseektime('31')">0:00:31</a> push me onto one side  
<a onclick="modifyYTiframeseektime('32')">0:00:32</a> one side i was just sat there um now  
<a onclick="modifyYTiframeseektime('36')">0:00:36</a> i'm still sad on the fence i'm still an  
<a onclick="modifyYTiframeseektime('38')">0:00:38</a> agnostic atheist of some description  
<a onclick="modifyYTiframeseektime('41')">0:00:41</a> but now it's more like there are equally  
<a onclick="modifyYTiframeseektime('43')">0:00:43</a> uh  
<a onclick="modifyYTiframeseektime('44')">0:00:44</a> beautiful breezes pushing in opposite  
<a onclick="modifyYTiframeseektime('45')">0:00:45</a> directions right so i do  
<a onclick="modifyYTiframeseektime('47')">0:00:47</a> think that uh the contingency argument  
<a onclick="modifyYTiframeseektime('51')">0:00:51</a> for the existence of god is a strong one  
<a onclick="modifyYTiframeseektime('53')">0:00:53</a> i do think that  
<a onclick="modifyYTiframeseektime('55')">0:00:55</a> certain ontological arguments you know  
<a onclick="modifyYTiframeseektime('56')">0:00:56</a> if there are certain quarrels like the  
<a onclick="modifyYTiframeseektime('58')">0:00:58</a> one we're having now can be  
<a onclick="modifyYTiframeseektime('59')">0:00:59</a> resolved like is is a good argument is  
<a onclick="modifyYTiframeseektime('62')">0:01:02</a> at least a good attempt  
<a onclick="modifyYTiframeseektime('62')">0:01:02</a> to prove the existence of god um i think  
<a onclick="modifyYTiframeseektime('64')">0:01:04</a> that the idea of an infinite regress  
<a onclick="modifyYTiframeseektime('66')">0:01:06</a> probably does lead to unacceptable  
<a onclick="modifyYTiframeseektime('68')">0:01:08</a> paradoxes and so  
<a onclick="modifyYTiframeseektime('70')">0:01:10</a> i would say that on its own yes  
<a onclick="modifyYTiframeseektime('73')">0:01:13</a> like it's a it's a i think there's good  
<a onclick="modifyYTiframeseektime('76')">0:01:16</a> reason to think that there is a  
<a onclick="modifyYTiframeseektime('77')">0:01:17</a> necessary unmoved mover  
<a onclick="modifyYTiframeseektime('78')">0:01:18</a> however now the agnosticism is that  
<a onclick="modifyYTiframeseektime('80')">0:01:20</a> that's the breeze pushing in one  
<a onclick="modifyYTiframeseektime('81')">0:01:21</a> direction  
<a onclick="modifyYTiframeseektime('82')">0:01:22</a> uh but there's also now i've i've been  
<a onclick="modifyYTiframeseektime('85')">0:01:25</a> more  
<a onclick="modifyYTiframeseektime('86')">0:01:26</a> um uh i've i've thought a lot more and a  
<a onclick="modifyYTiframeseektime('90')">0:01:30</a> lot more deeply about the breezes that  
<a onclick="modifyYTiframeseektime('91')">0:01:31</a> would go in the opposite direction  
<a onclick="modifyYTiframeseektime('93')">0:01:33</a> involving the problem of evil or divine  
<a onclick="modifyYTiframeseektime('94')">0:01:34</a> hiddenness or animal suffering in  
<a onclick="modifyYTiframeseektime('95')">0:01:35</a> particular and these kinds of things  
<a onclick="modifyYTiframeseektime('97')">0:01:37</a> the potential paradox is involved in the  
<a onclick="modifyYTiframeseektime('99')">0:01:39</a> necessary being arguments about modal  
<a onclick="modifyYTiframeseektime('101')">0:01:41</a> fatalism for instance that we were just  
<a onclick="modifyYTiframeseektime('102')">0:01:42</a> talking about  
<a onclick="modifyYTiframeseektime('103')">0:01:43</a> that now pushed me in the other  
<a onclick="modifyYTiframeseektime('104')">0:01:44</a> direction so on its own yeah i do i do  
<a onclick="modifyYTiframeseektime('107')">0:01:47</a> i do find more plausible on a surface  
<a onclick="modifyYTiframeseektime('109')">0:01:49</a> level  
<a onclick="modifyYTiframeseektime('110')">0:01:50</a> um the idea of a necessary unmoved mover  
<a onclick="modifyYTiframeseektime('113')">0:01:53</a> than the idea of an infinite regress of  
<a onclick="modifyYTiframeseektime('115')">0:01:55</a> causes  
<a onclick="modifyYTiframeseektime('116')">0:01:56</a> if you asked about it in isolation  
<a onclick="modifyYTiframeseektime('119')">0:01:59</a> as you guys saw there cosmic has come to  
<a onclick="modifyYTiframeseektime('122')">0:02:02</a> a good realization i believe  
<a onclick="modifyYTiframeseektime('123')">0:02:03</a> which shows criticality possibly  
<a onclick="modifyYTiframeseektime('126')">0:02:06</a> sincerity shows open-mindedness on his  
<a onclick="modifyYTiframeseektime('128')">0:02:08</a> behalf  
<a onclick="modifyYTiframeseektime('129')">0:02:09</a> that uh you know there are good reasons  
<a onclick="modifyYTiframeseektime('132')">0:02:12</a> to believe in things like the  
<a onclick="modifyYTiframeseektime('132')">0:02:12</a> contingency argument which as  
<a onclick="modifyYTiframeseektime('134')">0:02:14</a> many of you know i've written a book  
<a onclick="modifyYTiframeseektime('135')">0:02:15</a> about i'm doing my phd about  
<a onclick="modifyYTiframeseektime('137')">0:02:17</a> because i personally believe it's it's  
<a onclick="modifyYTiframeseektime('140')">0:02:20</a> something which is really it's  
<a onclick="modifyYTiframeseektime('141')">0:02:21</a> inescapable the conclusion of it is  
<a onclick="modifyYTiframeseektime('142')">0:02:22</a> inescapable almost it's irrefutable i  
<a onclick="modifyYTiframeseektime('144')">0:02:24</a> believe and it's been around  
<a onclick="modifyYTiframeseektime('146')">0:02:26</a> uh forms of it have been around for for  
<a onclick="modifyYTiframeseektime('148')">0:02:28</a> thousands of years it's been around  
<a onclick="modifyYTiframeseektime('149')">0:02:29</a> since the hellenistic period  
<a onclick="modifyYTiframeseektime('151')">0:02:31</a> and then it's been kind of revamped by  
<a onclick="modifyYTiframeseektime('153')">0:02:33</a> avicenna  
<a onclick="modifyYTiframeseektime('154')">0:02:34</a> and then it was uh taken again by thomas  
<a onclick="modifyYTiframeseektime('156')">0:02:36</a> aquinas and maimonides and musabi  
<a onclick="modifyYTiframeseektime('159')">0:02:39</a> and it was taken again by leibniz and  
<a onclick="modifyYTiframeseektime('161')">0:02:41</a> different forms has been  
<a onclick="modifyYTiframeseektime('162')">0:02:42</a> elaborated upon and uh spoken about by  
<a onclick="modifyYTiframeseektime('165')">0:02:45</a> different thinkers and  
<a onclick="modifyYTiframeseektime('166')">0:02:46</a> in my estimation it's it's the least  
<a onclick="modifyYTiframeseektime('168')">0:02:48</a> refuted argument for god's existence yes  
<a onclick="modifyYTiframeseektime('170')">0:02:50</a> there are other arguments  
<a onclick="modifyYTiframeseektime('171')">0:02:51</a> that have been used and these are kalam  
<a onclick="modifyYTiframeseektime('174')">0:02:54</a> cosmological arguments  
<a onclick="modifyYTiframeseektime('175')">0:02:55</a> and different types of calam  
<a onclick="modifyYTiframeseektime('176')">0:02:56</a> cosmological arguments of course i've  
<a onclick="modifyYTiframeseektime('178')">0:02:58</a> written a book called  
<a onclick="modifyYTiframeseektime('179')">0:02:59</a> cosmological arguments if you guys are  
<a onclick="modifyYTiframeseektime('180')">0:03:00</a> interested and of course  
<a onclick="modifyYTiframeseektime('182')">0:03:02</a> in this in the debate i had of course  
<a onclick="modifyYTiframeseektime('184')">0:03:04</a> mick i brought the contingency argument  
<a onclick="modifyYTiframeseektime('186')">0:03:06</a> up now unfortunately you know  
<a onclick="modifyYTiframeseektime('189')">0:03:09</a> we we couldn't really get anything from  
<a onclick="modifyYTiframeseektime('191')">0:03:11</a> him as to  
<a onclick="modifyYTiframeseektime('192')">0:03:12</a> by way of a refutation of the argument  
<a onclick="modifyYTiframeseektime('194')">0:03:14</a> now we know he actually sees it as  
<a onclick="modifyYTiframeseektime('195')">0:03:15</a> actually quite powerful argument  
<a onclick="modifyYTiframeseektime('197')">0:03:17</a> which is good i'm happy that he's come  
<a onclick="modifyYTiframeseektime('199')">0:03:19</a> to this conclusion it shows it shows  
<a onclick="modifyYTiframeseektime('200')">0:03:20</a> maturity on his behalf educational  
<a onclick="modifyYTiframeseektime('202')">0:03:22</a> maturity i really hope he doesn't change  
<a onclick="modifyYTiframeseektime('204')">0:03:24</a> his mind on this and  
<a onclick="modifyYTiframeseektime('205')">0:03:25</a> because that will show instability in uh  
<a onclick="modifyYTiframeseektime('208')">0:03:28</a> in process and  
<a onclick="modifyYTiframeseektime('209')">0:03:29</a> cognitive processes that one day you  
<a onclick="modifyYTiframeseektime('211')">0:03:31</a> believe in this and that you know and  
<a onclick="modifyYTiframeseektime('212')">0:03:32</a> that they believe in that  
<a onclick="modifyYTiframeseektime('213')">0:03:33</a> i really hope that he sticks to his guns  
<a onclick="modifyYTiframeseektime('215')">0:03:35</a> on this and he doesn't change his mind  
<a onclick="modifyYTiframeseektime('217')">0:03:37</a> on his at least  
<a onclick="modifyYTiframeseektime('218')">0:03:38</a> his classification of design um and also  
<a onclick="modifyYTiframeseektime('221')">0:03:41</a> i would say well done  
<a onclick="modifyYTiframeseektime('222')">0:03:42</a> well done to him good man that you've  
<a onclick="modifyYTiframeseektime('223')">0:03:43</a> done that the things that he's actually  
<a onclick="modifyYTiframeseektime('225')">0:03:45</a> mentioned  
<a onclick="modifyYTiframeseektime('226')">0:03:46</a> um in terms of things that are pushing  
<a onclick="modifyYTiframeseektime('228')">0:03:48</a> him in the other direction  
<a onclick="modifyYTiframeseektime('230')">0:03:50</a> on his analogy or his uh language some  
<a onclick="modifyYTiframeseektime('233')">0:03:53</a> the breeze that pushes the other way  
<a onclick="modifyYTiframeseektime('235')">0:03:55</a> things like divine heightenedness or our  
<a onclick="modifyYTiframeseektime('237')">0:03:57</a> hiddenness  
<a onclick="modifyYTiframeseektime('238')">0:03:58</a> and um you know the problem of evil  
<a onclick="modifyYTiframeseektime('241')">0:04:01</a> obviously it's been spoken about at  
<a onclick="modifyYTiframeseektime('242')">0:04:02</a> length  
<a onclick="modifyYTiframeseektime('243')">0:04:03</a> we have um videos on it you can put my  
<a onclick="modifyYTiframeseektime('245')">0:04:05</a> name on youtube and put  
<a onclick="modifyYTiframeseektime('246')">0:04:06</a> for example the problem of evil i've  
<a onclick="modifyYTiframeseektime('247')">0:04:07</a> spoken about it at length and what is  
<a onclick="modifyYTiframeseektime('249')">0:04:09</a> evil does it even exist on  
<a onclick="modifyYTiframeseektime('250')">0:04:10</a> the atheistic paradigm does it even  
<a onclick="modifyYTiframeseektime('252')">0:04:12</a> exist from the materialistic paradigm  
<a onclick="modifyYTiframeseektime('254')">0:04:14</a> um you know and so on  
<a onclick="modifyYTiframeseektime('258')">0:04:18</a> what does it mean to to say well does  
<a onclick="modifyYTiframeseektime('261')">0:04:21</a> evil exist does that disprove  
<a onclick="modifyYTiframeseektime('262')">0:04:22</a> in god we've had these conversations of  
<a onclick="modifyYTiframeseektime('264')">0:04:24</a> course these are secondary  
<a onclick="modifyYTiframeseektime('266')">0:04:26</a> considerations in my opinion these are  
<a onclick="modifyYTiframeseektime('267')">0:04:27</a> secondary considerations once you've  
<a onclick="modifyYTiframeseektime('269')">0:04:29</a> established  
<a onclick="modifyYTiframeseektime('270')">0:04:30</a> the reality of a necessary existence  
<a onclick="modifyYTiframeseektime('271')">0:04:31</a> this is more powerful than anything else  
<a onclick="modifyYTiframeseektime('273')">0:04:33</a> and the fact that he's been able to do  
<a onclick="modifyYTiframeseektime('275')">0:04:35</a> this is really really good and he's one  
<a onclick="modifyYTiframeseektime('277')">0:04:37</a> step closer to the ultimate truth and i  
<a onclick="modifyYTiframeseektime('279')">0:04:39</a> really encourage him to do that  
<a onclick="modifyYTiframeseektime('281')">0:04:41</a> to move in that direction maybe what he  
<a onclick="modifyYTiframeseektime('283')">0:04:43</a> said would not have been well received  
<a onclick="modifyYTiframeseektime('285')">0:04:45</a> uh with with his people and this the  
<a onclick="modifyYTiframeseektime('287')">0:04:47</a> people supporters and you know  
<a onclick="modifyYTiframeseektime('289')">0:04:49</a> subscribers and so on but i i really  
<a onclick="modifyYTiframeseektime('292')">0:04:52</a> acknowledge that this is a brave step  
<a onclick="modifyYTiframeseektime('293')">0:04:53</a> forward and i hope we continue taking  
<a onclick="modifyYTiframeseektime('294')">0:04:54</a> these brave step forwards well done to  
<a onclick="modifyYTiframeseektime('296')">0:04:56</a> him  
<a onclick="modifyYTiframeseektime('296')">0:04:56</a> um the other thing divine hiddenness or  
<a onclick="modifyYTiframeseektime('299')">0:04:59</a> the fact that god is hidden from the  
<a onclick="modifyYTiframeseektime('300')">0:05:00</a> people  
<a onclick="modifyYTiframeseektime('301')">0:05:01</a> why is he so hidden this is something  
<a onclick="modifyYTiframeseektime('303')">0:05:03</a> obviously we as muslims don't believe  
<a onclick="modifyYTiframeseektime('305')">0:05:05</a> and we believe that  
<a onclick="modifyYTiframeseektime('308')">0:05:08</a> that every human being is born on the  
<a onclick="modifyYTiframeseektime('310')">0:05:10</a> predisposition and believing in god  
<a onclick="modifyYTiframeseektime('312')">0:05:12</a> and this is something i've mentioned  
<a onclick="modifyYTiframeseektime('313')">0:05:13</a> this i think even the debate i mentioned  
<a onclick="modifyYTiframeseektime('314')">0:05:14</a> but i want to remind everyone of it  
<a onclick="modifyYTiframeseektime('316')">0:05:16</a> it's the uh the or the predisposition is  
<a onclick="modifyYTiframeseektime('318')">0:05:18</a> something which has good  
<a onclick="modifyYTiframeseektime('319')">0:05:19</a> evidence by way of anthropological  
<a onclick="modifyYTiframeseektime('322')">0:05:22</a> evidence and sociological evidence so  
<a onclick="modifyYTiframeseektime('324')">0:05:24</a> for example justin barrett  
<a onclick="modifyYTiframeseektime('325')">0:05:25</a> who in 2011 part of the oxford  
<a onclick="modifyYTiframeseektime('328')">0:05:28</a> anthropological society  
<a onclick="modifyYTiframeseektime('330')">0:05:30</a> uh spoke about us having an innate  
<a onclick="modifyYTiframeseektime('332')">0:05:32</a> receptivity to believing in god and  
<a onclick="modifyYTiframeseektime('334')">0:05:34</a> you know he done these the study that  
<a onclick="modifyYTiframeseektime('335')">0:05:35</a> children before socialization  
<a onclick="modifyYTiframeseektime('337')">0:05:37</a> that there's something which is kind of  
<a onclick="modifyYTiframeseektime('339')">0:05:39</a> um corresponds across culture  
<a onclick="modifyYTiframeseektime('342')">0:05:42</a> cross-culturally uh among children which  
<a onclick="modifyYTiframeseektime('344')">0:05:44</a> is that children do have this  
<a onclick="modifyYTiframeseektime('345')">0:05:45</a> receptivity  
<a onclick="modifyYTiframeseektime('346')">0:05:46</a> in his words uh in a a receptivity to  
<a onclick="modifyYTiframeseektime('349')">0:05:49</a> believing in a higher being  
<a onclick="modifyYTiframeseektime('350')">0:05:50</a> and i say that this is this is evidence  
<a onclick="modifyYTiframeseektime('352')">0:05:52</a> to the contrary of  
<a onclick="modifyYTiframeseektime('354')">0:05:54</a> um which can be juxtaposed with the idea  
<a onclick="modifyYTiframeseektime('358')">0:05:58</a> of uh  
<a onclick="modifyYTiframeseektime('364')">0:06:04</a> hide-and-seek  
<a onclick="modifyYTiframeseektime('366')">0:06:06</a> that's one thing aside i wanted to  
<a onclick="modifyYTiframeseektime('367')">0:06:07</a> continue thinking about these things and  
<a onclick="modifyYTiframeseektime('369')">0:06:09</a> obviously animal rights or something  
<a onclick="modifyYTiframeseektime('370')">0:06:10</a> which we as muslims  
<a onclick="modifyYTiframeseektime('372')">0:06:12</a> we very much we very much respect  
<a onclick="modifyYTiframeseektime('375')">0:06:15</a> there's a hadith of a woman who's a  
<a onclick="modifyYTiframeseektime('377')">0:06:17</a> prostitute okay  
<a onclick="modifyYTiframeseektime('378')">0:06:18</a> that she gave a dog water and according  
<a onclick="modifyYTiframeseektime('381')">0:06:21</a> to that she was forgiven for her sins  
<a onclick="modifyYTiframeseektime('383')">0:06:23</a> for doing that  
<a onclick="modifyYTiframeseektime('383')">0:06:23</a> just because she gave a dog water even  
<a onclick="modifyYTiframeseektime('385')">0:06:25</a> though she's defiled herself  
<a onclick="modifyYTiframeseektime('387')">0:06:27</a> in the most disgusting way possible by  
<a onclick="modifyYTiframeseektime('390')">0:06:30</a> living  
<a onclick="modifyYTiframeseektime('391')">0:06:31</a> not the most disgusting way possible  
<a onclick="modifyYTiframeseektime('393')">0:06:33</a> doing that would be to be a polytheist  
<a onclick="modifyYTiframeseektime('395')">0:06:35</a> but in a very damning way but that she  
<a onclick="modifyYTiframeseektime('398')">0:06:38</a> gave that dog  
<a onclick="modifyYTiframeseektime('399')">0:06:39</a> water would put her in a among the  
<a onclick="modifyYTiframeseektime('402')">0:06:42</a> people that are forgiven as a dog  
<a onclick="modifyYTiframeseektime('404')">0:06:44</a> and we believe that the day of judgment  
<a onclick="modifyYTiframeseektime('405')">0:06:45</a> is a forum where in which all of these  
<a onclick="modifyYTiframeseektime('408')">0:06:48</a> kinds of  
<a onclick="modifyYTiframeseektime('408')">0:06:48</a> injustices that have been done to  
<a onclick="modifyYTiframeseektime('410')">0:06:50</a> animals will be kind of um  
<a onclick="modifyYTiframeseektime('412')">0:06:52</a> adjusted and in fact that is the day of  
<a onclick="modifyYTiframeseektime('414')">0:06:54</a> recompense and we have a beautiful  
<a onclick="modifyYTiframeseektime('415')">0:06:55</a> hadith  
<a onclick="modifyYTiframeseektime('416')">0:06:56</a> um that talks about the two goats one of  
<a onclick="modifyYTiframeseektime('418')">0:06:58</a> them horned goat and the other one is  
<a onclick="modifyYTiframeseektime('419')">0:06:59</a> not horned  
<a onclick="modifyYTiframeseektime('420')">0:07:00</a> and the one that attacked one horned  
<a onclick="modifyYTiframeseektime('422')">0:07:02</a> goat the attack the other goat without  
<a onclick="modifyYTiframeseektime('424')">0:07:04</a> horns  
<a onclick="modifyYTiframeseektime('425')">0:07:05</a> will now get its retribution so  
<a onclick="modifyYTiframeseektime('426')">0:07:06</a> everything will be  
<a onclick="modifyYTiframeseektime('428')">0:07:08</a> fully uh and yeah it's true like what we  
<a onclick="modifyYTiframeseektime('430')">0:07:10</a> see today and obviously we don't come to  
<a onclick="modifyYTiframeseektime('432')">0:07:12</a> vegan conclusions  
<a onclick="modifyYTiframeseektime('433')">0:07:13</a> but we see today by way of uh animal  
<a onclick="modifyYTiframeseektime('436')">0:07:16</a> suffering so like  
<a onclick="modifyYTiframeseektime('437')">0:07:17</a> we we think that that is against the sun  
<a onclick="modifyYTiframeseektime('439')">0:07:19</a> against islam you know the  
<a onclick="modifyYTiframeseektime('440')">0:07:20</a> cutting the beaks off the chicken and  
<a onclick="modifyYTiframeseektime('442')">0:07:22</a> suffocating them and so on  
<a onclick="modifyYTiframeseektime('443')">0:07:23</a> this is if the prophet was around he  
<a onclick="modifyYTiframeseektime('445')">0:07:25</a> would surely have  
<a onclick="modifyYTiframeseektime('446')">0:07:26</a> uh have have negated and  
<a onclick="modifyYTiframeseektime('450')">0:07:30</a> refuted that kind of thing uh especially  
<a onclick="modifyYTiframeseektime('453')">0:07:33</a> when we have hadith to that effect for  
<a onclick="modifyYTiframeseektime('454')">0:07:34</a> example the woman who's  
<a onclick="modifyYTiframeseektime('456')">0:07:36</a> who um was torturing her cat okay and  
<a onclick="modifyYTiframeseektime('460')">0:07:40</a> she went to hell  
<a onclick="modifyYTiframeseektime('460')">0:07:40</a> for that or she we know that she's gonna  
<a onclick="modifyYTiframeseektime('462')">0:07:42</a> go to hell for that because she  
<a onclick="modifyYTiframeseektime('464')">0:07:44</a> what kind of person does it take to  
<a onclick="modifyYTiframeseektime('465')">0:07:45</a> really torture another innocent creature  
<a onclick="modifyYTiframeseektime('467')">0:07:47</a> like a cat  
<a onclick="modifyYTiframeseektime('468')">0:07:48</a> so yeah animal rights are important uh  
<a onclick="modifyYTiframeseektime('470')">0:07:50</a> divine hiddenness if you think of it in  
<a onclick="modifyYTiframeseektime('472')">0:07:52</a> you know in contra in contra distinction  
<a onclick="modifyYTiframeseektime('475')">0:07:55</a> with the fetal you'll realize  
<a onclick="modifyYTiframeseektime('477')">0:07:57</a> that the fethra of the predisposition is  
<a onclick="modifyYTiframeseektime('479')">0:07:59</a> actually something which is super  
<a onclick="modifyYTiframeseektime('480')">0:08:00</a> rational and um  
<a onclick="modifyYTiframeseektime('482')">0:08:02</a> precedes any rational argumentation  
<a onclick="modifyYTiframeseektime('483')">0:08:03</a> which is why i was thinking about this  
<a onclick="modifyYTiframeseektime('485')">0:08:05</a> this verse in the quran which is a  
<a onclick="modifyYTiframeseektime('488')">0:08:08</a> really beautiful verse  
<a onclick="modifyYTiframeseektime('489')">0:08:09</a> and it came about in and i thought about  
<a onclick="modifyYTiframeseektime('491')">0:08:11</a> pondering over it it was a  
<a onclick="modifyYTiframeseektime('493')">0:08:13</a> verse that said uh  
<a onclick="modifyYTiframeseektime('503')">0:08:23</a> you know if you're in any doubt as to  
<a onclick="modifyYTiframeseektime('506')">0:08:26</a> the religion of islam  
<a onclick="modifyYTiframeseektime('507')">0:08:27</a> my religion the prophet muhammad's  
<a onclick="modifyYTiframeseektime('509')">0:08:29</a> religion not just his religion but the  
<a onclick="modifyYTiframeseektime('510')">0:08:30</a> religion of moses and abraham and jesus  
<a onclick="modifyYTiframeseektime('512')">0:08:32</a> and those as well then i don't worship  
<a onclick="modifyYTiframeseektime('515')">0:08:35</a> other gods that you that are worshiped  
<a onclick="modifyYTiframeseektime('519')">0:08:39</a> aside from god but i worship god who  
<a onclick="modifyYTiframeseektime('522')">0:08:42</a> who brings us like who who takes away  
<a onclick="modifyYTiframeseektime('524')">0:08:44</a> our lives and takes away our souls and  
<a onclick="modifyYTiframeseektime('526')">0:08:46</a> takes away our consciousness  
<a onclick="modifyYTiframeseektime('529')">0:08:49</a> this is such a powerful thing because  
<a onclick="modifyYTiframeseektime('531')">0:08:51</a> really if you look at the six  
<a onclick="modifyYTiframeseektime('532')">0:08:52</a> major world religions in the world today  
<a onclick="modifyYTiframeseektime('536')">0:08:56</a> you'll find that islam is the only one  
<a onclick="modifyYTiframeseektime('537')">0:08:57</a> with the conception of god which is also  
<a onclick="modifyYTiframeseektime('539')">0:08:59</a> not only only natural but rational as  
<a onclick="modifyYTiframeseektime('541')">0:09:01</a> well  
<a onclick="modifyYTiframeseektime('542')">0:09:02</a> this is the reality like we don't  
<a onclick="modifyYTiframeseektime('544')">0:09:04</a> believe in a man god we don't believe  
<a onclick="modifyYTiframeseektime('546')">0:09:06</a> it's conceivable or intelligible  
<a onclick="modifyYTiframeseektime('548')">0:09:08</a> or acceptable to believe that there's  
<a onclick="modifyYTiframeseektime('549')">0:09:09</a> any part any human being is  
<a onclick="modifyYTiframeseektime('551')">0:09:11</a> is is god because it necessitates  
<a onclick="modifyYTiframeseektime('554')">0:09:14</a> contradictions in terms we don't believe  
<a onclick="modifyYTiframeseektime('556')">0:09:16</a> in an animal god we don't believe in a  
<a onclick="modifyYTiframeseektime('558')">0:09:18</a> man god  
<a onclick="modifyYTiframeseektime('559')">0:09:19</a> you see what i mean and so you've  
<a onclick="modifyYTiframeseektime('561')">0:09:21</a> already stricken off  
<a onclick="modifyYTiframeseektime('562')">0:09:22</a> christianity we've already stricken off  
<a onclick="modifyYTiframeseektime('563')">0:09:23</a> hinduism a pantheistic notion of it  
<a onclick="modifyYTiframeseektime('565')">0:09:25</a> we've already stricken off fantastic  
<a onclick="modifyYTiframeseektime('567')">0:09:27</a> notions of sikhism  
<a onclick="modifyYTiframeseektime('568')">0:09:28</a> uh so what are we left with we're left  
<a onclick="modifyYTiframeseektime('571')">0:09:31</a> with judaism  
<a onclick="modifyYTiframeseektime('572')">0:09:32</a> right which is a very um exclusivist  
<a onclick="modifyYTiframeseektime('574')">0:09:34</a> faith what we left with right  
<a onclick="modifyYTiframeseektime('577')">0:09:37</a> not much buddhism which is not even a  
<a onclick="modifyYTiframeseektime('579')">0:09:39</a> faith really in that sense  
<a onclick="modifyYTiframeseektime('581')">0:09:41</a> uh so what we say therefore is keep  
<a onclick="modifyYTiframeseektime('584')">0:09:44</a> looking  
<a onclick="modifyYTiframeseektime('584')">0:09:44</a> not just to him but to his followers as  
<a onclick="modifyYTiframeseektime('586')">0:09:46</a> well keep looking keep being  
<a onclick="modifyYTiframeseektime('588')">0:09:48</a> critical and you'll come to this  
<a onclick="modifyYTiframeseektime('590')">0:09:50</a> conclusion but just one more thing be  
<a onclick="modifyYTiframeseektime('592')">0:09:52</a> spiritual as well if there is a  
<a onclick="modifyYTiframeseektime('593')">0:09:53</a> necessary existence  
<a onclick="modifyYTiframeseektime('595')">0:09:55</a> then think of one thing what  
<a onclick="modifyYTiframeseektime('597')">0:09:57</a> relationship are we meant to have with  
<a onclick="modifyYTiframeseektime('598')">0:09:58</a> this necessary existence  
<a onclick="modifyYTiframeseektime('601')">0:10:01</a> what relationship are we meant to have  
<a onclick="modifyYTiframeseektime('602')">0:10:02</a> and the answer we give is as follows  
<a onclick="modifyYTiframeseektime('604')">0:10:04</a> the relationship we are meant to have  
<a onclick="modifyYTiframeseektime('605')">0:10:05</a> with the necessary existence is the  
<a onclick="modifyYTiframeseektime('607')">0:10:07</a> relationship of submission  
<a onclick="modifyYTiframeseektime('608')">0:10:08</a> everything else in creation is  
<a onclick="modifyYTiframeseektime('610')">0:10:10</a> submitting to the will of the necessary  
<a onclick="modifyYTiframeseektime('612')">0:10:12</a> existence  
<a onclick="modifyYTiframeseektime('613')">0:10:13</a> we must do the same if we do the same we  
<a onclick="modifyYTiframeseektime('616')">0:10:16</a> will be at one with nature in the  
<a onclick="modifyYTiframeseektime('618')">0:10:18</a> sense of the word which is acceptable uh  
<a onclick="modifyYTiframeseektime('621')">0:10:21</a> you know which is which makes sense  
<a onclick="modifyYTiframeseektime('623')">0:10:23</a> because we'll be doing everything we'll  
<a onclick="modifyYTiframeseektime('624')">0:10:24</a> be doing things which everything else in  
<a onclick="modifyYTiframeseektime('626')">0:10:26</a> creation is doing which is submitting to  
<a onclick="modifyYTiframeseektime('628')">0:10:28</a> the laws of the law maker  
<a onclick="modifyYTiframeseektime('630')">0:10:30</a> and so think think think and i would ask  
<a onclick="modifyYTiframeseektime('632')">0:10:32</a> i would ask everyone really if  
<a onclick="modifyYTiframeseektime('634')">0:10:34</a> just make supplication because we  
<a onclick="modifyYTiframeseektime('637')">0:10:37</a> believe as muslims  
<a onclick="modifyYTiframeseektime('638')">0:10:38</a> the quran says  
<a onclick="modifyYTiframeseektime('644')">0:10:44</a> and if my slaves doesn't say the muslims  
<a onclick="modifyYTiframeseektime('648')">0:10:48</a> if my slaves ask about me then i am near  
<a onclick="modifyYTiframeseektime('651')">0:10:51</a> and i answer the caller of the call when  
<a onclick="modifyYTiframeseektime('653')">0:10:53</a> he calls so call  
<a onclick="modifyYTiframeseektime('655')">0:10:55</a> on to god and ask him to guide you  
<a onclick="modifyYTiframeseektime('656')">0:10:56</a> because believe me  
<a onclick="modifyYTiframeseektime('658')">0:10:58</a> believe you me if you do it you will be  
<a onclick="modifyYTiframeseektime('660')">0:11:00</a> successful  
</details>