# Dr. Jordan Peterson's Major Blunders and Weak Points on Islam (2021-11-07)

<iframe loading='lazy' src='https://www.youtube.com/embed/dt7ruyaA0t4'></iframe>

## Description

Twitter: https://twitter.com/mohammed_hijab?s=20
Instagram: https://www.instagram.com/mohammedhijabofficial/?hl=en
Facebook: https://www.facebook.com/brothermohammedhijab/
Soundcloud: https://soundcloud.com/mohammed-hijab-465985305
My book: https://sapienceinstitute.org/the-scientific-deception-of-the-new-atheists/

## Summary of [Dr. Jordan Peterson's Major Blunders and Weak Points on Islam](https://www.youtube.com/watch?v=dt7ruyaA0t4)


*<span style="color:red; font-size:125%">This summary is AI generated - there may be inaccuracies</span>. [](/)*

### <a onclick="modifyYTiframeseektime('0')">00:00:00</a> - <a onclick="modifyYTiframeseektime('600')">00:10:00</a>

Jordan Peterson's arguments about Islam are flawed and inaccurate. He fails to take into account the different ethics and cultures of different countries, and his arguments do not take into account the Islamic contribution to civilizations such as the West. Peterson's followers may benefit from his corrections.

**<a onclick="modifyYTiframeseektime('0')">00:00:00</a>** Jordan Peterson claims that Islam is a religion of war and that it was embroiled in a civil war from the day of Muhammad's death. He provides no evidence to support these claims, and his statement is inaccurate.
* **<a onclick="modifyYTiframeseektime('300')">00:05:00</a>** Jordan Peterson's argument that states that are occupied by Islam are not economically productive is flawed. Peterson does not provide any evidence to support this claim, and instead resorts to vague language and anecdotes. Additionally, Peterson's argument is contradicted by historical examples of successful Islamic empires.
* **<a onclick="modifyYTiframeseektime('600')">00:10:00</a>** Jordan Peterson's arguments about Islam are flawed and inaccurate. He fails to take into account the different ethics and cultures of different countries, and his arguments do not take into account the Islamic contribution to civilizations such as the West. Peterson's followers may benefit from his corrections.

<details><summary><h2>Full transcript with timestamps: CLICK TO EXPAND</h2></summary>

<a onclick="modifyYTiframeseektime('0')">0:00:00</a> [Music]  
<a onclick="modifyYTiframeseektime('5')">0:00:05</a> go to kuala lude app inshallah the app  
<a onclick="modifyYTiframeseektime('7')">0:00:07</a> tracks versus pages and time spent  
<a onclick="modifyYTiframeseektime('10')">0:00:10</a> reading and the verses to pages function  
<a onclick="modifyYTiframeseektime('12')">0:00:12</a> takes you from reading a few verses a  
<a onclick="modifyYTiframeseektime('14')">0:00:14</a> day to a few pages a day this project is  
<a onclick="modifyYTiframeseektime('17')">0:00:17</a> for the real enthusiasts if there's  
<a onclick="modifyYTiframeseektime('19')">0:00:19</a> enough of us out there this will become  
<a onclick="modifyYTiframeseektime('21')">0:00:21</a> the future of quran  
<a onclick="modifyYTiframeseektime('23')">0:00:23</a> and support the project if you can insha  
<a onclick="modifyYTiframeseektime('25')">0:00:25</a> allah may allah bless all of you  
<a onclick="modifyYTiframeseektime('28')">0:00:28</a> assalamu  
<a onclick="modifyYTiframeseektime('30')">0:00:30</a> how are you guys doing and welcome to  
<a onclick="modifyYTiframeseektime('32')">0:00:32</a> the third  
<a onclick="modifyYTiframeseektime('33')">0:00:33</a> of a series of videos we're doing  
<a onclick="modifyYTiframeseektime('35')">0:00:35</a> correcting some of the mistakes of dr  
<a onclick="modifyYTiframeseektime('36')">0:00:36</a> jordan peterson about islam and muslims  
<a onclick="modifyYTiframeseektime('39')">0:00:39</a> and really this series is uh intended to  
<a onclick="modifyYTiframeseektime('41')">0:00:41</a> edify and to educate not just jordan  
<a onclick="modifyYTiframeseektime('44')">0:00:44</a> peterson himself but some of his  
<a onclick="modifyYTiframeseektime('45')">0:00:45</a> followers who maybe may have  
<a onclick="modifyYTiframeseektime('48')">0:00:48</a> been misled with all due respect on  
<a onclick="modifyYTiframeseektime('50')">0:00:50</a> certain points of information that dr  
<a onclick="modifyYTiframeseektime('52')">0:00:52</a> jordan peterson an influential figure as  
<a onclick="modifyYTiframeseektime('54')">0:00:54</a> he is  
<a onclick="modifyYTiframeseektime('55')">0:00:55</a> has made about islam and muslims today  
<a onclick="modifyYTiframeseektime('57')">0:00:57</a> in sha allah we're going to be covering  
<a onclick="modifyYTiframeseektime('59')">0:00:59</a> two or three different statements that  
<a onclick="modifyYTiframeseektime('60')">0:01:00</a> he has made let's start with the first  
<a onclick="modifyYTiframeseektime('62')">0:01:02</a> one because it's um a historical and  
<a onclick="modifyYTiframeseektime('65')">0:01:05</a> it's easy to refute let's take a look at  
<a onclick="modifyYTiframeseektime('67')">0:01:07</a> it when the founder of your religion  
<a onclick="modifyYTiframeseektime('69')">0:01:09</a> spread that religion by the sword  
<a onclick="modifyYTiframeseektime('72')">0:01:12</a> it makes it rather difficult and when  
<a onclick="modifyYTiframeseektime('74')">0:01:14</a> your religion has been embroiled in a  
<a onclick="modifyYTiframeseektime('76')">0:01:16</a> vicious civil war from the day of  
<a onclick="modifyYTiframeseektime('79')">0:01:19</a> muhammad's death which is exactly the  
<a onclick="modifyYTiframeseektime('81')">0:01:21</a> case in islam between the sunnis and the  
<a onclick="modifyYTiframeseektime('83')">0:01:23</a> shiites that war started literally the  
<a onclick="modifyYTiframeseektime('85')">0:01:25</a> day that muhammad died it's very  
<a onclick="modifyYTiframeseektime('88')">0:01:28</a> difficult for me to see how that can be  
<a onclick="modifyYTiframeseektime('90')">0:01:30</a> reconciled with the claims that islam is  
<a onclick="modifyYTiframeseektime('92')">0:01:32</a> a religion of peace right so he states  
<a onclick="modifyYTiframeseektime('95')">0:01:35</a> that  
<a onclick="modifyYTiframeseektime('96')">0:01:36</a> islam was embroiled in a vicious civil  
<a onclick="modifyYTiframeseektime('98')">0:01:38</a> war  
<a onclick="modifyYTiframeseektime('99')">0:01:39</a> our question is can you name me with i  
<a onclick="modifyYTiframeseektime('101')">0:01:41</a> know you're watching this dr jordan  
<a onclick="modifyYTiframeseektime('103')">0:01:43</a> peterson because  
<a onclick="modifyYTiframeseektime('104')">0:01:44</a> uh clearly it would make sense for you  
<a onclick="modifyYTiframeseektime('106')">0:01:46</a> to do so  
<a onclick="modifyYTiframeseektime('107')">0:01:47</a> what is the name of that civil war  
<a onclick="modifyYTiframeseektime('108')">0:01:48</a> you're talking about that commenced the  
<a onclick="modifyYTiframeseektime('110')">0:01:50</a> day the prophet salallahu  
<a onclick="modifyYTiframeseektime('114')">0:01:54</a> and please give me a source for that  
<a onclick="modifyYTiframeseektime('116')">0:01:56</a> because  
<a onclick="modifyYTiframeseektime('117')">0:01:57</a> let me tell you something dr jordan  
<a onclick="modifyYTiframeseektime('118')">0:01:58</a> pearson no such war took place  
<a onclick="modifyYTiframeseektime('122')">0:02:02</a> now you may say well the war took place  
<a onclick="modifyYTiframeseektime('123')">0:02:03</a> 30 years after safiy and jamal these  
<a onclick="modifyYTiframeseektime('125')">0:02:05</a> wars took place 30 to 40 years after but  
<a onclick="modifyYTiframeseektime('127')">0:02:07</a> that's not  
<a onclick="modifyYTiframeseektime('128')">0:02:08</a> what you said  
<a onclick="modifyYTiframeseektime('130')">0:02:10</a> you stated that it happened the day  
<a onclick="modifyYTiframeseektime('132')">0:02:12</a> the prophet died and then you use that  
<a onclick="modifyYTiframeseektime('134')">0:02:14</a> as a point  
<a onclick="modifyYTiframeseektime('136')">0:02:16</a> um just to to conclude  
<a onclick="modifyYTiframeseektime('138')">0:02:18</a> that you can't  
<a onclick="modifyYTiframeseektime('140')">0:02:20</a> reconcile this fact with the fact that  
<a onclick="modifyYTiframeseektime('141')">0:02:21</a> islam is a religion of peace  
<a onclick="modifyYTiframeseektime('143')">0:02:23</a> so already you've got a point that you  
<a onclick="modifyYTiframeseektime('144')">0:02:24</a> want to make and the evidence that  
<a onclick="modifyYTiframeseektime('146')">0:02:26</a> you're using doesn't match this point  
<a onclick="modifyYTiframeseektime('149')">0:02:29</a> and in fact it's a false piece of  
<a onclick="modifyYTiframeseektime('150')">0:02:30</a> evidence and it's another example where  
<a onclick="modifyYTiframeseektime('152')">0:02:32</a> you violate your own rules  
<a onclick="modifyYTiframeseektime('154')">0:02:34</a> the rules um namely the rules to speak  
<a onclick="modifyYTiframeseektime('157')">0:02:37</a> the truth or at least don't lie  
<a onclick="modifyYTiframeseektime('159')">0:02:39</a> and be precise in speech you violate  
<a onclick="modifyYTiframeseektime('161')">0:02:41</a> your own rules you're not precise here  
<a onclick="modifyYTiframeseektime('163')">0:02:43</a> this is inaccurate for an intellectual  
<a onclick="modifyYTiframeseektime('165')">0:02:45</a> you need to be more careful with all due  
<a onclick="modifyYTiframeseektime('166')">0:02:46</a> respect because if you don't know  
<a onclick="modifyYTiframeseektime('168')">0:02:48</a> something and this is false according to  
<a onclick="modifyYTiframeseektime('170')">0:02:50</a> all accounts there was no war sorry  
<a onclick="modifyYTiframeseektime('173')">0:02:53</a> dr peterson there was no war that  
<a onclick="modifyYTiframeseektime('175')">0:02:55</a> commenced the day the prophet died this  
<a onclick="modifyYTiframeseektime('177')">0:02:57</a> is false  
<a onclick="modifyYTiframeseektime('179')">0:02:59</a> but as an intellectual or as an academic  
<a onclick="modifyYTiframeseektime('181')">0:03:01</a> you should check before you speak with  
<a onclick="modifyYTiframeseektime('184')">0:03:04</a> all due respect  
<a onclick="modifyYTiframeseektime('185')">0:03:05</a> and already this you could say i mean  
<a onclick="modifyYTiframeseektime('187')">0:03:07</a> you have to ask yourself dr jordan  
<a onclick="modifyYTiframeseektime('189')">0:03:09</a> peterson are you making this point to  
<a onclick="modifyYTiframeseektime('191')">0:03:11</a> try and score points against islam  
<a onclick="modifyYTiframeseektime('193')">0:03:13</a> because you already have a cognitive  
<a onclick="modifyYTiframeseektime('194')">0:03:14</a> bias  
<a onclick="modifyYTiframeseektime('195')">0:03:15</a> because the pulse  
<a onclick="modifyYTiframeseektime('197')">0:03:17</a> the evidence you used was a false piece  
<a onclick="modifyYTiframeseektime('198')">0:03:18</a> of evidence so what is the motivating  
<a onclick="modifyYTiframeseektime('201')">0:03:21</a> factor here  
<a onclick="modifyYTiframeseektime('203')">0:03:23</a> now the point that you were making about  
<a onclick="modifyYTiframeseektime('204')">0:03:24</a> islam being a religion of peace  
<a onclick="modifyYTiframeseektime('207')">0:03:27</a> look i'm not in favor of calling islam a  
<a onclick="modifyYTiframeseektime('209')">0:03:29</a> religion of peace  
<a onclick="modifyYTiframeseektime('210')">0:03:30</a> but i'm not in favor of calling islam a  
<a onclick="modifyYTiframeseektime('212')">0:03:32</a> religion of war either because islam  
<a onclick="modifyYTiframeseektime('214')">0:03:34</a> really means it's islam which means  
<a onclick="modifyYTiframeseektime('216')">0:03:36</a> submission  
<a onclick="modifyYTiframeseektime('217')">0:03:37</a> and islam  
<a onclick="modifyYTiframeseektime('218')">0:03:38</a> is submission to one god  
<a onclick="modifyYTiframeseektime('220')">0:03:40</a> submission and worship of the god of  
<a onclick="modifyYTiframeseektime('222')">0:03:42</a> abraham the god of moses and the god of  
<a onclick="modifyYTiframeseektime('224')">0:03:44</a> jesus the god of muhammad  
<a onclick="modifyYTiframeseektime('227')">0:03:47</a> this is what primarily islam is  
<a onclick="modifyYTiframeseektime('229')">0:03:49</a> which leads me on to your second point  
<a onclick="modifyYTiframeseektime('230')">0:03:50</a> because you state islam is primarily a  
<a onclick="modifyYTiframeseektime('234')">0:03:54</a> political system let's take a look at  
<a onclick="modifyYTiframeseektime('236')">0:03:56</a> what you have to say but i'm really  
<a onclick="modifyYTiframeseektime('238')">0:03:58</a> stumbling with islam it's really hard  
<a onclick="modifyYTiframeseektime('241')">0:04:01</a> for me to  
<a onclick="modifyYTiframeseektime('243')">0:04:03</a> to see it as  
<a onclick="modifyYTiframeseektime('245')">0:04:05</a> other than a primarily political system  
<a onclick="modifyYTiframeseektime('248')">0:04:08</a> this is false dr peterson with all due  
<a onclick="modifyYTiframeseektime('250')">0:04:10</a> respect  
<a onclick="modifyYTiframeseektime('251')">0:04:11</a> i don't know of any scholar of islam  
<a onclick="modifyYTiframeseektime('255')">0:04:15</a> in the classical period who defined  
<a onclick="modifyYTiframeseektime('257')">0:04:17</a> islam vastly that islam is a political  
<a onclick="modifyYTiframeseektime('260')">0:04:20</a> system primarily a political system how  
<a onclick="modifyYTiframeseektime('262')">0:04:22</a> could it be  
<a onclick="modifyYTiframeseektime('264')">0:04:24</a> it's a very there's a very clear  
<a onclick="modifyYTiframeseektime('266')">0:04:26</a> theocentric motif in the quran  
<a onclick="modifyYTiframeseektime('270')">0:04:30</a> a book of  
<a onclick="modifyYTiframeseektime('271')">0:04:31</a> 6236 verses which has been translated  
<a onclick="modifyYTiframeseektime('274')">0:04:34</a> the meanings of have been translated  
<a onclick="modifyYTiframeseektime('275')">0:04:35</a> into english  
<a onclick="modifyYTiframeseektime('277')">0:04:37</a> and i don't think that statement that  
<a onclick="modifyYTiframeseektime('278')">0:04:38</a> you've mentioned about islam is anywhere  
<a onclick="modifyYTiframeseektime('281')">0:04:41</a> to be found in the quran  
<a onclick="modifyYTiframeseektime('283')">0:04:43</a> and it's nowhere to be found in the  
<a onclick="modifyYTiframeseektime('284')">0:04:44</a> statements of the prophet  
<a onclick="modifyYTiframeseektime('286')">0:04:46</a> so where do you get this idea that islam  
<a onclick="modifyYTiframeseektime('288')">0:04:48</a> is primarily a political system  
<a onclick="modifyYTiframeseektime('291')">0:04:51</a> why is this the narrative that you want  
<a onclick="modifyYTiframeseektime('292')">0:04:52</a> to portray  
<a onclick="modifyYTiframeseektime('294')">0:04:54</a> what is the motivating factor here this  
<a onclick="modifyYTiframeseektime('296')">0:04:56</a> is false as i've mentioned islam quite  
<a onclick="modifyYTiframeseektime('299')">0:04:59</a> clearly  
<a onclick="modifyYTiframeseektime('300')">0:05:00</a> at the center center of islam or central  
<a onclick="modifyYTiframeseektime('303')">0:05:03</a> to it is the idea of monotheism  
<a onclick="modifyYTiframeseektime('306')">0:05:06</a> monotheism to worship one god that's  
<a onclick="modifyYTiframeseektime('310')">0:05:10</a> really the the main message of islam the  
<a onclick="modifyYTiframeseektime('312')">0:05:12</a> shahada is  
<a onclick="modifyYTiframeseektime('315')">0:05:15</a> there is no god worthy of worship  
<a onclick="modifyYTiframeseektime('318')">0:05:18</a> except for allah the creator of the  
<a onclick="modifyYTiframeseektime('321')">0:05:21</a> heavens and the earth the higher power  
<a onclick="modifyYTiframeseektime('323')">0:05:23</a> the higher power which jesus himself  
<a onclick="modifyYTiframeseektime('326')">0:05:26</a> beseeched and prayed to that moses  
<a onclick="modifyYTiframeseektime('328')">0:05:28</a> prayed to that abraham prayed to  
<a onclick="modifyYTiframeseektime('331')">0:05:31</a> we don't believe that jesus was god or  
<a onclick="modifyYTiframeseektime('333')">0:05:33</a> the son of god we don't believe that a  
<a onclick="modifyYTiframeseektime('335')">0:05:35</a> man can be god we don't believe in any  
<a onclick="modifyYTiframeseektime('337')">0:05:37</a> of those things the center of our faith  
<a onclick="modifyYTiframeseektime('340')">0:05:40</a> is very simply to worship one god that  
<a onclick="modifyYTiframeseektime('342')">0:05:42</a> is islam  
<a onclick="modifyYTiframeseektime('344')">0:05:44</a> so to to call it primarily a political  
<a onclick="modifyYTiframeseektime('347')">0:05:47</a> system  
<a onclick="modifyYTiframeseektime('348')">0:05:48</a> is  
<a onclick="modifyYTiframeseektime('348')">0:05:48</a> false it's imprecise speech  
<a onclick="modifyYTiframeseektime('351')">0:05:51</a> or it's not speaking the truth of islam  
<a onclick="modifyYTiframeseektime('353')">0:05:53</a> what islam is  
<a onclick="modifyYTiframeseektime('355')">0:05:55</a> then you go on to say something which is  
<a onclick="modifyYTiframeseektime('357')">0:05:57</a> i believe is a slight and i believe it's  
<a onclick="modifyYTiframeseektime('360')">0:06:00</a> an attempt to try and score points  
<a onclick="modifyYTiframeseektime('361')">0:06:01</a> against islam it's very clear that it is  
<a onclick="modifyYTiframeseektime('364')">0:06:04</a> but it's also  
<a onclick="modifyYTiframeseektime('366')">0:06:06</a> weak as an argument let's see what you  
<a onclick="modifyYTiframeseektime('368')">0:06:08</a> have to say about islam  
<a onclick="modifyYTiframeseektime('369')">0:06:09</a> or muslim countries and  
<a onclick="modifyYTiframeseektime('372')">0:06:12</a> the state of economic affairs in muslim  
<a onclick="modifyYTiframeseektime('374')">0:06:14</a> countries you know the  
<a onclick="modifyYTiframeseektime('376')">0:06:16</a> the  
<a onclick="modifyYTiframeseektime('377')">0:06:17</a> states dominated by islam are not  
<a onclick="modifyYTiframeseektime('379')">0:06:19</a> economically productive  
<a onclick="modifyYTiframeseektime('382')">0:06:22</a> and that's quite an interesting mystery  
<a onclick="modifyYTiframeseektime('384')">0:06:24</a> so this point that jordan peterson makes  
<a onclick="modifyYTiframeseektime('386')">0:06:26</a> here he says states that are occupied by  
<a onclick="modifyYTiframeseektime('388')">0:06:28</a> islam are not economically productive  
<a onclick="modifyYTiframeseektime('392')">0:06:32</a> first of all how do you define occupied  
<a onclick="modifyYTiframeseektime('393')">0:06:33</a> by islam and secondly how do you define  
<a onclick="modifyYTiframeseektime('396')">0:06:36</a> economically productive  
<a onclick="modifyYTiframeseektime('397')">0:06:37</a> what are the  
<a onclick="modifyYTiframeseektime('399')">0:06:39</a> measures that you're using gdp per  
<a onclick="modifyYTiframeseektime('400')">0:06:40</a> capita for example where four muslim  
<a onclick="modifyYTiframeseektime('403')">0:06:43</a> majority countries are in the top ten  
<a onclick="modifyYTiframeseektime('405')">0:06:45</a> which ones are you talking about are you  
<a onclick="modifyYTiframeseektime('406')">0:06:46</a> talking about gdp  
<a onclick="modifyYTiframeseektime('408')">0:06:48</a> or what exactly and i must say this is a  
<a onclick="modifyYTiframeseektime('411')">0:06:51</a> methodologically flawed approach in the  
<a onclick="modifyYTiframeseektime('413')">0:06:53</a> first instance  
<a onclick="modifyYTiframeseektime('415')">0:06:55</a> analyzing an ideology  
<a onclick="modifyYTiframeseektime('417')">0:06:57</a> and  
<a onclick="modifyYTiframeseektime('419')">0:06:59</a> economic productivity of a country why  
<a onclick="modifyYTiframeseektime('422')">0:07:02</a> because why today first of all first of  
<a onclick="modifyYTiframeseektime('423')">0:07:03</a> all why today why not look 400 years ago  
<a onclick="modifyYTiframeseektime('426')">0:07:06</a> in the ottoman empire or islamic spain  
<a onclick="modifyYTiframeseektime('428')">0:07:08</a> or the abbasids or the omo yon or the  
<a onclick="modifyYTiframeseektime('431')">0:07:11</a> khilaf rashidah when economic  
<a onclick="modifyYTiframeseektime('432')">0:07:12</a> productivity was very high and islam was  
<a onclick="modifyYTiframeseektime('435')">0:07:15</a> being implemented at a much more strict  
<a onclick="modifyYTiframeseektime('438')">0:07:18</a> level if you like  
<a onclick="modifyYTiframeseektime('439')">0:07:19</a> is it because it fits a particular  
<a onclick="modifyYTiframeseektime('441')">0:07:21</a> narrative which may indicate that  
<a onclick="modifyYTiframeseektime('445')">0:07:25</a> islam as a religion inhibits economic  
<a onclick="modifyYTiframeseektime('447')">0:07:27</a> productivity  
<a onclick="modifyYTiframeseektime('449')">0:07:29</a> similar to the kind of narrative we  
<a onclick="modifyYTiframeseektime('451')">0:07:31</a> dealt with in the previous episode  
<a onclick="modifyYTiframeseektime('454')">0:07:34</a> this is a weak argument i'm really sorry  
<a onclick="modifyYTiframeseektime('456')">0:07:36</a> it's a weak argument and with all due  
<a onclick="modifyYTiframeseektime('458')">0:07:38</a> respect you weren't even brave enough to  
<a onclick="modifyYTiframeseektime('460')">0:07:40</a> make the argument properly because you  
<a onclick="modifyYTiframeseektime('462')">0:07:42</a> said it's an interesting mystery and you  
<a onclick="modifyYTiframeseektime('464')">0:07:44</a> shroud  
<a onclick="modifyYTiframeseektime('466')">0:07:46</a> your sentences  
<a onclick="modifyYTiframeseektime('468')">0:07:48</a> with words of ambiguity and uncertainty  
<a onclick="modifyYTiframeseektime('472')">0:07:52</a> when  
<a onclick="modifyYTiframeseektime('473')">0:07:53</a> with all due respect sometimes you don't  
<a onclick="modifyYTiframeseektime('475')">0:07:55</a> want to make the argument directly  
<a onclick="modifyYTiframeseektime('477')">0:07:57</a> because you know it's susceptible to a  
<a onclick="modifyYTiframeseektime('479')">0:07:59</a> high level refutation like the one  
<a onclick="modifyYTiframeseektime('481')">0:08:01</a> you're seeing right now  
<a onclick="modifyYTiframeseektime('483')">0:08:03</a> because the question is if it's to do  
<a onclick="modifyYTiframeseektime('485')">0:08:05</a> with ideology  
<a onclick="modifyYTiframeseektime('487')">0:08:07</a> my question to you is in the mid 18th  
<a onclick="modifyYTiframeseektime('489')">0:08:09</a> century 1760 when the industrial  
<a onclick="modifyYTiframeseektime('492')">0:08:12</a> revolution started in britain for  
<a onclick="modifyYTiframeseektime('494')">0:08:14</a> example  
<a onclick="modifyYTiframeseektime('496')">0:08:16</a> what were what was the state of affairs  
<a onclick="modifyYTiframeseektime('499')">0:08:19</a> relating to ideologies the same are the  
<a onclick="modifyYTiframeseektime('500')">0:08:20</a> morals and ethics  
<a onclick="modifyYTiframeseektime('502')">0:08:22</a> of britain in the 18th century  
<a onclick="modifyYTiframeseektime('505')">0:08:25</a> similar or distinctly different from the  
<a onclick="modifyYTiframeseektime('507')">0:08:27</a> moles and ethics that we're seeing today  
<a onclick="modifyYTiframeseektime('508')">0:08:28</a> in the 21st century i would wager  
<a onclick="modifyYTiframeseektime('510')">0:08:30</a> especially on women's rights that's  
<a onclick="modifyYTiframeseektime('512')">0:08:32</a> completely different  
<a onclick="modifyYTiframeseektime('513')">0:08:33</a> and in fact that was a time  
<a onclick="modifyYTiframeseektime('516')">0:08:36</a> where economic productivity in britain  
<a onclick="modifyYTiframeseektime('518')">0:08:38</a> was very very high comparative to the  
<a onclick="modifyYTiframeseektime('519')">0:08:39</a> other states in fact you could say the  
<a onclick="modifyYTiframeseektime('520')">0:08:40</a> highest  
<a onclick="modifyYTiframeseektime('522')">0:08:42</a> you can make this argument  
<a onclick="modifyYTiframeseektime('523')">0:08:43</a> and so if it was to do with ideology  
<a onclick="modifyYTiframeseektime('526')">0:08:46</a> then once again you'd expect  
<a onclick="modifyYTiframeseektime('528')">0:08:48</a> the morals and the ethics  
<a onclick="modifyYTiframeseektime('530')">0:08:50</a> and the ideological standpoints to have  
<a onclick="modifyYTiframeseektime('532')">0:08:52</a> an impact in the inhibitive or negative  
<a onclick="modifyYTiframeseektime('536')">0:08:56</a> effect of that economy  
<a onclick="modifyYTiframeseektime('539')">0:08:59</a> likewise you can say the same thing  
<a onclick="modifyYTiframeseektime('540')">0:09:00</a> about the slave trade  
<a onclick="modifyYTiframeseektime('542')">0:09:02</a> well  
<a onclick="modifyYTiframeseektime('542')">0:09:02</a> america was doing very well when it had  
<a onclick="modifyYTiframeseektime('544')">0:09:04</a> black slaves  
<a onclick="modifyYTiframeseektime('546')">0:09:06</a> it was doing very well when it was  
<a onclick="modifyYTiframeseektime('547')">0:09:07</a> trading them and when it was forcing  
<a onclick="modifyYTiframeseektime('549')">0:09:09</a> them to pick cotton and so on  
<a onclick="modifyYTiframeseektime('552')">0:09:12</a> before the um american civil war  
<a onclick="modifyYTiframeseektime('555')">0:09:15</a> in the mid 19th century  
<a onclick="modifyYTiframeseektime('557')">0:09:17</a> were the morals and the ethics and the  
<a onclick="modifyYTiframeseektime('559')">0:09:19</a> ideological standpoints especially of  
<a onclick="modifyYTiframeseektime('561')">0:09:21</a> let's say southern states in america  
<a onclick="modifyYTiframeseektime('563')">0:09:23</a> were they the same or distinctly  
<a onclick="modifyYTiframeseektime('565')">0:09:25</a> different from the way they are now  
<a onclick="modifyYTiframeseektime('567')">0:09:27</a> i think you would say the latter  
<a onclick="modifyYTiframeseektime('569')">0:09:29</a> so much so that i had a constitutional  
<a onclick="modifyYTiframeseektime('572')">0:09:32</a> effect with the third the 13th amendment  
<a onclick="modifyYTiframeseektime('575')">0:09:35</a> and other such things that happened in  
<a onclick="modifyYTiframeseektime('577')">0:09:37</a> the cultural atmosphere in america  
<a onclick="modifyYTiframeseektime('579')">0:09:39</a> ideological differences  
<a onclick="modifyYTiframeseektime('580')">0:09:40</a> yet despite the ideological differences  
<a onclick="modifyYTiframeseektime('584')">0:09:44</a> which  
<a onclick="modifyYTiframeseektime('586')">0:09:46</a> one can notice  
<a onclick="modifyYTiframeseektime('587')">0:09:47</a> in the mid-19th century say and now say  
<a onclick="modifyYTiframeseektime('591')">0:09:51</a> in american culture  
<a onclick="modifyYTiframeseektime('593')">0:09:53</a> we still see that america was doing very  
<a onclick="modifyYTiframeseektime('596')">0:09:56</a> well economically at a time where its  
<a onclick="modifyYTiframeseektime('598')">0:09:58</a> ideology was different to the way it is  
<a onclick="modifyYTiframeseektime('599')">0:09:59</a> now  
<a onclick="modifyYTiframeseektime('600')">0:10:00</a> so if ideology  
<a onclick="modifyYTiframeseektime('602')">0:10:02</a> or liberal or the liberal ideology of  
<a onclick="modifyYTiframeseektime('604')">0:10:04</a> today let's say western ideology of  
<a onclick="modifyYTiframeseektime('606')">0:10:06</a> today  
<a onclick="modifyYTiframeseektime('607')">0:10:07</a> the cultural and  
<a onclick="modifyYTiframeseektime('609')">0:10:09</a> uh  
<a onclick="modifyYTiframeseektime('609')">0:10:09</a> moral and ethical standpoints of the  
<a onclick="modifyYTiframeseektime('611')">0:10:11</a> west today  
<a onclick="modifyYTiframeseektime('612')">0:10:12</a> were  
<a onclick="modifyYTiframeseektime('614')">0:10:14</a> shaping forces for how the economy  
<a onclick="modifyYTiframeseektime('616')">0:10:16</a> behaves  
<a onclick="modifyYTiframeseektime('618')">0:10:18</a> then why do we see that it behaves  
<a onclick="modifyYTiframeseektime('621')">0:10:21</a> in sometimes even a comparatively  
<a onclick="modifyYTiframeseektime('623')">0:10:23</a> stronger way  
<a onclick="modifyYTiframeseektime('625')">0:10:25</a> in the past where ethics were different  
<a onclick="modifyYTiframeseektime('627')">0:10:27</a> in america and in the west generally  
<a onclick="modifyYTiframeseektime('630')">0:10:30</a> to the way it is now so you see this is  
<a onclick="modifyYTiframeseektime('632')">0:10:32</a> a methodologically flawed thing because  
<a onclick="modifyYTiframeseektime('635')">0:10:35</a> we're seeing transient ethics here and  
<a onclick="modifyYTiframeseektime('638')">0:10:38</a> this is really  
<a onclick="modifyYTiframeseektime('639')">0:10:39</a> basic for a social scientist that  
<a onclick="modifyYTiframeseektime('642')">0:10:42</a> correlation does not always mean  
<a onclick="modifyYTiframeseektime('643')">0:10:43</a> causation  
<a onclick="modifyYTiframeseektime('644')">0:10:44</a> and if it was to do with ethics and  
<a onclick="modifyYTiframeseektime('646')">0:10:46</a> morals and ideology then why do we  
<a onclick="modifyYTiframeseektime('649')">0:10:49</a> seeing the rise of japan  
<a onclick="modifyYTiframeseektime('651')">0:10:51</a> japan is not a western country and it  
<a onclick="modifyYTiframeseektime('654')">0:10:54</a> has ethics and cultures distinct from  
<a onclick="modifyYTiframeseektime('656')">0:10:56</a> the west and yet we're seeing its  
<a onclick="modifyYTiframeseektime('657')">0:10:57</a> economy rise as staggering rate  
<a onclick="modifyYTiframeseektime('660')">0:11:00</a> technological and scientific and  
<a onclick="modifyYTiframeseektime('663')">0:11:03</a> economic developments there  
<a onclick="modifyYTiframeseektime('665')">0:11:05</a> moreover if you wanted to play this game  
<a onclick="modifyYTiframeseektime('667')">0:11:07</a> we can go further  
<a onclick="modifyYTiframeseektime('669')">0:11:09</a> and we can say to you  
<a onclick="modifyYTiframeseektime('670')">0:11:10</a> that in fact  
<a onclick="modifyYTiframeseektime('673')">0:11:13</a> most i'm not going to say most but many  
<a onclick="modifyYTiframeseektime('675')">0:11:15</a> of the countries which are  
<a onclick="modifyYTiframeseektime('678')">0:11:18</a> which have let's say western enlightened  
<a onclick="modifyYTiframeseektime('680')">0:11:20</a> enlightenment ideas in sub-saharan  
<a onclick="modifyYTiframeseektime('683')">0:11:23</a> africa  
<a onclick="modifyYTiframeseektime('684')">0:11:24</a> and in southern  
<a onclick="modifyYTiframeseektime('686')">0:11:26</a> uh in in southern america  
<a onclick="modifyYTiframeseektime('689')">0:11:29</a> are below the poverty line and in fact  
<a onclick="modifyYTiframeseektime('691')">0:11:31</a> do worse than even on a gdp level okay  
<a onclick="modifyYTiframeseektime('696')">0:11:36</a> muslim majority countries so if what we  
<a onclick="modifyYTiframeseektime('699')">0:11:39</a> are saying is if we put western  
<a onclick="modifyYTiframeseektime('700')">0:11:40</a> enlightenment ideas  
<a onclick="modifyYTiframeseektime('702')">0:11:42</a> into countries we expect the economic  
<a onclick="modifyYTiframeseektime('704')">0:11:44</a> development to be  
<a onclick="modifyYTiframeseektime('707')">0:11:47</a> better then why are we not seeing that  
<a onclick="modifyYTiframeseektime('709')">0:11:49</a> in countries  
<a onclick="modifyYTiframeseektime('710')">0:11:50</a> in south america and sub-saharan africa  
<a onclick="modifyYTiframeseektime('714')">0:11:54</a> where they're  
<a onclick="modifyYTiframeseektime('714')">0:11:54</a> indebted where they're impoverished  
<a onclick="modifyYTiframeseektime('717')">0:11:57</a> and so on  
<a onclick="modifyYTiframeseektime('719')">0:11:59</a> so you see it's a failed attempt a  
<a onclick="modifyYTiframeseektime('722')">0:12:02</a> slight at the islamic civilization and a  
<a onclick="modifyYTiframeseektime('724')">0:12:04</a> weak argument that we expected better  
<a onclick="modifyYTiframeseektime('727')">0:12:07</a> from dr jordan peterson and it's these  
<a onclick="modifyYTiframeseektime('729')">0:12:09</a> kinds of arguments with all due respect  
<a onclick="modifyYTiframeseektime('731')">0:12:11</a> which go back to our theme  
<a onclick="modifyYTiframeseektime('733')">0:12:13</a> the theme is you're trying to whitewash  
<a onclick="modifyYTiframeseektime('736')">0:12:16</a> the muslim contribution you're trying to  
<a onclick="modifyYTiframeseektime('739')">0:12:19</a> minimize the islamic contribution and  
<a onclick="modifyYTiframeseektime('742')">0:12:22</a> somehow and you could say with this with  
<a onclick="modifyYTiframeseektime('743')">0:12:23</a> this kind of lexus here it's clear that  
<a onclick="modifyYTiframeseektime('746')">0:12:26</a> you're trying to connect  
<a onclick="modifyYTiframeseektime('748')">0:12:28</a> failure  
<a onclick="modifyYTiframeseektime('749')">0:12:29</a> with islam somehow whether it's economic  
<a onclick="modifyYTiframeseektime('751')">0:12:31</a> failure scientific failure or  
<a onclick="modifyYTiframeseektime('754')">0:12:34</a> lack of productivity or whatever it may  
<a onclick="modifyYTiframeseektime('756')">0:12:36</a> be with islam  
<a onclick="modifyYTiframeseektime('758')">0:12:38</a> and it's failed the arguments have  
<a onclick="modifyYTiframeseektime('760')">0:12:40</a> failed and maybe this is the reason why  
<a onclick="modifyYTiframeseektime('763')">0:12:43</a> you didn't want to have a discussion  
<a onclick="modifyYTiframeseektime('764')">0:12:44</a> with me because you knew these things  
<a onclick="modifyYTiframeseektime('766')">0:12:46</a> are on the record and you knew you'd be  
<a onclick="modifyYTiframeseektime('768')">0:12:48</a> accounted for it but i think it's high  
<a onclick="modifyYTiframeseektime('770')">0:12:50</a> time jordan peterson if we want to have  
<a onclick="modifyYTiframeseektime('771')">0:12:51</a> an authentic discussion we have to start  
<a onclick="modifyYTiframeseektime('774')">0:12:54</a> with retractions because these kinds of  
<a onclick="modifyYTiframeseektime('776')">0:12:56</a> things are not just imprecise as we've  
<a onclick="modifyYTiframeseektime('778')">0:12:58</a> shown sorry they're imprecise they're a  
<a onclick="modifyYTiframeseektime('780')">0:13:00</a> historical they're inaccurate but  
<a onclick="modifyYTiframeseektime('781')">0:13:01</a> they're weak as arguments and unless one  
<a onclick="modifyYTiframeseektime('784')">0:13:04</a> revises and retracts or otherwise  
<a onclick="modifyYTiframeseektime('787')">0:13:07</a> suspends at least suspends judgments  
<a onclick="modifyYTiframeseektime('791')">0:13:11</a> on issues to do like with these kinds of  
<a onclick="modifyYTiframeseektime('794')">0:13:14</a> points that you've mentioned here  
<a onclick="modifyYTiframeseektime('796')">0:13:16</a> then how are we going to have a proper  
<a onclick="modifyYTiframeseektime('797')">0:13:17</a> dialogue  
<a onclick="modifyYTiframeseektime('799')">0:13:19</a> between islam about islam and the west  
<a onclick="modifyYTiframeseektime('801')">0:13:21</a> for example in the interaction between  
<a onclick="modifyYTiframeseektime('802')">0:13:22</a> these two things if we can separate them  
<a onclick="modifyYTiframeseektime('804')">0:13:24</a> at all and hopefully  
<a onclick="modifyYTiframeseektime('806')">0:13:26</a> that edified some of jordan peterson's  
<a onclick="modifyYTiframeseektime('809')">0:13:29</a> followers  
<a onclick="modifyYTiframeseektime('810')">0:13:30</a> and insha'allah even jordan peterson  
<a onclick="modifyYTiframeseektime('812')">0:13:32</a> himself  
</details>