# Dr. Jordan Peterson Questioned on 'Message to Muslims' (2022-10-18)

<iframe loading='lazy' src='https://www.youtube.com/embed/jxr6ykYcA1M'></iframe>

## Description

DONATE NOW: https://www.saveiman.com/fb?affiliate_id=3414212 ⬅

The Prophet ﷺ said: “𝙒𝙝𝙤𝙚𝙫𝙚𝙧 𝙗𝙪𝙞𝙡𝙙𝙨 𝙖 𝙈𝙤𝙨𝙦𝙪𝙚 𝙛𝙤𝙧 𝘼𝙡𝙡𝙖𝙝, 𝘼𝙡𝙡𝙖𝙝 𝙬𝙞𝙡𝙡 𝙗𝙪𝙞𝙡𝙙 𝙛𝙤𝙧 𝙝𝙞𝙢 𝙖 𝙨𝙞𝙢𝙞𝙡𝙖𝙧 𝙝𝙤𝙪𝙨𝙚 𝙞𝙣 𝙅𝙖𝙣𝙣𝙖𝙝.”

If you support this project, you will in sha Allah get a house in Jannah and share in the rewards of all the people:

✅ Praying in the Masjid!
✅ Making Dhikr!
✅ Memorizing the Qur’an!

Please donate and help establish this Masjid and earn your reward ➡ https://www.saveiman.com/fb?affiliate_id=3414212 ⬅

## Summary of [Dr. Jordan Peterson Questioned on 'Message to Muslims'](https://www.youtube.com/watch?v=jxr6ykYcA1M)


*<span style="color:red; font-size:125%">This summary is AI generated - there may be inaccuracies</span>. [](/)*

### <a onclick="modifyYTiframeseektime('0')">00:00:00</a> - <a onclick="modifyYTiframeseektime('600')">00:10:00</a>

Dr. Jordan Peterson is questioned on his thoughts about Muslims in the West and how to start a dialogue with them. He believes that it is important to be honest about the history of colonialism and Islam's place in it, and that it is often difficult to talk to people from other cultures.

**<a onclick="modifyYTiframeseektime('0')">00:00:00</a>** Dr. Jordan Peterson is asked about his thoughts on Muslims in the West and how to start a dialogue with them. He believes that it is important to be honest about the history of colonialism and Islam's place in it, and that it is often difficult to talk to people from other cultures.
* **<a onclick="modifyYTiframeseektime('300')">00:05:00</a>** Jordan Peterson is questioned on "Message to Muslims." Peterson argues that, while there are historical atrocities committed by both the West and Islam, Islam is not wholly to blame. He also points out that, while liberalism was an important part of the development of the West, it is not the only factor.
* **<a onclick="modifyYTiframeseektime('600')">00:10:00</a>**  Dr. Jordan Peterson is questioned about the historical record of Western civilization, which he argues does not show that the ideology of the West can fix our problems. Peterson also discusses the idea of body count, which he believes shows that societies with a depleted communitarian ethic and bereft of a respectful tradition are more likely to experience bloodshed.

<details><summary><h2>Full transcript with timestamps: CLICK TO EXPAND</h2></summary>

<a onclick="modifyYTiframeseektime('0')">0:00:00</a> your brothers and sisters in the slum  
<a onclick="modifyYTiframeseektime('2')">0:00:02</a> net from Norway are establishing a  
<a onclick="modifyYTiframeseektime('4')">0:00:04</a> Masjid a dawa Center this Center this  
<a onclick="modifyYTiframeseektime('8')">0:00:08</a> Masjid this educational institution will  
<a onclick="modifyYTiframeseektime('10')">0:00:10</a> act like a beacon of light calling the  
<a onclick="modifyYTiframeseektime('14')">0:00:14</a> Muslims in Norway back to the essence of  
<a onclick="modifyYTiframeseektime('16')">0:00:16</a> Islam so give generously and Allah  
<a onclick="modifyYTiframeseektime('18')">0:00:18</a> azzawajal would give you even  
<a onclick="modifyYTiframeseektime('21')">0:00:21</a> I it is not obvious to me that I let me  
<a onclick="modifyYTiframeseektime('23')">0:00:23</a> kind of push back a little bit on that  
<a onclick="modifyYTiframeseektime('25')">0:00:25</a> point because you're an individual like  
<a onclick="modifyYTiframeseektime('27')">0:00:27</a> obviously in your newest book you're  
<a onclick="modifyYTiframeseektime('28')">0:00:28</a> talking about  
<a onclick="modifyYTiframeseektime('29')">0:00:29</a> um category about precision and I would  
<a onclick="modifyYTiframeseektime('31')">0:00:31</a> say you're an individual that is very  
<a onclick="modifyYTiframeseektime('32')">0:00:32</a> precise they're categorized like if I  
<a onclick="modifyYTiframeseektime('34')">0:00:34</a> was to say anything I would say that  
<a onclick="modifyYTiframeseektime('36')">0:00:36</a> you're individual that's scrupulously  
<a onclick="modifyYTiframeseektime('37')">0:00:37</a> meticulous inexactitude and I don't know  
<a onclick="modifyYTiframeseektime('40')">0:00:40</a> meticulousness or whatever yeah so you  
<a onclick="modifyYTiframeseektime('42')">0:00:42</a> speak and you think about what you're  
<a onclick="modifyYTiframeseektime('44')">0:00:44</a> going to say before you say it that's  
<a onclick="modifyYTiframeseektime('46')">0:00:46</a> what you're known for in fact if someone  
<a onclick="modifyYTiframeseektime('48')">0:00:48</a> says something which is uh kind of off  
<a onclick="modifyYTiframeseektime('50')">0:00:50</a> the market ill but you pull them up for  
<a onclick="modifyYTiframeseektime('52')">0:00:52</a> it right and you know usually because I  
<a onclick="modifyYTiframeseektime('54')">0:00:54</a> don't understand it then yeah for  
<a onclick="modifyYTiframeseektime('56')">0:00:56</a> example like the Kathy Newman interview  
<a onclick="modifyYTiframeseektime('57')">0:00:57</a> like the assumptions and the questioning  
<a onclick="modifyYTiframeseektime('59')">0:00:59</a> that she had she had when she was  
<a onclick="modifyYTiframeseektime('61')">0:01:01</a> questioning yourself you pulled her up  
<a onclick="modifyYTiframeseektime('62')">0:01:02</a> on it and that's why it became so uh  
<a onclick="modifyYTiframeseektime('64')">0:01:04</a> popular the discussion was so popular  
<a onclick="modifyYTiframeseektime('66')">0:01:06</a> and you're a clinical psychologist so  
<a onclick="modifyYTiframeseektime('69')">0:01:09</a> what I was going to say is that for  
<a onclick="modifyYTiframeseektime('70')">0:01:10</a> example if I were to make a video right  
<a onclick="modifyYTiframeseektime('71')">0:01:11</a> I say this message to the you know to  
<a onclick="modifyYTiframeseektime('73')">0:01:13</a> White Canadians or something yeah yeah  
<a onclick="modifyYTiframeseektime('75')">0:01:15</a> and I said you know it's hard to talk to  
<a onclick="modifyYTiframeseektime('77')">0:01:17</a> them I say look you know um sensitively  
<a onclick="modifyYTiframeseektime('79')">0:01:19</a> why don't you reach out to some Russians  
<a onclick="modifyYTiframeseektime('81')">0:01:21</a> you know know or you know heaven forbid  
<a onclick="modifyYTiframeseektime('83')">0:01:23</a> you know reach out to Black Africans or  
<a onclick="modifyYTiframeseektime('85')">0:01:25</a> First Nation people you know whatever it  
<a onclick="modifyYTiframeseektime('88')">0:01:28</a> may be  
<a onclick="modifyYTiframeseektime('89')">0:01:29</a> how do you think  
<a onclick="modifyYTiframeseektime('91')">0:01:31</a> the community of why Canadians let's say  
<a onclick="modifyYTiframeseektime('94')">0:01:34</a> for the sake of argument will react to  
<a onclick="modifyYTiframeseektime('95')">0:01:35</a> that kind of message what if it was you  
<a onclick="modifyYTiframeseektime('97')">0:01:37</a> yeah well you're pretty disagreeable so  
<a onclick="modifyYTiframeseektime('99')">0:01:39</a> you'd probably get bit back a lot yeah  
<a onclick="modifyYTiframeseektime('100')">0:01:40</a> but exactly I don't I don't it's hard to  
<a onclick="modifyYTiframeseektime('103')">0:01:43</a> say until you do it you know yeah I mean  
<a onclick="modifyYTiframeseektime('105')">0:01:45</a> I have reached out to other communities  
<a onclick="modifyYTiframeseektime('108')">0:01:48</a> let's say I did an interview with a  
<a onclick="modifyYTiframeseektime('110')">0:01:50</a> friend of mine who's a Native American  
<a onclick="modifyYTiframeseektime('112')">0:01:52</a> Carver who lives on the west coast and  
<a onclick="modifyYTiframeseektime('115')">0:01:55</a> you know I'm not very happy with the  
<a onclick="modifyYTiframeseektime('117')">0:01:57</a> narrative that's being promoted in  
<a onclick="modifyYTiframeseektime('119')">0:01:59</a> Canada which is that the European  
<a onclick="modifyYTiframeseektime('123')">0:02:03</a> settlement of Canada is best viewed as  
<a onclick="modifyYTiframeseektime('126')">0:02:06</a> genocidally Colonial  
<a onclick="modifyYTiframeseektime('129')">0:02:09</a> and having said that my friend this  
<a onclick="modifyYTiframeseektime('131')">0:02:11</a> Carver was in a residential school in  
<a onclick="modifyYTiframeseektime('134')">0:02:14</a> Canada and the residential schools were  
<a onclick="modifyYTiframeseektime('136')">0:02:16</a> put forward by the government in an  
<a onclick="modifyYTiframeseektime('139')">0:02:19</a> attempt and other institutions in an  
<a onclick="modifyYTiframeseektime('141')">0:02:21</a> attempt to separate the indigenous  
<a onclick="modifyYTiframeseektime('143')">0:02:23</a> children from their families and then  
<a onclick="modifyYTiframeseektime('145')">0:02:25</a> socialize them rapidly according to  
<a onclick="modifyYTiframeseektime('148')">0:02:28</a> European norms and there was some  
<a onclick="modifyYTiframeseektime('150')">0:02:30</a> positive motivation for that and  
<a onclick="modifyYTiframeseektime('153')">0:02:33</a> sometimes that helped and work but one  
<a onclick="modifyYTiframeseektime('156')">0:02:36</a> of the things that did happen was that  
<a onclick="modifyYTiframeseektime('157')">0:02:37</a> some schools were let's say invaded by  
<a onclick="modifyYTiframeseektime('160')">0:02:40</a> people of a pronounced pedophilic and  
<a onclick="modifyYTiframeseektime('163')">0:02:43</a> and sadistic bent and my friend ended up  
<a onclick="modifyYTiframeseektime('166')">0:02:46</a> in one of those schools and his life was  
<a onclick="modifyYTiframeseektime('168')">0:02:48</a> so Dreadful that you can't even hear  
<a onclick="modifyYTiframeseektime('170')">0:02:50</a> about it without  
<a onclick="modifyYTiframeseektime('172')">0:02:52</a> without  
<a onclick="modifyYTiframeseektime('173')">0:02:53</a> serious emotional damage and so you know  
<a onclick="modifyYTiframeseektime('176')">0:02:56</a> I went forward with that discussion and  
<a onclick="modifyYTiframeseektime('178')">0:02:58</a> it was very contentious but it went very  
<a onclick="modifyYTiframeseektime('181')">0:03:01</a> well and it it told a story that was  
<a onclick="modifyYTiframeseektime('184')">0:03:04</a> true and needed to be told and so you  
<a onclick="modifyYTiframeseektime('186')">0:03:06</a> know you step into foreign territory at  
<a onclick="modifyYTiframeseektime('188')">0:03:08</a> your peril that's for sure but  
<a onclick="modifyYTiframeseektime('191')">0:03:11</a> you know and it was relatively difficult  
<a onclick="modifyYTiframeseektime('193')">0:03:13</a> for me to arrange  
<a onclick="modifyYTiframeseektime('195')">0:03:15</a> for this to be a possibility of course  
<a onclick="modifyYTiframeseektime('197')">0:03:17</a> and and but my my thought again because  
<a onclick="modifyYTiframeseektime('202')">0:03:22</a> I'm trying to look for what we have to  
<a onclick="modifyYTiframeseektime('204')">0:03:24</a> offer each other rather than what  
<a onclick="modifyYTiframeseektime('206')">0:03:26</a> divides us I thought it was worthwhile  
<a onclick="modifyYTiframeseektime('208')">0:03:28</a> so let me push back again once again  
<a onclick="modifyYTiframeseektime('210')">0:03:30</a> once again on this plan so for example  
<a onclick="modifyYTiframeseektime('212')">0:03:32</a> it's not always what you say sometimes  
<a onclick="modifyYTiframeseektime('214')">0:03:34</a> it can be what you don't say so for  
<a onclick="modifyYTiframeseektime('216')">0:03:36</a> instance  
<a onclick="modifyYTiframeseektime('217')">0:03:37</a> I think you've become somewhat of an  
<a onclick="modifyYTiframeseektime('219')">0:03:39</a> emblem of Western Civilization right in  
<a onclick="modifyYTiframeseektime('221')">0:03:41</a> terms of your intention help us no you  
<a onclick="modifyYTiframeseektime('224')">0:03:44</a> have and I also pushed back at the point  
<a onclick="modifyYTiframeseektime('225')">0:03:45</a> that this is a foreign culture because I  
<a onclick="modifyYTiframeseektime('226')">0:03:46</a> think that it's like I mean you've  
<a onclick="modifyYTiframeseektime('227')">0:03:47</a> mentioned this in lecture as well that  
<a onclick="modifyYTiframeseektime('228')">0:03:48</a> Islam has now become part of like you  
<a onclick="modifyYTiframeseektime('230')">0:03:50</a> know Western culture yeah well that's  
<a onclick="modifyYTiframeseektime('232')">0:03:52</a> the open question as as we noted in the  
<a onclick="modifyYTiframeseektime('235')">0:03:55</a> introductory marks it's like well our is  
<a onclick="modifyYTiframeseektime('238')">0:03:58</a> Islam part of the West we're kind of  
<a onclick="modifyYTiframeseektime('239')">0:03:59</a> having the same discussion about Russia  
<a onclick="modifyYTiframeseektime('241')">0:04:01</a> in some real sense and yeah that's  
<a onclick="modifyYTiframeseektime('243')">0:04:03</a> really going well at the moment yeah so  
<a onclick="modifyYTiframeseektime('245')">0:04:05</a> there's that part but what I would say  
<a onclick="modifyYTiframeseektime('246')">0:04:06</a> is that you know if there is a bloody  
<a onclick="modifyYTiframeseektime('250')">0:04:10</a> history of Western colonialism and  
<a onclick="modifyYTiframeseektime('252')">0:04:12</a> that's almost undeniable like for  
<a onclick="modifyYTiframeseektime('253')">0:04:13</a> example look at Algeria for instance  
<a onclick="modifyYTiframeseektime('255')">0:04:15</a> Algeria when it was annexed by France  
<a onclick="modifyYTiframeseektime('258')">0:04:18</a> and there's no dispute there's no  
<a onclick="modifyYTiframeseektime('260')">0:04:20</a> dispute in what happened there so the  
<a onclick="modifyYTiframeseektime('261')">0:04:21</a> issue like I'll give you one example of  
<a onclick="modifyYTiframeseektime('263')">0:04:23</a> many this Spanish colonialism of Latin  
<a onclick="modifyYTiframeseektime('266')">0:04:26</a> America for example  
<a onclick="modifyYTiframeseektime('268')">0:04:28</a> um there are things that happened and  
<a onclick="modifyYTiframeseektime('269')">0:04:29</a> it's I'm not saying that's not things  
<a onclick="modifyYTiframeseektime('271')">0:04:31</a> that happened on only just on the  
<a onclick="modifyYTiframeseektime('273')">0:04:33</a> Western Front yeah uh there are things  
<a onclick="modifyYTiframeseektime('275')">0:04:35</a> that happened on the Muslim front as  
<a onclick="modifyYTiframeseektime('276')">0:04:36</a> well of course that's true yeah no doubt  
<a onclick="modifyYTiframeseektime('278')">0:04:38</a> about it right no I'm not going to stand  
<a onclick="modifyYTiframeseektime('280')">0:04:40</a> here and you know defend them who came  
<a onclick="modifyYTiframeseektime('282')">0:04:42</a> and we're very intolerant to uh  
<a onclick="modifyYTiframeseektime('284')">0:04:44</a> producing Christians and kick them out  
<a onclick="modifyYTiframeseektime('285')">0:04:45</a> of their homes and stuff like that who  
<a onclick="modifyYTiframeseektime('287')">0:04:47</a> existed in Spain as well in fact so the  
<a onclick="modifyYTiframeseektime('289')">0:04:49</a> point is I feel like I don't know as a  
<a onclick="modifyYTiframeseektime('291')">0:04:51</a> psychologist I think my question would  
<a onclick="modifyYTiframeseektime('293')">0:04:53</a> be to you that don't you think is it of  
<a onclick="modifyYTiframeseektime('295')">0:04:55</a> any benefit to be concessionary in this  
<a onclick="modifyYTiframeseektime('297')">0:04:57</a> regard like to start off a discussion by  
<a onclick="modifyYTiframeseektime('299')">0:04:59</a> saying like we know  
<a onclick="modifyYTiframeseektime('301')">0:05:01</a> um that these are things that could  
<a onclick="modifyYTiframeseektime('302')">0:05:02</a> cause resentment yes because like for  
<a onclick="modifyYTiframeseektime('305')">0:05:05</a> example I know a lot of Algerian people  
<a onclick="modifyYTiframeseektime('307')">0:05:07</a> and this is very clear in their  
<a onclick="modifyYTiframeseektime('308')">0:05:08</a> historical memory yes and the the  
<a onclick="modifyYTiframeseektime('311')">0:05:11</a> accusation will be that the West have  
<a onclick="modifyYTiframeseektime('313')">0:05:13</a> Colonial Amnesia here they don't they  
<a onclick="modifyYTiframeseektime('316')">0:05:16</a> are not taking into account what they've  
<a onclick="modifyYTiframeseektime('317')">0:05:17</a> done I'll be honest with you they don't  
<a onclick="modifyYTiframeseektime('319')">0:05:19</a> don't even know how well okay yeah well  
<a onclick="modifyYTiframeseektime('322')">0:05:22</a> absolutely I mean look here here's how I  
<a onclick="modifyYTiframeseektime('325')">0:05:25</a> would address that psychologically  
<a onclick="modifyYTiframeseektime('328')">0:05:28</a> um in in many of the mythological  
<a onclick="modifyYTiframeseektime('331')">0:05:31</a> stories that I've read There is the  
<a onclick="modifyYTiframeseektime('334')">0:05:34</a> motif of the evil uncle  
<a onclick="modifyYTiframeseektime('336')">0:05:36</a> and so for example in the ancient  
<a onclick="modifyYTiframeseektime('339')">0:05:39</a> Egyptian cosmology  
<a onclick="modifyYTiframeseektime('341')">0:05:41</a> that there were two there were four  
<a onclick="modifyYTiframeseektime('344')">0:05:44</a> deities four Central deities although a  
<a onclick="modifyYTiframeseektime('346')">0:05:46</a> host of associated deities and one of  
<a onclick="modifyYTiframeseektime('348')">0:05:48</a> them was Osiris who was the deity of the  
<a onclick="modifyYTiframeseektime('350')">0:05:50</a> state that might be a good way of  
<a onclick="modifyYTiframeseektime('352')">0:05:52</a> thinking about it and he had an evil  
<a onclick="modifyYTiframeseektime('353')">0:05:53</a> brother Seth who was always conspiring  
<a onclick="modifyYTiframeseektime('356')">0:05:56</a> in the background to overthrow the state  
<a onclick="modifyYTiframeseektime('358')">0:05:58</a> and to establish his own rules say based  
<a onclick="modifyYTiframeseektime('361')">0:06:01</a> on Power and the Egyptians this is  
<a onclick="modifyYTiframeseektime('364')">0:06:04</a> thousands of years ago had figured out  
<a onclick="modifyYTiframeseektime('365')">0:06:05</a> by that point because their society was  
<a onclick="modifyYTiframeseektime('367')">0:06:07</a> quite large that  
<a onclick="modifyYTiframeseektime('369')">0:06:09</a> there is something in the social  
<a onclick="modifyYTiframeseektime('370')">0:06:10</a> structure itself that posed a threat to  
<a onclick="modifyYTiframeseektime('372')">0:06:12</a> the structure and that was the tendency  
<a onclick="modifyYTiframeseektime('374')">0:06:14</a> for the structure and its leaders to  
<a onclick="modifyYTiframeseektime('376')">0:06:16</a> become willfully blind and for  
<a onclick="modifyYTiframeseektime('378')">0:06:18</a> conspiratorial  
<a onclick="modifyYTiframeseektime('381')">0:06:21</a> powers or patterns that would use  
<a onclick="modifyYTiframeseektime('383')">0:06:23</a> resentment and the desire for power to  
<a onclick="modifyYTiframeseektime('385')">0:06:25</a> overthrow that and they thought of  
<a onclick="modifyYTiframeseektime('387')">0:06:27</a> Osiris as willfully blind and Seth has  
<a onclick="modifyYTiframeseektime('390')">0:06:30</a> an eternal danger and that's true and  
<a onclick="modifyYTiframeseektime('391')">0:06:31</a> and then but there's a there's another  
<a onclick="modifyYTiframeseektime('394')">0:06:34</a> element to the evil Uncle too which is  
<a onclick="modifyYTiframeseektime('396')">0:06:36</a> that in some real sense and it's a very  
<a onclick="modifyYTiframeseektime('399')">0:06:39</a> difficult thing to sort through morally  
<a onclick="modifyYTiframeseektime('401')">0:06:41</a> all of us walk on blood soaked ground  
<a onclick="modifyYTiframeseektime('403')">0:06:43</a> because human history is in some regards  
<a onclick="modifyYTiframeseektime('408')">0:06:48</a> a nightmarish catastrophe and some of  
<a onclick="modifyYTiframeseektime('410')">0:06:50</a> that's just because life was so  
<a onclick="modifyYTiframeseektime('412')">0:06:52</a> difficult but it's also because people  
<a onclick="modifyYTiframeseektime('414')">0:06:54</a> did in unbelievably cruel and malicious  
<a onclick="modifyYTiframeseektime('417')">0:06:57</a> and deceptive  
<a onclick="modifyYTiframeseektime('419')">0:06:59</a> uh  
<a onclick="modifyYTiframeseektime('420')">0:07:00</a> committed committed unbelievably cruel  
<a onclick="modifyYTiframeseektime('422')">0:07:02</a> and atrocious and deceptive acts and so  
<a onclick="modifyYTiframeseektime('425')">0:07:05</a> we're all stuck with this problem that  
<a onclick="modifyYTiframeseektime('427')">0:07:07</a> here we are in relative peace and  
<a onclick="modifyYTiframeseektime('430')">0:07:10</a> Harmony so far although we seem to be  
<a onclick="modifyYTiframeseektime('432')">0:07:12</a> doing everything we can to try to  
<a onclick="modifyYTiframeseektime('434')">0:07:14</a> disrupt that at the moment and part of  
<a onclick="modifyYTiframeseektime('437')">0:07:17</a> the price that's being paid for that is  
<a onclick="modifyYTiframeseektime('439')">0:07:19</a> an endless Litany of historical  
<a onclick="modifyYTiframeseektime('441')">0:07:21</a> catastrophe and then we all have to face  
<a onclick="modifyYTiframeseektime('444')">0:07:24</a> up to well what does that mean for us in  
<a onclick="modifyYTiframeseektime('447')">0:07:27</a> terms of our individual responsibility  
<a onclick="modifyYTiframeseektime('448')">0:07:28</a> and how do we construe ourselves in our  
<a onclick="modifyYTiframeseektime('451')">0:07:31</a> society in light of that fact and we  
<a onclick="modifyYTiframeseektime('454')">0:07:34</a> could go back and forth continually  
<a onclick="modifyYTiframeseektime('456')">0:07:36</a> about whose historical atrocities were  
<a onclick="modifyYTiframeseektime('458')">0:07:38</a> worse and that's a rough contest because  
<a onclick="modifyYTiframeseektime('461')">0:07:41</a> you know the devil is definitely in the  
<a onclick="modifyYTiframeseektime('463')">0:07:43</a> details there and then it also brings up  
<a onclick="modifyYTiframeseektime('465')">0:07:45</a> the other problem which is well  
<a onclick="modifyYTiframeseektime('467')">0:07:47</a> when the Spaniards went to Central  
<a onclick="modifyYTiframeseektime('470')">0:07:50</a> America a lot of the Bloodshed they  
<a onclick="modifyYTiframeseektime('473')">0:07:53</a> produced or the death they produced was  
<a onclick="modifyYTiframeseektime('475')">0:07:55</a> actually a consequence of the  
<a onclick="modifyYTiframeseektime('476')">0:07:56</a> introduction of disease because that  
<a onclick="modifyYTiframeseektime('478')">0:07:58</a> took out about 95 percent of the native  
<a onclick="modifyYTiframeseektime('480')">0:08:00</a> population in the Western Hemisphere and  
<a onclick="modifyYTiframeseektime('483')">0:08:03</a> then the conquistadors were well maybe  
<a onclick="modifyYTiframeseektime('486')">0:08:06</a> they weren't the finest representatives  
<a onclick="modifyYTiframeseektime('488')">0:08:08</a> of the of the highest flowering Western  
<a onclick="modifyYTiframeseektime('490')">0:08:10</a> Civilization we don't know what to what  
<a onclick="modifyYTiframeseektime('493')">0:08:13</a> degree they were the sort of thugs that  
<a onclick="modifyYTiframeseektime('495')">0:08:15</a> couldn't get along at home and went out  
<a onclick="modifyYTiframeseektime('497')">0:08:17</a> adventuring and and then and and even if  
<a onclick="modifyYTiframeseektime('500')">0:08:20</a> I say attempted to take full  
<a onclick="modifyYTiframeseektime('502')">0:08:22</a> responsibility for that I'm not sure  
<a onclick="modifyYTiframeseektime('504')">0:08:24</a> what it would mean because I suspect I  
<a onclick="modifyYTiframeseektime('506')">0:08:26</a> have a lot more in common with you  
<a onclick="modifyYTiframeseektime('508')">0:08:28</a> people in the modern world than I do  
<a onclick="modifyYTiframeseektime('510')">0:08:30</a> with Spanish conquistadors from 300  
<a onclick="modifyYTiframeseektime('512')">0:08:32</a> years ago now I'm not saying I bear no  
<a onclick="modifyYTiframeseektime('515')">0:08:35</a> responsibility for the Bloodshed of the  
<a onclick="modifyYTiframeseektime('518')">0:08:38</a> past but I would say we all bear that  
<a onclick="modifyYTiframeseektime('521')">0:08:41</a> responsibility and that's something I  
<a onclick="modifyYTiframeseektime('523')">0:08:43</a> would say that something like the  
<a onclick="modifyYTiframeseektime('524')">0:08:44</a> conception of original sin yeah that's  
<a onclick="modifyYTiframeseektime('526')">0:08:46</a> the point of difference to be honest I  
<a onclick="modifyYTiframeseektime('528')">0:08:48</a> would disagree with that point like as a  
<a onclick="modifyYTiframeseektime('530')">0:08:50</a> Muslim there is a verse no Quran says  
<a onclick="modifyYTiframeseektime('533')">0:08:53</a> that one Soul should not bear the  
<a onclick="modifyYTiframeseektime('535')">0:08:55</a> responsibility of someone else's actions  
<a onclick="modifyYTiframeseektime('537')">0:08:57</a> yeah well that that's the other ethical  
<a onclick="modifyYTiframeseektime('539')">0:08:59</a> complications so can you call me out in  
<a onclick="modifyYTiframeseektime('543')">0:09:03</a> relationship  
<a onclick="modifyYTiframeseektime('545')">0:09:05</a> but it's complicated right because yeah  
<a onclick="modifyYTiframeseektime('548')">0:09:08</a> but because at the same time you do say  
<a onclick="modifyYTiframeseektime('550')">0:09:10</a> and I don't mean you personally but you  
<a onclick="modifyYTiframeseektime('553')">0:09:13</a> know we can say things like Well the  
<a onclick="modifyYTiframeseektime('555')">0:09:15</a> West is not bearing sufficient  
<a onclick="modifyYTiframeseektime('556')">0:09:16</a> responsibility for its Colonial past and  
<a onclick="modifyYTiframeseektime('559')">0:09:19</a> so at some level that kind of devolves  
<a onclick="modifyYTiframeseektime('561')">0:09:21</a> down to the individual so let me let me  
<a onclick="modifyYTiframeseektime('564')">0:09:24</a> kind of rephrase it then I think you  
<a onclick="modifyYTiframeseektime('565')">0:09:25</a> know I think that's more of a left-wing  
<a onclick="modifyYTiframeseektime('567')">0:09:27</a> criticism that's like you know there's  
<a onclick="modifyYTiframeseektime('568')">0:09:28</a> reparations and affirmative action  
<a onclick="modifyYTiframeseektime('570')">0:09:30</a> programs yeah I'm not advocating any of  
<a onclick="modifyYTiframeseektime('572')">0:09:32</a> that and not I even believe in any of  
<a onclick="modifyYTiframeseektime('573')">0:09:33</a> that to be honest with you or me yeah so  
<a onclick="modifyYTiframeseektime('575')">0:09:35</a> what I was putting as an alternative to  
<a onclick="modifyYTiframeseektime('577')">0:09:37</a> that is this is there is this kind of I  
<a onclick="modifyYTiframeseektime('579')">0:09:39</a> would call this maybe an oriental it's a  
<a onclick="modifyYTiframeseektime('581')">0:09:41</a> new orientalist narrative which states  
<a onclick="modifyYTiframeseektime('583')">0:09:43</a> that Islam is incapable of XYZ call it  
<a onclick="modifyYTiframeseektime('585')">0:09:45</a> tolerance Call It Whatever It Is and  
<a onclick="modifyYTiframeseektime('588')">0:09:48</a> look at what's happened in Islamic  
<a onclick="modifyYTiframeseektime('589')">0:09:49</a> history you've got all of these deaths  
<a onclick="modifyYTiframeseektime('591')">0:09:51</a> and you've got all of these kinds of  
<a onclick="modifyYTiframeseektime('592')">0:09:52</a> things are happening comparative to what  
<a onclick="modifyYTiframeseektime('594')">0:09:54</a> we have in the west and what we're  
<a onclick="modifyYTiframeseektime('595')">0:09:55</a> saying is that let's look at what you  
<a onclick="modifyYTiframeseektime('597')">0:09:57</a> have in the west because liberalism was  
<a onclick="modifyYTiframeseektime('598')">0:09:58</a> an ideology that was cited in the 17th  
<a onclick="modifyYTiframeseektime('600')">0:10:00</a> century like I mean really it was  
<a onclick="modifyYTiframeseektime('601')">0:10:01</a> crystallized you know with John Locke  
<a onclick="modifyYTiframeseektime('602')">0:10:02</a> and all those kind of things then and  
<a onclick="modifyYTiframeseektime('604')">0:10:04</a> after liberalism was established in fact  
<a onclick="modifyYTiframeseektime('606')">0:10:06</a> the Constitution and the documents for  
<a onclick="modifyYTiframeseektime('609')">0:10:09</a> founding fathers and stuff like that  
<a onclick="modifyYTiframeseektime('610')">0:10:10</a> were based on the liberal secular  
<a onclick="modifyYTiframeseektime('612')">0:10:12</a> principles even after that you had  
<a onclick="modifyYTiframeseektime('614')">0:10:14</a> Napoleonic Wars even after that you had  
<a onclick="modifyYTiframeseektime('616')">0:10:16</a> colonialism continue you had slavery  
<a onclick="modifyYTiframeseektime('617')">0:10:17</a> continue until 1867 whatever was you  
<a onclick="modifyYTiframeseektime('620')">0:10:20</a> know the American Civil War ended  
<a onclick="modifyYTiframeseektime('622')">0:10:22</a> um so what we're saying is that this  
<a onclick="modifyYTiframeseektime('624')">0:10:24</a> picture of history that you know the  
<a onclick="modifyYTiframeseektime('626')">0:10:26</a> West is best basically this idea because  
<a onclick="modifyYTiframeseektime('628')">0:10:28</a> our ideology can fix all problems it's  
<a onclick="modifyYTiframeseektime('631')">0:10:31</a> not reasonable when you look at the  
<a onclick="modifyYTiframeseektime('633')">0:10:33</a> Historical records I mean one of um one  
<a onclick="modifyYTiframeseektime('635')">0:10:35</a> scholar called Navid Sheikh actually  
<a onclick="modifyYTiframeseektime('636')">0:10:36</a> done a piece it's called body count and  
<a onclick="modifyYTiframeseektime('639')">0:10:39</a> he was counting the amount of people  
<a onclick="modifyYTiframeseektime('641')">0:10:41</a> that died in each civilization and he  
<a onclick="modifyYTiframeseektime('644')">0:10:44</a> put the Western Civilization is the  
<a onclick="modifyYTiframeseektime('646')">0:10:46</a> highest and because you have things like  
<a onclick="modifyYTiframeseektime('647')">0:10:47</a> World War one and World War II and these  
<a onclick="modifyYTiframeseektime('649')">0:10:49</a> things were World War One World War II  
<a onclick="modifyYTiframeseektime('650')">0:10:50</a> were nationalistic conquests they were  
<a onclick="modifyYTiframeseektime('652')">0:10:52</a> not religiously inspired when you can  
<a onclick="modifyYTiframeseektime('654')">0:10:54</a> you can argue to what extent where World  
<a onclick="modifyYTiframeseektime('656')">0:10:56</a> War one was religiously inspired but  
<a onclick="modifyYTiframeseektime('657')">0:10:57</a> certainly Islam didn't was not a main  
<a onclick="modifyYTiframeseektime('659')">0:10:59</a> feature of the 30 million people that  
<a onclick="modifyYTiframeseektime('661')">0:11:01</a> died in World War One or however many  
<a onclick="modifyYTiframeseektime('663')">0:11:03</a> many million people died in order to so  
<a onclick="modifyYTiframeseektime('665')">0:11:05</a> the point is that we're saying is that  
<a onclick="modifyYTiframeseektime('666')">0:11:06</a> and obviously you've got Concepts in the  
<a onclick="modifyYTiframeseektime('668')">0:11:08</a> west like Manifest Destiny and which I  
<a onclick="modifyYTiframeseektime('671')">0:11:11</a> think every single president of the  
<a onclick="modifyYTiframeseektime('672')">0:11:12</a> United States of America lived in  
<a onclick="modifyYTiframeseektime('673')">0:11:13</a> Westwood expansion these kind of things  
<a onclick="modifyYTiframeseektime('675')">0:11:15</a> the point is is that the proposition  
<a onclick="modifyYTiframeseektime('678')">0:11:18</a> that the ideology of the West can fix  
<a onclick="modifyYTiframeseektime('681')">0:11:21</a> our problems this is what we have an  
<a onclick="modifyYTiframeseektime('682')">0:11:22</a> issue with because what we're saying is  
<a onclick="modifyYTiframeseektime('684')">0:11:24</a> that if we look at the historical record  
<a onclick="modifyYTiframeseektime('685')">0:11:25</a> there is no evidence of that in fact  
<a onclick="modifyYTiframeseektime('688')">0:11:28</a> what has shown us is that there's more  
<a onclick="modifyYTiframeseektime('689')">0:11:29</a> Bloodshed individualism has caused More  
<a onclick="modifyYTiframeseektime('691')">0:11:31</a> Death like with all due respect I know  
<a onclick="modifyYTiframeseektime('694')">0:11:34</a> that you you do cherish individuals I'm  
<a onclick="modifyYTiframeseektime('696')">0:11:36</a> not saying everything is bad about it  
<a onclick="modifyYTiframeseektime('697')">0:11:37</a> but there's when when you have a society  
<a onclick="modifyYTiframeseektime('699')">0:11:39</a> deplete of a communitarian ethic  
<a onclick="modifyYTiframeseektime('702')">0:11:42</a> is bereft of a communitarian ethic then  
<a onclick="modifyYTiframeseektime('705')">0:11:45</a> you can have these issues and so these  
<a onclick="modifyYTiframeseektime('708')">0:11:48</a> are conversations and I think you are  
<a onclick="modifyYTiframeseektime('709')">0:11:49</a> moving towards a communitarianism your  
<a onclick="modifyYTiframeseektime('711')">0:11:51</a> newest book you're talking about  
<a onclick="modifyYTiframeseektime('712')">0:11:52</a> institutions and these kind of things  
<a onclick="modifyYTiframeseektime('713')">0:11:53</a> and the respectful tradition and these  
<a onclick="modifyYTiframeseektime('715')">0:11:55</a> kind of things I'm not sure if I'm  
<a onclick="modifyYTiframeseektime('717')">0:11:57</a> reading you correctly but  
<a onclick="modifyYTiframeseektime('718')">0:11:58</a> these are the kinds of conversations I  
<a onclick="modifyYTiframeseektime('720')">0:12:00</a> think we need to have but on that point  
<a onclick="modifyYTiframeseektime('722')">0:12:02</a> I think  
<a onclick="modifyYTiframeseektime('723')">0:12:03</a> I don't want this to be interrogative  
</details>