# Ex-Shia Muslim TV host Interview (Fascinating) || Br. Mohammed Hijab PART 1/2 (2016-11-09)

<iframe loading='lazy' src='https://www.youtube.com/embed/kxQ_YABUmJ8'></iframe>

## Description

A proper understanding of the Shia argument by a former Shia preacher.


Useful sites and references: 

www.sonsofsunnah.com 

www.twelvershia.net 

- reference for "Sunni narrated more from ahlul bayt than Shia " claim - https://youpuncturedtheark.wordpress.com/2011/04/27/narrations-from-ahl-albayt-present-in-books-the-main-books-of-ahlesunnah/amp/

Reference for "12 caliph claim not referring to infallible imams" 
https://www.youtube.com/shared?ci=Yg0VTHjUNBw



Follow brother Mohammed hijab on: 

 www.facebook.com/brothermohammedhijab
 www.instagram.com/bromohammedhijab

## Summary of [Ex-Shia Muslim TV host Interview (Fascinating) || Br. Mohammed Hijab PART 1/2](https://www.youtube.com/watch?v=kxQ_YABUmJ8)


*<span style="color:red; font-size:125%">This summary is AI generated - there may be inaccuracies</span>. [](/)*

### <a onclick="modifyYTiframeseektime('0')">00:00:00</a> - <a onclick="modifyYTiframeseektime('1800')">00:30:00</a>

, an ex-Shia Muslim TV host interviews Br. Mohammed Hijab about the different beliefs of Shia and Sunni Muslims. Hijab discusses the Quran's teachings on gender equality and the Sunnah, which he believes are the source of Islamic law. He notes that many Shia Muslims adhere to a sectarian mindset and engage in copy-pasting and discussions in order to find evidence to support their beliefs, instead of relying on the Quran and Sunnah.

**<a onclick="modifyYTiframeseektime('0')">00:00:00</a>** Alastair Hasan Rashid is a former Shia Muslim TV host who has recently shifted his focus to Sunni issues. He discusses the different beliefs about the Imams among Shia Muslims, and how this differs from mainstream Sunni beliefs.
* **<a onclick="modifyYTiframeseektime('300')">00:05:00</a>** The host of a former Shia Muslim TV show discusses some of the beliefs of mainstream Shia Muslims, including the idea that a certain Imam is a "correct imam." The host also points out that mainstream Shia Muslims believe in a number of other beliefs which Sunnis and Shia agree on, such as the correctness of one Imam after Prophet Muhammad.
* **<a onclick="modifyYTiframeseektime('600')">00:10:00</a>** The host of an ex-Shia Muslim TV show discusses the Ayah (verse) "Verily, in them like certainly Allah desires to remove the risk from you, a little bit" and how it is used as one of the strongest evidences against other Muslims. Their belief is that this verse speaks to the wives of the Prophet Muhammad (peace be upon him), and that it should be addressed in a muscular form.
* **<a onclick="modifyYTiframeseektime('900')">00:15:00</a>** The host of an ex-Shia Muslim TV show interviews Br. Mohammed Hijab, a Muslim scholar and ex-Shia who has since converted to Sunni Islam. Hijab discusses the Qur'an's teachings on gender equality and the Sunnah, which he believes are the source of Islamic law. He notes that many Shia Muslims adhere to a sectarian mindset and engage in copy-pasting and discussions in order to find evidence to support their beliefs, instead of relying on the Quran and Sunnah.
* **<a onclick="modifyYTiframeseektime('1200')">00:20:00</a>** The Shia Muslim TV host interviews Br. Mohammed Hijab about the relationship between the prophet Muhammad's family and the sahaba. He explains that for Shia Muslims, the key tenants are that the prophet left behind two things - the Quran and the prophet's family. This is clear evidences that Shia Muslims should be following the bait and not following the sahaba. Sunnis believe that Abdullah bin Abbas is a little bit of a scholar and that he is the translator in the Quran. Another interesting point made is that Abu Bakr and Omar are also well known among the scholars, but Ali is known more so for his role as the first khalif (caliph). There is no contradiction in accepting amar, or other companions of the prophet, while rejecting other companions like Awakening.
* **<a onclick="modifyYTiframeseektime('1500')">00:25:00</a>** Nakshawani, a Shi'ite Muslim apologist, says that Sunnis do not discuss these topics and that they are not prepared to debate. He also says that the Sahaba, or early companions of the Prophet Muhammad, included many great personalities with one creed, one belief system, and one way of life. Nakshawani challenges accept no that Sunnis should not debate him, and he provides a clip of a recent lecture in which he says that the root of terrorism is Wahhabism, a sect of Sunni Islam.
* **<a onclick="modifyYTiframeseektime('1800')">00:30:00</a>** features an ex-Shia Muslim TV host discussing how he changed his views on Sunni Muslims after watching a lecture by Br. Mohammed Hijab. He says that while he used to think that sunnis could discuss issues such as salah and conquest, he now realizes that this is not the case. He also says that he hopes Br. Mohammed Hijab will accept this challenge and have a discussion with him.

<details><summary><h2>Full transcript with timestamps: CLICK TO EXPAND</h2></summary>

<a onclick="modifyYTiframeseektime('2')">0:00:02</a> guys today we've got a very special  
<a onclick="modifyYTiframeseektime('3')">0:00:03</a> guest  
<a onclick="modifyYTiframeseektime('4')">0:00:04</a> his name is alastair hassan rashid he is  
<a onclick="modifyYTiframeseektime('7')">0:00:07</a> actually a  
<a onclick="modifyYTiframeseektime('8')">0:00:08</a> researcher in shia islam for many many  
<a onclick="modifyYTiframeseektime('11')">0:00:11</a> years he has many publications he is  
<a onclick="modifyYTiframeseektime('14')">0:00:14</a> someone who has his own tv program  
<a onclick="modifyYTiframeseektime('16')">0:00:16</a> in farsi language which is one of many  
<a onclick="modifyYTiframeseektime('19')">0:00:19</a> languages he knows how to speak he's  
<a onclick="modifyYTiframeseektime('20')">0:00:20</a> multilingual  
<a onclick="modifyYTiframeseektime('21')">0:00:21</a> he knows how to speak four or five  
<a onclick="modifyYTiframeseektime('22')">0:00:22</a> different languages and he's with us  
<a onclick="modifyYTiframeseektime('25')">0:00:25</a> today  
<a onclick="modifyYTiframeseektime('25')">0:00:25</a> to discuss this all important topic  
<a onclick="modifyYTiframeseektime('42')">0:00:42</a> that i cover most things  
<a onclick="modifyYTiframeseektime('66')">0:01:06</a> to all the viewers and to you bravo yes  
<a onclick="modifyYTiframeseektime('70')">0:01:10</a> everything you said is correct except  
<a onclick="modifyYTiframeseektime('72')">0:01:12</a> you said that um  
<a onclick="modifyYTiframeseektime('73')">0:01:13</a> i publish a lot of things i'm not really  
<a onclick="modifyYTiframeseektime('75')">0:01:15</a> i haven't yet wrote  
<a onclick="modifyYTiframeseektime('77')">0:01:17</a> books maybe in the future insha allah  
<a onclick="modifyYTiframeseektime('78')">0:01:18</a> but yes um  
<a onclick="modifyYTiframeseektime('80')">0:01:20</a> it's now uh more than a decade that i'm  
<a onclick="modifyYTiframeseektime('83')">0:01:23</a> doing  
<a onclick="modifyYTiframeseektime('84')">0:01:24</a> in this field researching she sunni  
<a onclick="modifyYTiframeseektime('87')">0:01:27</a> issues  
<a onclick="modifyYTiframeseektime('88')">0:01:28</a> and my background as you stated is  
<a onclick="modifyYTiframeseektime('90')">0:01:30</a> correct yes i'm  
<a onclick="modifyYTiframeseektime('91')">0:01:31</a> i'm i was born in iran and um  
<a onclick="modifyYTiframeseektime('95')">0:01:35</a> i'm not raised most of my life in the  
<a onclick="modifyYTiframeseektime('96')">0:01:36</a> west and i've seen both  
<a onclick="modifyYTiframeseektime('98')">0:01:38</a> visited iran many times yeah and  
<a onclick="modifyYTiframeseektime('102')">0:01:42</a> you speak farsi fully i speak farsi i  
<a onclick="modifyYTiframeseektime('104')">0:01:44</a> speak uh would you mind saying something  
<a onclick="modifyYTiframeseektime('106')">0:01:46</a> for the camera  
<a onclick="modifyYTiframeseektime('107')">0:01:47</a> maybe someone could uh  
<a onclick="modifyYTiframeseektime('111')">0:01:51</a> yes i speak farsi fully i speak arabic  
<a onclick="modifyYTiframeseektime('114')">0:01:54</a> and i speak other languages as well  
<a onclick="modifyYTiframeseektime('115')">0:01:55</a> alhamdulillah  
<a onclick="modifyYTiframeseektime('116')">0:01:56</a> and um yes  
<a onclick="modifyYTiframeseektime('119')">0:01:59</a> as you correctly said it i'm doing this  
<a onclick="modifyYTiframeseektime('121')">0:02:01</a> now for over a decade now  
<a onclick="modifyYTiframeseektime('123')">0:02:03</a> um the most recent thing i've done  
<a onclick="modifyYTiframeseektime('126')">0:02:06</a> i was a host uh  
<a onclick="modifyYTiframeseektime('129')">0:02:09</a> i had my own show alhamdulillah on the  
<a onclick="modifyYTiframeseektime('131')">0:02:11</a> islamic  
<a onclick="modifyYTiframeseektime('132')">0:02:12</a> tv channel persian tv channel and um  
<a onclick="modifyYTiframeseektime('136')">0:02:16</a> maybe later on we can talk about that a  
<a onclick="modifyYTiframeseektime('138')">0:02:18</a> little bit more to explain what kind of  
<a onclick="modifyYTiframeseektime('140')">0:02:20</a> islamic means a lot of people i want to  
<a onclick="modifyYTiframeseektime('142')">0:02:22</a> ask you the first question get straight  
<a onclick="modifyYTiframeseektime('143')">0:02:23</a> into it inshallah  
<a onclick="modifyYTiframeseektime('145')">0:02:25</a> am i right in saying that probably imam  
<a onclick="modifyYTiframeseektime('148')">0:02:28</a> or the concept of imam that she has  
<a onclick="modifyYTiframeseektime('150')">0:02:30</a> believed in is the most  
<a onclick="modifyYTiframeseektime('152')">0:02:32</a> is the biggest difference between sunnis  
<a onclick="modifyYTiframeseektime('154')">0:02:34</a> and shia that's correct  
<a onclick="modifyYTiframeseektime('156')">0:02:36</a> could you explain exactly what this is  
<a onclick="modifyYTiframeseektime('158')">0:02:38</a> and for the viewers in china  
<a onclick="modifyYTiframeseektime('160')">0:02:40</a> first let me confirm what you said yes  
<a onclick="modifyYTiframeseektime('163')">0:02:43</a> imam  
<a onclick="modifyYTiframeseektime('164')">0:02:44</a> is is one of the or the two main  
<a onclick="modifyYTiframeseektime('167')">0:02:47</a> issue although some people might also  
<a onclick="modifyYTiframeseektime('169')">0:02:49</a> add that  
<a onclick="modifyYTiframeseektime('170')">0:02:50</a> issues such as the meaning of worship  
<a onclick="modifyYTiframeseektime('173')">0:02:53</a> what is worship and rituals that are  
<a onclick="modifyYTiframeseektime('176')">0:02:56</a> very different between sunnis and shias  
<a onclick="modifyYTiframeseektime('178')">0:02:58</a> are  
<a onclick="modifyYTiframeseektime('178')">0:02:58</a> maybe even bigger than imam but  
<a onclick="modifyYTiframeseektime('180')">0:03:00</a> everything really goes back to imam  
<a onclick="modifyYTiframeseektime('182')">0:03:02</a> of course because the shia sect in  
<a onclick="modifyYTiframeseektime('184')">0:03:04</a> general  
<a onclick="modifyYTiframeseektime('185')">0:03:05</a> is a sect that believes that um  
<a onclick="modifyYTiframeseektime('189')">0:03:09</a> the imam the the rulership after the  
<a onclick="modifyYTiframeseektime('192')">0:03:12</a> prophet sallallahu alaihi  
<a onclick="modifyYTiframeseektime('193')">0:03:13</a> wasallam should have been state within  
<a onclick="modifyYTiframeseektime('195')">0:03:15</a> the prophet's family this is just  
<a onclick="modifyYTiframeseektime('197')">0:03:17</a> generally speaking yeah of course when  
<a onclick="modifyYTiframeseektime('198')">0:03:18</a> me and you are mentioning  
<a onclick="modifyYTiframeseektime('200')">0:03:20</a> shia shia we should be a bit more  
<a onclick="modifyYTiframeseektime('201')">0:03:21</a> precise shira means a lot of things  
<a onclick="modifyYTiframeseektime('204')">0:03:24</a> so when we say imam to different shias  
<a onclick="modifyYTiframeseektime('206')">0:03:26</a> does it mean different things  
<a onclick="modifyYTiframeseektime('207')">0:03:27</a> yes to differentiate mean different  
<a onclick="modifyYTiframeseektime('209')">0:03:29</a> things to the zedis who ruled yemen for  
<a onclick="modifyYTiframeseektime('211')">0:03:31</a> thousand years it mean it is a political  
<a onclick="modifyYTiframeseektime('213')">0:03:33</a> thing  
<a onclick="modifyYTiframeseektime('214')">0:03:34</a> um it is not restricted to to a specific  
<a onclick="modifyYTiframeseektime('218')">0:03:38</a> group let alone to 12 individuals it's  
<a onclick="modifyYTiframeseektime('220')">0:03:40</a> different it's not twelve imams for  
<a onclick="modifyYTiframeseektime('222')">0:03:42</a> eighties  
<a onclick="modifyYTiframeseektime('222')">0:03:42</a> no it's not it's not travel monster to  
<a onclick="modifyYTiframeseektime('224')">0:03:44</a> non-group except the 12 verse  
<a onclick="modifyYTiframeseektime('226')">0:03:46</a> so the thing is in our age in time when  
<a onclick="modifyYTiframeseektime('229')">0:03:49</a> we speak when people use the word shia  
<a onclick="modifyYTiframeseektime('231')">0:03:51</a> shia  
<a onclick="modifyYTiframeseektime('232')">0:03:52</a> yes of course they mean to 12 because  
<a onclick="modifyYTiframeseektime('234')">0:03:54</a> they are they happen to be today the  
<a onclick="modifyYTiframeseektime('236')">0:03:56</a> majority they were not always the  
<a onclick="modifyYTiframeseektime('237')">0:03:57</a> majority  
<a onclick="modifyYTiframeseektime('238')">0:03:58</a> there were times for example in my own  
<a onclick="modifyYTiframeseektime('239')">0:03:59</a> country iran where  
<a onclick="modifyYTiframeseektime('242')">0:04:02</a> before the suffoli era where iran was a  
<a onclick="modifyYTiframeseektime('244')">0:04:04</a> majority sunni country  
<a onclick="modifyYTiframeseektime('246')">0:04:06</a> just 500 years ago there were shia in  
<a onclick="modifyYTiframeseektime('248')">0:04:08</a> iran yeah  
<a onclick="modifyYTiframeseektime('249')">0:04:09</a> even even when iran was the majority of  
<a onclick="modifyYTiframeseektime('250')">0:04:10</a> sonic country but there were zadis the  
<a onclick="modifyYTiframeseektime('252')">0:04:12</a> vast majority  
<a onclick="modifyYTiframeseektime('253')">0:04:13</a> so there was a time in islamic history  
<a onclick="modifyYTiframeseektime('255')">0:04:15</a> where the vast majority of shias in the  
<a onclick="modifyYTiframeseektime('256')">0:04:16</a> world  
<a onclick="modifyYTiframeseektime('257')">0:04:17</a> were zades is it true that so what what  
<a onclick="modifyYTiframeseektime('260')">0:04:20</a> do  
<a onclick="modifyYTiframeseektime('261')">0:04:21</a> shiites or let's say 12 is in particular  
<a onclick="modifyYTiframeseektime('263')">0:04:23</a> what do they believe about the imams  
<a onclick="modifyYTiframeseektime('266')">0:04:26</a> well the of twelvers have certain  
<a onclick="modifyYTiframeseektime('267')">0:04:27</a> beliefs about the imams which ha which  
<a onclick="modifyYTiframeseektime('269')">0:04:29</a> are  
<a onclick="modifyYTiframeseektime('270')">0:04:30</a> believed as in consensus they have okay  
<a onclick="modifyYTiframeseektime('274')">0:04:34</a> so i'm gonna what i'm gonna mention i'm  
<a onclick="modifyYTiframeseektime('275')">0:04:35</a> not gonna mention anything which is um  
<a onclick="modifyYTiframeseektime('278')">0:04:38</a> you know disputed yeah you know where  
<a onclick="modifyYTiframeseektime('280')">0:04:40</a> somebody could say i know but this is  
<a onclick="modifyYTiframeseektime('282')">0:04:42</a> you know this this is disputed  
<a onclick="modifyYTiframeseektime('284')">0:04:44</a> this is not mainstream i'm going to  
<a onclick="modifyYTiframeseektime('285')">0:04:45</a> mention only mainstream  
<a onclick="modifyYTiframeseektime('287')">0:04:47</a> among the mainstream is of course they  
<a onclick="modifyYTiframeseektime('289')">0:04:49</a> believe in 12 imams who  
<a onclick="modifyYTiframeseektime('291')">0:04:51</a> are infallible like prophets or  
<a onclick="modifyYTiframeseektime('293')">0:04:53</a> infallible like prophets  
<a onclick="modifyYTiframeseektime('295')">0:04:55</a> they are chosen by allah and his  
<a onclick="modifyYTiframeseektime('297')">0:04:57</a> messenger  
<a onclick="modifyYTiframeseektime('298')">0:04:58</a> yeah by clear nos means text from the  
<a onclick="modifyYTiframeseektime('301')">0:05:01</a> quran  
<a onclick="modifyYTiframeseektime('302')">0:05:02</a> as they claim and so we have  
<a onclick="modifyYTiframeseektime('305')">0:05:05</a> 12 men who are apparently infallible  
<a onclick="modifyYTiframeseektime('309')">0:05:09</a> apparently clear-cut chosen in the  
<a onclick="modifyYTiframeseektime('311')">0:05:11</a> islamic text  
<a onclick="modifyYTiframeseektime('312')">0:05:12</a> and and there's some other things such  
<a onclick="modifyYTiframeseektime('315')">0:05:15</a> as  
<a onclick="modifyYTiframeseektime('317')">0:05:17</a> yeah that they have the knowledge of the  
<a onclick="modifyYTiframeseektime('319')">0:05:19</a> unseen  
<a onclick="modifyYTiframeseektime('320')">0:05:20</a> not as mainstream muslims believe of  
<a onclick="modifyYTiframeseektime('323')">0:05:23</a> course we believe that the prophet  
<a onclick="modifyYTiframeseektime('324')">0:05:24</a> salallahu or even you me and you  
<a onclick="modifyYTiframeseektime('326')">0:05:26</a> we we know we have knowledge of certain  
<a onclick="modifyYTiframeseektime('328')">0:05:28</a> things about the future what our prophet  
<a onclick="modifyYTiframeseektime('330')">0:05:30</a> told us  
<a onclick="modifyYTiframeseektime('331')">0:05:31</a> but you don't go around and say have the  
<a onclick="modifyYTiframeseektime('333')">0:05:33</a> knowledge of the unseen so  
<a onclick="modifyYTiframeseektime('335')">0:05:35</a> does that mean in totality they have all  
<a onclick="modifyYTiframeseektime('337')">0:05:37</a> the knowledge of the unseen they believe  
<a onclick="modifyYTiframeseektime('338')">0:05:38</a> they know everything i i yes they know  
<a onclick="modifyYTiframeseektime('342')">0:05:42</a> we i can go as far as to say it is  
<a onclick="modifyYTiframeseektime('346')">0:05:46</a> literally describe their knowledge as  
<a onclick="modifyYTiframeseektime('348')">0:05:48</a> allah's knowledge  
<a onclick="modifyYTiframeseektime('349')">0:05:49</a> and it's easy for anybody to check what  
<a onclick="modifyYTiframeseektime('351')">0:05:51</a> i say you want you need to so what kind  
<a onclick="modifyYTiframeseektime('352')">0:05:52</a> of references are there the references  
<a onclick="modifyYTiframeseektime('354')">0:05:54</a> you don't even need to go and look for  
<a onclick="modifyYTiframeseektime('356')">0:05:56</a> hadith life and  
<a onclick="modifyYTiframeseektime('358')">0:05:58</a> sahih you know somebody's saying yeah  
<a onclick="modifyYTiframeseektime('360')">0:06:00</a> are you are you  
<a onclick="modifyYTiframeseektime('361')">0:06:01</a> suggesting our weak hadith or whatever  
<a onclick="modifyYTiframeseektime('363')">0:06:03</a> no you just need to go and look the  
<a onclick="modifyYTiframeseektime('365')">0:06:05</a> chapters of al-qafi  
<a onclick="modifyYTiframeseektime('367')">0:06:07</a> al-kafi is the main shia book some  
<a onclick="modifyYTiframeseektime('369')">0:06:09</a> sunnis have mis  
<a onclick="modifyYTiframeseektime('371')">0:06:11</a> misconception about it they think it is  
<a onclick="modifyYTiframeseektime('372')">0:06:12</a> it is exactly like the bukhari of the  
<a onclick="modifyYTiframeseektime('374')">0:06:14</a> sunnis  
<a onclick="modifyYTiframeseektime('375')">0:06:15</a> it's not okay it's not exactly it's they  
<a onclick="modifyYTiframeseektime('377')">0:06:17</a> treat it different however it is correct  
<a onclick="modifyYTiframeseektime('379')">0:06:19</a> to say this is the most  
<a onclick="modifyYTiframeseektime('380')">0:06:20</a> important and the most authentic book of  
<a onclick="modifyYTiframeseektime('383')">0:06:23</a> hadith according to them  
<a onclick="modifyYTiframeseektime('385')">0:06:25</a> not everything there is authentic i'm  
<a onclick="modifyYTiframeseektime('386')">0:06:26</a> not saying that nobody should say this  
<a onclick="modifyYTiframeseektime('388')">0:06:28</a> yeah we should be honest with everybody  
<a onclick="modifyYTiframeseektime('390')">0:06:30</a> with any religion every ideology  
<a onclick="modifyYTiframeseektime('393')">0:06:33</a> we should say only the truth about them  
<a onclick="modifyYTiframeseektime('395')">0:06:35</a> however when you go through coffee and  
<a onclick="modifyYTiframeseektime('397')">0:06:37</a> you can do that  
<a onclick="modifyYTiframeseektime('398')">0:06:38</a> and um and just  
<a onclick="modifyYTiframeseektime('401')">0:06:41</a> about the chapters  
<a onclick="modifyYTiframeseektime('404')">0:06:44</a> the chapters for example i myself on my  
<a onclick="modifyYTiframeseektime('407')">0:06:47</a> show i'll never forget that just  
<a onclick="modifyYTiframeseektime('408')">0:06:48</a> quickly um one day on my show we had a  
<a onclick="modifyYTiframeseektime('411')">0:06:51</a> show about  
<a onclick="modifyYTiframeseektime('412')">0:06:52</a> uh the coffer beliefs  
<a onclick="modifyYTiframeseektime('415')">0:06:55</a> according to mainstream islam which can  
<a onclick="modifyYTiframeseektime('419')">0:06:59</a> be derived by just  
<a onclick="modifyYTiframeseektime('420')">0:07:00</a> reading the chapters of al qaeda of  
<a onclick="modifyYTiframeseektime('423')">0:07:03</a> course  
<a onclick="modifyYTiframeseektime('423')">0:07:03</a> a few examples well there's there's  
<a onclick="modifyYTiframeseektime('425')">0:07:05</a> chapters there's a number of chapters  
<a onclick="modifyYTiframeseektime('427')">0:07:07</a> about  
<a onclick="modifyYTiframeseektime('427')">0:07:07</a> what kind of knowledge the imams have  
<a onclick="modifyYTiframeseektime('429')">0:07:09</a> all right this is important  
<a onclick="modifyYTiframeseektime('431')">0:07:11</a> for example there are there's a chapter  
<a onclick="modifyYTiframeseektime('433')">0:07:13</a> that the imams know when they die  
<a onclick="modifyYTiframeseektime('435')">0:07:15</a> and so on the imam's knowledge is like  
<a onclick="modifyYTiframeseektime('437')">0:07:17</a> the he  
<a onclick="modifyYTiframeseektime('438')">0:07:18</a> has knowledge uh narrations are under  
<a onclick="modifyYTiframeseektime('441')">0:07:21</a> these chapters that the knowledge of the  
<a onclick="modifyYTiframeseektime('442')">0:07:22</a> imam is exactly he knows  
<a onclick="modifyYTiframeseektime('446')">0:07:26</a> every leafs every leaf that drops from a  
<a onclick="modifyYTiframeseektime('448')">0:07:28</a> tree  
<a onclick="modifyYTiframeseektime('449')">0:07:29</a> he knows every drop in the ocean now me  
<a onclick="modifyYTiframeseektime('451')">0:07:31</a> and you every muslim knows  
<a onclick="modifyYTiframeseektime('453')">0:07:33</a> who is described with this kind of emory  
<a onclick="modifyYTiframeseektime('457')">0:07:37</a> so you see these word games by saying  
<a onclick="modifyYTiframeseektime('460')">0:07:40</a> but every muslim believes kind of in the  
<a onclick="modifyYTiframeseektime('463')">0:07:43</a> prophet saws got some information from  
<a onclick="modifyYTiframeseektime('465')">0:07:45</a> the rape  
<a onclick="modifyYTiframeseektime('466')">0:07:46</a> yes but who said that the prophet  
<a onclick="modifyYTiframeseektime('468')">0:07:48</a> salallahu  
<a onclick="modifyYTiframeseektime('470')">0:07:50</a> which sect has ever said the prophet  
<a onclick="modifyYTiframeseektime('472')">0:07:52</a> sallallahu alaihi wasallam  
<a onclick="modifyYTiframeseektime('473')">0:07:53</a> knows every drop in the ocean yeah even  
<a onclick="modifyYTiframeseektime('476')">0:07:56</a> the quran  
<a onclick="modifyYTiframeseektime('485')">0:08:05</a> telling the prophet that say i'm not  
<a onclick="modifyYTiframeseektime('487')">0:08:07</a> something new of the prophets and i  
<a onclick="modifyYTiframeseektime('488')">0:08:08</a> don't know what's going to happen to me  
<a onclick="modifyYTiframeseektime('490')">0:08:10</a> yeah  
<a onclick="modifyYTiframeseektime('492')">0:08:12</a> there's other verses there's verses in  
<a onclick="modifyYTiframeseektime('493')">0:08:13</a> the quran uh  
<a onclick="modifyYTiframeseektime('495')">0:08:15</a> about the prophet not knowing the moon  
<a onclick="modifyYTiframeseektime('498')">0:08:18</a> which unfortunately according to  
<a onclick="modifyYTiframeseektime('500')">0:08:20</a> the sahaba we'll come to that in a  
<a onclick="modifyYTiframeseektime('502')">0:08:22</a> second  
<a onclick="modifyYTiframeseektime('503')">0:08:23</a> but just to complete that  
<a onclick="modifyYTiframeseektime('514')">0:08:34</a> i think all of these we can put it in  
<a onclick="modifyYTiframeseektime('516')">0:08:36</a> the description but people can do their  
<a onclick="modifyYTiframeseektime('517')">0:08:37</a> research  
<a onclick="modifyYTiframeseektime('518')">0:08:38</a> if this is the  
<a onclick="modifyYTiframeseektime('523')">0:08:43</a> describing the prophet in that way then  
<a onclick="modifyYTiframeseektime('525')">0:08:45</a> you have a religion where 12 people  
<a onclick="modifyYTiframeseektime('527')">0:08:47</a> after him know every leaf that drops  
<a onclick="modifyYTiframeseektime('529')">0:08:49</a> from a tree  
<a onclick="modifyYTiframeseektime('530')">0:08:50</a> no every drop that is in the ocean these  
<a onclick="modifyYTiframeseektime('533')">0:08:53</a> are not hadith sahih  
<a onclick="modifyYTiframeseektime('534')">0:08:54</a> so somebody can reject it okay chapters  
<a onclick="modifyYTiframeseektime('537')">0:08:57</a> are put and people of knowledge know  
<a onclick="modifyYTiframeseektime('538')">0:08:58</a> that  
<a onclick="modifyYTiframeseektime('539')">0:08:59</a> if a scholar puts chapters  
<a onclick="modifyYTiframeseektime('542')">0:09:02</a> why does he put these chapters to fill  
<a onclick="modifyYTiframeseektime('544')">0:09:04</a> in beliefs  
<a onclick="modifyYTiframeseektime('546')">0:09:06</a> right for example usual kafi al-kafi is  
<a onclick="modifyYTiframeseektime('548')">0:09:08</a> divided into three  
<a onclick="modifyYTiframeseektime('550')">0:09:10</a> usual rav turkafi and so on usual  
<a onclick="modifyYTiframeseektime('553')">0:09:13</a> is the main body of al-kafi where they  
<a onclick="modifyYTiframeseektime('556')">0:09:16</a> derive their beliefs  
<a onclick="modifyYTiframeseektime('558')">0:09:18</a> one of the belief which is exaggeration  
<a onclick="modifyYTiframeseektime('561')">0:09:21</a> with the imams we believe is the belief  
<a onclick="modifyYTiframeseektime('562')">0:09:22</a> about  
<a onclick="modifyYTiframeseektime('563')">0:09:23</a> the way they believe about the imams as  
<a onclick="modifyYTiframeseektime('565')">0:09:25</a> in regards to  
<a onclick="modifyYTiframeseektime('567')">0:09:27</a> what evidences um do shias have from the  
<a onclick="modifyYTiframeseektime('571')">0:09:31</a> quran  
<a onclick="modifyYTiframeseektime('571')">0:09:31</a> or from the sunnah that everyone is  
<a onclick="modifyYTiframeseektime('574')">0:09:34</a> basically sunnis and shias  
<a onclick="modifyYTiframeseektime('576')">0:09:36</a> agree on that this imam is  
<a onclick="modifyYTiframeseektime('579')">0:09:39</a> a correct imam uh or a true one  
<a onclick="modifyYTiframeseektime('582')">0:09:42</a> imam as in imam of twelve imams that  
<a onclick="modifyYTiframeseektime('585')">0:09:45</a> have to be obeyed after the prophet  
<a onclick="modifyYTiframeseektime('588')">0:09:48</a> well of course she is like every other  
<a onclick="modifyYTiframeseektime('590')">0:09:50</a> sect for the main belief have filled  
<a onclick="modifyYTiframeseektime('592')">0:09:52</a> books  
<a onclick="modifyYTiframeseektime('592')">0:09:52</a> claiming that it's very clear in the  
<a onclick="modifyYTiframeseektime('594')">0:09:54</a> quran very clear in the sunnah the imam  
<a onclick="modifyYTiframeseektime('596')">0:09:56</a> of ali  
<a onclick="modifyYTiframeseektime('597')">0:09:57</a> and the imam of the second imam al-hasan  
<a onclick="modifyYTiframeseektime('599')">0:09:59</a> and the imam of the third imam  
<a onclick="modifyYTiframeseektime('600')">0:10:00</a> al-hussein an imam of the fourth imam  
<a onclick="modifyYTiframeseektime('602')">0:10:02</a> uh  
<a onclick="modifyYTiframeseektime('607')">0:10:07</a> there's no doubt about that they have  
<a onclick="modifyYTiframeseektime('609')">0:10:09</a> written a lot but the thing is um  
<a onclick="modifyYTiframeseektime('612')">0:10:12</a> what we believe in regard to what they  
<a onclick="modifyYTiframeseektime('614')">0:10:14</a> use as evidence is that  
<a onclick="modifyYTiframeseektime('616')">0:10:16</a> all these evidences are shallow they are  
<a onclick="modifyYTiframeseektime('618')">0:10:18</a> not strong  
<a onclick="modifyYTiframeseektime('619')">0:10:19</a> for example you if you want really now  
<a onclick="modifyYTiframeseektime('621')">0:10:21</a> examples i can tell you  
<a onclick="modifyYTiframeseektime('623')">0:10:23</a> the famous and you have heard of it um  
<a onclick="modifyYTiframeseektime('627')">0:10:27</a> and they are also very quick in giving  
<a onclick="modifyYTiframeseektime('628')">0:10:28</a> names to these eyes making them  
<a onclick="modifyYTiframeseektime('630')">0:10:30</a> ayata  
<a onclick="modifyYTiframeseektime('641')">0:10:41</a> one of the first shocking thing is it's  
<a onclick="modifyYTiframeseektime('643')">0:10:43</a> not even a complete ayah what they  
<a onclick="modifyYTiframeseektime('644')">0:10:44</a> recite they  
<a onclick="modifyYTiframeseektime('650')">0:10:50</a> this is not even a complete verse it is  
<a onclick="modifyYTiframeseektime('652')">0:10:52</a> it is is cut in half  
<a onclick="modifyYTiframeseektime('654')">0:10:54</a> but they call it a verse and remember  
<a onclick="modifyYTiframeseektime('658')">0:10:58</a> in mosque and she a mosque that i used  
<a onclick="modifyYTiframeseektime('660')">0:11:00</a> to go  
<a onclick="modifyYTiframeseektime('661')">0:11:01</a> on the member especially they write the  
<a onclick="modifyYTiframeseektime('663')">0:11:03</a> ayah yeah and remember when they  
<a onclick="modifyYTiframeseektime('665')">0:11:05</a> often when the imam sits behind him you  
<a onclick="modifyYTiframeseektime('666')">0:11:06</a> see on the top  
<a onclick="modifyYTiframeseektime('669')">0:11:09</a> and then you ask what they say oh it's  
<a onclick="modifyYTiframeseektime('670')">0:11:10</a> the verse of purification  
<a onclick="modifyYTiframeseektime('685')">0:11:25</a> how would you translate this well first  
<a onclick="modifyYTiframeseektime('687')">0:11:27</a> and foremost  
<a onclick="modifyYTiframeseektime('688')">0:11:28</a> as people probably can hear i'm not a  
<a onclick="modifyYTiframeseektime('690')">0:11:30</a> native speaker i'm not a native speaker  
<a onclick="modifyYTiframeseektime('692')">0:11:32</a> i do speak english since childhood but  
<a onclick="modifyYTiframeseektime('694')">0:11:34</a> it's not my mother tongue so i will try  
<a onclick="modifyYTiframeseektime('695')">0:11:35</a> my utmost to translate if you say verily  
<a onclick="modifyYTiframeseektime('697')">0:11:37</a> in them like certainly allah  
<a onclick="modifyYTiframeseektime('715')">0:11:55</a> from you  
<a onclick="modifyYTiframeseektime('719')">0:11:59</a> a little bit allah wants to  
<a onclick="modifyYTiframeseektime('723')">0:12:03</a> wants to remove the risk from you a  
<a onclick="modifyYTiframeseektime('726')">0:12:06</a> little bit  
<a onclick="modifyYTiframeseektime('726')">0:12:06</a> so this brother what's this got to do  
<a onclick="modifyYTiframeseektime('729')">0:12:09</a> with the imam again  
<a onclick="modifyYTiframeseektime('730')">0:12:10</a> well they use this as one of the  
<a onclick="modifyYTiframeseektime('733')">0:12:13</a> yeah one of the if not the yeah but  
<a onclick="modifyYTiframeseektime('736')">0:12:16</a> could be among them some of them  
<a onclick="modifyYTiframeseektime('738')">0:12:18</a> there's ayahuaya but it's definitely one  
<a onclick="modifyYTiframeseektime('740')">0:12:20</a> of the most strongest evidences  
<a onclick="modifyYTiframeseektime('742')">0:12:22</a> they use against the rest of the muslims  
<a onclick="modifyYTiframeseektime('744')">0:12:24</a> to say no we are on the truth  
<a onclick="modifyYTiframeseektime('746')">0:12:26</a> okay so our belief is right where does  
<a onclick="modifyYTiframeseektime('747')">0:12:27</a> it say anywhere in that verse that  
<a onclick="modifyYTiframeseektime('748')">0:12:28</a> you've got to follow 12 imams that are  
<a onclick="modifyYTiframeseektime('750')">0:12:30</a> infallible and that know that knowledge  
<a onclick="modifyYTiframeseektime('752')">0:12:32</a> yeah well that's the thing that's the  
<a onclick="modifyYTiframeseektime('753')">0:12:33</a> thing that's where the  
<a onclick="modifyYTiframeseektime('755')">0:12:35</a> this is where orthodoxy comes  
<a onclick="modifyYTiframeseektime('756')">0:12:36</a> orthodoxycoms  
<a onclick="modifyYTiframeseektime('758')">0:12:38</a> in the last hundred and thousand years  
<a onclick="modifyYTiframeseektime('761')">0:12:41</a> has  
<a onclick="modifyYTiframeseektime('762')">0:12:42</a> nothing to do with new movements it is  
<a onclick="modifyYTiframeseektime('765')">0:12:45</a> sunni islam in general which rejects  
<a onclick="modifyYTiframeseektime('767')">0:12:47</a> imam rejects belief in twelve infallible  
<a onclick="modifyYTiframeseektime('769')">0:12:49</a> imams does not reject these 12  
<a onclick="modifyYTiframeseektime('771')">0:12:51</a> personalities by the way yeah  
<a onclick="modifyYTiframeseektime('773')">0:12:53</a> it's very important for me especially so  
<a onclick="modifyYTiframeseektime('775')">0:12:55</a> they were historical most of them are  
<a onclick="modifyYTiframeseektime('776')">0:12:56</a> historical figures  
<a onclick="modifyYTiframeseektime('777')">0:12:57</a> they were historical figures they were  
<a onclick="modifyYTiframeseektime('779')">0:12:59</a> scholars they were praised they were  
<a onclick="modifyYTiframeseektime('781')">0:13:01</a> they were praised by the biggest  
<a onclick="modifyYTiframeseektime('782')">0:13:02</a> scholars of islam imam zahabi in  
<a onclick="modifyYTiframeseektime('784')">0:13:04</a> um  
<a onclick="modifyYTiframeseektime('791')">0:13:11</a> the only thing we disagree with is  
<a onclick="modifyYTiframeseektime('795')">0:13:15</a> in the same way we disagree with the  
<a onclick="modifyYTiframeseektime('798')">0:13:18</a> person  
<a onclick="modifyYTiframeseektime('799')">0:13:19</a> with the virgin of jesus in trinity ism  
<a onclick="modifyYTiframeseektime('803')">0:13:23</a> in the  
<a onclick="modifyYTiframeseektime('803')">0:13:23</a> in the in the pollism form paulism form  
<a onclick="modifyYTiframeseektime('806')">0:13:26</a> of christianity we don't accept it  
<a onclick="modifyYTiframeseektime('808')">0:13:28</a> we don't accept it to be the true  
<a onclick="modifyYTiframeseektime('809')">0:13:29</a> religion of jesus we don't  
<a onclick="modifyYTiframeseektime('811')">0:13:31</a> accept christianity any form of  
<a onclick="modifyYTiframeseektime('813')">0:13:33</a> christianity to be a reflection of jesus  
<a onclick="modifyYTiframeseektime('815')">0:13:35</a> believe say we don't accept that  
<a onclick="modifyYTiframeseektime('817')">0:13:37</a> twelve-ism or any other ism  
<a onclick="modifyYTiframeseektime('819')">0:13:39</a> shi-ism is a form of reflection of the  
<a onclick="modifyYTiframeseektime('822')">0:13:42</a> beliefs  
<a onclick="modifyYTiframeseektime('822')">0:13:42</a> of this person what about the sunnah  
<a onclick="modifyYTiframeseektime('824')">0:13:44</a> because there's there are the hadith  
<a onclick="modifyYTiframeseektime('825')">0:13:45</a> that says that the prophet says  
<a onclick="modifyYTiframeseektime('827')">0:13:47</a> after me will be 12 khalifs for example  
<a onclick="modifyYTiframeseektime('829')">0:13:49</a> yeah  
<a onclick="modifyYTiframeseektime('830')">0:13:50</a> you know now we we go from the ayah they  
<a onclick="modifyYTiframeseektime('832')">0:13:52</a> use we talked about the  
<a onclick="modifyYTiframeseektime('834')">0:13:54</a> ayat here which we don't believe is a  
<a onclick="modifyYTiframeseektime('836')">0:13:56</a> strong evidence because it doesn't even  
<a onclick="modifyYTiframeseektime('837')">0:13:57</a> it it it it mentions first of all in  
<a onclick="modifyYTiframeseektime('840')">0:14:00</a> general  
<a onclick="modifyYTiframeseektime('841')">0:14:01</a> it talks about that allah wants to  
<a onclick="modifyYTiframeseektime('844')">0:14:04</a> purify them  
<a onclick="modifyYTiframeseektime('845')">0:14:05</a> and anybody who reads the whole verse  
<a onclick="modifyYTiframeseektime('847')">0:14:07</a> and i think here we forgot to go back  
<a onclick="modifyYTiframeseektime('850')">0:14:10</a> the first is cut it's cut by them  
<a onclick="modifyYTiframeseektime('853')">0:14:13</a> cut as in when when they normally uh so  
<a onclick="modifyYTiframeseektime('855')">0:14:15</a> it starts with  
<a onclick="modifyYTiframeseektime('856')">0:14:16</a> enough so it's talking to the prophet's  
<a onclick="modifyYTiframeseektime('859')">0:14:19</a> wives it's talking about the prophet's  
<a onclick="modifyYTiframeseektime('860')">0:14:20</a> wife  
<a onclick="modifyYTiframeseektime('860')">0:14:20</a> of course and then come you know we can  
<a onclick="modifyYTiframeseektime('863')">0:14:23</a> talk discuss hours now  
<a onclick="modifyYTiframeseektime('864')">0:14:24</a> some then say why is the does it  
<a onclick="modifyYTiframeseektime('868')">0:14:28</a> it changes to the masculine form yeah  
<a onclick="modifyYTiframeseektime('871')">0:14:31</a> this is answered by anybody who has  
<a onclick="modifyYTiframeseektime('874')">0:14:34</a> little knowledge  
<a onclick="modifyYTiframeseektime('875')">0:14:35</a> that is  
<a onclick="modifyYTiframeseektime('879')">0:14:39</a> is masculine and masculine must be  
<a onclick="modifyYTiframeseektime('881')">0:14:41</a> addressed  
<a onclick="modifyYTiframeseektime('882')">0:14:42</a> in a muscular form so that's why you say  
<a onclick="modifyYTiframeseektime('884')">0:14:44</a> assalamu alaikum  
<a onclick="modifyYTiframeseektime('886')">0:14:46</a> even if there are um four wives and one  
<a onclick="modifyYTiframeseektime('889')">0:14:49</a> husband  
<a onclick="modifyYTiframeseektime('890')">0:14:50</a> why do you say alaikum you you and arab  
<a onclick="modifyYTiframeseektime('892')">0:14:52</a> you're native arab  
<a onclick="modifyYTiframeseektime('893')">0:14:53</a> and when i ask you why do i say assalamu  
<a onclick="modifyYTiframeseektime('895')">0:14:55</a> when i see somebody for example with his  
<a onclick="modifyYTiframeseektime('897')">0:14:57</a> four wives  
<a onclick="modifyYTiframeseektime('898')">0:14:58</a> let's say we are in the time of the  
<a onclick="modifyYTiframeseektime('899')">0:14:59</a> prophet  
<a onclick="modifyYTiframeseektime('902')">0:15:02</a> i mean why do i say alaikum although  
<a onclick="modifyYTiframeseektime('904')">0:15:04</a> they are for women  
<a onclick="modifyYTiframeseektime('906')">0:15:06</a> because obviously because in arabic this  
<a onclick="modifyYTiframeseektime('908')">0:15:08</a> is god that this is these are rules in  
<a onclick="modifyYTiframeseektime('910')">0:15:10</a> arabic language  
<a onclick="modifyYTiframeseektime('911')">0:15:11</a> obvious that one male person is enough  
<a onclick="modifyYTiframeseektime('914')">0:15:14</a> in the group to make it  
<a onclick="modifyYTiframeseektime('916')">0:15:16</a> to make it masculine so this is about uh  
<a onclick="modifyYTiframeseektime('919')">0:15:19</a> the verse and there's other  
<a onclick="modifyYTiframeseektime('920')">0:15:20</a> verses they use of course then you ask  
<a onclick="modifyYTiframeseektime('922')">0:15:22</a> about the sunnah the is  
<a onclick="modifyYTiframeseektime('924')">0:15:24</a> and he how you said in english the way  
<a onclick="modifyYTiframeseektime('927')">0:15:27</a> they yeah  
<a onclick="modifyYTiframeseektime('927')">0:15:27</a> they're trying to drive evidences from  
<a onclick="modifyYTiframeseektime('929')">0:15:29</a> the church exactly the way they do this  
<a onclick="modifyYTiframeseektime('932')">0:15:32</a> just i always say as an actual person  
<a onclick="modifyYTiframeseektime('936')">0:15:36</a> yeah just like the hoj  
<a onclick="modifyYTiframeseektime('955')">0:15:55</a> okay so what about this it says twelve  
<a onclick="modifyYTiframeseektime('957')">0:15:57</a> uh leaders after the uh you know the  
<a onclick="modifyYTiframeseektime('959')">0:15:59</a> bring me you  
<a onclick="modifyYTiframeseektime('960')">0:16:00</a> you as a sunday you have some experience  
<a onclick="modifyYTiframeseektime('961')">0:16:01</a> bring me the strongest  
<a onclick="modifyYTiframeseektime('963')">0:16:03</a> evidence that you know that you know of  
<a onclick="modifyYTiframeseektime('966')">0:16:06</a> from the sunnah bring me this  
<a onclick="modifyYTiframeseektime('967')">0:16:07</a> this is the one they would say this is  
<a onclick="modifyYTiframeseektime('969')">0:16:09</a> there's 12 uh there are 12 leaders  
<a onclick="modifyYTiframeseektime('971')">0:16:11</a> the prophet said this is a sahih hadith  
<a onclick="modifyYTiframeseektime('972')">0:16:12</a> found in many different books of hadith  
<a onclick="modifyYTiframeseektime('974')">0:16:14</a> yeah as far as i know it's in in is in  
<a onclick="modifyYTiframeseektime('976')">0:16:16</a> the sahaya muslim or  
<a onclick="modifyYTiframeseektime('978')">0:16:18</a> definitely one of the book nobody  
<a onclick="modifyYTiframeseektime('980')">0:16:20</a> rejects the hadith  
<a onclick="modifyYTiframeseektime('981')">0:16:21</a> nobody hides the hadith but the thing is  
<a onclick="modifyYTiframeseektime('984')">0:16:24</a> um  
<a onclick="modifyYTiframeseektime('984')">0:16:24</a> i believe that if somebody wants the  
<a onclick="modifyYTiframeseektime('987')">0:16:27</a> truth and does proper research  
<a onclick="modifyYTiframeseektime('990')">0:16:30</a> and this is unfortunately my experience  
<a onclick="modifyYTiframeseektime('992')">0:16:32</a> even myself when i used to be shiri  
<a onclick="modifyYTiframeseektime('994')">0:16:34</a> most of the time i spent was  
<a onclick="modifyYTiframeseektime('997')">0:16:37</a> um and this is what the scholars of  
<a onclick="modifyYTiframeseektime('999')">0:16:39</a> islam said they say the people of the  
<a onclick="modifyYTiframeseektime('1001')">0:16:41</a> truth the people of the sunnah  
<a onclick="modifyYTiframeseektime('1003')">0:16:43</a> they um they they they they see the  
<a onclick="modifyYTiframeseektime('1006')">0:16:46</a> kitab in the sunnah they see the book  
<a onclick="modifyYTiframeseektime('1008')">0:16:48</a> of allah they see the waters the mass  
<a onclick="modifyYTiframeseektime('1010')">0:16:50</a> narrated sunnah clear-cut the beliefs  
<a onclick="modifyYTiframeseektime('1012')">0:16:52</a> are in front of them  
<a onclick="modifyYTiframeseektime('1014')">0:16:54</a> and then believe in it yeah the people  
<a onclick="modifyYTiframeseektime('1016')">0:16:56</a> of falsehood  
<a onclick="modifyYTiframeseektime('1018')">0:16:58</a> they make up beliefs and then they look  
<a onclick="modifyYTiframeseektime('1020')">0:17:00</a> for  
<a onclick="modifyYTiframeseektime('1021')">0:17:01</a> the evidence superimposing their own  
<a onclick="modifyYTiframeseektime('1022')">0:17:02</a> exactly then they look forward to  
<a onclick="modifyYTiframeseektime('1024')">0:17:04</a> somehow construct  
<a onclick="modifyYTiframeseektime('1025')">0:17:05</a> the evidence so those two those two that  
<a onclick="modifyYTiframeseektime('1028')">0:17:08</a> are mentioned by the prophet  
<a onclick="modifyYTiframeseektime('1030')">0:17:10</a> uh so are they the twelve infallible  
<a onclick="modifyYTiframeseektime('1033')">0:17:13</a> imams that we must follow and does it  
<a onclick="modifyYTiframeseektime('1034')">0:17:14</a> say that in hadith  
<a onclick="modifyYTiframeseektime('1035')">0:17:15</a> you already gave the answer the prophet  
<a onclick="modifyYTiframeseektime('1036')">0:17:16</a> salallahu said 12  
<a onclick="modifyYTiframeseektime('1040')">0:17:20</a> yeah or in other narrations versions um  
<a onclick="modifyYTiframeseektime('1042')">0:17:22</a> yeah  
<a onclick="modifyYTiframeseektime('1043')">0:17:23</a> um is the plural of amir  
<a onclick="modifyYTiframeseektime('1046')">0:17:26</a> so the prophet sallallahu islam is  
<a onclick="modifyYTiframeseektime('1048')">0:17:28</a> speaking here about people who actually  
<a onclick="modifyYTiframeseektime('1050')">0:17:30</a> rule  
<a onclick="modifyYTiframeseektime('1051')">0:17:31</a> and you see this is the problem with  
<a onclick="modifyYTiframeseektime('1053')">0:17:33</a> people who are attached to these number  
<a onclick="modifyYTiframeseektime('1056')">0:17:36</a> games  
<a onclick="modifyYTiframeseektime('1056')">0:17:36</a> yeah when people why is it 12  
<a onclick="modifyYTiframeseektime('1059')">0:17:39</a> what it doesn't matter if it's 12 or 14  
<a onclick="modifyYTiframeseektime('1061')">0:17:41</a> or 16 the prophet saws  
<a onclick="modifyYTiframeseektime('1062')">0:17:42</a> i'm speaking about we won't do now  
<a onclick="modifyYTiframeseektime('1066')">0:17:46</a> a full explanation of the hadees but the  
<a onclick="modifyYTiframeseektime('1068')">0:17:48</a> prophet says the islam will be as he is  
<a onclick="modifyYTiframeseektime('1070')">0:17:50</a> and he will be powerful respected and so  
<a onclick="modifyYTiframeseektime('1072')">0:17:52</a> on as long as these twelve rule  
<a onclick="modifyYTiframeseektime('1075')">0:17:55</a> none of them have ruled none of them  
<a onclick="modifyYTiframeseektime('1078')">0:17:58</a> have ruled  
<a onclick="modifyYTiframeseektime('1079')">0:17:59</a> and and that's one more thing the  
<a onclick="modifyYTiframeseektime('1081')">0:18:01</a> problem is really with this word  
<a onclick="modifyYTiframeseektime('1082')">0:18:02</a> with these number games you know do you  
<a onclick="modifyYTiframeseektime('1084')">0:18:04</a> how many disciples had jesus had  
<a onclick="modifyYTiframeseektime('1086')">0:18:06</a> 12 12. and one of them became what  
<a onclick="modifyYTiframeseektime('1090')">0:18:10</a> was he a good one one of them became  
<a onclick="modifyYTiframeseektime('1091')">0:18:11</a> really really bad yeah really bad  
<a onclick="modifyYTiframeseektime('1093')">0:18:13</a> so you see we can if we want to play  
<a onclick="modifyYTiframeseektime('1096')">0:18:16</a> this these kind of games because the  
<a onclick="modifyYTiframeseektime('1097')">0:18:17</a> 12 is mentioned there well jesus had 12  
<a onclick="modifyYTiframeseektime('1100')">0:18:20</a> disciples one of them was a  
<a onclick="modifyYTiframeseektime('1101')">0:18:21</a> big-time munafer if you like so about  
<a onclick="modifyYTiframeseektime('1104')">0:18:24</a> what about moses he had 12  
<a onclick="modifyYTiframeseektime('1106')">0:18:26</a> tribes and anyway this belief of 12  
<a onclick="modifyYTiframeseektime('1109')">0:18:29</a> yesterday i saw a from the torah that  
<a onclick="modifyYTiframeseektime('1112')">0:18:32</a> this belief of 12 is  
<a onclick="modifyYTiframeseektime('1113')">0:18:33</a> is taken from the torah and and and the  
<a onclick="modifyYTiframeseektime('1115')">0:18:35</a> prophet sallallahu alaihi sallam  
<a onclick="modifyYTiframeseektime('1117')">0:18:37</a> we have the sunnah all these praises of  
<a onclick="modifyYTiframeseektime('1121')">0:18:41</a> problem is and i said really as actually  
<a onclick="modifyYTiframeseektime('1124')">0:18:44</a> because i was  
<a onclick="modifyYTiframeseektime('1126')">0:18:46</a> i had the same problem and due to i  
<a onclick="modifyYTiframeseektime('1129')">0:18:49</a> believe this is my personal opinion due  
<a onclick="modifyYTiframeseektime('1131')">0:18:51</a> to bias  
<a onclick="modifyYTiframeseektime('1132')">0:18:52</a> due to growing up in that environment  
<a onclick="modifyYTiframeseektime('1134')">0:18:54</a> due to  
<a onclick="modifyYTiframeseektime('1136')">0:18:56</a> i believe shiaism is really much by  
<a onclick="modifyYTiframeseektime('1139')">0:18:59</a> default sectarian because uh look  
<a onclick="modifyYTiframeseektime('1143')">0:19:03</a> i remember when i used to be shiri the  
<a onclick="modifyYTiframeseektime('1145')">0:19:05</a> dawah is uh  
<a onclick="modifyYTiframeseektime('1146')">0:19:06</a> the dawah they do for example is  
<a onclick="modifyYTiframeseektime('1148')">0:19:08</a> addressed to who  
<a onclick="modifyYTiframeseektime('1150')">0:19:10</a> sunnis they go after mostly  
<a onclick="modifyYTiframeseektime('1153')">0:19:13</a> especially innocent sunnis  
<a onclick="modifyYTiframeseektime('1157')">0:19:17</a> uh gullible sunnis who don't have much  
<a onclick="modifyYTiframeseektime('1159')">0:19:19</a> knowledge  
<a onclick="modifyYTiframeseektime('1160')">0:19:20</a> whereas whereas the muslims the majority  
<a onclick="modifyYTiframeseektime('1162')">0:19:22</a> of the muslims our da'wah is addressed  
<a onclick="modifyYTiframeseektime('1164')">0:19:24</a> today  
<a onclick="modifyYTiframeseektime('1165')">0:19:25</a> to everybody and especially to  
<a onclick="modifyYTiframeseektime('1166')">0:19:26</a> non-muslims mainstream muslims exactly  
<a onclick="modifyYTiframeseektime('1169')">0:19:29</a> so because this this mentality that she  
<a onclick="modifyYTiframeseektime('1171')">0:19:31</a> has from  
<a onclick="modifyYTiframeseektime('1172')">0:19:32</a> early childhood and especially when he's  
<a onclick="modifyYTiframeseektime('1174')">0:19:34</a> religious from his religious family  
<a onclick="modifyYTiframeseektime('1176')">0:19:36</a> they're looking looking looking for any  
<a onclick="modifyYTiframeseektime('1178')">0:19:38</a> evidence where they can construct  
<a onclick="modifyYTiframeseektime('1180')">0:19:40</a> their beliefs were you part of that as  
<a onclick="modifyYTiframeseektime('1181')">0:19:41</a> well did you fall into that when you  
<a onclick="modifyYTiframeseektime('1182')">0:19:42</a> were you were ashamed  
<a onclick="modifyYTiframeseektime('1183')">0:19:43</a> i i can't believe that any shia it does  
<a onclick="modifyYTiframeseektime('1186')">0:19:46</a> not fall into it i believe that the vast  
<a onclick="modifyYTiframeseektime('1187')">0:19:47</a> majority of shias who are religious  
<a onclick="modifyYTiframeseektime('1189')">0:19:49</a> we're talking about religious yes  
<a onclick="modifyYTiframeseektime('1190')">0:19:50</a> they fall into this looking copy pasting  
<a onclick="modifyYTiframeseektime('1193')">0:19:53</a> and discussing  
<a onclick="modifyYTiframeseektime('1194')">0:19:54</a> looking to somehow you know to fill that  
<a onclick="modifyYTiframeseektime('1196')">0:19:56</a> allow that narrative to  
<a onclick="modifyYTiframeseektime('1198')">0:19:58</a> yes so it's i call it desperation can i  
<a onclick="modifyYTiframeseektime('1201')">0:20:01</a> ask you  
<a onclick="modifyYTiframeseektime('1202')">0:20:02</a> now in regards to the this is another  
<a onclick="modifyYTiframeseektime('1203')">0:20:03</a> issue of the sahaba and the ahma bayt  
<a onclick="modifyYTiframeseektime('1206')">0:20:06</a> and the relationship between the two  
<a onclick="modifyYTiframeseektime('1207')">0:20:07</a> because one  
<a onclick="modifyYTiframeseektime('1209')">0:20:09</a> very key tenant for shia people is that  
<a onclick="modifyYTiframeseektime('1211')">0:20:11</a> they say look the prophet muhammad said  
<a onclick="modifyYTiframeseektime('1214')">0:20:14</a> in the in the salah and many hadees and  
<a onclick="modifyYTiframeseektime('1217')">0:20:17</a> we have it as mortal  
<a onclick="modifyYTiframeseektime('1218')">0:20:18</a> we have it as at least very strong  
<a onclick="modifyYTiframeseektime('1220')">0:20:20</a> authentic in our books  
<a onclick="modifyYTiframeseektime('1229')">0:20:29</a> so so the prophet said that you know  
<a onclick="modifyYTiframeseektime('1231')">0:20:31</a> i've left with you  
<a onclick="modifyYTiframeseektime('1233')">0:20:33</a> two things  
<a onclick="modifyYTiframeseektime('1239')">0:20:39</a> so the point is all of these different  
<a onclick="modifyYTiframeseektime('1241')">0:20:41</a> constructions or these different uh  
<a onclick="modifyYTiframeseektime('1243')">0:20:43</a> phraseologies of the prophet muhammad  
<a onclick="modifyYTiframeseektime('1245')">0:20:45</a> were telling us that there's gonna have  
<a onclick="modifyYTiframeseektime('1246')">0:20:46</a> something that's going to  
<a onclick="modifyYTiframeseektime('1247')">0:20:47</a> you leave he's left behind two things  
<a onclick="modifyYTiframeseektime('1249')">0:20:49</a> which is the kitab allah  
<a onclick="modifyYTiframeseektime('1251')">0:20:51</a> and the bait meaning the prophet's  
<a onclick="modifyYTiframeseektime('1252')">0:20:52</a> family yeah so  
<a onclick="modifyYTiframeseektime('1254')">0:20:54</a> this for the shia is clear evidences  
<a onclick="modifyYTiframeseektime('1257')">0:20:57</a> yeah  
<a onclick="modifyYTiframeseektime('1257')">0:20:57</a> that you should be following bait and  
<a onclick="modifyYTiframeseektime('1260')">0:21:00</a> you should not be following the sahaba  
<a onclick="modifyYTiframeseektime('1263')">0:21:03</a> um i say who said that the sun is done  
<a onclick="modifyYTiframeseektime('1265')">0:21:05</a> for bait  
<a onclick="modifyYTiframeseektime('1267')">0:21:07</a> you know this is who said sunnis we  
<a onclick="modifyYTiframeseektime('1270')">0:21:10</a> believe that abdullah bin abbas is a  
<a onclick="modifyYTiframeseektime('1272')">0:21:12</a> little bit  
<a onclick="modifyYTiframeseektime('1272')">0:21:12</a> and who is abdallah abbas and what do we  
<a onclick="modifyYTiframeseektime('1274')">0:21:14</a> call it uh  
<a onclick="modifyYTiframeseektime('1275')">0:21:15</a> in arabic how do you translate into in  
<a onclick="modifyYTiframeseektime('1279')">0:21:19</a> english is you know is someone like uh  
<a onclick="modifyYTiframeseektime('1282')">0:21:22</a> you can say  
<a onclick="modifyYTiframeseektime('1282')">0:21:22</a> the scholar one of the scholars  
<a onclick="modifyYTiframeseektime('1286')">0:21:26</a> we say he's the translator in the quran  
<a onclick="modifyYTiframeseektime('1288')">0:21:28</a> yeah  
<a onclick="modifyYTiframeseektime('1331')">0:22:11</a> sorry constrained there or a certain  
<a onclick="modifyYTiframeseektime('1333')">0:22:13</a> number confine it yeah that's the word  
<a onclick="modifyYTiframeseektime('1335')">0:22:15</a> okay first of all just to complete what  
<a onclick="modifyYTiframeseektime('1336')">0:22:16</a> i wanted to say is that um  
<a onclick="modifyYTiframeseektime('1338')">0:22:18</a> first of all we this is the you see this  
<a onclick="modifyYTiframeseektime('1341')">0:22:21</a> is where the first misconception really  
<a onclick="modifyYTiframeseektime('1342')">0:22:22</a> starts yeah  
<a onclick="modifyYTiframeseektime('1343')">0:22:23</a> like that's why in arabic they always  
<a onclick="modifyYTiframeseektime('1345')">0:22:25</a> say the scholars in arabic they call us  
<a onclick="modifyYTiframeseektime('1347')">0:22:27</a> they call them they're called muslims  
<a onclick="modifyYTiframeseektime('1350')">0:22:30</a> which means  
<a onclick="modifyYTiframeseektime('1351')">0:22:31</a> the communists or they call them sahaba  
<a onclick="modifyYTiframeseektime('1355')">0:22:35</a> the school of the sahaba or  
<a onclick="modifyYTiframeseektime('1359')">0:22:39</a> this itself is wrong every student  
<a onclick="modifyYTiframeseektime('1361')">0:22:41</a> should get offended  
<a onclick="modifyYTiframeseektime('1362')">0:22:42</a> no sunnis believe they follow the  
<a onclick="modifyYTiframeseektime('1364')">0:22:44</a> prophet sallam the only  
<a onclick="modifyYTiframeseektime('1366')">0:22:46</a> and real masoom okay the only real  
<a onclick="modifyYTiframeseektime('1368')">0:22:48</a> infallible  
<a onclick="modifyYTiframeseektime('1369')">0:22:49</a> and his companions and his family yeah  
<a onclick="modifyYTiframeseektime('1372')">0:22:52</a> despite whatever it's  
<a onclick="modifyYTiframeseektime('1373')">0:22:53</a> happening they had one akida one  
<a onclick="modifyYTiframeseektime('1376')">0:22:56</a> one creed one akida and uh  
<a onclick="modifyYTiframeseektime('1380')">0:23:00</a> among them albeit and sunnis have taken  
<a onclick="modifyYTiframeseektime('1382')">0:23:02</a> from abdullah bin abbas is one of the  
<a onclick="modifyYTiframeseektime('1383')">0:23:03</a> main  
<a onclick="modifyYTiframeseektime('1384')">0:23:04</a> he's a hashimi one of the main  
<a onclick="modifyYTiframeseektime('1386')">0:23:06</a> fascinating among  
<a onclick="modifyYTiframeseektime('1388')">0:23:08</a> another thing just to mention quickly a  
<a onclick="modifyYTiframeseektime('1390')">0:23:10</a> very good friend of mine  
<a onclick="modifyYTiframeseektime('1392')">0:23:12</a> also a researcher he and i translated an  
<a onclick="modifyYTiframeseektime('1396')">0:23:16</a> article for him  
<a onclick="modifyYTiframeseektime('1397')">0:23:17</a> from arabic which is a this pro  
<a onclick="modifyYTiframeseektime('1400')">0:23:20</a> this is a huge task whoever the the  
<a onclick="modifyYTiframeseektime('1403')">0:23:23</a> sheikh who  
<a onclick="modifyYTiframeseektime('1404')">0:23:24</a> to translate who who did the research it  
<a onclick="modifyYTiframeseektime('1407')">0:23:27</a> was about  
<a onclick="modifyYTiframeseektime('1407')">0:23:27</a> who narrated more from the albeit sunni  
<a onclick="modifyYTiframeseektime('1411')">0:23:31</a> authentic with proper chains of  
<a onclick="modifyYTiframeseektime('1412')">0:23:32</a> narrations okay i found this article in  
<a onclick="modifyYTiframeseektime('1414')">0:23:34</a> arabic i said i need to translate this i  
<a onclick="modifyYTiframeseektime('1416')">0:23:36</a> translated it and gave it to a number of  
<a onclick="modifyYTiframeseektime('1418')">0:23:38</a> websites  
<a onclick="modifyYTiframeseektime('1419')">0:23:39</a> the result was that ali abi talib did  
<a onclick="modifyYTiframeseektime('1422')">0:23:42</a> you know and i know that most sunnis  
<a onclick="modifyYTiframeseektime('1424')">0:23:44</a> don't even know that  
<a onclick="modifyYTiframeseektime('1424')">0:23:44</a> alibaba talib narrated musa hadith  
<a onclick="modifyYTiframeseektime('1428')">0:23:48</a> authentic hadith in our books  
<a onclick="modifyYTiframeseektime('1431')">0:23:51</a> then abu bakr and  
<a onclick="modifyYTiframeseektime('1435')">0:23:55</a> omar and uthman together that's because  
<a onclick="modifyYTiframeseektime('1438')">0:23:58</a> of his age isn't it  
<a onclick="modifyYTiframeseektime('1439')">0:23:59</a> not just because of his age this is well  
<a onclick="modifyYTiframeseektime('1442')">0:24:02</a> it's  
<a onclick="modifyYTiframeseektime('1443')">0:24:03</a> but it's not just just because of that  
<a onclick="modifyYTiframeseektime('1444')">0:24:04</a> it is also because um  
<a onclick="modifyYTiframeseektime('1447')">0:24:07</a> abu bakr for example if you read what  
<a onclick="modifyYTiframeseektime('1449')">0:24:09</a> the scholars wrote about him  
<a onclick="modifyYTiframeseektime('1451')">0:24:11</a> was more known and ali as well but even  
<a onclick="modifyYTiframeseektime('1453')">0:24:13</a> more so what's known as the fakie and so  
<a onclick="modifyYTiframeseektime('1455')">0:24:15</a> was um  
<a onclick="modifyYTiframeseektime('1456')">0:24:16</a> they were not known as muhaddis they're  
<a onclick="modifyYTiframeseektime('1458')">0:24:18</a> writing too much okay  
<a onclick="modifyYTiframeseektime('1459')">0:24:19</a> another thing in the muslim ahmed only  
<a onclick="modifyYTiframeseektime('1461')">0:24:21</a> one khalif  
<a onclick="modifyYTiframeseektime('1462')">0:24:22</a> narrates more than ali  
<a onclick="modifyYTiframeseektime('1466')">0:24:26</a> abu bakr and uthman ali narrates more  
<a onclick="modifyYTiframeseektime('1469')">0:24:29</a> than awakening  
<a onclick="modifyYTiframeseektime('1470')">0:24:30</a> so is there any contradiction at all in  
<a onclick="modifyYTiframeseektime('1473')">0:24:33</a> accepting  
<a onclick="modifyYTiframeseektime('1474')">0:24:34</a> uh you know amar for example or off men  
<a onclick="modifyYTiframeseektime('1478')">0:24:38</a> or whatever et cetera or these  
<a onclick="modifyYTiframeseektime('1479')">0:24:39</a> what we couldn't consider companions and  
<a onclick="modifyYTiframeseektime('1483')">0:24:43</a> other companions like that shares  
<a onclick="modifyYTiframeseektime('1485')">0:24:45</a> obviously not don't accept  
<a onclick="modifyYTiframeseektime('1487')">0:24:47</a> and also at the same time accepting the  
<a onclick="modifyYTiframeseektime('1488')">0:24:48</a> base of the family of the prophet  
<a onclick="modifyYTiframeseektime('1490')">0:24:50</a> no of course as as mainstream muslims  
<a onclick="modifyYTiframeseektime('1494')">0:24:54</a> of course we believe there's no  
<a onclick="modifyYTiframeseektime('1495')">0:24:55</a> contradiction  
<a onclick="modifyYTiframeseektime('1497')">0:24:57</a> of course at the same time we do not  
<a onclick="modifyYTiframeseektime('1499')">0:24:59</a> believe  
<a onclick="modifyYTiframeseektime('1500')">0:25:00</a> as some people claim like the likes of  
<a onclick="modifyYTiframeseektime('1502')">0:25:02</a> nakshawani who say the sunnis do not  
<a onclick="modifyYTiframeseektime('1504')">0:25:04</a> discuss these things and they are not  
<a onclick="modifyYTiframeseektime('1506')">0:25:06</a> prepared to debate these things  
<a onclick="modifyYTiframeseektime('1508')">0:25:08</a> we just we have written our scholars  
<a onclick="modifyYTiframeseektime('1510')">0:25:10</a> before  
<a onclick="modifyYTiframeseektime('1511')">0:25:11</a> me and you were born and our  
<a onclick="modifyYTiframeseektime('1512')">0:25:12</a> grandparents were born have written  
<a onclick="modifyYTiframeseektime('1513')">0:25:13</a> about these things  
<a onclick="modifyYTiframeseektime('1515')">0:25:15</a> have written about fitter and that  
<a onclick="modifyYTiframeseektime('1516')">0:25:16</a> happened after the prophet sallallahu  
<a onclick="modifyYTiframeseektime('1518')">0:25:18</a> alaihi  
<a onclick="modifyYTiframeseektime('1518')">0:25:18</a> wasallam problems that was between one  
<a onclick="modifyYTiframeseektime('1520')">0:25:20</a> sahabi and another sahabi one sahabi and  
<a onclick="modifyYTiframeseektime('1522')">0:25:22</a> the sabbath  
<a onclick="modifyYTiframeseektime('1523')">0:25:23</a> nobody denies these things but what we  
<a onclick="modifyYTiframeseektime('1525')">0:25:25</a> believe firmly is that the sahaba and  
<a onclick="modifyYTiframeseektime('1528')">0:25:28</a> the sahaba would we say sahabah includes  
<a onclick="modifyYTiframeseektime('1535')">0:25:35</a> all these great personalities they had  
<a onclick="modifyYTiframeseektime('1537')">0:25:37</a> one creed one belief one belief system  
<a onclick="modifyYTiframeseektime('1540')">0:25:40</a> and they were especially the albeit  
<a onclick="modifyYTiframeseektime('1545')">0:25:45</a> did not share any of the beliefs of the  
<a onclick="modifyYTiframeseektime('1547')">0:25:47</a> twelvers okay any  
<a onclick="modifyYTiframeseektime('1549')">0:25:49</a> this is what we firmly believe then of  
<a onclick="modifyYTiframeseektime('1551')">0:25:51</a> course this opens then  
<a onclick="modifyYTiframeseektime('1553')">0:25:53</a> a number of other doors for discussions  
<a onclick="modifyYTiframeseektime('1555')">0:25:55</a> and for debates  
<a onclick="modifyYTiframeseektime('1557')">0:25:57</a> and to discuss this further but this is  
<a onclick="modifyYTiframeseektime('1558')">0:25:58</a> our firm belief we do not  
<a onclick="modifyYTiframeseektime('1560')">0:26:00</a> i remember when i used to be she they  
<a onclick="modifyYTiframeseektime('1562')">0:26:02</a> used to say yes sunnis do believe  
<a onclick="modifyYTiframeseektime('1564')">0:26:04</a> love albeit but that's not enough  
<a onclick="modifyYTiframeseektime('1567')">0:26:07</a> this is how i used to make dawah to  
<a onclick="modifyYTiframeseektime('1569')">0:26:09</a> innocent sunnis to ignorance among them  
<a onclick="modifyYTiframeseektime('1571')">0:26:11</a> said to them innocent sunni for example  
<a onclick="modifyYTiframeseektime('1573')">0:26:13</a> came to me and say i do love  
<a onclick="modifyYTiframeseektime('1575')">0:26:15</a> it what do you want from me i love i  
<a onclick="modifyYTiframeseektime('1577')">0:26:17</a> love ali i love hassan i love her  
<a onclick="modifyYTiframeseektime('1579')">0:26:19</a> yeah but you love the enemies of albert  
<a onclick="modifyYTiframeseektime('1580')">0:26:20</a> as well you see  
<a onclick="modifyYTiframeseektime('1582')">0:26:22</a> that's the catchy thing that's what they  
<a onclick="modifyYTiframeseektime('1583')">0:26:23</a> call who are the enemies of alibaba you  
<a onclick="modifyYTiframeseektime('1585')">0:26:25</a> think abu lahab  
<a onclick="modifyYTiframeseektime('1587')">0:26:27</a> and then it believes of course it's the  
<a onclick="modifyYTiframeseektime('1589')">0:26:29</a> closest friends of the prophet  
<a onclick="modifyYTiframeseektime('1590')">0:26:30</a> sallallahu islam  
<a onclick="modifyYTiframeseektime('1592')">0:26:32</a> it's his wives and so on so forth now  
<a onclick="modifyYTiframeseektime('1594')">0:26:34</a> that needs to be dismantled let's be  
<a onclick="modifyYTiframeseektime('1595')">0:26:35</a> disproves  
<a onclick="modifyYTiframeseektime('1596')">0:26:36</a> it can and it has been topic really it's  
<a onclick="modifyYTiframeseektime('1598')">0:26:38</a> a whole different topic we have  
<a onclick="modifyYTiframeseektime('1600')">0:26:40</a> we have friends and references which  
<a onclick="modifyYTiframeseektime('1601')">0:26:41</a> we're going to put in the description  
<a onclick="modifyYTiframeseektime('1602')">0:26:42</a> box  
<a onclick="modifyYTiframeseektime('1603')">0:26:43</a> friends of mine colleagues of mine we  
<a onclick="modifyYTiframeseektime('1605')">0:26:45</a> have we we run websites  
<a onclick="modifyYTiframeseektime('1607')">0:26:47</a> literally every sub hub every  
<a onclick="modifyYTiframeseektime('1609')">0:26:49</a> transaction  
<a onclick="modifyYTiframeseektime('1610')">0:26:50</a> doubts that they may raise or have  
<a onclick="modifyYTiframeseektime('1612')">0:26:52</a> raised and do raise constantly  
<a onclick="modifyYTiframeseektime('1617')">0:26:57</a> they're not unknown to us there's  
<a onclick="modifyYTiframeseektime('1619')">0:26:59</a> answers to this you know especially with  
<a onclick="modifyYTiframeseektime('1621')">0:27:01</a> iranians who say or claim their actions  
<a onclick="modifyYTiframeseektime('1625')">0:27:05</a> i often heard this in my life they say  
<a onclick="modifyYTiframeseektime('1626')">0:27:06</a> oh yo you know these iranians most of  
<a onclick="modifyYTiframeseektime('1628')">0:27:08</a> them in the west they were never really  
<a onclick="modifyYTiframeseektime('1629')">0:27:09</a> shared in the real  
<a onclick="modifyYTiframeseektime('1631')">0:27:11</a> in the first place you were not real  
<a onclick="modifyYTiframeseektime('1633')">0:27:13</a> shia  
<a onclick="modifyYTiframeseektime('1634')">0:27:14</a> i say nobody should say these things i  
<a onclick="modifyYTiframeseektime('1636')">0:27:16</a> don't even like when muslims hear  
<a onclick="modifyYTiframeseektime('1638')">0:27:18</a> somebody leaving islam saying he never  
<a onclick="modifyYTiframeseektime('1639')">0:27:19</a> been a real muslim  
<a onclick="modifyYTiframeseektime('1641')">0:27:21</a> in the first place why are you saying  
<a onclick="modifyYTiframeseektime('1642')">0:27:22</a> such a thing is it impossible to become  
<a onclick="modifyYTiframeseektime('1643')">0:27:23</a> a mortal  
<a onclick="modifyYTiframeseektime('1644')">0:27:24</a> is it impossible to become an apostate  
<a onclick="modifyYTiframeseektime('1647')">0:27:27</a> it's not  
<a onclick="modifyYTiframeseektime('1648')">0:27:28</a> muslims become jew you become muslim i  
<a onclick="modifyYTiframeseektime('1650')">0:27:30</a> don't know muslim becomes the atheist  
<a onclick="modifyYTiframeseektime('1651')">0:27:31</a> shia becomes  
<a onclick="modifyYTiframeseektime('1652')">0:27:32</a> there's even a video maybe somehow we  
<a onclick="modifyYTiframeseektime('1654')">0:27:34</a> included in this clip  
<a onclick="modifyYTiframeseektime('1656')">0:27:36</a> famous video of hasan asalallah in  
<a onclick="modifyYTiframeseektime('1657')">0:27:37</a> arabic unfortunately nobody has  
<a onclick="modifyYTiframeseektime('1658')">0:27:38</a> translated it  
<a onclick="modifyYTiframeseektime('1659')">0:27:39</a> where he says many people have become  
<a onclick="modifyYTiframeseektime('1661')">0:27:41</a> sunni he says it  
<a onclick="modifyYTiframeseektime('1662')">0:27:42</a> in imagine thousands of followers in  
<a onclick="modifyYTiframeseektime('1666')">0:27:46</a> front of him  
<a onclick="modifyYTiframeseektime('1666')">0:27:46</a> and millions of viewers he has he says  
<a onclick="modifyYTiframeseektime('1669')">0:27:49</a> many people have become  
<a onclick="modifyYTiframeseektime('1670')">0:27:50</a> sunni from shias from auschwitz and then  
<a onclick="modifyYTiframeseektime('1673')">0:27:53</a> he says and many sunni shias  
<a onclick="modifyYTiframeseektime('1675')">0:27:55</a> uh sorry sunnis let everybody  
<a onclick="modifyYTiframeseektime('1678')">0:27:58</a> actually i really you have to give  
<a onclick="modifyYTiframeseektime('1680')">0:28:00</a> credit where credit is due i liked it i  
<a onclick="modifyYTiframeseektime('1682')">0:28:02</a> said okay look this man at least yeah  
<a onclick="modifyYTiframeseektime('1684')">0:28:04</a> i'm not pro him and he's definitely not  
<a onclick="modifyYTiframeseektime('1687')">0:28:07</a> a favorite but  
<a onclick="modifyYTiframeseektime('1688')">0:28:08</a> this is the stance people generally  
<a onclick="modifyYTiframeseektime('1691')">0:28:11</a> should have  
<a onclick="modifyYTiframeseektime('1691')">0:28:11</a> yeah so i want to pause for a break now  
<a onclick="modifyYTiframeseektime('1695')">0:28:15</a> because you mentioned nakshwani who's  
<a onclick="modifyYTiframeseektime('1697')">0:28:17</a> who's a  
<a onclick="modifyYTiframeseektime('1698')">0:28:18</a> famous uh really i would describe him as  
<a onclick="modifyYTiframeseektime('1701')">0:28:21</a> a shiite  
<a onclick="modifyYTiframeseektime('1703')">0:28:23</a> apologist or a sunni a shiite apologist  
<a onclick="modifyYTiframeseektime('1706')">0:28:26</a> to sunism  
<a onclick="modifyYTiframeseektime('1707')">0:28:27</a> but he does other lectures as well and  
<a onclick="modifyYTiframeseektime('1709')">0:28:29</a> he's recently come out with a very  
<a onclick="modifyYTiframeseektime('1711')">0:28:31</a> provocative lecture and this is a  
<a onclick="modifyYTiframeseektime('1715')">0:28:35</a> a clip hopefully that you guys could  
<a onclick="modifyYTiframeseektime('1717')">0:28:37</a> benefit from  
<a onclick="modifyYTiframeseektime('1723')">0:28:43</a> someone says but how do i know you're  
<a onclick="modifyYTiframeseektime('1724')">0:28:44</a> not concealing your faith 24 7. me  
<a onclick="modifyYTiframeseektime('1727')">0:28:47</a> you know i'm going to conceal my faith  
<a onclick="modifyYTiframeseektime('1728')">0:28:48</a> you want to debate me  
<a onclick="modifyYTiframeseektime('1730')">0:28:50</a> come and debate me  
<a onclick="modifyYTiframeseektime('1735')">0:28:55</a> he wants to debate he wants to talk he  
<a onclick="modifyYTiframeseektime('1737')">0:28:57</a> wants to be out he wants to discuss his  
<a onclick="modifyYTiframeseektime('1739')">0:28:59</a> views  
<a onclick="modifyYTiframeseektime('1740')">0:29:00</a> and he wants to discuss them openly and  
<a onclick="modifyYTiframeseektime('1742')">0:29:02</a> this is exactly  
<a onclick="modifyYTiframeseektime('1743')">0:29:03</a> what we want we invite you to come and  
<a onclick="modifyYTiframeseektime('1744')">0:29:04</a> talk to us and see whether we have the  
<a onclick="modifyYTiframeseektime('1746')">0:29:06</a> huck or not  
<a onclick="modifyYTiframeseektime('1757')">0:29:17</a> what do you think of that what do you  
<a onclick="modifyYTiframeseektime('1758')">0:29:18</a> think of this of this  
<a onclick="modifyYTiframeseektime('1760')">0:29:20</a> clip well for the benefit of the viewers  
<a onclick="modifyYTiframeseektime('1762')">0:29:22</a> we should quickly summarize what is it  
<a onclick="modifyYTiframeseektime('1764')">0:29:24</a> about  
<a onclick="modifyYTiframeseektime('1765')">0:29:25</a> so us  
<a onclick="modifyYTiframeseektime('1768')">0:29:28</a> is challenging accepting no not he is  
<a onclick="modifyYTiframeseektime('1770')">0:29:30</a> challenging nakshawani  
<a onclick="modifyYTiframeseektime('1772')">0:29:32</a> yakshiwani um said in the clip i'm ready  
<a onclick="modifyYTiframeseektime('1774')">0:29:34</a> um  
<a onclick="modifyYTiframeseektime('1775')">0:29:35</a> don't do tapia debate me so we have here  
<a onclick="modifyYTiframeseektime('1778')">0:29:38</a> a historian  
<a onclick="modifyYTiframeseektime('1779')">0:29:39</a> we have here a known person who is a  
<a onclick="modifyYTiframeseektime('1782')">0:29:42</a> sunni  
<a onclick="modifyYTiframeseektime('1782')">0:29:42</a> muslim who says i'm ready to discuss  
<a onclick="modifyYTiframeseektime('1784')">0:29:44</a> these things and  
<a onclick="modifyYTiframeseektime('1786')">0:29:46</a> what is important for the view obviously  
<a onclick="modifyYTiframeseektime('1787')">0:29:47</a> is that narshawani in this year's  
<a onclick="modifyYTiframeseektime('1790')">0:29:50</a> one of his lectures uh  
<a onclick="modifyYTiframeseektime('1793')">0:29:53</a> very provocative lecture he said that  
<a onclick="modifyYTiframeseektime('1796')">0:29:56</a> the root of terrorism  
<a onclick="modifyYTiframeseektime('1797')">0:29:57</a> the past they used to say is wahhabis  
<a onclick="modifyYTiframeseektime('1799')">0:29:59</a> and i don't know whatever sect  
<a onclick="modifyYTiframeseektime('1801')">0:30:01</a> no he literally said the sahaba  
<a onclick="modifyYTiframeseektime('1803')">0:30:03</a> mentioned names  
<a onclick="modifyYTiframeseektime('1807')">0:30:07</a> or whatever term he used for him  
<a onclick="modifyYTiframeseektime('1808')">0:30:08</a> criminals and so on and so forth  
<a onclick="modifyYTiframeseektime('1811')">0:30:11</a> so um and i watched the whole you know  
<a onclick="modifyYTiframeseektime('1814')">0:30:14</a> you asked me regarding  
<a onclick="modifyYTiframeseektime('1816')">0:30:16</a> this i watched this whole lecture and  
<a onclick="modifyYTiframeseektime('1818')">0:30:18</a> what many people don't know is  
<a onclick="modifyYTiframeseektime('1819')">0:30:19</a> this is not a new or you say in english  
<a onclick="modifyYTiframeseektime('1822')">0:30:22</a> rhetoric it's  
<a onclick="modifyYTiframeseektime('1824')">0:30:24</a> not new uh yes in the past  
<a onclick="modifyYTiframeseektime('1828')">0:30:28</a> like few years ago he wasn't like this  
<a onclick="modifyYTiframeseektime('1830')">0:30:30</a> but last year he had a similar lecture  
<a onclick="modifyYTiframeseektime('1832')">0:30:32</a> and interesting for me was when i  
<a onclick="modifyYTiframeseektime('1835')">0:30:35</a> watched the whole lecture is that he  
<a onclick="modifyYTiframeseektime('1837')">0:30:37</a> said  
<a onclick="modifyYTiframeseektime('1837')">0:30:37</a> you know they can discuss everything  
<a onclick="modifyYTiframeseektime('1838')">0:30:38</a> these sunnis they can discuss salah  
<a onclick="modifyYTiframeseektime('1841')">0:30:41</a> they can discuss  
<a onclick="modifyYTiframeseektime('1844')">0:30:44</a> conquest conquest where they take pride  
<a onclick="modifyYTiframeseektime('1846')">0:30:46</a> in and so and so forth  
<a onclick="modifyYTiframeseektime('1848')">0:30:48</a> but not the fit and the trials after the  
<a onclick="modifyYTiframeseektime('1851')">0:30:51</a> prophet sallam the wars that happened  
<a onclick="modifyYTiframeseektime('1852')">0:30:52</a> between sahaba no  
<a onclick="modifyYTiframeseektime('1853')">0:30:53</a> don't talk about this don't talk about  
<a onclick="modifyYTiframeseektime('1855')">0:30:55</a> it he claims that this is the sunni  
<a onclick="modifyYTiframeseektime('1857')">0:30:57</a> attitude  
<a onclick="modifyYTiframeseektime('1859')">0:30:59</a> so that we or let's say we our scholars  
<a onclick="modifyYTiframeseektime('1862')">0:31:02</a> or  
<a onclick="modifyYTiframeseektime('1862')">0:31:02</a> preachers or researchers to hide this  
<a onclick="modifyYTiframeseektime('1864')">0:31:04</a> from the aram from the  
<a onclick="modifyYTiframeseektime('1866')">0:31:06</a> from the communists which is nonsense  
<a onclick="modifyYTiframeseektime('1868')">0:31:08</a> yeah that's i think it's unfortunate  
<a onclick="modifyYTiframeseektime('1870')">0:31:10</a> that  
<a onclick="modifyYTiframeseektime('1870')">0:31:10</a> he's the one who's kind of made the  
<a onclick="modifyYTiframeseektime('1872')">0:31:12</a> challenge now he's made a sort of career  
<a onclick="modifyYTiframeseektime('1874')">0:31:14</a> out of  
<a onclick="modifyYTiframeseektime('1874')">0:31:14</a> uh being an apologist to sunnism  
<a onclick="modifyYTiframeseektime('1878')">0:31:18</a> and he's never actually had one  
<a onclick="modifyYTiframeseektime('1880')">0:31:20</a> discussion with the sunni  
<a onclick="modifyYTiframeseektime('1882')">0:31:22</a> this reminds me of  
<a onclick="modifyYTiframeseektime('1885')">0:31:25</a> of a dear friend who helped me and the  
<a onclick="modifyYTiframeseektime('1888')">0:31:28</a> early stages when i left jesus  
<a onclick="modifyYTiframeseektime('1890')">0:31:30</a> he said to me take from his his  
<a onclick="modifyYTiframeseektime('1893')">0:31:33</a> all these references and what they use  
<a onclick="modifyYTiframeseektime('1896')">0:31:36</a> today and copy paste  
<a onclick="modifyYTiframeseektime('1898')">0:31:38</a> and somebody says well you need these  
<a onclick="modifyYTiframeseektime('1899')">0:31:39</a> are the evidences  
<a onclick="modifyYTiframeseektime('1901')">0:31:41</a> we're talking about what shias normally  
<a onclick="modifyYTiframeseektime('1903')">0:31:43</a> do maybe you have experience with it  
<a onclick="modifyYTiframeseektime('1904')">0:31:44</a> they bring you some random statement  
<a onclick="modifyYTiframeseektime('1906')">0:31:46</a> random hadith and then they put you know  
<a onclick="modifyYTiframeseektime('1908')">0:31:48</a> and  
<a onclick="modifyYTiframeseektime('1908')">0:31:48</a> a whole train of sunni references and  
<a onclick="modifyYTiframeseektime('1911')">0:31:51</a> then you see kansas  
<a onclick="modifyYTiframeseektime('1912')">0:31:52</a> and you know usually  
<a onclick="modifyYTiframeseektime('1915')">0:31:55</a> weak sources sources late sources for  
<a onclick="modifyYTiframeseektime('1918')">0:31:58</a> example one of the  
<a onclick="modifyYTiframeseektime('1919')">0:31:59</a> sources they're often used as kansa  
<a onclick="modifyYTiframeseektime('1921')">0:32:01</a> amalev thousand years of the hijra  
<a onclick="modifyYTiframeseektime('1923')">0:32:03</a> written  
<a onclick="modifyYTiframeseektime('1924')">0:32:04</a> and if they use sources authentic  
<a onclick="modifyYTiframeseektime('1926')">0:32:06</a> sources then they are  
<a onclick="modifyYTiframeseektime('1927')">0:32:07</a> taken out of context that their their  
<a onclick="modifyYTiframeseektime('1930')">0:32:10</a> interpretation is forced on it  
<a onclick="modifyYTiframeseektime('1932')">0:32:12</a> so his advice or statement was he said  
<a onclick="modifyYTiframeseektime('1935')">0:32:15</a> to me take from them  
<a onclick="modifyYTiframeseektime('1936')">0:32:16</a> these things what they normally copy and  
<a onclick="modifyYTiframeseektime('1938')">0:32:18</a> paste and sit with them  
<a onclick="modifyYTiframeseektime('1940')">0:32:20</a> and discuss so that's why i uh  
<a onclick="modifyYTiframeseektime('1943')">0:32:23</a> i really appreciate that the stuff that  
<a onclick="modifyYTiframeseektime('1949')">0:32:29</a> has challenged nakshawani and the  
<a onclick="modifyYTiframeseektime('1951')">0:32:31</a> challenge on its own  
<a onclick="modifyYTiframeseektime('1953')">0:32:33</a> it's really a refutation because  
<a onclick="modifyYTiframeseektime('1954')">0:32:34</a> nakshawani said to his followers  
<a onclick="modifyYTiframeseektime('1957')">0:32:37</a> thousands and more of shays that these  
<a onclick="modifyYTiframeseektime('1959')">0:32:39</a> sunnis they don't discuss they keep this  
<a onclick="modifyYTiframeseektime('1961')">0:32:41</a> you know these things about sahaba and  
<a onclick="modifyYTiframeseektime('1963')">0:32:43</a> what happened to fitan  
<a onclick="modifyYTiframeseektime('1964')">0:32:44</a> they don't discuss these things and then  
<a onclick="modifyYTiframeseektime('1966')">0:32:46</a> suddenly we see somebody  
<a onclick="modifyYTiframeseektime('1968')">0:32:48</a> suddenly confident historian saying  
<a onclick="modifyYTiframeseektime('1971')">0:32:51</a> let's discuss this and there are others  
<a onclick="modifyYTiframeseektime('1973')">0:32:53</a> of course and if this inshallah  
<a onclick="modifyYTiframeseektime('1975')">0:32:55</a> if it goes uh the discussion actually  
<a onclick="modifyYTiframeseektime('1978')">0:32:58</a> happens insha'allah then people can  
<a onclick="modifyYTiframeseektime('1981')">0:33:01</a> judge that's right i'm always  
<a onclick="modifyYTiframeseektime('1983')">0:33:03</a> i'm always for discussion and especially  
<a onclick="modifyYTiframeseektime('1986')">0:33:06</a> of course  
<a onclick="modifyYTiframeseektime('1987')">0:33:07</a> you give a preference to people who are  
<a onclick="modifyYTiframeseektime('1989')">0:33:09</a> people of knowledge people  
<a onclick="modifyYTiframeseektime('1990')">0:33:10</a> uh like sheikha atnan and and others  
<a onclick="modifyYTiframeseektime('1995')">0:33:15</a> and but let's see if the likes of  
<a onclick="modifyYTiframeseektime('1997')">0:33:17</a> nakshawani  
<a onclick="modifyYTiframeseektime('1998')">0:33:18</a> yeah because he does represent we're not  
<a onclick="modifyYTiframeseektime('2000')">0:33:20</a> going to debate and discuss with  
<a onclick="modifyYTiframeseektime('2001')">0:33:21</a> everybody it's also important  
<a onclick="modifyYTiframeseektime('2002')">0:33:22</a> this is an advice i've been given in a  
<a onclick="modifyYTiframeseektime('2004')">0:33:24</a> very early stage one of jesus you know  
<a onclick="modifyYTiframeseektime('2006')">0:33:26</a> not going to sit with everybody discuss  
<a onclick="modifyYTiframeseektime('2008')">0:33:28</a> with everybody and  
<a onclick="modifyYTiframeseektime('2009')">0:33:29</a> same with you you're not going to meet  
<a onclick="modifyYTiframeseektime('2010')">0:33:30</a> with everybody somebody who's for  
<a onclick="modifyYTiframeseektime('2012')">0:33:32</a> example  
<a onclick="modifyYTiframeseektime('2012')">0:33:32</a> not representing christians at all well  
<a onclick="modifyYTiframeseektime('2016')">0:33:36</a> you discuss with the main people  
<a onclick="modifyYTiframeseektime('2018')">0:33:38</a> you know catholics and orthodox and so  
<a onclick="modifyYTiframeseektime('2020')">0:33:40</a> on so forth  
<a onclick="modifyYTiframeseektime('2021')">0:33:41</a> so same with us i believe we should be  
<a onclick="modifyYTiframeseektime('2023')">0:33:43</a> careful who we so hopefully this will be  
<a onclick="modifyYTiframeseektime('2025')">0:33:45</a> something that he  
<a onclick="modifyYTiframeseektime('2026')">0:33:46</a> accepts because i mean uh it would be  
<a onclick="modifyYTiframeseektime('2030')">0:33:50</a> basically meeting his requirement he  
<a onclick="modifyYTiframeseektime('2031')">0:33:51</a> said he wanted someone to discuss he  
<a onclick="modifyYTiframeseektime('2033')">0:33:53</a> wanted to challenge someone  
<a onclick="modifyYTiframeseektime('2034')">0:33:54</a> but it would be a discussion format and  
<a onclick="modifyYTiframeseektime('2036')">0:33:56</a> hopefully uh you know be the first time  
<a onclick="modifyYTiframeseektime('2038')">0:33:58</a> he's ever  
<a onclick="modifyYTiframeseektime('2039')">0:33:59</a> put his actual ideas and his references  
<a onclick="modifyYTiframeseektime('2041')">0:34:01</a> on the table to be scrutinized because  
<a onclick="modifyYTiframeseektime('2043')">0:34:03</a> it's very easy  
<a onclick="modifyYTiframeseektime('2044')">0:34:04</a> for someone to make comments in a mosque  
<a onclick="modifyYTiframeseektime('2047')">0:34:07</a> where everyone is  
<a onclick="modifyYTiframeseektime('2048')">0:34:08</a> is basically blind to the references  
<a onclick="modifyYTiframeseektime('2050')">0:34:10</a> blind to the scholarly discussions  
<a onclick="modifyYTiframeseektime('2052')">0:34:12</a> but it's a bit more difficult to  
<a onclick="modifyYTiframeseektime('2054')">0:34:14</a> actually con to confront someone or to  
<a onclick="modifyYTiframeseektime('2056')">0:34:16</a> speak to someone  
<a onclick="modifyYTiframeseektime('2057')">0:34:17</a> who believes in something which is  
<a onclick="modifyYTiframeseektime('2058')">0:34:18</a> opposite to you uh  
<a onclick="modifyYTiframeseektime('2060')">0:34:20</a> and we hope that nakshwani will accept  
<a onclick="modifyYTiframeseektime('2063')">0:34:23</a> this challenge because uh  
<a onclick="modifyYTiframeseektime('2064')">0:34:24</a> because this will be the first time he's  
<a onclick="modifyYTiframeseektime('2065')">0:34:25</a> actually put his rhetoric to  
<a onclick="modifyYTiframeseektime('2067')">0:34:27</a> the test there was then one person  
<a onclick="modifyYTiframeseektime('2071')">0:34:31</a> who was standing on a lorry and said and  
<a onclick="modifyYTiframeseektime('2074')">0:34:34</a> may imam hussain also reward all of you  
<a onclick="modifyYTiframeseektime('2077')">0:34:37</a> i was like i was i was looking i was  
<a onclick="modifyYTiframeseektime('2080')">0:34:40</a> just i was like  
<a onclick="modifyYTiframeseektime('2081')">0:34:41</a> frozen  
</details>
