# Firas Zahabi on Bravery, Health and Lifestyle. (2018-03-30)

<iframe loading='lazy' src='https://www.youtube.com/embed/wzWTLOTWkms'></iframe>

## Description

A really important discussion on how to stay healthy and creating balance in life. 

Make sure you visit Firas's channel -https://www.youtube.com/user/tristargymcanada

## Summary of [Firas Zahabi on Bravery, Health and Lifestyle.](https://www.youtube.com/watch?v=wzWTLOTWkms)


*<span style="color:red; font-size:125%">This summary is AI generated - there may be inaccuracies</span>. [](/)*

### <a onclick="modifyYTiframeseektime('0')">00:00:00</a> - <a onclick="modifyYTiframeseektime('1200')">00:20:00</a>

Firas Zahabi is a YouTube personality who discusses the importance of having a healthy lifestyle. In this particular video, he discusses how bravery, health, and lifestyle were important in the Islamic Golden Age of Science. He suggests that the backlash against the Golden Age, caused by the Mongolian invasion, was necessary for the return to spirituality.

**<a onclick="modifyYTiframeseektime('0')">00:00:00</a>** Firas Zahabi discusses how to live a healthy lifestyle, including eating the same foods every day, and calculating caloric intake. He also discusses how to increase caloric intake if you are feeling lighted or weak.
* **<a onclick="modifyYTiframeseektime('300')">00:05:00</a>** Firas Zahabi discusses the importance of having a healthy lifestyle and the role of motivation in training. He also discusses the importance of having a balanced diet and training regularly.
* **<a onclick="modifyYTiframeseektime('600')">00:10:00</a>** Firas Zahabi discusses the importance of developing competence and confidence, and how having both can help you in life.
* **<a onclick="modifyYTiframeseektime('900')">00:15:00</a>** , Firas Zahabi discusses how confidence can be built and how it can be useful in various aspects of life. He points to the example of a great burglar, Henry Manchester, and how his confidence was based on his skill and experience. He also discusses how confidence can be lost, and how it is important to maintain it through skill development and practice.
* **<a onclick="modifyYTiframeseektime('1200')">00:20:00</a>** Firas Zahabi discusses the importance of bravery, health, and lifestyle in the Islamic Golden Age of Science, which he believes was the greatest time in science ever. He also suggests that the backlash against the Golden Age, caused by the Mongolian invasion, was necessary for the return to spirituality.

<details><summary><h2>Full transcript with timestamps: CLICK TO EXPAND</h2></summary>

<a onclick="modifyYTiframeseektime('12')">0:00:12</a> who is one of the most celebrated people  
<a onclick="modifyYTiframeseektime('32')">0:00:32</a> so I mean I believe that with the  
<a onclick="modifyYTiframeseektime('84')">0:01:24</a> knowledge we have today  
<a onclick="modifyYTiframeseektime('86')">0:01:26</a> that's me everybody should be within a  
<a onclick="modifyYTiframeseektime('88')">0:01:28</a> healthy body because we know the  
<a onclick="modifyYTiframeseektime('91')">0:01:31</a> benefits of it what are the blinders are  
<a onclick="modifyYTiframeseektime('93')">0:01:33</a> healthy for you  
<a onclick="modifyYTiframeseektime('94')">0:01:34</a> a young girl should be between 9 and 15  
<a onclick="modifyYTiframeseektime('98')">0:01:38</a> okay roughly roughly speaking now there  
<a onclick="modifyYTiframeseektime('100')">0:01:40</a> are gonna be some anomaly that's  
<a onclick="modifyYTiframeseektime('102')">0:01:42</a> somebody very good shape but why  
<a onclick="modifyYTiframeseektime('105')">0:01:45</a> shouldn't you be in good shape we have  
<a onclick="modifyYTiframeseektime('106')">0:01:46</a> so much science behind fitness no no we  
<a onclick="modifyYTiframeseektime('109')">0:01:49</a> can get in shape in 5 to 10 minutes a  
<a onclick="modifyYTiframeseektime('111')">0:01:51</a> day who doesn't have that incident if  
<a onclick="modifyYTiframeseektime('114')">0:01:54</a> their body their most prized machine  
<a onclick="modifyYTiframeseektime('117')">0:01:57</a> healthier you have time to fix your car  
<a onclick="modifyYTiframeseektime('120')">0:02:00</a> and clean up your room but you're not  
<a onclick="modifyYTiframeseektime('121')">0:02:01</a> have time you to keep your body healthy  
<a onclick="modifyYTiframeseektime('123')">0:02:03</a> it's you have to prioritize know what  
<a onclick="modifyYTiframeseektime('126')">0:02:06</a> kind of like now someone wants us lucky  
<a onclick="modifyYTiframeseektime('129')">0:02:09</a> help me they want to know what like the  
<a onclick="modifyYTiframeseektime('134')">0:02:14</a> rule of thumb if I could boil it down it  
<a onclick="modifyYTiframeseektime('136')">0:02:16</a> to me I like to keep things sets three  
<a onclick="modifyYTiframeseektime('137')">0:02:17</a> rules I find it's the easiest way to  
<a onclick="modifyYTiframeseektime('139')">0:02:19</a> learn learn three things that are fine  
<a onclick="modifyYTiframeseektime('140')">0:02:20</a> in a subject one would be know how many  
<a onclick="modifyYTiframeseektime('143')">0:02:23</a> calories you can use you can go on many  
<a onclick="modifyYTiframeseektime('146')">0:02:26</a> websites you find out how much your body  
<a onclick="modifyYTiframeseektime('148')">0:02:28</a> through your size your age weight your  
<a onclick="modifyYTiframeseektime('152')">0:02:32</a> goal for your weight how many calories  
<a onclick="modifyYTiframeseektime('154')">0:02:34</a> should you eat in containers there's  
<a onclick="modifyYTiframeseektime('155')">0:02:35</a> many programs and then practice  
<a onclick="modifyYTiframeseektime('158')">0:02:38</a> calculating your calories after a while  
<a onclick="modifyYTiframeseektime('160')">0:02:40</a> you'll just look at a piece of food and  
<a onclick="modifyYTiframeseektime('162')">0:02:42</a> you'll know about how many calendar  
<a onclick="modifyYTiframeseektime('165')">0:02:45</a> now you don't have to be perfectly exact  
<a onclick="modifyYTiframeseektime('167')">0:02:47</a> but over time after about a month and  
<a onclick="modifyYTiframeseektime('171')">0:02:51</a> you'll be an expert this is this how  
<a onclick="modifyYTiframeseektime('173')">0:02:53</a> many calories this is not many calories  
<a onclick="modifyYTiframeseektime('174')">0:02:54</a> this  
<a onclick="modifyYTiframeseektime('175')">0:02:55</a> you know I'm close to my to my quota for  
<a onclick="modifyYTiframeseektime('177')">0:02:57</a> the day I know how many calories you  
<a onclick="modifyYTiframeseektime('180')">0:03:00</a> should have a thing yeah you all know  
<a onclick="modifyYTiframeseektime('183')">0:03:03</a> that having that cookie is gonna cost me  
<a onclick="modifyYTiframeseektime('185')">0:03:05</a> this many calories on my go  
<a onclick="modifyYTiframeseektime('187')">0:03:07</a> once you get to your goal let's say you  
<a onclick="modifyYTiframeseektime('191')">0:03:11</a> get to eight percent but nine percent  
<a onclick="modifyYTiframeseektime('192')">0:03:12</a> whatever it is now you can have more off  
<a onclick="modifyYTiframeseektime('194')">0:03:14</a> these more days of surgery like I eat  
<a onclick="modifyYTiframeseektime('197')">0:03:17</a> this today I'm not worried I'm like I'm  
<a onclick="modifyYTiframeseektime('198')">0:03:18</a> gonna stay my buddy but I'm not gonna  
<a onclick="modifyYTiframeseektime('202')">0:03:22</a> you cannot be more than one pack one  
<a onclick="modifyYTiframeseektime('204')">0:03:24</a> pound one pound and a half in a week you  
<a onclick="modifyYTiframeseektime('206')">0:03:26</a> big dog you can gain water weight yes so  
<a onclick="modifyYTiframeseektime('211')">0:03:31</a> you have to know that your your goal  
<a onclick="modifyYTiframeseektime('212')">0:03:32</a> once you get it's easier to maintain  
<a onclick="modifyYTiframeseektime('214')">0:03:34</a> them to get there so I found it very  
<a onclick="modifyYTiframeseektime('216')">0:03:36</a> encouraging so how many calories you eat  
<a onclick="modifyYTiframeseektime('218')">0:03:38</a> and they figure that out you're gonna  
<a onclick="modifyYTiframeseektime('220')">0:03:40</a> have to experimental if you're a little  
<a onclick="modifyYTiframeseektime('222')">0:03:42</a> bit lightheaded that number is a little  
<a onclick="modifyYTiframeseektime('223')">0:03:43</a> bit low yeah weakened if you're not  
<a onclick="modifyYTiframeseektime('226')">0:03:46</a> losing a lot of weight after 2-3 weeks a  
<a onclick="modifyYTiframeseektime('228')">0:03:48</a> minute it might be a little high you  
<a onclick="modifyYTiframeseektime('230')">0:03:50</a> gotta lower it it's not an exact science  
<a onclick="modifyYTiframeseektime('232')">0:03:52</a> there is some adjusting that needs to be  
<a onclick="modifyYTiframeseektime('236')">0:03:56</a> done but the good news is very simple if  
<a onclick="modifyYTiframeseektime('239')">0:03:59</a> you're feeling bad increasing the small  
<a onclick="modifyYTiframeseektime('241')">0:04:01</a> amount increase of your calories by five  
<a onclick="modifyYTiframeseektime('242')">0:04:02</a> or ten percent and now once you find  
<a onclick="modifyYTiframeseektime('245')">0:04:05</a> that number you'll find yourself full  
<a onclick="modifyYTiframeseektime('247')">0:04:07</a> just eating better second I would say a  
<a onclick="modifyYTiframeseektime('253')">0:04:13</a> good rule of thumb would be to eat the  
<a onclick="modifyYTiframeseektime('256')">0:04:16</a> same foods every day like I have I know  
<a onclick="modifyYTiframeseektime('258')">0:04:18</a> I have meals I make the recommended  
<a onclick="modifyYTiframeseektime('259')">0:04:19</a> calories I know I do I do  
<a onclick="modifyYTiframeseektime('263')">0:04:23</a> one meal that I do most every day is one  
<a onclick="modifyYTiframeseektime('265')">0:04:25</a> banana two ends I mash them up I make a  
<a onclick="modifyYTiframeseektime('268')">0:04:28</a> pancake I make three pancakes with the  
<a onclick="modifyYTiframeseektime('270')">0:04:30</a> higher you make a packet yeah mash them  
<a onclick="modifyYTiframeseektime('272')">0:04:32</a> up make a pancake and I had 50 calories  
<a onclick="modifyYTiframeseektime('274')">0:04:34</a> worth of honey I love honey any things I  
<a onclick="modifyYTiframeseektime('277')">0:04:37</a> love thank you  
<a onclick="modifyYTiframeseektime('278')">0:04:38</a> yes um that was I know that's 200 men  
<a onclick="modifyYTiframeseektime('282')">0:04:42</a> you tell me I have dates for $75 each  
<a onclick="modifyYTiframeseektime('285')">0:04:45</a> I know how many right away gets on the  
<a onclick="modifyYTiframeseektime('287')">0:04:47</a> stage Nate's is amazing for treating the  
<a onclick="modifyYTiframeseektime('289')">0:04:49</a> backsight not sugar fiber carbohydrate a  
<a onclick="modifyYTiframeseektime('293')">0:04:53</a> slowly releasing easy to digest  
<a onclick="modifyYTiframeseektime('296')">0:04:56</a> I miss the perfect food I was biting at  
<a onclick="modifyYTiframeseektime('298')">0:04:58</a> what happened I have certain smoothies I  
<a onclick="modifyYTiframeseektime('301')">0:05:01</a> make I know that we never stop I know my  
<a onclick="modifyYTiframeseektime('303')">0:05:03</a> blocks calories and I'll be fine if I'm  
<a onclick="modifyYTiframeseektime('306')">0:05:06</a> in the mood to eat a hamburger I know  
<a onclick="modifyYTiframeseektime('307')">0:05:07</a> that a big Max's I don't feel like the  
<a onclick="modifyYTiframeseektime('313')">0:05:13</a> fries I don't always naturally but I  
<a onclick="modifyYTiframeseektime('320')">0:05:20</a> know how many calories I should even  
<a onclick="modifyYTiframeseektime('321')">0:05:21</a> today and for me it keeps me lean  
<a onclick="modifyYTiframeseektime('323')">0:05:23</a> healthy and it keeps the energy going  
<a onclick="modifyYTiframeseektime('324')">0:05:24</a> because if you eat too many calories and  
<a onclick="modifyYTiframeseektime('326')">0:05:26</a> energy of tools project three to little  
<a onclick="modifyYTiframeseektime('329')">0:05:29</a> you'll feel like head into me how'd you  
<a onclick="modifyYTiframeseektime('332')">0:05:32</a> how'd you keep that good every day I  
<a onclick="modifyYTiframeseektime('336')">0:05:36</a> feel tired like how do I change that no  
<a onclick="modifyYTiframeseektime('340')">0:05:40</a> the right amount of calories and three I  
<a onclick="modifyYTiframeseektime('347')">0:05:47</a> would say you know you have to have a  
<a onclick="modifyYTiframeseektime('348')">0:05:48</a> cheat meal here bed never let your  
<a onclick="modifyYTiframeseektime('350')">0:05:50</a> cravings get out of control if you're  
<a onclick="modifyYTiframeseektime('352')">0:05:52</a> not at your target weight have one or  
<a onclick="modifyYTiframeseektime('354')">0:05:54</a> two cheat meals a week meals not days  
<a onclick="modifyYTiframeseektime('356')">0:05:56</a> two days one or two cheeseburger fries  
<a onclick="modifyYTiframeseektime('360')">0:06:00</a> okay coming to efface Turkish restaurant  
<a onclick="modifyYTiframeseektime('366')">0:06:06</a> another nice meal yeah  
<a onclick="modifyYTiframeseektime('368')">0:06:08</a> don't go overboard but have a nice meal  
<a onclick="modifyYTiframeseektime('370')">0:06:10</a> don't let your don't let your cravings  
<a onclick="modifyYTiframeseektime('372')">0:06:12</a> get out of control you know when I see  
<a onclick="modifyYTiframeseektime('374')">0:06:14</a> something I want to eat well I see  
<a onclick="modifyYTiframeseektime('378')">0:06:18</a> something I want to eat something okay  
<a onclick="modifyYTiframeseektime('379')">0:06:19</a> Saturday it's my cheek now I'm hiding  
<a onclick="modifyYTiframeseektime('381')">0:06:21</a> that so I look forward to it the  
<a onclick="modifyYTiframeseektime('383')">0:06:23</a> motivation is very important you know  
<a onclick="modifyYTiframeseektime('384')">0:06:24</a> and you know every year every  
<a onclick="modifyYTiframeseektime('388')">0:06:28</a> my birthday doesn't age see you coach  
<a onclick="modifyYTiframeseektime('422')">0:07:02</a> you're getting old because I haven't  
<a onclick="modifyYTiframeseektime('423')">0:07:03</a> taken down in ten years ten years I'm  
<a onclick="modifyYTiframeseektime('431')">0:07:11</a> still waiting for you think you don't  
<a onclick="modifyYTiframeseektime('433')">0:07:13</a> you can a driving this guy's new  
<a onclick="modifyYTiframeseektime('436')">0:07:16</a> consistent attendee is trying to train  
<a onclick="modifyYTiframeseektime('438')">0:07:18</a> with him take him down he's got that  
<a onclick="modifyYTiframeseektime('440')">0:07:20</a> persistent thing is with our technology  
<a onclick="modifyYTiframeseektime('442')">0:07:22</a> we have to the other water and knowledge  
<a onclick="modifyYTiframeseektime('443')">0:07:23</a> we have to think we're like ageing of  
<a onclick="modifyYTiframeseektime('445')">0:07:25</a> something this should be done very well  
<a onclick="modifyYTiframeseektime('447')">0:07:27</a> we have so much knowledge today health  
<a onclick="modifyYTiframeseektime('450')">0:07:30</a> health comes from eating right and  
<a onclick="modifyYTiframeseektime('452')">0:07:32</a> exercise would you think about me  
<a onclick="modifyYTiframeseektime('454')">0:07:34</a> because that was like the whole thing  
<a onclick="modifyYTiframeseektime('457')">0:07:37</a> I haven't I would say I like it dr. joel  
<a onclick="modifyYTiframeseektime('462')">0:07:42</a> Fuhrman says to deck of cards so about a  
<a onclick="modifyYTiframeseektime('465')">0:07:45</a> deck of cards worth of brandy or movie  
<a onclick="modifyYTiframeseektime('467')">0:07:47</a> or red meat twice a week not more than  
<a onclick="modifyYTiframeseektime('469')">0:07:49</a> that I think that's the ultimate the  
<a onclick="modifyYTiframeseektime('471')">0:07:51</a> star is optimal  
<a onclick="modifyYTiframeseektime('472')">0:07:52</a> I haven't I mean I go over that you have  
<a onclick="modifyYTiframeseektime('476')">0:07:56</a> such great food all the time or  
<a onclick="modifyYTiframeseektime('477')">0:07:57</a> traveling but it's the optimal when I do  
<a onclick="modifyYTiframeseektime('479')">0:07:59</a> that I feel my best when I'm lucid when  
<a onclick="modifyYTiframeseektime('481')">0:08:01</a> I try to lower my rope  
<a onclick="modifyYTiframeseektime('483')">0:08:03</a> I try to eat more fruits and vegetables  
<a onclick="modifyYTiframeseektime('485')">0:08:05</a> do you feel amazing yeah but then again  
<a onclick="modifyYTiframeseektime('487')">0:08:07</a> you go to these rare restaurants I don't  
<a onclick="modifyYTiframeseektime('489')">0:08:09</a> want to deny myself so  
<a onclick="modifyYTiframeseektime('490')">0:08:10</a> you know but next week now you know on  
<a onclick="modifyYTiframeseektime('492')">0:08:12</a> this trip I ate a little too much next  
<a onclick="modifyYTiframeseektime('494')">0:08:14</a> week I'm gonna be more strict yeah and  
<a onclick="modifyYTiframeseektime('496')">0:08:16</a> the way I am now I do 45 days of the  
<a onclick="modifyYTiframeseektime('498')">0:08:18</a> right amount of calories  
<a onclick="modifyYTiframeseektime('500')">0:08:20</a> but I also train along respective of how  
<a onclick="modifyYTiframeseektime('503')">0:08:23</a> active you are when you do these these  
<a onclick="modifyYTiframeseektime('505')">0:08:25</a> websites that you go on this front they  
<a onclick="modifyYTiframeseektime('507')">0:08:27</a> can ask you how active is your lifestyle  
<a onclick="modifyYTiframeseektime('508')">0:08:28</a> very moderate where you train every day  
<a onclick="modifyYTiframeseektime('510')">0:08:30</a> I can train a lot you know one day with  
<a onclick="modifyYTiframeseektime('512')">0:08:32</a> I one day a restaurant for me ok let's  
<a onclick="modifyYTiframeseektime('518')">0:08:38</a> move on to training your training is  
<a onclick="modifyYTiframeseektime('522')">0:08:42</a> mostly what's the trailer you know what  
<a onclick="modifyYTiframeseektime('525')">0:08:45</a> yeah I can't run on a trip I got left  
<a onclick="modifyYTiframeseektime('527')">0:08:47</a> when it's too boring  
<a onclick="modifyYTiframeseektime('528')">0:08:48</a> I've been training a long time for me  
<a onclick="modifyYTiframeseektime('530')">0:08:50</a> training is a player and it's many and  
<a onclick="modifyYTiframeseektime('535')">0:08:55</a> many other great fights I do Jiu Jitsu  
<a onclick="modifyYTiframeseektime('537')">0:08:57</a> wrestling kickboxing boxing this thing  
<a onclick="modifyYTiframeseektime('541')">0:09:01</a> did you tell me we're gonna wrestle for  
<a onclick="modifyYTiframeseektime('542')">0:09:02</a> one hour to me one hour is not a  
<a onclick="modifyYTiframeseektime('544')">0:09:04</a> question because we run on a treadmill  
<a onclick="modifyYTiframeseektime('545')">0:09:05</a> for an hour after Dennis I'm not tired  
<a onclick="modifyYTiframeseektime('554')">0:09:14</a> you can have the motivation to go right  
<a onclick="modifyYTiframeseektime('556')">0:09:16</a> this training is 99% motivation you know  
<a onclick="modifyYTiframeseektime('560')">0:09:20</a> one thing I found my way the senses are  
<a onclick="modifyYTiframeseektime('568')">0:09:28</a> missing are gonna be less than 1% Oh  
<a onclick="modifyYTiframeseektime('572')">0:09:32</a> but she'll try to tell me we make it fun  
<a onclick="modifyYTiframeseektime('575')">0:09:35</a> gotta cut me with cakes honey of this  
<a onclick="modifyYTiframeseektime('578')">0:09:38</a> but you need motivation like this it  
<a onclick="modifyYTiframeseektime('582')">0:09:42</a> comes to training motivation support  
<a onclick="modifyYTiframeseektime('585')">0:09:45</a> like me my sons are trained my son's  
<a onclick="modifyYTiframeseektime('586')">0:09:46</a> yeah I taught my son's if you train what  
<a onclick="modifyYTiframeseektime('590')">0:09:50</a> do you want this toy that's all  
<a onclick="modifyYTiframeseektime('591')">0:09:51</a> yes that's what yes  
<a onclick="modifyYTiframeseektime('595')">0:09:55</a> we was eating  
<a onclick="modifyYTiframeseektime('610')">0:10:10</a> [Music]  
<a onclick="modifyYTiframeseektime('654')">0:10:54</a> anyways I go stir everything it's like  
<a onclick="modifyYTiframeseektime('657')">0:10:57</a> it's not a question whether I'm gonna  
<a onclick="modifyYTiframeseektime('658')">0:10:58</a> trim it it's like what's your train  
<a onclick="modifyYTiframeseektime('660')">0:11:00</a> driver - how many allergy  
<a onclick="modifyYTiframeseektime('663')">0:11:03</a> how many chores do we Trinity that's my  
<a onclick="modifyYTiframeseektime('668')">0:11:08</a> day every day - in the heart that's my  
<a onclick="modifyYTiframeseektime('670')">0:11:10</a> day everything listening do did you do  
<a onclick="modifyYTiframeseektime('672')">0:11:12</a> this far oh yeah yeah it's funny - then  
<a onclick="modifyYTiframeseektime('677')">0:11:17</a> pretty much Java or injured ribbon yeah  
<a onclick="modifyYTiframeseektime('679')">0:11:19</a> but I'll tell you one thing here's my  
<a onclick="modifyYTiframeseektime('682')">0:11:22</a> philosophy  
<a onclick="modifyYTiframeseektime('684')">0:11:24</a> yeah yeah there's no excuse no excuse  
<a onclick="modifyYTiframeseektime('688')">0:11:28</a> can you do one push up a date I'll tell  
<a onclick="modifyYTiframeseektime('691')">0:11:31</a> you the biggest secret to training yeah  
<a onclick="modifyYTiframeseektime('693')">0:11:33</a> never train 100% trained always 70 to  
<a onclick="modifyYTiframeseektime('698')">0:11:38</a> 80% save some for tomorrow so somebody's  
<a onclick="modifyYTiframeseektime('704')">0:11:44</a> completely out of shape let's say the  
<a onclick="modifyYTiframeseektime('705')">0:11:45</a> guy he hasn't trained in 10 years I felt  
<a onclick="modifyYTiframeseektime('708')">0:11:48</a> like it tomorrow doing one pushing this  
<a onclick="modifyYTiframeseektime('710')">0:11:50</a> money don't tell me you don't have the  
<a onclick="modifyYTiframeseektime('711')">0:11:51</a> time now if you tell me you don't have  
<a onclick="modifyYTiframeseektime('712')">0:11:52</a> that fine call us I won't leave you're  
<a onclick="modifyYTiframeseektime('714')">0:11:54</a> not you're not serious about being  
<a onclick="modifyYTiframeseektime('715')">0:11:55</a> healthy I've given up I call that  
<a onclick="modifyYTiframeseektime('718')">0:11:58</a> defeatist yeah you've given up a street  
<a onclick="modifyYTiframeseektime('719')">0:11:59</a> I can you do one pushup  
<a onclick="modifyYTiframeseektime('723')">0:12:03</a> don't give me ask one push up that one  
<a onclick="modifyYTiframeseektime('727')">0:12:07</a> push up it's gonna turn 2 2 2 is gonna  
<a onclick="modifyYTiframeseektime('731')">0:12:11</a> be enjoyable actually you're gonna crave  
<a onclick="modifyYTiframeseektime('734')">0:12:14</a> number three and after the number three  
<a onclick="modifyYTiframeseektime('737')">0:12:17</a> is gonna turn to a five because three is  
<a onclick="modifyYTiframeseektime('738')">0:12:18</a> uncomfortable it's not it's not a  
<a onclick="modifyYTiframeseektime('740')">0:12:20</a> satisfying spoon fight it's gonna grow  
<a onclick="modifyYTiframeseektime('742')">0:12:22</a> and you've created a spark I have it for  
<a onclick="modifyYTiframeseektime('745')">0:12:25</a> me now I'm at the point where I train  
<a onclick="modifyYTiframeseektime('746')">0:12:26</a> three hours and for me a regular me  
<a onclick="modifyYTiframeseektime('748')">0:12:28</a> maybe somebody trained three hours  
<a onclick="modifyYTiframeseektime('751')">0:12:31</a> follow that was exhausting for me it's  
<a onclick="modifyYTiframeseektime('753')">0:12:33</a> just a regular thing I got to that point  
<a onclick="modifyYTiframeseektime('755')">0:12:35</a> but it's one step at a time  
<a onclick="modifyYTiframeseektime('760')">0:12:40</a> so here when I trained someone I hold  
<a onclick="modifyYTiframeseektime('763')">0:12:43</a> their hand until they feel stronger and  
<a onclick="modifyYTiframeseektime('765')">0:12:45</a> they're carrying me you could take them  
<a onclick="modifyYTiframeseektime('766')">0:12:46</a> step by step my son's I started with a  
<a onclick="modifyYTiframeseektime('768')">0:12:48</a> little bit of truth  
<a onclick="modifyYTiframeseektime('769')">0:12:49</a> a little more a little more and then  
<a onclick="modifyYTiframeseektime('773')">0:12:53</a> training an old mandatory if you want  
<a onclick="modifyYTiframeseektime('777')">0:12:57</a> the things you like homework and  
<a onclick="modifyYTiframeseektime('780')">0:13:00</a> training is manual before was this the  
<a onclick="modifyYTiframeseektime('782')">0:13:02</a> game no mom I want this okay no but we  
<a onclick="modifyYTiframeseektime('785')">0:13:05</a> save our money for it but if you have  
<a onclick="modifyYTiframeseektime('786')">0:13:06</a> good discipline  
<a onclick="modifyYTiframeseektime('787')">0:13:07</a> I give you everything I think the worst  
<a onclick="modifyYTiframeseektime('790')">0:13:10</a> thing you could do to a child is give  
<a onclick="modifyYTiframeseektime('792')">0:13:12</a> them without their learning the worst  
<a onclick="modifyYTiframeseektime('795')">0:13:15</a> I'm a very serious father I really  
<a onclick="modifyYTiframeseektime('797')">0:13:17</a> amazing children especially have a you  
<a onclick="modifyYTiframeseektime('801')">0:13:21</a> know a background philosophize a lot  
<a onclick="modifyYTiframeseektime('803')">0:13:23</a> about raising children and children need  
<a onclick="modifyYTiframeseektime('808')">0:13:28</a> to develop their competence they have  
<a onclick="modifyYTiframeseektime('812')">0:13:32</a> the more confidence a lot of superficial  
<a onclick="modifyYTiframeseektime('814')">0:13:34</a> actually I'm not just on children but  
<a onclick="modifyYTiframeseektime('816')">0:13:36</a> just on young people grow up cuz  
<a onclick="modifyYTiframeseektime('817')">0:13:37</a> obviously like have this self insecurity  
<a onclick="modifyYTiframeseektime('825')">0:13:45</a> yeah participation trophy yeah and so on  
<a onclick="modifyYTiframeseektime('828')">0:13:48</a> yeah I was gonna ask you like what you I  
<a onclick="modifyYTiframeseektime('831')">0:13:51</a> think this is one thing people do the  
<a onclick="modifyYTiframeseektime('835')">0:13:55</a> best veterans are probably talk about  
<a onclick="modifyYTiframeseektime('838')">0:13:58</a> it's a quality that we will talk about  
<a onclick="modifyYTiframeseektime('840')">0:14:00</a> bravery beautifying  
<a onclick="modifyYTiframeseektime('844')">0:14:04</a> all players you've seen a lot what's the  
<a onclick="modifyYTiframeseektime('847')">0:14:07</a> best way to feel free I would say  
<a onclick="modifyYTiframeseektime('850')">0:14:10</a> developing competence the more  
<a onclick="modifyYTiframeseektime('853')">0:14:13</a> competence you have the more the  
<a onclick="modifyYTiframeseektime('855')">0:14:15</a> byproduct is confidence against that  
<a onclick="modifyYTiframeseektime('859')">0:14:19</a> yeah so the more I prepared I always  
<a onclick="modifyYTiframeseektime('861')">0:14:21</a> stop into this if your competence is  
<a onclick="modifyYTiframeseektime('864')">0:14:24</a> here your confidence here if their  
<a onclick="modifyYTiframeseektime('868')">0:14:28</a> competence is here and your confidence  
<a onclick="modifyYTiframeseektime('869')">0:14:29</a> is here the real world the world is  
<a onclick="modifyYTiframeseektime('873')">0:14:33</a> gonna shut you down if your competence  
<a onclick="modifyYTiframeseektime('877')">0:14:37</a> is here and your confidence is here  
<a onclick="modifyYTiframeseektime('881')">0:14:41</a> you won't live up to your potential so  
<a onclick="modifyYTiframeseektime('884')">0:14:44</a> what we need is to be realistic if you  
<a onclick="modifyYTiframeseektime('886')">0:14:46</a> drive your car every day to work safely  
<a onclick="modifyYTiframeseektime('888')">0:14:48</a> you should assume that tomorrow you'll  
<a onclick="modifyYTiframeseektime('889')">0:14:49</a> drive it towards things if you're  
<a onclick="modifyYTiframeseektime('892')">0:14:52</a> getting into an accident every two days  
<a onclick="modifyYTiframeseektime('893')">0:14:53</a> I'm like don't take the country I'm not  
<a onclick="modifyYTiframeseektime('897')">0:14:57</a> confident you can drive like to coin the  
<a onclick="modifyYTiframeseektime('901')">0:15:01</a> term basic test measure retest  
<a onclick="modifyYTiframeseektime('906')">0:15:06</a> build your confidence supporting I think  
<a onclick="modifyYTiframeseektime('909')">0:15:09</a> sensible so kids young kids the reason  
<a onclick="modifyYTiframeseektime('912')">0:15:12</a> why they lack confidence is because you  
<a onclick="modifyYTiframeseektime('916')">0:15:16</a> know I hate to bring philosophy all you  
<a onclick="modifyYTiframeseektime('919')">0:15:19</a> ever heard me choose last man Nietzsche  
<a onclick="modifyYTiframeseektime('922')">0:15:22</a> says rookies yeah the last man yes the  
<a onclick="modifyYTiframeseektime('928')">0:15:28</a> opposite of the last man Yes Doctor  
<a onclick="modifyYTiframeseektime('930')">0:15:30</a> he says look society's quick creating a  
<a onclick="modifyYTiframeseektime('933')">0:15:33</a> shock we talked about this hey look hey  
<a onclick="modifyYTiframeseektime('935')">0:15:35</a> buddy you have pioneers people you have  
<a onclick="modifyYTiframeseektime('938')">0:15:38</a> nothing when you have nothing and you  
<a onclick="modifyYTiframeseektime('940')">0:15:40</a> fight you claw your way to the top yeah  
<a onclick="modifyYTiframeseektime('942')">0:15:42</a> and they can have something and your son  
<a onclick="modifyYTiframeseektime('945')">0:15:45</a> he saw you work hard you're the first  
<a onclick="modifyYTiframeseektime('947')">0:15:47</a> generation of workers we came to the  
<a onclick="modifyYTiframeseektime('949')">0:15:49</a> land and you boil the land  
<a onclick="modifyYTiframeseektime('950')">0:15:50</a> you built in your son he saw but your  
<a onclick="modifyYTiframeseektime('954')">0:15:54</a> son's life is better than life because  
<a onclick="modifyYTiframeseektime('956')">0:15:56</a> now I have things to give you I had  
<a onclick="modifyYTiframeseektime('959')">0:15:59</a> nothing  
<a onclick="modifyYTiframeseektime('959')">0:15:59</a> and tomorrow when I die you have  
<a onclick="modifyYTiframeseektime('961')">0:16:01</a> inheritance so you started higher than  
<a onclick="modifyYTiframeseektime('963')">0:16:03</a> me I boosted you up and then your son is  
<a onclick="modifyYTiframeseektime('966')">0:16:06</a> gonna see you you didn't work as hard  
<a onclick="modifyYTiframeseektime('969')">0:16:09</a> but you have so much and the third child  
<a onclick="modifyYTiframeseektime('972')">0:16:12</a> is even Richard and he got just God he  
<a onclick="modifyYTiframeseektime('976')">0:16:16</a> didn't work  
<a onclick="modifyYTiframeseektime('976')">0:16:16</a> he just got an okay takes more than  
<a onclick="modifyYTiframeseektime('980')">0:16:20</a> three generations to speak but there's a  
<a onclick="modifyYTiframeseektime('981')">0:16:21</a> generation they're spoiled  
<a onclick="modifyYTiframeseektime('983')">0:16:23</a> that's what he just said look Society is  
<a onclick="modifyYTiframeseektime('985')">0:16:25</a> making us more and more spoiled because  
<a onclick="modifyYTiframeseektime('987')">0:16:27</a> the hand-me-downs are coming then one  
<a onclick="modifyYTiframeseektime('988')">0:16:28</a> day you're a hot captain on a silk  
<a onclick="modifyYTiframeseektime('990')">0:16:30</a> pillow but the world out there is too  
<a onclick="modifyYTiframeseektime('994')">0:16:34</a> hard for you so you have this deep  
<a onclick="modifyYTiframeseektime('996')">0:16:36</a> insecurity you can't go out there in the  
<a onclick="modifyYTiframeseektime('998')">0:16:38</a> world and get a kill and begin back home  
<a onclick="modifyYTiframeseektime('1001')">0:16:41</a> for us to me you've the comforts of the  
<a onclick="modifyYTiframeseektime('1004')">0:16:44</a> world and I can give you many example  
<a onclick="modifyYTiframeseektime('1006')">0:16:46</a> stories men the comforts of the world  
<a onclick="modifyYTiframeseektime('1011')">0:16:51</a> have become a prison to you so now when  
<a onclick="modifyYTiframeseektime('1014')">0:16:54</a> you mean I said I felt my kids my wife  
<a onclick="modifyYTiframeseektime('1016')">0:16:56</a> what I never want to be soft to be the  
<a onclick="modifyYTiframeseektime('1019')">0:16:59</a> guy who just tells people what to do but  
<a onclick="modifyYTiframeseektime('1021')">0:17:01</a> I can't do it too  
<a onclick="modifyYTiframeseektime('1022')">0:17:02</a> I fear one day I'm gonna become old and  
<a onclick="modifyYTiframeseektime('1024')">0:17:04</a> I have to become sightline but then I'm  
<a onclick="modifyYTiframeseektime('1028')">0:17:08</a> gonna feel softer I don't want to be the  
<a onclick="modifyYTiframeseektime('1031')">0:17:11</a> guy on the pillows people think being  
<a onclick="modifyYTiframeseektime('1034')">0:17:14</a> born in abundance money  
<a onclick="modifyYTiframeseektime('1039')">0:17:19</a> bless it can be because should be a  
<a onclick="modifyYTiframeseektime('1041')">0:17:21</a> curse to have everything so I mean  
<a onclick="modifyYTiframeseektime('1045')">0:17:25</a> there's so much to know about raising a  
<a onclick="modifyYTiframeseektime('1047')">0:17:27</a> healthy human being so you're saying  
<a onclick="modifyYTiframeseektime('1049')">0:17:29</a> bravery true bravery because the thing  
<a onclick="modifyYTiframeseektime('1056')">0:17:36</a> is people can act confident but they're  
<a onclick="modifyYTiframeseektime('1058')">0:17:38</a> masking a layer of insecurity this is  
<a onclick="modifyYTiframeseektime('1061')">0:17:41</a> common the key right strong with the  
<a onclick="modifyYTiframeseektime('1062')">0:17:42</a> keys yes blah so yeah I believe you're  
<a onclick="modifyYTiframeseektime('1068')">0:17:48</a> raising competencies if you want to make  
<a onclick="modifyYTiframeseektime('1070')">0:17:50</a> somebody help you happy raise their  
<a onclick="modifyYTiframeseektime('1072')">0:17:52</a> confidence imagine let me do a thought  
<a onclick="modifyYTiframeseektime('1075')">0:17:55</a> experiment imagine I could survive in  
<a onclick="modifyYTiframeseektime('1078')">0:17:58</a> the wild right now perfectly  
<a onclick="modifyYTiframeseektime('1081')">0:18:01</a> tomorrow the government's froze your  
<a onclick="modifyYTiframeseektime('1083')">0:18:03</a> bank account sheet chart at the home  
<a onclick="modifyYTiframeseektime('1085')">0:18:05</a> throughout in the street  
<a onclick="modifyYTiframeseektime('1087')">0:18:07</a> seek you out of it you would even sweat  
<a onclick="modifyYTiframeseektime('1090')">0:18:10</a> one visa  
<a onclick="modifyYTiframeseektime('1090')">0:18:10</a> why I remember a story about a bourbon  
<a onclick="modifyYTiframeseektime('1094')">0:18:14</a> what the greatest burglar of all time  
<a onclick="modifyYTiframeseektime('1095')">0:18:15</a> the greatest burglar well that was if I  
<a onclick="modifyYTiframeseektime('1098')">0:18:18</a> remember correctly  
<a onclick="modifyYTiframeseektime('1099')">0:18:19</a> Henry Manchester I was a young kid when  
<a onclick="modifyYTiframeseektime('1101')">0:18:21</a> I heard his story I watched a  
<a onclick="modifyYTiframeseektime('1102')">0:18:22</a> documentary I could have beat the  
<a onclick="modifyYTiframeseektime('1104')">0:18:24</a> confidence it's my hybrid 14 years he's  
<a onclick="modifyYTiframeseektime('1107')">0:18:27</a> robbing banks and then stole over said  
<a onclick="modifyYTiframeseektime('1109')">0:18:29</a> everybody's robbing everybody  
<a onclick="modifyYTiframeseektime('1111')">0:18:31</a> they call him the rooftop burglar it  
<a onclick="modifyYTiframeseektime('1113')">0:18:33</a> would make a hole in the roof stop read  
<a onclick="modifyYTiframeseektime('1115')">0:18:35</a> the manual of alarm  
<a onclick="modifyYTiframeseektime('1116')">0:18:36</a> this is disabled a large untouchable is  
<a onclick="modifyYTiframeseektime('1119')">0:18:39</a> that one day they caught him and he  
<a onclick="modifyYTiframeseektime('1121')">0:18:41</a> confess to other crimes they're like you  
<a onclick="modifyYTiframeseektime('1123')">0:18:43</a> confess all the credit  
<a onclick="modifyYTiframeseektime('1124')">0:18:44</a> I did all those burglaries you want my  
<a onclick="modifyYTiframeseektime('1126')">0:18:46</a> things when they put him in jail he was  
<a onclick="modifyYTiframeseektime('1129')">0:18:49</a> so smart he got out of the jail like he  
<a onclick="modifyYTiframeseektime('1131')">0:18:51</a> was so confident that's why he had  
<a onclick="modifyYTiframeseektime('1133')">0:18:53</a> extremely he was a genius  
<a onclick="modifyYTiframeseektime('1135')">0:18:55</a> well I he was a genius at the end that  
<a onclick="modifyYTiframeseektime('1137')">0:18:57</a> I'm getting caught because he fell in  
<a onclick="modifyYTiframeseektime('1138')">0:18:58</a> love with a girl the girl called him to  
<a onclick="modifyYTiframeseektime('1139')">0:18:59</a> call the cops like it was an emotion we  
<a onclick="modifyYTiframeseektime('1142')">0:19:02</a> had higher Q but not equal intelligence  
<a onclick="modifyYTiframeseektime('1147')">0:19:07</a> 0 IQ huge but you see yes I remember  
<a onclick="modifyYTiframeseektime('1150')">0:19:10</a> watching that documentary his confidence  
<a onclick="modifyYTiframeseektime('1152')">0:19:12</a> was incredible yeah but it can't even  
<a onclick="modifyYTiframeseektime('1154')">0:19:14</a> hold them in the prison so this this  
<a onclick="modifyYTiframeseektime('1157')">0:19:17</a> confidence comes from legitimately  
<a onclick="modifyYTiframeseektime('1160')">0:19:20</a> developing your skill that's why I told  
<a onclick="modifyYTiframeseektime('1161')">0:19:21</a> you no oh yes I've reached thousands of  
<a onclick="modifyYTiframeseektime('1164')">0:19:24</a> young men I was incursion to exploit the  
<a onclick="modifyYTiframeseektime('1168')">0:19:28</a> tempature God give you a potential out  
<a onclick="modifyYTiframeseektime('1170')">0:19:30</a> there to learn to think to study our  
<a onclick="modifyYTiframeseektime('1173')">0:19:33</a> creature to be exploited to get you  
<a onclick="modifyYTiframeseektime('1175')">0:19:35</a> that's what the professor plan will come  
<a onclick="modifyYTiframeseektime('1177')">0:19:37</a> son from the cuts he said you know take  
<a onclick="modifyYTiframeseektime('1180')">0:19:40</a> five little pipe  
<a onclick="modifyYTiframeseektime('1188')">0:19:48</a> was it take like the treasures of five  
<a onclick="modifyYTiframeseektime('1191')">0:19:51</a> days before pockets I said one of the  
<a onclick="modifyYTiframeseektime('1193')">0:19:53</a> three centers help before illness comes  
<a onclick="modifyYTiframeseektime('1197')">0:19:57</a> before old age puzzle people take a  
<a onclick="modifyYTiframeseektime('1209')">0:20:09</a> little bit people sometimes forget that  
<a onclick="modifyYTiframeseektime('1216')">0:20:16</a> being physically emotionally  
<a onclick="modifyYTiframeseektime('1218')">0:20:18</a> in fact the choice it's also a very  
<a onclick="modifyYTiframeseektime('1221')">0:20:21</a> thing he would really functioning in  
<a onclick="modifyYTiframeseektime('1224')">0:20:24</a> life so thanks my that was really good  
<a onclick="modifyYTiframeseektime('1227')">0:20:27</a> advice  
<a onclick="modifyYTiframeseektime('1227')">0:20:27</a> now obviously YouTube channel what you  
<a onclick="modifyYTiframeseektime('1231')">0:20:31</a> do like tutorials and stuff like that  
<a onclick="modifyYTiframeseektime('1233')">0:20:33</a> it's cool Tristar Tristar gym which is  
<a onclick="modifyYTiframeseektime('1237')">0:20:37</a> FG my husband Thomas great great spires  
<a onclick="modifyYTiframeseektime('1239')">0:20:39</a> really have  
<a onclick="modifyYTiframeseektime('1244')">0:20:44</a> so anyone who wants to to go on there  
<a onclick="modifyYTiframeseektime('1247')">0:20:47</a> and to watch those videos was really  
<a onclick="modifyYTiframeseektime('1249')">0:20:49</a> very very beneficial you have to go into  
<a onclick="modifyYTiframeseektime('1252')">0:20:52</a> more efficient into what we've got kind  
<a onclick="modifyYTiframeseektime('1254')">0:20:54</a> of similar discussion today so that's  
<a onclick="modifyYTiframeseektime('1257')">0:20:57</a> also on there there's never been a  
<a onclick="modifyYTiframeseektime('1269')">0:21:09</a> golden age in science greater than the  
<a onclick="modifyYTiframeseektime('1274')">0:21:14</a> Golden Age of Islam during the Golden  
<a onclick="modifyYTiframeseektime('1275')">0:21:15</a> Age of Islam was the Golden Age of  
<a onclick="modifyYTiframeseektime('1278')">0:21:18</a> science there's never been a greater  
<a onclick="modifyYTiframeseektime('1279')">0:21:19</a> golden age before or after he says it in  
<a onclick="modifyYTiframeseektime('1281')">0:21:21</a> his speech even if it's who says that  
<a onclick="modifyYTiframeseektime('1282')">0:21:22</a> was his name Neil deGrasse Tyson  
<a onclick="modifyYTiframeseektime('1284')">0:21:24</a> where does he say he says it no more of  
<a onclick="modifyYTiframeseektime('1287')">0:21:27</a> his lecture a lot of it is very open  
<a onclick="modifyYTiframeseektime('1289')">0:21:29</a> about in on stasis book that the stars  
<a onclick="modifyYTiframeseektime('1291')">0:21:31</a> are Arabic names why do you think that  
<a onclick="modifyYTiframeseektime('1293')">0:21:33</a> is because the Arabs were very stron  
<a onclick="modifyYTiframeseektime('1295')">0:21:35</a> averse and they push science to the to  
<a onclick="modifyYTiframeseektime('1297')">0:21:37</a> the greatest degree but when the  
<a onclick="modifyYTiframeseektime('1300')">0:21:40</a> Mongolians came and burned our libraries  
<a onclick="modifyYTiframeseektime('1301')">0:21:41</a> and crushed the Muslim empire  
<a onclick="modifyYTiframeseektime('1305')">0:21:45</a> the blowback was hey we have to go make  
<a onclick="modifyYTiframeseektime('1307')">0:21:47</a> it right with Allah we're too much in  
<a onclick="modifyYTiframeseektime('1309')">0:21:49</a> the dunya know I get a lot experience  
<a onclick="modifyYTiframeseektime('1312')">0:21:52</a> this is what I've understood  
<a onclick="modifyYTiframeseektime('1316')">0:21:56</a> from the  
<a onclick="modifyYTiframeseektime('1318')">0:21:58</a> trying to accumulate what happened to  
<a onclick="modifyYTiframeseektime('1320')">0:22:00</a> the Golden Age  
<a onclick="modifyYTiframeseektime('1322')">0:22:02</a> is that the blowback was look we've got  
<a onclick="modifyYTiframeseektime('1323')">0:22:03</a> so much fascinated by the dunya  
<a onclick="modifyYTiframeseektime('1328')">0:22:08</a> so they remember Isaiah we started to  
<a onclick="modifyYTiframeseektime('1330')">0:22:10</a> tell them look come back to the D like  
<a onclick="modifyYTiframeseektime('1331')">0:22:11</a> we don't go back to this is our this is  
<a onclick="modifyYTiframeseektime('1333')">0:22:13</a> our our our  
<a onclick="modifyYTiframeseektime('1336')">0:22:16</a> our is how they interpret  
<a onclick="modifyYTiframeseektime('1339')">0:22:19</a> this was because don't forget this is  
<a onclick="modifyYTiframeseektime('1342')">0:22:22</a> obviously was it wasn't in Congress who  
<a onclick="modifyYTiframeseektime('1344')">0:22:24</a> like who is Manson but supposedly  
<a onclick="modifyYTiframeseektime('1347')">0:22:27</a> according to you sir Kylie says when  
<a onclick="modifyYTiframeseektime('1349')">0:22:29</a> Genghis Khan King to the boss a camera  
<a onclick="modifyYTiframeseektime('1351')">0:22:31</a> which one there was a prominent Moscow  
<a onclick="modifyYTiframeseektime('1353')">0:22:33</a> famous Marcello and I 15 ft which I'm  
<a onclick="modifyYTiframeseektime('1355')">0:22:35</a> Yura cut that Allah I'm here since I'm  
<a onclick="modifyYTiframeseektime('1358')">0:22:38</a> here because for your punishment of your  
<a onclick="modifyYTiframeseektime('1360')">0:22:40</a> sins source people he understood the  
<a onclick="modifyYTiframeseektime('1363')">0:22:43</a> Dean right no man could do anything to  
<a onclick="modifyYTiframeseektime('1364')">0:22:44</a> you if Allah doesn't alive so he started  
<a onclick="modifyYTiframeseektime('1366')">0:22:46</a> that the laws allow you to do this you  
<a onclick="modifyYTiframeseektime('1367')">0:22:47</a> because of your sins  
<a onclick="modifyYTiframeseektime('1369')">0:22:49</a> so in Imam has a nice time from what I  
<a onclick="modifyYTiframeseektime('1371')">0:22:51</a> understand  
<a onclick="modifyYTiframeseektime('1373')">0:22:53</a> in Missouri from one else that was very  
<a onclick="modifyYTiframeseektime('1374')">0:22:54</a> Pro philosophy and through learning and  
<a onclick="modifyYTiframeseektime('1377')">0:22:57</a> through science in San  
<a onclick="modifyYTiframeseektime('1380')">0:23:00</a> however he was also trying to bring them  
<a onclick="modifyYTiframeseektime('1382')">0:23:02</a> back to spirituality  
<a onclick="modifyYTiframeseektime('1384')">0:23:04</a> as this may be the case but it's time  
<a onclick="modifyYTiframeseektime('1387')">0:23:07</a> for a recovery you know it's time for us  
<a onclick="modifyYTiframeseektime('1389')">0:23:09</a> to start being more  
<a onclick="modifyYTiframeseektime('1391')">0:23:11</a> however we are I mean you know people  
<a onclick="modifyYTiframeseektime('1393')">0:23:13</a> you know  
<a onclick="modifyYTiframeseektime('1395')">0:23:15</a> it doesn't mean because you're religious  
<a onclick="modifyYTiframeseektime('1397')">0:23:17</a> can't be scientific it doesn't because  
<a onclick="modifyYTiframeseektime('1398')">0:23:18</a> your scientific teller  
<a onclick="modifyYTiframeseektime('1399')">0:23:19</a> they're not exclusive shouldn't be  
</details>