# Muslim Surprises Presenter With... (2017-11-02)

<iframe loading='lazy' src='https://www.youtube.com/embed/VtiHUsuKhlE'></iframe>

## Description

Radio station presenter interviews Muslim about some of the controversial issues regarding Islam and the media. An interesting and fruitful discussion is had with interesting and surprising comments made.

Full video 
https://youtu.be/v4KiiFMFQJg

## Summary of [Muslim Surprises Presenter With...](https://www.youtube.com/watch?v=VtiHUsuKhlE)


*<span style="color:red; font-size:125%">This summary is AI generated - there may be inaccuracies</span>. [](/)*

### <a onclick="modifyYTiframeseektime('0')">00:00:00</a> - <a onclick="modifyYTiframeseektime('1500')">00:25:00</a>

discusses how some Muslims view suicide bombers as martyrs, and how this understanding of suicide bombing can be used to justify the act. points out that many civilians are also casualties of suicide bombings, and that there should be a concordance or explanation next to verses in the Quran that refer to suicide bombing.

**<a onclick="modifyYTiframeseektime('0')">00:00:00</a>* Discusses how Muslim Surprises Presenter with money, citizenship, and platforms, and how the Muslim world is in a post-colonial reality. Rabia discusses how some verses in the Quran are foundational to a specific interpretation, and how some people may misinterpret these verses.
* **<a onclick="modifyYTiframeseektime('300')">00:05:00</a>** The presenter discusses how some Muslims believe that it is okay to fight back against those who attack them, even if it means killing them. The presenter also points out that this is not the same as terrorism, which is a term that is typically applied to violence perpetrated against civilians for political purposes.
* **<a onclick="modifyYTiframeseektime('600')">00:10:00</a>** This Muslim surprises presenter with his dedication to not killing another person over their blood or great property and land. He goes on to say that this same dedication applies to people in the West, and that the same Western Colonial person that really the same the Western Colonial master came to your parents country, justification of cultural superiority, justified killing based on culture, and taking of young girls as slave girls in the Old Testament, is still at it today, trying to go into the Middle East from an unnecessary Africa.
* **<a onclick="modifyYTiframeseektime('900')">00:15:00</a>* Discusses how some Muslims view suicide bombers as martyrs, and how this understanding of suicide bombing can be used to justify the act. points out that many civilians are also casualties of suicide bombings, and that there should be a concordance or explanation next to verses in the Quran that refer to suicide bombing.
* **<a onclick="modifyYTiframeseektime('1200')">00:20:00</a>** The presenter discusses how Islam comes with a message of submission to the creator, as well as an evidence base of rational evidences to support the Quran's authenticity. The presenter points out how post-colonial realities still exist today, and how those living in them are constantly being infiltrated and controlled by outside forces.
* **<a onclick="modifyYTiframeseektime('1500')">00:25:00</a>** The presenter discusses the differences between Muslim and non-Muslim civilizations, and how Muslim empires were more successful than non-Muslim ones. He also points out that Western technological progress has been negative overall, and that African traditions have taken up most of the scientific progress.

<details><summary><h2>Full transcript with timestamps: CLICK TO EXPAND</h2></summary>

<a onclick="modifyYTiframeseektime('0')">0:00:00</a> finances play a massive part in this but  
<a onclick="modifyYTiframeseektime('3')">0:00:03</a> let's say go peace-loving or the ones  
<a onclick="modifyYTiframeseektime('7')">0:00:07</a> that follow Islam in the correct fashion  
<a onclick="modifyYTiframeseektime('9')">0:00:09</a> let's say in Saudi Arabia they they have  
<a onclick="modifyYTiframeseektime('12')">0:00:12</a> billions why would they not use that -  
<a onclick="modifyYTiframeseektime('15')">0:00:15</a> instead of giving citizenship - oh yeah  
<a onclick="modifyYTiframeseektime('19')">0:00:19</a> but still and now there's a massive  
<a onclick="modifyYTiframeseektime('21')">0:00:21</a> platform for us knowing certainty has  
<a onclick="modifyYTiframeseektime('23')">0:00:23</a> sadly Rabia citizenship yeah tell me  
<a onclick="modifyYTiframeseektime('25')">0:00:25</a> baby they'd have platforms their biggest  
<a onclick="modifyYTiframeseektime('27')">0:00:27</a> biggest channel anti-derivative arabiya  
<a onclick="modifyYTiframeseektime('29')">0:00:29</a> and it's almost you could say liberal  
<a onclick="modifyYTiframeseektime('31')">0:00:31</a> channel yes it's a liberal channel in  
<a onclick="modifyYTiframeseektime('33')">0:00:33</a> the sense they promote you could cook  
<a onclick="modifyYTiframeseektime('35')">0:00:35</a> you could say you could argue a twist  
<a onclick="modifyYTiframeseektime('37')">0:00:37</a> and liberal narrative so this is ironic  
<a onclick="modifyYTiframeseektime('41')">0:00:41</a> in a sense that the biggest channels in  
<a onclick="modifyYTiframeseektime('43')">0:00:43</a> the Muslim old are promoting the same  
<a onclick="modifyYTiframeseektime('45')">0:00:45</a> things that the Westeros and that's due  
<a onclick="modifyYTiframeseektime('49')">0:00:49</a> to the ties of money oil possibly it  
<a onclick="modifyYTiframeseektime('52')">0:00:52</a> could be but a generous Jew - I think a  
<a onclick="modifyYTiframeseektime('55')">0:00:55</a> post-colonial reality now Saudi Arabia  
<a onclick="modifyYTiframeseektime('58')">0:00:58</a> itself is used as an example wasn't  
<a onclick="modifyYTiframeseektime('60')">0:01:00</a> colonized by the British yeah  
<a onclick="modifyYTiframeseektime('61')">0:01:01</a> but the majority of countries in North  
<a onclick="modifyYTiframeseektime('64')">0:01:04</a> Africa yeah including memory foam which  
<a onclick="modifyYTiframeseektime('67')">0:01:07</a> is Egypt were cordoned : Viper Egypt  
<a onclick="modifyYTiframeseektime('69')">0:01:09</a> there by Britain or France yeah so that  
<a onclick="modifyYTiframeseektime('73')">0:01:13</a> mentality obviously the African  
<a onclick="modifyYTiframeseektime('74')">0:01:14</a> countries themselves and have the other  
<a onclick="modifyYTiframeseektime('76')">0:01:16</a> effects of that muscular in the reality  
<a onclick="modifyYTiframeseektime('78')">0:01:18</a> which is why you'll find in a lot of our  
<a onclick="modifyYTiframeseektime('80')">0:01:20</a> countries you're getting African would  
<a onclick="modifyYTiframeseektime('84')">0:01:24</a> you make it more like Caribbean yeah so  
<a onclick="modifyYTiframeseektime('86')">0:01:26</a> what you're originally African let's say  
<a onclick="modifyYTiframeseektime('89')">0:01:29</a> yeah that reality has spillover to  
<a onclick="modifyYTiframeseektime('92')">0:01:32</a> seeing things like hey no fair and  
<a onclick="modifyYTiframeseektime('94')">0:01:34</a> lovely fur lovely the white is something  
<a onclick="modifyYTiframeseektime('97')">0:01:37</a> that wipe the skin basically so it  
<a onclick="modifyYTiframeseektime('99')">0:01:39</a> ranges now the post-colonial reality  
<a onclick="modifyYTiframeseektime('101')">0:01:41</a> ranges from finding Beauty aesthetically  
<a onclick="modifyYTiframeseektime('104')">0:01:44</a> have seen more white it's actually being  
<a onclick="modifyYTiframeseektime('107')">0:01:47</a> an agreement with everything the white  
<a onclick="modifyYTiframeseektime('108')">0:01:48</a> colonial post-colonial master tells you  
<a onclick="modifyYTiframeseektime('110')">0:01:50</a> that is true and we don't know how much  
<a onclick="modifyYTiframeseektime('112')">0:01:52</a> this has encroached us this is important  
<a onclick="modifyYTiframeseektime('114')">0:01:54</a> so much that now every question you  
<a onclick="modifyYTiframeseektime('116')">0:01:56</a> asked I promise you is going to have a  
<a onclick="modifyYTiframeseektime('118')">0:01:58</a> Western colonial post-colonial slum and  
<a onclick="modifyYTiframeseektime('122')">0:02:02</a> that's orient what you're going to say  
<a onclick="modifyYTiframeseektime('126')">0:02:06</a> we could even like before when you  
<a onclick="modifyYTiframeseektime('130')">0:02:10</a> before you came in Linda but you had no  
<a onclick="modifyYTiframeseektime('133')">0:02:13</a> crane here and we've been quoted by why  
<a onclick="modifyYTiframeseektime('135')">0:02:15</a> does it have I think like you said how  
<a onclick="modifyYTiframeseektime('137')">0:02:17</a> the Western media portrayal is why thank  
<a onclick="modifyYTiframeseektime('140')">0:02:20</a> you  
<a onclick="modifyYTiframeseektime('141')">0:02:21</a> this is it they should be the way to  
<a onclick="modifyYTiframeseektime('142')">0:02:22</a> lighten that disease look hat because  
<a onclick="modifyYTiframeseektime('148')">0:02:28</a> someone asked me platform and I'll put  
<a onclick="modifyYTiframeseektime('150')">0:02:30</a> you up with regards to the Koala vigil  
<a onclick="modifyYTiframeseektime('154')">0:02:34</a> smart broom when it's my recognizes a  
<a onclick="modifyYTiframeseektime('162')">0:02:42</a> smart man that makes you smart so  
<a onclick="modifyYTiframeseektime('163')">0:02:43</a> telling someone said that there's  
<a onclick="modifyYTiframeseektime('170')">0:02:50</a> certain parts of the Quran as well as  
<a onclick="modifyYTiframeseektime('172')">0:02:52</a> the Bible updated so when I raised  
<a onclick="modifyYTiframeseektime('175')">0:02:55</a> points surrounding violence yeah waging  
<a onclick="modifyYTiframeseektime('178')">0:02:58</a> a holy war G has once again the  
<a onclick="modifyYTiframeseektime('181')">0:03:01</a> post-colonial start as slot spots there  
<a onclick="modifyYTiframeseektime('183')">0:03:03</a> what the narratives us having with that  
<a onclick="modifyYTiframeseektime('186')">0:03:06</a> Polly is important to duty before I'm  
<a onclick="modifyYTiframeseektime('190')">0:03:10</a> going to be asking questions that people  
<a onclick="modifyYTiframeseektime('191')">0:03:11</a> ask me as well I'm practicing Muslim so  
<a onclick="modifyYTiframeseektime('196')">0:03:16</a> I just want to know when looking at the  
<a onclick="modifyYTiframeseektime('199')">0:03:19</a> Quran yeah how can you and see what is  
<a onclick="modifyYTiframeseektime('202')">0:03:22</a> metaphorically may be the case and what  
<a onclick="modifyYTiframeseektime('205')">0:03:25</a> it's not like before you go ok chapter 3  
<a onclick="modifyYTiframeseektime('208')">0:03:28</a> verse 7 who told you that it tells you  
<a onclick="modifyYTiframeseektime('209')">0:03:29</a> that you that submit away mmm what  
<a onclick="modifyYTiframeseektime('211')">0:03:31</a> commands will hum no Lupita not too  
<a onclick="modifyYTiframeseektime('214')">0:03:34</a> shabby and so since that this book has  
<a onclick="modifyYTiframeseektime('216')">0:03:36</a> in it  
<a onclick="modifyYTiframeseektime('217')">0:03:37</a> verses which are basically ambiguous and  
<a onclick="modifyYTiframeseektime('220')">0:03:40</a> other verses which are foundational to  
<a onclick="modifyYTiframeseektime('222')">0:03:42</a> no I'm reading the Quran how am I  
<a onclick="modifyYTiframeseektime('228')">0:03:48</a> supposed to know each one so one good  
<a onclick="modifyYTiframeseektime('230')">0:03:50</a> question as we push into the answer to a  
<a onclick="modifyYTiframeseektime('231')">0:03:51</a> question is that  
<a onclick="modifyYTiframeseektime('232')">0:03:52</a> those verses which speak in a way which  
<a onclick="modifyYTiframeseektime('235')">0:03:55</a> can only be interpreted in a way in one  
<a onclick="modifyYTiframeseektime('237')">0:03:57</a> way are the foundational verses for  
<a onclick="modifyYTiframeseektime('239')">0:03:59</a> example chapter 112  
<a onclick="modifyYTiframeseektime('242')">0:04:02</a> verse 1 to 4 put although I say DS Allah  
<a onclick="modifyYTiframeseektime('245')">0:04:05</a> will block one and only  
<a onclick="modifyYTiframeseektime('246')">0:04:06</a> so we believe in only one but did normal  
<a onclick="modifyYTiframeseektime('248')">0:04:08</a> so that's going to come out saying  
<a onclick="modifyYTiframeseektime('250')">0:04:10</a> two girls or three a Christian might say  
<a onclick="modifyYTiframeseektime('252')">0:04:12</a> I believe in the Trinity three one or  
<a onclick="modifyYTiframeseektime('253')">0:04:13</a> three  
<a onclick="modifyYTiframeseektime('254')">0:04:14</a> we don't have that we don't have that  
<a onclick="modifyYTiframeseektime('255')">0:04:15</a> confusion so we say football all I have  
<a onclick="modifyYTiframeseektime('258')">0:04:18</a> is a foundational verse no one can come  
<a onclick="modifyYTiframeseektime('259')">0:04:19</a> back and say look hold on if you don't  
<a onclick="modifyYTiframeseektime('261')">0:04:21</a> believe in blue velour head or we have a  
<a onclick="modifyYTiframeseektime('264')">0:04:24</a> different interpretation no one in the  
<a onclick="modifyYTiframeseektime('265')">0:04:25</a> history of Islam and I said that so  
<a onclick="modifyYTiframeseektime('266')">0:04:26</a> that's the foundational but that's not a  
<a onclick="modifyYTiframeseektime('268')">0:04:28</a> metaphoric verse and cannot be subject  
<a onclick="modifyYTiframeseektime('270')">0:04:30</a> to a different interpretation but then I  
<a onclick="modifyYTiframeseektime('273')">0:04:33</a> think you're coming from a place of  
<a onclick="modifyYTiframeseektime('274')">0:04:34</a> being educated because there's many  
<a onclick="modifyYTiframeseektime('277')">0:04:37</a> people that I feel whether that be in  
<a onclick="modifyYTiframeseektime('280')">0:04:40</a> rural places of the Middle East or even  
<a onclick="modifyYTiframeseektime('282')">0:04:42</a> here where they're looking for belonging  
<a onclick="modifyYTiframeseektime('284')">0:04:44</a> and they attach themselves to certain  
<a onclick="modifyYTiframeseektime('285')">0:04:45</a> groups how would they how you eloquently  
<a onclick="modifyYTiframeseektime('288')">0:04:48</a> explained that how would they know that  
<a onclick="modifyYTiframeseektime('290')">0:04:50</a> for example someone's message me saying  
<a onclick="modifyYTiframeseektime('291')">0:04:51</a> in the Quran it says and kill them  
<a onclick="modifyYTiframeseektime('293')">0:04:53</a> wherever you find them and turn them out  
<a onclick="modifyYTiframeseektime('295')">0:04:55</a> from where they have turned to you out  
<a onclick="modifyYTiframeseektime('297')">0:04:57</a> okay that's slow so let me let me  
<a onclick="modifyYTiframeseektime('299')">0:04:59</a> quickly answer both question okay boy  
<a onclick="modifyYTiframeseektime('301')">0:05:01</a> you've what you've posited in the first  
<a onclick="modifyYTiframeseektime('303')">0:05:03</a> instance is called an argument ignorance  
<a onclick="modifyYTiframeseektime('305')">0:05:05</a> it's a fallacy in logic okay so if you  
<a onclick="modifyYTiframeseektime('307')">0:05:07</a> don't know something exists it doesn't  
<a onclick="modifyYTiframeseektime('308')">0:05:08</a> mean as pulse so if I say okay this  
<a onclick="modifyYTiframeseektime('311')">0:05:11</a> person doesn't know it therefore it must  
<a onclick="modifyYTiframeseektime('312')">0:05:12</a> be false that's called an argument from  
<a onclick="modifyYTiframeseektime('314')">0:05:14</a> ignorance if I say as was the case that  
<a onclick="modifyYTiframeseektime('316')">0:05:16</a> Neptune doesn't exist because I can't  
<a onclick="modifyYTiframeseektime('318')">0:05:18</a> see it it couldn't see Neptune at one  
<a onclick="modifyYTiframeseektime('319')">0:05:19</a> point yeah and they have to kind of find  
<a onclick="modifyYTiframeseektime('322')">0:05:22</a> that you the time Neptune after you they  
<a onclick="modifyYTiframeseektime('324')">0:05:24</a> have to track your based on planet it  
<a onclick="modifyYTiframeseektime('326')">0:05:26</a> doesn't exist therefore it doesn't exist  
<a onclick="modifyYTiframeseektime('328')">0:05:28</a> that's an island with midnight so for my  
<a onclick="modifyYTiframeseektime('329')">0:05:29</a> logical perspective it doesn't carry any  
<a onclick="modifyYTiframeseektime('331')">0:05:31</a> weight people don't understand things  
<a onclick="modifyYTiframeseektime('333')">0:05:33</a> they have to get educated that Francis  
<a onclick="modifyYTiframeseektime('334')">0:05:34</a> Bacon said knowledge is power it's not  
<a onclick="modifyYTiframeseektime('336')">0:05:36</a> my problem but there is an excuse in  
<a onclick="modifyYTiframeseektime('339')">0:05:39</a> this time moving that it would be nice  
<a onclick="modifyYTiframeseektime('340')">0:05:40</a> how it is more like someone ignorant God  
<a onclick="modifyYTiframeseektime('342')">0:05:42</a> will take care of them  
<a onclick="modifyYTiframeseektime('343')">0:05:43</a> accordance with the knowledge that they  
<a onclick="modifyYTiframeseektime('345')">0:05:45</a> know yeah not even in Christianity if  
<a onclick="modifyYTiframeseektime('347')">0:05:47</a> there's life you will be treated on on  
<a onclick="modifyYTiframeseektime('349')">0:05:49</a> the basis of what light you know you  
<a onclick="modifyYTiframeseektime('352')">0:05:52</a> don't know how ever so let's look at in  
<a onclick="modifyYTiframeseektime('356')">0:05:56</a> the most basic way possible you have  
<a onclick="modifyYTiframeseektime('358')">0:05:58</a> young people that I've seen that many of  
<a onclick="modifyYTiframeseektime('360')">0:06:00</a> their family members are being killed  
<a onclick="modifyYTiframeseektime('363')">0:06:03</a> due to Western performing some program  
<a onclick="modifyYTiframeseektime('365')">0:06:05</a> and then they need whether it's ignorant  
<a onclick="modifyYTiframeseektime('368')">0:06:08</a> individual that's parts of group and  
<a onclick="modifyYTiframeseektime('369')">0:06:09</a> says listen the Quran justifies us going  
<a onclick="modifyYTiframeseektime('372')">0:06:12</a> and killing these people that are  
<a onclick="modifyYTiframeseektime('373')">0:06:13</a> killing us or as answers  
<a onclick="modifyYTiframeseektime('374')">0:06:14</a> now you've measured is why so let me  
<a onclick="modifyYTiframeseektime('375')">0:06:15</a> then meet let me put this in the  
<a onclick="modifyYTiframeseektime('377')">0:06:17</a> simplest way possible  
<a onclick="modifyYTiframeseektime('378')">0:06:18</a> try and make it yeah certifiable next up  
<a onclick="modifyYTiframeseektime('381')">0:06:21</a> blame  
<a onclick="modifyYTiframeseektime('381')">0:06:21</a> okay so the blog has in it like you just  
<a onclick="modifyYTiframeseektime('384')">0:06:24</a> mentioned chapter nine verse five yeah  
<a onclick="modifyYTiframeseektime('386')">0:06:26</a> what you just mentioned before kill the  
<a onclick="modifyYTiframeseektime('388')">0:06:28</a> women to climb up laughs kind of you can  
<a onclick="modifyYTiframeseektime('390')">0:06:30</a> you can say that right so you just rich  
<a onclick="modifyYTiframeseektime('391')">0:06:31</a> in top of the mango spike okay that's  
<a onclick="modifyYTiframeseektime('394')">0:06:34</a> the problem because why you know mention  
<a onclick="modifyYTiframeseektime('395')">0:06:35</a> in chapter 9 verse 1 2 3 4 5 & 6 then 7  
<a onclick="modifyYTiframeseektime('399')">0:06:39</a> but their decibel reading out of context  
<a onclick="modifyYTiframeseektime('401')">0:06:41</a> yeah so chapter 9 verses 1 to 4  
<a onclick="modifyYTiframeseektime('404')">0:06:44</a> stipulates that there was some kind of  
<a onclick="modifyYTiframeseektime('405')">0:06:45</a> agreement between the Muslims and at  
<a onclick="modifyYTiframeseektime('408')">0:06:48</a> that particular time the pagan Arabs  
<a onclick="modifyYTiframeseektime('409')">0:06:49</a> they animated an agreement  
<a onclick="modifyYTiframeseektime('411')">0:06:51</a> what's up muzzle taken have a guitar  
<a onclick="modifyYTiframeseektime('413')">0:06:53</a> absorb a bullet in so at the time of  
<a onclick="modifyYTiframeseektime('416')">0:06:56</a> Muhammad Ali Kemp's know people that I  
<a onclick="modifyYTiframeseektime('418')">0:06:58</a> just really become Muslim and people  
<a onclick="modifyYTiframeseektime('421')">0:07:01</a> that stayed upon the religion of their  
<a onclick="modifyYTiframeseektime('422')">0:07:02</a> forefathers and believed in a  
<a onclick="modifyYTiframeseektime('423')">0:07:03</a> multiplicity of gods  
<a onclick="modifyYTiframeseektime('424')">0:07:04</a> ok so they believed in different statute  
<a onclick="modifyYTiframeseektime('427')">0:07:07</a> goes that they used to worship yeah so  
<a onclick="modifyYTiframeseektime('429')">0:07:09</a> there was an agreement between those two  
<a onclick="modifyYTiframeseektime('431')">0:07:11</a> camps between the Muslims and the pagan  
<a onclick="modifyYTiframeseektime('434')">0:07:14</a> Arabs now the first verse of chapter 9  
<a onclick="modifyYTiframeseektime('436')">0:07:16</a> which is possible to tell ba and the  
<a onclick="modifyYTiframeseektime('438')">0:07:18</a> Quran says that they're basically that  
<a onclick="modifyYTiframeseektime('440')">0:07:20</a> they have these pagan Arabs have not the  
<a onclick="modifyYTiframeseektime('444')">0:07:24</a> agreement has been hoping that taken  
<a onclick="modifyYTiframeseektime('447')">0:07:27</a> care of in other words that they have  
<a onclick="modifyYTiframeseektime('450')">0:07:30</a> betrayed the agreement then it continues  
<a onclick="modifyYTiframeseektime('453')">0:07:33</a> talking about what you should do it says  
<a onclick="modifyYTiframeseektime('455')">0:07:35</a> find that what you kill them when you  
<a onclick="modifyYTiframeseektime('457')">0:07:37</a> find them etc talking about in the  
<a onclick="modifyYTiframeseektime('460')">0:07:40</a> context of war is now at war has been  
<a onclick="modifyYTiframeseektime('462')">0:07:42</a> issued just like in any international  
<a onclick="modifyYTiframeseektime('464')">0:07:44</a> relationship where you have a treaty  
<a onclick="modifyYTiframeseektime('467')">0:07:47</a> that's I'm gay it was look my treaty  
<a onclick="modifyYTiframeseektime('470')">0:07:50</a> that signed international relations  
<a onclick="modifyYTiframeseektime('472')">0:07:52</a> perspective that mountains been broken  
<a onclick="modifyYTiframeseektime('474')">0:07:54</a> and now one party has the right to  
<a onclick="modifyYTiframeseektime('476')">0:07:56</a> offend it's also offend will defend  
<a onclick="modifyYTiframeseektime('479')">0:07:59</a> itself on the offending pipe yeah here  
<a onclick="modifyYTiframeseektime('481')">0:08:01</a> is in chapter 2 verse 1 mighty he says  
<a onclick="modifyYTiframeseektime('484')">0:08:04</a> well positively dealing you but even  
<a onclick="modifyYTiframeseektime('486')">0:08:06</a> when I tell him in a lie that you do not  
<a onclick="modifyYTiframeseektime('489')">0:08:09</a> see that fight those people who fight  
<a onclick="modifyYTiframeseektime('491')">0:08:11</a> you and don't go across the bounds was  
<a onclick="modifyYTiframeseektime('493')">0:08:13</a> God doesn't like those who go across the  
<a onclick="modifyYTiframeseektime('495')">0:08:15</a> bow so that still relate to you today  
<a onclick="modifyYTiframeseektime('497')">0:08:17</a> find those people who'd want you  
<a onclick="modifyYTiframeseektime('501')">0:08:21</a> basically Islamic law pacifistic  
<a onclick="modifyYTiframeseektime('504')">0:08:24</a> so we're not saying that you know the  
<a onclick="modifyYTiframeseektime('508')">0:08:28</a> idea of sorry but I'm gonna do the  
<a onclick="modifyYTiframeseektime('510')">0:08:30</a> crudest those terms are not fencing  
<a onclick="modifyYTiframeseektime('511')">0:08:31</a> nationís but the idea of slapping  
<a onclick="modifyYTiframeseektime('514')">0:08:34</a> someone that she can give them the other  
<a onclick="modifyYTiframeseektime('515')">0:08:35</a> G we don't have that idea  
<a onclick="modifyYTiframeseektime('518')">0:08:38</a> we have if someone's like to to cheat  
<a onclick="modifyYTiframeseektime('520')">0:08:40</a> you are allowed to slap them back on  
<a onclick="modifyYTiframeseektime('522')">0:08:42</a> their cheek okay II understand so if  
<a onclick="modifyYTiframeseektime('525')">0:08:45</a> someone attacks me on the road yeah yeah  
<a onclick="modifyYTiframeseektime('527')">0:08:47</a> I'm allowed to fight them so then would  
<a onclick="modifyYTiframeseektime('529')">0:08:49</a> you say basically will defense so from  
<a onclick="modifyYTiframeseektime('532')">0:08:52</a> an international relations respect yeah  
<a onclick="modifyYTiframeseektime('534')">0:08:54</a> different country is being attacked they  
<a onclick="modifyYTiframeseektime('537')">0:08:57</a> must fight back it's not about that they  
<a onclick="modifyYTiframeseektime('539')">0:08:59</a> should fight back will they have the  
<a onclick="modifyYTiframeseektime('541')">0:09:01</a> option of like they actually you have to  
<a onclick="modifyYTiframeseektime('543')">0:09:03</a> do this them to fight back after me oh  
<a onclick="modifyYTiframeseektime('544')">0:09:04</a> so you're saying that it's okay for them  
<a onclick="modifyYTiframeseektime('547')">0:09:07</a> to defend themselves to defend so what's  
<a onclick="modifyYTiframeseektime('551')">0:09:11</a> happening now what okay so terrorism is  
<a onclick="modifyYTiframeseektime('556')">0:09:16</a> basically you said that everything that  
<a onclick="modifyYTiframeseektime('560')">0:09:20</a> we think about is from a Western  
<a onclick="modifyYTiframeseektime('564')">0:09:24</a> ideology  
<a onclick="modifyYTiframeseektime('565')">0:09:25</a> however Zi and myself have spoken about  
<a onclick="modifyYTiframeseektime('568')">0:09:28</a> this in the past  
<a onclick="modifyYTiframeseektime('569')">0:09:29</a> we're on air management I'm not going to  
<a onclick="modifyYTiframeseektime('573')">0:09:33</a> justify your however I can understand  
<a onclick="modifyYTiframeseektime('576')">0:09:36</a> that  
<a onclick="modifyYTiframeseektime('576')">0:09:36</a> I see could continuous bomb into my  
<a onclick="modifyYTiframeseektime('579')">0:09:39</a> country yeah  
<a onclick="modifyYTiframeseektime('580')">0:09:40</a> if that means a couple casualties hey  
<a onclick="modifyYTiframeseektime('582')">0:09:42</a> how will you see it from the outside as  
<a onclick="modifyYTiframeseektime('585')">0:09:45</a> necessarily a bad thing in a way the  
<a onclick="modifyYTiframeseektime('586')">0:09:46</a> West is asking for it to a degree but is  
<a onclick="modifyYTiframeseektime('589')">0:09:49</a> it justified then yeah as much as a part  
<a onclick="modifyYTiframeseektime('591')">0:09:51</a> of it so it's not just look it's written  
<a onclick="modifyYTiframeseektime('594')">0:09:54</a> may their chapter 5 verse 32 it says in  
<a onclick="modifyYTiframeseektime('598')">0:09:58</a> them under the knife whoever kills one  
<a onclick="modifyYTiframeseektime('600')">0:10:00</a> person devotedness  
<a onclick="modifyYTiframeseektime('601')">0:10:01</a> for not killing another person over  
<a onclick="modifyYTiframeseektime('603')">0:10:03</a> their blood or great property and land  
<a onclick="modifyYTiframeseektime('606')">0:10:06</a> again hunted and I said you know it's as  
<a onclick="modifyYTiframeseektime('608')">0:10:08</a> if if humanity so killing one innocent  
<a onclick="modifyYTiframeseektime('611')">0:10:11</a> person or the lady who's little almost  
<a onclick="modifyYTiframeseektime('612')">0:10:12</a> there was kidding  
<a onclick="modifyYTiframeseektime('613')">0:10:13</a> like they love you right that's a very  
<a onclick="modifyYTiframeseektime('614')">0:10:14</a> famous person underline the point big is  
<a onclick="modifyYTiframeseektime('617')">0:10:17</a> this you just have to think yeah the  
<a onclick="modifyYTiframeseektime('622')">0:10:22</a> difference is this if they're combatants  
<a onclick="modifyYTiframeseektime('624')">0:10:24</a> and text you that is a combatant someone  
<a onclick="modifyYTiframeseektime('627')">0:10:27</a> who wants to fight you whereas if it's a  
<a onclick="modifyYTiframeseektime('630')">0:10:30</a> non-combatants someone who isn't  
<a onclick="modifyYTiframeseektime('632')">0:10:32</a> the Prophet told us you're not allowed  
<a onclick="modifyYTiframeseektime('634')">0:10:34</a> to kill categories of people of them are  
<a onclick="modifyYTiframeseektime('636')">0:10:36</a> they're non-combative women children  
<a onclick="modifyYTiframeseektime('638')">0:10:38</a> even most priests you don't have to cut  
<a onclick="modifyYTiframeseektime('640')">0:10:40</a> down trees very stupid question yeah  
<a onclick="modifyYTiframeseektime('643')">0:10:43</a> well it's not a play it's very stupid  
<a onclick="modifyYTiframeseektime('645')">0:10:45</a> by the way this is not something  
<a onclick="modifyYTiframeseektime('646')">0:10:46</a> controversial the only reason and I'll  
<a onclick="modifyYTiframeseektime('648')">0:10:48</a> tell you once again the only reason why  
<a onclick="modifyYTiframeseektime('650')">0:10:50</a> you asking this question is actually is  
<a onclick="modifyYTiframeseektime('652')">0:10:52</a> sad enough and funny enough I'll tell  
<a onclick="modifyYTiframeseektime('654')">0:10:54</a> you why I said nothing was funny it's  
<a onclick="modifyYTiframeseektime('656')">0:10:56</a> sad because actually the same reason  
<a onclick="modifyYTiframeseektime('658')">0:10:58</a> you're asking it is because the same  
<a onclick="modifyYTiframeseektime('661')">0:11:01</a> Western colonial person that really the  
<a onclick="modifyYTiframeseektime('665')">0:11:05</a> same the Western colonial master came to  
<a onclick="modifyYTiframeseektime('667')">0:11:07</a> your parents country yeah yeah and they  
<a onclick="modifyYTiframeseektime('671')">0:11:11</a> did that because they justified cultural  
<a onclick="modifyYTiframeseektime('673')">0:11:13</a> superiority they said we are culturally  
<a onclick="modifyYTiframeseektime('675')">0:11:15</a> we are culturally superior to your  
<a onclick="modifyYTiframeseektime('677')">0:11:17</a> parents yeah they have been traveled  
<a onclick="modifyYTiframeseektime('680')">0:11:20</a> religion and the African tribal systems  
<a onclick="modifyYTiframeseektime('682')">0:11:22</a> are inferior systems and therefore we we  
<a onclick="modifyYTiframeseektime('687')">0:11:27</a> have a culture which we need to give to  
<a onclick="modifyYTiframeseektime('689')">0:11:29</a> these individuals push revolution pour  
<a onclick="modifyYTiframeseektime('691')">0:11:31</a> culture I think the same reason now now  
<a onclick="modifyYTiframeseektime('694')">0:11:34</a> it's being moved from the corner  
<a onclick="modifyYTiframeseektime('695')">0:11:35</a> colonial landscape to a hospital or  
<a onclick="modifyYTiframeseektime('697')">0:11:37</a> landscape you still have the equatorial  
<a onclick="modifyYTiframeseektime('699')">0:11:39</a> region Wanek western USA that is  
<a onclick="modifyYTiframeseektime('703')">0:11:43</a> attempting now to go into the Middle  
<a onclick="modifyYTiframeseektime('704')">0:11:44</a> East from an unnecessary Africa as much  
<a onclick="modifyYTiframeseektime('706')">0:11:46</a> as much for colonial economic reasons so  
<a onclick="modifyYTiframeseektime('710')">0:11:50</a> they've had to invent a narrative this  
<a onclick="modifyYTiframeseektime('712')">0:11:52</a> narrative is a narrative of Samuel  
<a onclick="modifyYTiframeseektime('714')">0:11:54</a> Huntington a clash of civilizations and  
<a onclick="modifyYTiframeseektime('717')">0:11:57</a> a civilization a civilizational clash  
<a onclick="modifyYTiframeseektime('719')">0:11:59</a> between the Muslims and the Western  
<a onclick="modifyYTiframeseektime('721')">0:12:01</a> Hemisphere that narrative now which has  
<a onclick="modifyYTiframeseektime('723')">0:12:03</a> been invented yeah people are starting  
<a onclick="modifyYTiframeseektime('726')">0:12:06</a> to believe in it because they're not  
<a onclick="modifyYTiframeseektime('727')">0:12:07</a> critical thinkers they don't thinking  
<a onclick="modifyYTiframeseektime('728')">0:12:08</a> okay well actually what is special about  
<a onclick="modifyYTiframeseektime('730')">0:12:10</a> this version of Quran because actually  
<a onclick="modifyYTiframeseektime('733')">0:12:13</a> if you look at the Old Testament book of  
<a onclick="modifyYTiframeseektime('734')">0:12:14</a> numbers 31 18 it says not only did you  
<a onclick="modifyYTiframeseektime('738')">0:12:18</a> kill the enemy but you take the young  
<a onclick="modifyYTiframeseektime('740')">0:12:20</a> girls as slave girls and in the Old  
<a onclick="modifyYTiframeseektime('742')">0:12:22</a> Testament right yeah so in other words  
<a onclick="modifyYTiframeseektime('744')">0:12:24</a> prepubescence you take them you slightly  
<a onclick="modifyYTiframeseektime('746')">0:12:26</a> enslave them you rape them you can rate  
<a onclick="modifyYTiframeseektime('748')">0:12:28</a> them almost almost it also says that  
<a onclick="modifyYTiframeseektime('750')">0:12:30</a> most of the commentators have said that  
<a onclick="modifyYTiframeseektime('753')">0:12:33</a> no one I had not come across one single  
<a onclick="modifyYTiframeseektime('755')">0:12:35</a> common to our country that has actually  
<a onclick="modifyYTiframeseektime('757')">0:12:37</a> differed from that understanding that  
<a onclick="modifyYTiframeseektime('760')">0:12:40</a> literally comes  
<a onclick="modifyYTiframeseektime('762')">0:12:42</a> so why don't we talk about that verse  
<a onclick="modifyYTiframeseektime('763')">0:12:43</a> because that was actually more dramatic  
<a onclick="modifyYTiframeseektime('765')">0:12:45</a> than any person that we're on didn't  
<a onclick="modifyYTiframeseektime('767')">0:12:47</a> fight but then when when we look at the  
<a onclick="modifyYTiframeseektime('770')">0:12:50</a> Old Testament oftentimes that the death  
<a onclick="modifyYTiframeseektime('774')">0:12:54</a> of Jesus does away with a lot of the old  
<a onclick="modifyYTiframeseektime('776')">0:12:56</a> practices in the Old Testament so the  
<a onclick="modifyYTiframeseektime('778')">0:12:58</a> New Testament so Matthew so it says  
<a onclick="modifyYTiframeseektime('781')">0:13:01</a> Jesus says I'm not coming to do it  
<a onclick="modifyYTiframeseektime('782')">0:13:02</a> without comfort affirm them what is the  
<a onclick="modifyYTiframeseektime('784')">0:13:04</a> word firmly this is a discussion but the  
<a onclick="modifyYTiframeseektime('787')">0:13:07</a> thing is as follows if Jesus Christ is  
<a onclick="modifyYTiframeseektime('789')">0:13:09</a> God if Jesus Christ is God that is the  
<a onclick="modifyYTiframeseektime('792')">0:13:12</a> Nicene Creed through 2580 understanding  
<a onclick="modifyYTiframeseektime('795')">0:13:15</a> of Christianity yeah he is the author of  
<a onclick="modifyYTiframeseektime('798')">0:13:18</a> the Old Testament because the Father the  
<a onclick="modifyYTiframeseektime('800')">0:13:20</a> sign of the Holy Spirit or one therefore  
<a onclick="modifyYTiframeseektime('802')">0:13:22</a> those texts induce wanna be like  
<a onclick="modifyYTiframeseektime('804')">0:13:24</a> Deuteronomy chapter 21 verse 10 Jude  
<a onclick="modifyYTiframeseektime('807')">0:13:27</a> numbers chapter 31 verse 18 and other  
<a onclick="modifyYTiframeseektime('810')">0:13:30</a> verses which are very very much  
<a onclick="modifyYTiframeseektime('812')">0:13:32</a> you know vicious you could say very  
<a onclick="modifyYTiframeseektime('815')">0:13:35</a> vicious these are not only authored by  
<a onclick="modifyYTiframeseektime('819')">0:13:39</a> Jesus Christ but they sanctioned by him  
<a onclick="modifyYTiframeseektime('821')">0:13:41</a> himself because he is God so if the  
<a onclick="modifyYTiframeseektime('824')">0:13:44</a> argument is that the Old Testament is  
<a onclick="modifyYTiframeseektime('826')">0:13:46</a> the New Testament yeah well Jesus must  
<a onclick="modifyYTiframeseektime('829')">0:13:49</a> have read all of the Old Testament  
<a onclick="modifyYTiframeseektime('831')">0:13:51</a> because he's God yeah a lot of questions  
<a onclick="modifyYTiframeseektime('834')">0:13:54</a> are even after you move across the  
<a onclick="modifyYTiframeseektime('835')">0:13:55</a> Trinity but coming back to offending  
<a onclick="modifyYTiframeseektime('837')">0:13:57</a> your country you'll say that in terms of  
<a onclick="modifyYTiframeseektime('841')">0:14:01</a> you can defend yourself if there's a  
<a onclick="modifyYTiframeseektime('843')">0:14:03</a> combatant but my thing is how the  
<a onclick="modifyYTiframeseektime('845')">0:14:05</a> Western world is set up in invading many  
<a onclick="modifyYTiframeseektime('849')">0:14:09</a> countries how would you then defend your  
<a onclick="modifyYTiframeseektime('852')">0:14:12</a> country because you're not gonna go to  
<a onclick="modifyYTiframeseektime('854')">0:14:14</a> if you know Trump sits down to either  
<a onclick="modifyYTiframeseektime('856')">0:14:16</a> male for example if thou do you defend  
<a onclick="modifyYTiframeseektime('861')">0:14:21</a> if you're seated right if you live in  
<a onclick="modifyYTiframeseektime('864')">0:14:24</a> those countries and people come into  
<a onclick="modifyYTiframeseektime('865')">0:14:25</a> those countries trying to attack you and  
<a onclick="modifyYTiframeseektime('868')">0:14:28</a> take your sovereignty away as a  
<a onclick="modifyYTiframeseektime('869')">0:14:29</a> independent autonomous human being you  
<a onclick="modifyYTiframeseektime('872')">0:14:32</a> do the same thing as the Kenyans did  
<a onclick="modifyYTiframeseektime('873')">0:14:33</a> when the British came to invade you  
<a onclick="modifyYTiframeseektime('875')">0:14:35</a> fight back and it would have been cool  
<a onclick="modifyYTiframeseektime('877')">0:14:37</a> terrorism as we call flying through your  
<a onclick="modifyYTiframeseektime('879')">0:14:39</a> land  
<a onclick="modifyYTiframeseektime('879')">0:14:39</a> exactly okay so Susan so my thing is  
<a onclick="modifyYTiframeseektime('882')">0:14:42</a> because we know now that technology is  
<a onclick="modifyYTiframeseektime('885')">0:14:45</a> so advanced from when the Quran was  
<a onclick="modifyYTiframeseektime('888')">0:14:48</a> written then it's not as simple assault  
<a onclick="modifyYTiframeseektime('891')">0:14:51</a> as running into York  
<a onclick="modifyYTiframeseektime('892')">0:14:52</a> tree and you having a what punch others  
<a onclick="modifyYTiframeseektime('896')">0:14:56</a> whether the same time she blows it up up  
<a onclick="modifyYTiframeseektime('899')">0:14:59</a> in fact doesn't have these because I had  
<a onclick="modifyYTiframeseektime('901')">0:15:01</a> these with the Prophet Muhammad they had  
<a onclick="modifyYTiframeseektime('903')">0:15:03</a> these is a saying of the Prophet  
<a onclick="modifyYTiframeseektime('904')">0:15:04</a> Muhammad everyone that kills themselves  
<a onclick="modifyYTiframeseektime('906')">0:15:06</a> just generally speaking suicide that  
<a onclick="modifyYTiframeseektime('908')">0:15:08</a> they will continue to do that in the  
<a onclick="modifyYTiframeseektime('909')">0:15:09</a> Hellfire to themselves okay so why do  
<a onclick="modifyYTiframeseektime('911')">0:15:11</a> these suicide bombers do that whenever  
<a onclick="modifyYTiframeseektime('914')">0:15:14</a> they get any prom they must be getting  
<a onclick="modifyYTiframeseektime('916')">0:15:16</a> education how about that because  
<a onclick="modifyYTiframeseektime('922')">0:15:22</a> displace our market itself accommodation  
<a onclick="modifyYTiframeseektime('925')">0:15:25</a> but let me go make thick they get a look  
<a onclick="modifyYTiframeseektime('928')">0:15:28</a> around because of those salespeople okay  
<a onclick="modifyYTiframeseektime('930')">0:15:30</a> which act will says be modest is that  
<a onclick="modifyYTiframeseektime('933')">0:15:33</a> were are in a way which two groups of  
<a onclick="modifyYTiframeseektime('937')">0:15:37</a> people have bought into one of them are  
<a onclick="modifyYTiframeseektime('940')">0:15:40</a> these fabricators and the other one are  
<a onclick="modifyYTiframeseektime('942')">0:15:42</a> the terrorists the Islamic haters and  
<a onclick="modifyYTiframeseektime('945')">0:15:45</a> the terrorists have the same  
<a onclick="modifyYTiframeseektime('946')">0:15:46</a> understanding the Quran yeah both of  
<a onclick="modifyYTiframeseektime('950')">0:15:50</a> those have that understanding that  
<a onclick="modifyYTiframeseektime('953')">0:15:53</a> actually those verses which are talking  
<a onclick="modifyYTiframeseektime('956')">0:15:56</a> about war and clearly in the context a  
<a onclick="modifyYTiframeseektime('958')">0:15:58</a> regime of so the table chapter 9 verse 1  
<a onclick="modifyYTiframeseektime('959')">0:15:59</a> to 5 is talking about international  
<a onclick="modifyYTiframeseektime('962')">0:16:02</a> relations nations treaties etc those  
<a onclick="modifyYTiframeseektime('966')">0:16:06</a> sales people which Apple sales people  
<a onclick="modifyYTiframeseektime('967')">0:16:07</a> they've been able to manipulate the text  
<a onclick="modifyYTiframeseektime('970')">0:16:10</a> using hermeneutical domestics and x2  
<a onclick="modifyYTiframeseektime('972')">0:16:12</a> Jesus can you tell me what the truth is  
<a onclick="modifyYTiframeseektime('974')">0:16:14</a> in English stop I'm Dracula where the  
<a onclick="modifyYTiframeseektime('976')">0:16:16</a> Saudi verses there are so many verses  
<a onclick="modifyYTiframeseektime('980')">0:16:20</a> there's nothing in the Quran you know  
<a onclick="modifyYTiframeseektime('983')">0:16:23</a> I'm saying in the quran verse says you  
<a onclick="modifyYTiframeseektime('984')">0:16:24</a> can fight the enemy okay the enemy who  
<a onclick="modifyYTiframeseektime('987')">0:16:27</a> is the enemy now basically what I'm  
<a onclick="modifyYTiframeseektime('990')">0:16:30</a> saying to you is the Islamic haters and  
<a onclick="modifyYTiframeseektime('993')">0:16:33</a> the terrorists have the same  
<a onclick="modifyYTiframeseektime('995')">0:16:35</a> understanding of who the enemy is  
<a onclick="modifyYTiframeseektime('996')">0:16:36</a> okay who is actually any civilian any  
<a onclick="modifyYTiframeseektime('999')">0:16:39</a> civilian why are they the enemy the way  
<a onclick="modifyYTiframeseektime('1002')">0:16:42</a> they justify it is as follows and they  
<a onclick="modifyYTiframeseektime('1003')">0:16:43</a> put inoperative and people the general  
<a onclick="modifyYTiframeseektime('1007')">0:16:47</a> populace yeah they actually endorse yes  
<a onclick="modifyYTiframeseektime('1011')">0:16:51</a> the leaders yeah this is the way many of  
<a onclick="modifyYTiframeseektime('1014')">0:16:54</a> the sales people they they actually  
<a onclick="modifyYTiframeseektime('1018')">0:16:58</a> pitch it they say that they endorsed  
<a onclick="modifyYTiframeseektime('1019')">0:16:59</a> their leaders  
<a onclick="modifyYTiframeseektime('1020')">0:17:00</a> therefore they are responsible for what  
<a onclick="modifyYTiframeseektime('1023')">0:17:03</a> their leaders from a foreign policy  
<a onclick="modifyYTiframeseektime('1024')">0:17:04</a> perspective  
<a onclick="modifyYTiframeseektime('1026')">0:17:06</a> say and do so if they're if they're  
<a onclick="modifyYTiframeseektime('1029')">0:17:09</a> leaders black in 2003 say let's go to  
<a onclick="modifyYTiframeseektime('1031')">0:17:11</a> Iraq and kill hundred thirty three  
<a onclick="modifyYTiframeseektime('1033')">0:17:13</a> thousand people yeah then they are  
<a onclick="modifyYTiframeseektime('1034')">0:17:14</a> responsible that's how they justify it  
<a onclick="modifyYTiframeseektime('1037')">0:17:17</a> so now they're able to shift the blame  
<a onclick="modifyYTiframeseektime('1039')">0:17:19</a> from the politician and the military  
<a onclick="modifyYTiframeseektime('1042')">0:17:22</a> complex to the general populace and  
<a onclick="modifyYTiframeseektime('1045')">0:17:25</a> therefore general populace blood becomes  
<a onclick="modifyYTiframeseektime('1047')">0:17:27</a> as you know as easy to get as the for  
<a onclick="modifyYTiframeseektime('1052')">0:17:32</a> example military only punishes blood so  
<a onclick="modifyYTiframeseektime('1055')">0:17:35</a> all the company Edison see a few people  
<a onclick="modifyYTiframeseektime('1058')">0:17:38</a> that want to cool in you can call it we  
<a onclick="modifyYTiframeseektime('1060')">0:17:40</a> have literally got half an hour left oh  
<a onclick="modifyYTiframeseektime('1061')">0:17:41</a> seven nine five one four nine seven  
<a onclick="modifyYTiframeseektime('1064')">0:17:44</a> eight seven eight  
<a onclick="modifyYTiframeseektime('1065')">0:17:45</a> you can call in speech and how many to  
<a onclick="modifyYTiframeseektime('1067')">0:17:47</a> answer your questions you've got you've  
<a onclick="modifyYTiframeseektime('1069')">0:17:49</a> got one guy do to start you're so strong  
<a onclick="modifyYTiframeseektime('1071')">0:17:51</a> outstanding tellin state poppies going  
<a onclick="modifyYTiframeseektime('1073')">0:17:53</a> in do you think you're right do you do  
<a onclick="modifyYTiframeseektime('1077')">0:17:57</a> you think that there should be a modern  
<a onclick="modifyYTiframeseektime('1080')">0:18:00</a> day writing of the put on because like  
<a onclick="modifyYTiframeseektime('1084')">0:18:04</a> you like you say that there are certain  
<a onclick="modifyYTiframeseektime('1086')">0:18:06</a> things that are taken out of context why  
<a onclick="modifyYTiframeseektime('1094')">0:18:14</a> should these people that I'm me okay  
<a onclick="modifyYTiframeseektime('1100')">0:18:20</a> that when I speak to them about  
<a onclick="modifyYTiframeseektime('1103')">0:18:23</a> capitalism or communism left-right  
<a onclick="modifyYTiframeseektime('1107')">0:18:27</a> colonialism they don't have Scooby they  
<a onclick="modifyYTiframeseektime('1110')">0:18:30</a> don't all that it's not taught in the  
<a onclick="modifyYTiframeseektime('1111')">0:18:31</a> schools properly unless you wanna study  
<a onclick="modifyYTiframeseektime('1113')">0:18:33</a> in university okay so when you have  
<a onclick="modifyYTiframeseektime('1116')">0:18:36</a> young let's say even young but when you  
<a onclick="modifyYTiframeseektime('1119')">0:18:39</a> have certain people that may go into  
<a onclick="modifyYTiframeseektime('1121')">0:18:41</a> prism and there's a brother William  
<a onclick="modifyYTiframeseektime('1122')">0:18:42</a> prism that's going to protect them they  
<a onclick="modifyYTiframeseektime('1125')">0:18:45</a> start reading the Quran they don't have  
<a onclick="modifyYTiframeseektime('1128')">0:18:48</a> the ingenuity or the education behind it  
<a onclick="modifyYTiframeseektime('1131')">0:18:51</a> to be able to contextualize business  
<a onclick="modifyYTiframeseektime('1132')">0:18:52</a> over good then that's why I'm saying  
<a onclick="modifyYTiframeseektime('1135')">0:18:55</a> should there be some sort of concordance  
<a onclick="modifyYTiframeseektime('1137')">0:18:57</a> or explanation next to these verses to  
<a onclick="modifyYTiframeseektime('1140')">0:19:00</a> state that this is what it actually  
<a onclick="modifyYTiframeseektime('1142')">0:19:02</a> means however if you read another person  
<a onclick="modifyYTiframeseektime('1144')">0:19:04</a> could look like it's contradictory but  
<a onclick="modifyYTiframeseektime('1147')">0:19:07</a> as usual by interpretation well I have  
<a onclick="modifyYTiframeseektime('1149')">0:19:09</a> the black sometimes the vial is got hurt  
<a onclick="modifyYTiframeseektime('1151')">0:19:11</a> so there's a dog this is not a lot of  
<a onclick="modifyYTiframeseektime('1154')">0:19:14</a> Muslims  
<a onclick="modifyYTiframeseektime('1158')">0:19:18</a> no it's Jesus is when scholars of the  
<a onclick="modifyYTiframeseektime('1161')">0:19:21</a> profile on the Bible or any religious  
<a onclick="modifyYTiframeseektime('1163')">0:19:23</a> texts and yeah they interpret it in  
<a onclick="modifyYTiframeseektime('1166')">0:19:26</a> accordance with language the lens that  
<a onclick="modifyYTiframeseektime('1168')">0:19:28</a> the events of good equal the Hermit  
<a onclick="modifyYTiframeseektime('1170')">0:19:30</a> useful approach musical yes will how  
<a onclick="modifyYTiframeseektime('1172')">0:19:32</a> musical approach so they use different  
<a onclick="modifyYTiframeseektime('1175')">0:19:35</a> tools to access the religious texts that  
<a onclick="modifyYTiframeseektime('1177')">0:19:37</a> is that's done everywhere that's done  
<a onclick="modifyYTiframeseektime('1179')">0:19:39</a> within Islam Christianity Judaism  
<a onclick="modifyYTiframeseektime('1180')">0:19:40</a> understand text Zone seven sex ok kill  
<a onclick="modifyYTiframeseektime('1183')">0:19:43</a> the Liberty is a lot small is called the  
<a onclick="modifyYTiframeseektime('1185')">0:19:45</a> her musical approach and people that are  
<a onclick="modifyYTiframeseektime('1187')">0:19:47</a> studying the Quran for the first time  
<a onclick="modifyYTiframeseektime('1189')">0:19:49</a> she view cookies which option that's a  
<a onclick="modifyYTiframeseektime('1191')">0:19:51</a> good point exactly so in other words  
<a onclick="modifyYTiframeseektime('1193')">0:19:53</a> what a young terrorist want to be looks  
<a onclick="modifyYTiframeseektime('1196')">0:19:56</a> at the exegesis yeah yeah and he and he  
<a onclick="modifyYTiframeseektime('1199')">0:19:59</a> realizes that the way he's interpreted  
<a onclick="modifyYTiframeseektime('1201')">0:20:01</a> the Quran is not in line with the  
<a onclick="modifyYTiframeseektime('1203')">0:20:03</a> classic interpretation from day one for  
<a onclick="modifyYTiframeseektime('1206')">0:20:06</a> the first person to according to my  
<a onclick="modifyYTiframeseektime('1208')">0:20:08</a> knowledge to to interpret the provider  
<a onclick="modifyYTiframeseektime('1210')">0:20:10</a> for a summer book ended poverty and 310  
<a onclick="modifyYTiframeseektime('1214')">0:20:14</a> aah yeah and then you have then you have  
<a onclick="modifyYTiframeseektime('1217')">0:20:17</a> someone like a wooded here  
<a onclick="modifyYTiframeseektime('1218')">0:20:18</a> very famous that's here or very famous  
<a onclick="modifyYTiframeseektime('1220')">0:20:20</a> into Jesus that was written in 774 aah  
<a onclick="modifyYTiframeseektime('1223')">0:20:23</a> and others like for example a seal to  
<a onclick="modifyYTiframeseektime('1226')">0:20:26</a> ruin my night one anyways all nine one  
<a onclick="modifyYTiframeseektime('1229')">0:20:29</a> one which is actually funny there's like  
<a onclick="modifyYTiframeseektime('1231')">0:20:31</a> nine eleven and well that's what he died  
<a onclick="modifyYTiframeseektime('1235')">0:20:35</a> at the point being is that these stuff  
<a onclick="modifyYTiframeseektime('1237')">0:20:37</a> the stuff is there the scholars have  
<a onclick="modifyYTiframeseektime('1239')">0:20:39</a> done the work all that needs to happen  
<a onclick="modifyYTiframeseektime('1241')">0:20:41</a> is that the young people that are  
<a onclick="modifyYTiframeseektime('1242')">0:20:42</a> persuaded yeah by the terroristic  
<a onclick="modifyYTiframeseektime('1245')">0:20:45</a> narrative which is actually in many ways  
<a onclick="modifyYTiframeseektime('1247')">0:20:47</a> similar to the anti slamming narrative  
<a onclick="modifyYTiframeseektime('1249')">0:20:49</a> or the same they should look at those  
<a onclick="modifyYTiframeseektime('1251')">0:20:51</a> things before making a judgment and when  
<a onclick="modifyYTiframeseektime('1255')">0:20:55</a> they look at it properly they will then  
<a onclick="modifyYTiframeseektime('1257')">0:20:57</a> see that actually what they mothers do  
<a onclick="modifyYTiframeseektime('1259')">0:20:59</a> the plan to be is different its  
<a onclick="modifyYTiframeseektime('1261')">0:21:01</a> disjointed from the way the classical  
<a onclick="modifyYTiframeseektime('1263')">0:21:03</a> scholars from day one have ever seen  
<a onclick="modifyYTiframeseektime('1265')">0:21:05</a> them so how do you feel about these  
<a onclick="modifyYTiframeseektime('1267')">0:21:07</a> canudas talking about or like this new  
<a onclick="modifyYTiframeseektime('1269')">0:21:09</a> trend of you know it's cool to be Muslim  
<a onclick="modifyYTiframeseektime('1271')">0:21:11</a> a lot of that I know a lot of pies it in  
<a onclick="modifyYTiframeseektime('1274')">0:21:14</a> Muslim and then with menu but it comes  
<a onclick="modifyYTiframeseektime('1276')">0:21:16</a> around to random their path being  
<a onclick="modifyYTiframeseektime('1277')">0:21:17</a> mothers to leave a club do whatever we  
<a onclick="modifyYTiframeseektime('1280')">0:21:20</a> do you think about this whole new wave  
<a onclick="modifyYTiframeseektime('1282')">0:21:22</a> or you know it's come to be over soon  
<a onclick="modifyYTiframeseektime('1283')">0:21:23</a> now  
<a onclick="modifyYTiframeseektime('1288')">0:21:28</a> look it's lemons is forest maybe just  
<a onclick="modifyYTiframeseektime('1289')">0:21:29</a> for people that don't know I mean to  
<a onclick="modifyYTiframeseektime('1291')">0:21:31</a> hear me talking a lot of answers like  
<a onclick="modifyYTiframeseektime('1293')">0:21:33</a> took a lot of big words I'm not trying  
<a onclick="modifyYTiframeseektime('1295')">0:21:35</a> to be I'm not trying to pontificate much  
<a onclick="modifyYTiframeseektime('1297')">0:21:37</a> so it's intimate but what do you do I'm  
<a onclick="modifyYTiframeseektime('1301')">0:21:41</a> Deidre okay what do you teach history ah  
<a onclick="modifyYTiframeseektime('1305')">0:21:45</a> okay make sense  
<a onclick="modifyYTiframeseektime('1307')">0:21:47</a> all right okay so basically what I was  
<a onclick="modifyYTiframeseektime('1309')">0:21:49</a> gonna say was this is that I'm saying  
<a onclick="modifyYTiframeseektime('1312')">0:21:52</a> I've always wanted to gain access to the  
<a onclick="modifyYTiframeseektime('1313')">0:21:53</a> dating right yeah which was all the time  
<a onclick="modifyYTiframeseektime('1315')">0:21:55</a> just talking musically important people  
<a onclick="modifyYTiframeseektime('1317')">0:21:57</a> are talking about going back to basics  
<a onclick="modifyYTiframeseektime('1320')">0:22:00</a> aslam generally just means submissions  
<a onclick="modifyYTiframeseektime('1322')">0:22:02</a> but we believe that Godfrey the  
<a onclick="modifyYTiframeseektime('1324')">0:22:04</a> university maintain the universe he's  
<a onclick="modifyYTiframeseektime('1327')">0:22:07</a> the sustainable things yeah and that he  
<a onclick="modifyYTiframeseektime('1330')">0:22:10</a> sent messengers of wartime to respected  
<a onclick="modifyYTiframeseektime('1333')">0:22:13</a> peoples and localities to respective  
<a onclick="modifyYTiframeseektime('1335')">0:22:15</a> civilizations to tell them of the  
<a onclick="modifyYTiframeseektime('1337')">0:22:17</a> message of God which is to worship God  
<a onclick="modifyYTiframeseektime('1340')">0:22:20</a> to believe in him as a pitcher as well  
<a onclick="modifyYTiframeseektime('1341')">0:22:21</a> but he said Abraham and Moses and Jesus  
<a onclick="modifyYTiframeseektime('1345')">0:22:25</a> a pond of Muhammad at the end yeah and  
<a onclick="modifyYTiframeseektime('1347')">0:22:27</a> he is the final prophet  
<a onclick="modifyYTiframeseektime('1348')">0:22:28</a> so that's foundationally wife's lamb is  
<a onclick="modifyYTiframeseektime('1350')">0:22:30</a> and two things that Islam comes room is  
<a onclick="modifyYTiframeseektime('1353')">0:22:33</a> that message which is a basic premise  
<a onclick="modifyYTiframeseektime('1356')">0:22:36</a> believe the brush equal one God not  
<a onclick="modifyYTiframeseektime('1358')">0:22:38</a> three-in-one not the Trinity we  
<a onclick="modifyYTiframeseektime('1360')">0:22:40</a> disassociate ourselves from the Trinity  
<a onclick="modifyYTiframeseektime('1362')">0:22:42</a> and not an atheistic obviously narrative  
<a onclick="modifyYTiframeseektime('1364')">0:22:44</a> but here we're talking about just  
<a onclick="modifyYTiframeseektime('1366')">0:22:46</a> believing in one altima entity creator  
<a onclick="modifyYTiframeseektime('1368')">0:22:48</a> that has fashioned users is the state of  
<a onclick="modifyYTiframeseektime('1371')">0:22:51</a> you and maintaining you in this universe  
<a onclick="modifyYTiframeseektime('1373')">0:22:53</a> cosmos where we are significant aspects  
<a onclick="modifyYTiframeseektime('1377')">0:22:57</a> of that cosmos and what you could submit  
<a onclick="modifyYTiframeseektime('1379')">0:22:59</a> to that all-knowing entity that's  
<a onclick="modifyYTiframeseektime('1381')">0:23:01</a> basically this time after we believe we  
<a onclick="modifyYTiframeseektime('1383')">0:23:03</a> have evidences to prove that this  
<a onclick="modifyYTiframeseektime('1385')">0:23:05</a> narrative is true so do two things come  
<a onclick="modifyYTiframeseektime('1388')">0:23:08</a> and hand and have the message in them  
<a onclick="modifyYTiframeseektime('1389')">0:23:09</a> and the evidence base and all the  
<a onclick="modifyYTiframeseektime('1392')">0:23:12</a> prophets have come to their respective  
<a onclick="modifyYTiframeseektime('1393')">0:23:13</a> people's they have come with two things  
<a onclick="modifyYTiframeseektime('1396')">0:23:16</a> they've come with a message of Islam  
<a onclick="modifyYTiframeseektime('1397')">0:23:17</a> which is to submit to the creator and  
<a onclick="modifyYTiframeseektime('1399')">0:23:19</a> they've also come with an evidence base  
<a onclick="modifyYTiframeseektime('1401')">0:23:21</a> which is a range of rational evidences  
<a onclick="modifyYTiframeseektime('1405')">0:23:25</a> given to human beings to prove that the  
<a onclick="modifyYTiframeseektime('1407')">0:23:27</a> message is true so Islam comes hand in  
<a onclick="modifyYTiframeseektime('1410')">0:23:30</a> hand and some of those evidences are  
<a onclick="modifyYTiframeseektime('1411')">0:23:31</a> things like religions of the future  
<a onclick="modifyYTiframeseektime('1412')">0:23:32</a> things like the fact that before are as  
<a onclick="modifyYTiframeseektime('1415')">0:23:35</a> you mentioned  
<a onclick="modifyYTiframeseektime('1415')">0:23:35</a> before is the only preserved ancient  
<a onclick="modifyYTiframeseektime('1418')">0:23:38</a> religious texts the things like the fact  
<a onclick="modifyYTiframeseektime('1420')">0:23:40</a> that you will not be able to find the  
<a onclick="modifyYTiframeseektime('1422')">0:23:42</a> contradiction of behind the fact that  
<a onclick="modifyYTiframeseektime('1423')">0:23:43</a> the Quran is inevitable in other words  
<a onclick="modifyYTiframeseektime('1425')">0:23:45</a> it can't be imitated except for except  
<a onclick="modifyYTiframeseektime('1427')">0:23:47</a> us so from that perspective we feel we  
<a onclick="modifyYTiframeseektime('1429')">0:23:49</a> have a rational coherent worldview we  
<a onclick="modifyYTiframeseektime('1433')">0:23:53</a> have a coherent if this is monarchy and  
<a onclick="modifyYTiframeseektime('1435')">0:23:55</a> commitment ology we don't need a Western  
<a onclick="modifyYTiframeseektime('1438')">0:23:58</a> post-colonial narrative to tell us  
<a onclick="modifyYTiframeseektime('1440')">0:24:00</a> basically what modernity should look  
<a onclick="modifyYTiframeseektime('1442')">0:24:02</a> like what more Tennessee is it's easy  
<a onclick="modifyYTiframeseektime('1444')">0:24:04</a> for you to say though coming from the  
<a onclick="modifyYTiframeseektime('1446')">0:24:06</a> point of black ascent and educated point  
<a onclick="modifyYTiframeseektime('1448')">0:24:08</a> where there's many generations here that  
<a onclick="modifyYTiframeseektime('1451')">0:24:11</a> they always nice however you want to  
<a onclick="modifyYTiframeseektime('1454')">0:24:14</a> trust it up that due to schooling do too  
<a onclick="modifyYTiframeseektime('1458')">0:24:18</a> maybe the watering down of how and by  
<a onclick="modifyYTiframeseektime('1460')">0:24:20</a> the way I'm not against everything in  
<a onclick="modifyYTiframeseektime('1462')">0:24:22</a> the West I'm just saying why don't our  
<a onclick="modifyYTiframeseektime('1463')">0:24:23</a> full procedures they can come from oh  
<a onclick="modifyYTiframeseektime('1465')">0:24:25</a> very well you're out okay what do you  
<a onclick="modifyYTiframeseektime('1468')">0:24:28</a> like you're an African woman and your  
<a onclick="modifyYTiframeseektime('1470')">0:24:30</a> forefathers yeah we're Africans in the  
<a onclick="modifyYTiframeseektime('1473')">0:24:33</a> continent of Africa  
<a onclick="modifyYTiframeseektime('1474')">0:24:34</a> you're full of other white men came to  
<a onclick="modifyYTiframeseektime('1477')">0:24:37</a> your country and took over part of your  
<a onclick="modifyYTiframeseektime('1480')">0:24:40</a> land yeah that's what happened now you  
<a onclick="modifyYTiframeseektime('1483')">0:24:43</a> might think they'll those days are done  
<a onclick="modifyYTiframeseektime('1484')">0:24:44</a> those days are not done those days up  
<a onclick="modifyYTiframeseektime('1487')">0:24:47</a> continue and so this very day there is a  
<a onclick="modifyYTiframeseektime('1490')">0:24:50</a> post-colonial reality the way you dress  
<a onclick="modifyYTiframeseektime('1493')">0:24:53</a> the way you told everything about You  
<a onclick="modifyYTiframeseektime('1495')">0:24:55</a> screams I have been infiltrated and core  
<a onclick="modifyYTiframeseektime('1498')">0:24:58</a> tonight once again just like my  
<a onclick="modifyYTiframeseektime('1500')">0:25:00</a> forefathers were the only difference is  
<a onclick="modifyYTiframeseektime('1502')">0:25:02</a> that they will go for young people and  
<a onclick="modifyYTiframeseektime('1507')">0:25:07</a> your forefathers were colonized by men  
<a onclick="modifyYTiframeseektime('1510')">0:25:10</a> on brown boo-boos whereas you guys are  
<a onclick="modifyYTiframeseektime('1513')">0:25:13</a> colonized on so it's zero but when ideas  
<a onclick="modifyYTiframeseektime('1516')">0:25:16</a> yeah ideologically or colonize you can't  
<a onclick="modifyYTiframeseektime('1519')">0:25:19</a> think outside of this box of modernity  
<a onclick="modifyYTiframeseektime('1522')">0:25:22</a> Western discourse where is the African  
<a onclick="modifyYTiframeseektime('1525')">0:25:25</a> tribalism increases believe it I need to  
<a onclick="modifyYTiframeseektime('1528')">0:25:28</a> know it's time at the only religion in  
<a onclick="modifyYTiframeseektime('1530')">0:25:30</a> Africa which is actually the choice of  
<a onclick="modifyYTiframeseektime('1531')">0:25:31</a> the what's happening I'm going to say  
<a onclick="modifyYTiframeseektime('1533')">0:25:33</a> that but where it's Lamas the only  
<a onclick="modifyYTiframeseektime('1535')">0:25:35</a> religion in Africa which is the choice  
<a onclick="modifyYTiframeseektime('1537')">0:25:37</a> of the word after if you father was a  
<a onclick="modifyYTiframeseektime('1540')">0:25:40</a> religion with all of them I love it more  
<a onclick="modifyYTiframeseektime('1543')">0:25:43</a> spiritualism yeah I agree  
<a onclick="modifyYTiframeseektime('1545')">0:25:45</a> if you look at the body Empire the  
<a onclick="modifyYTiframeseektime('1548')">0:25:48</a> songhai empire if you look at the and  
<a onclick="modifyYTiframeseektime('1550')">0:25:50</a> the Ghana Empire all of these empires  
<a onclick="modifyYTiframeseektime('1552')">0:25:52</a> were Muslim empires and what the choice  
<a onclick="modifyYTiframeseektime('1554')">0:25:54</a> of the African if you want to go before  
<a onclick="modifyYTiframeseektime('1556')">0:25:56</a> us about what was the choices the West  
<a onclick="modifyYTiframeseektime('1557')">0:25:57</a> African non colonized person will talk  
<a onclick="modifyYTiframeseektime('1561')">0:26:01</a> about slam back to what you said I think  
<a onclick="modifyYTiframeseektime('1566')">0:26:06</a> as you're speaking on those things let's  
<a onclick="modifyYTiframeseektime('1569')">0:26:09</a> set aside Islam for one second how do  
<a onclick="modifyYTiframeseektime('1573')">0:26:13</a> you teach young people coming up how to  
<a onclick="modifyYTiframeseektime('1577')">0:26:17</a> think  
<a onclick="modifyYTiframeseektime('1578')">0:26:18</a> avoid all Western why I'm not saying  
<a onclick="modifyYTiframeseektime('1582')">0:26:22</a> that these ideas westernized these are  
<a onclick="modifyYTiframeseektime('1584')">0:26:24</a> very valued I don't ever wanted to say  
<a onclick="modifyYTiframeseektime('1587')">0:26:27</a> like I say well saying is coming from  
<a onclick="modifyYTiframeseektime('1591')">0:26:31</a> Western views so my thing is nothing  
<a onclick="modifyYTiframeseektime('1593')">0:26:33</a> wrong with that to a degree it's  
<a onclick="modifyYTiframeseektime('1594')">0:26:34</a> important if you're saying that our  
<a onclick="modifyYTiframeseektime('1596')">0:26:36</a> forefathers are African yeah we should  
<a onclick="modifyYTiframeseektime('1598')">0:26:38</a> be able to switch and think I'm saved  
<a onclick="modifyYTiframeseektime('1601')">0:26:41</a> your father like the truth is devoid of  
<a onclick="modifyYTiframeseektime('1604')">0:26:44</a> color creed what I'm saying is this is  
<a onclick="modifyYTiframeseektime('1607')">0:26:47</a> that when we are told that the truth is  
<a onclick="modifyYTiframeseektime('1610')">0:26:50</a> the truth because the white man sin so  
<a onclick="modifyYTiframeseektime('1612')">0:26:52</a> the post-enlightenment experiences so  
<a onclick="modifyYTiframeseektime('1614')">0:26:54</a> the post-colonial experiences so that's  
<a onclick="modifyYTiframeseektime('1617')">0:26:57</a> where takes it back so why is that it is  
<a onclick="modifyYTiframeseektime('1618')">0:26:58</a> why don't we do that love your father's  
<a onclick="modifyYTiframeseektime('1622')">0:27:02</a> dead after Christian white that's what  
<a onclick="modifyYTiframeseektime('1625')">0:27:05</a> we did that I live mandela mandela why  
<a onclick="modifyYTiframeseektime('1627')">0:27:07</a> do you think mountain is not why do you  
<a onclick="modifyYTiframeseektime('1628')">0:27:08</a> think mile is mine these people are  
<a onclick="modifyYTiframeseektime('1631')">0:27:11</a> these three ends are the way they are  
<a onclick="modifyYTiframeseektime('1632')">0:27:12</a> because they ask why and then they are  
<a onclick="modifyYTiframeseektime('1635')">0:27:15</a> an innocent no when he realized that  
<a onclick="modifyYTiframeseektime('1637')">0:27:17</a> there are several times actually yeah  
<a onclick="modifyYTiframeseektime('1638')">0:27:18</a> they are white and they're not  
<a onclick="modifyYTiframeseektime('1641')">0:27:21</a> with the answer then they said no that's  
<a onclick="modifyYTiframeseektime('1643')">0:27:23</a> what made these people successful  
<a onclick="modifyYTiframeseektime('1645')">0:27:25</a> definitely opportunity well I'm saying  
<a onclick="modifyYTiframeseektime('1647')">0:27:27</a> is a lot Los Angeles throw the baby with  
<a onclick="modifyYTiframeseektime('1649')">0:27:29</a> the bath more I'm all say let's take  
<a onclick="modifyYTiframeseektime('1651')">0:27:31</a> away okay all of the West to accomplish  
<a onclick="modifyYTiframeseektime('1655')">0:27:35</a> new because let's be frank  
<a onclick="modifyYTiframeseektime('1656')">0:27:36</a> Western technological progress is bad  
<a onclick="modifyYTiframeseektime('1658')">0:27:38</a> and the majority of the world what's the  
<a onclick="modifyYTiframeseektime('1661')">0:27:41</a> scientific progress is that apparently  
<a onclick="modifyYTiframeseektime('1662')">0:27:42</a> need yeah it's been taken it's been  
<a onclick="modifyYTiframeseektime('1664')">0:27:44</a> inherited by the outer issues or by the  
<a onclick="modifyYTiframeseektime('1666')">0:27:46</a> Chinese revision or by the African  
<a onclick="modifyYTiframeseektime('1668')">0:27:48</a> tradition and it's been blow up on top  
<a onclick="modifyYTiframeseektime('1670')">0:27:50</a> Minitab can take it that's a good thing  
<a onclick="modifyYTiframeseektime('1673')">0:27:53</a> there are lots of things like  
<a onclick="modifyYTiframeseektime('1675')">0:27:55</a> we didn't was the world militant  
<a onclick="modifyYTiframeseektime('1677')">0:27:57</a> anti-racism come to inclusivity tolerate  
<a onclick="modifyYTiframeseektime('1680')">0:28:00</a> I like that that's tough  
<a onclick="modifyYTiframeseektime('1682')">0:28:02</a> I will say let's call that probably what  
<a onclick="modifyYTiframeseektime('1684')">0:28:04</a> I'm saying is that the narrative them  
<a onclick="modifyYTiframeseektime('1685')">0:28:05</a> written out endure the Western man has  
<a onclick="modifyYTiframeseektime('1687')">0:28:07</a> has forced us to engage with that we  
<a onclick="modifyYTiframeseektime('1691')">0:28:11</a> should question they still having people  
<a onclick="modifyYTiframeseektime('1692')">0:28:12</a> ask  
</details>