# The REAL differences between SUNNI AND SHIA.|| BR. Mohammed Hijab (2016-10-12)

<iframe loading='lazy' src='https://www.youtube.com/embed/zZx5B1P8IM8'></iframe>

## Description

This video outlines the main differences between SUNNI and SHIA islam. This topic has been shied away from at the expense of educating both Muslims and Non-Muslim enquirers.

- An interesting website that further shows explores some key arguments regarding shiism -http://twelvershia.net/.
Follow Mohammed on:

www.facebook.com/brothermohammedhijab

www.instagram.com/bromohammedhijab

## Summary of [The REAL differences between SUNNI AND SHIA.|| BR. Mohammed Hijab](https://www.youtube.com/watch?v=zZx5B1P8IM8)


*<span style="color:red; font-size:125%">This summary is AI generated - there may be inaccuracies</span>. [](/)*

### <a onclick="modifyYTiframeseektime('0')">00:00:00</a> - <a onclick="modifyYTiframeseektime('1500')">00:25:00</a>

 discusses the differences between Sunni and Shia Muslims, with a focus on how they interpret the Quran and the status of the Sahaba.  argues that Shia Muslims believe that the Imams know something that Allah does not know, and that Sunni Muslims believe that the successor of Prophet Muhammad is the only one who can guide Muslims correctly.

**<a onclick="modifyYTiframeseektime('0')">00:00:00</a>** of the video discusses the differences between Sunni and Shia Muslims, emphasizing the importance of Quran preservation. He points out that there are two different interpretations of this issue within Shia scholarship, with the majority believing that the Quran was preserved. He goes on to discuss the second difference, which is the status of the Sahaba. Sunni Muslims believe that the Sahaba were the closest companions of the Prophet, whereas Shia Muslims believe that Ali, the son-in-law of the Prophet, was the most appropriate Companion.
* **<a onclick="modifyYTiframeseektime('300')">00:05:00</a>** Shia Muslims believe that some of the Sahaba were apostates, while Sunnis believe that all of the Sahaba were Muslims. Differences between Sunni and Shia interpretations of the Sahaba also exist in regards to who is a legitimate successor to the Prophet Muhammad.
* **<a onclick="modifyYTiframeseektime('600')">00:10:00</a>** Sunnis believe that there are six pillars of faith and that the Quran mentions them explicitly, while Shia believe that there are twelve imams, some of which are infallible, and that the Quran preserves these imams' teachings.
* **<a onclick="modifyYTiframeseektime('900')">00:15:00</a>* Discusses the differences between Sunni and Shia beliefs about the Imams, and argues that the Imams do not know everything as Prophet Muhammad said.
* **<a onclick="modifyYTiframeseektime('1200')">00:20:00</a>* Discusses the differences between Sunni and Shia Islam. Sunni Islam believes that Allah knows everything, while Shia Islam believes that the Imams (the leaders of Shia Islam) know something that Allah does not know. In addition, Sunni Muslims believe that the successor of Prophet Muhammad (PBUH) is the only one who can guide Muslims correctly. Shia Muslims, on the other hand, believe that there are many legitimate leaders who can guide Muslims. Finally, this video explains how Sunni and Shia Muslims commemorate the death of Prophet Muhammad (PBUH).
* **<a onclick="modifyYTiframeseektime('1500')">00:25:00</a>* Discusses the differences between Sunni and Shia beliefs, and offers sources for both sides. It concludes with a message to viewers to subscribe to the channel and ask questions.

<details><summary><h2>Full transcript with timestamps: CLICK TO EXPAND</h2></summary>

<a onclick="modifyYTiframeseektime('1')">0:00:01</a> leaders feel so dirty  
<a onclick="modifyYTiframeseektime('6')">0:00:06</a> easy what Jamie I thought miss Molloy  
<a onclick="modifyYTiframeseektime('12')">0:00:12</a> r-rahman r-rahim  
<a onclick="modifyYTiframeseektime('14')">0:00:14</a> today one will be talking about is I'm  
<a onclick="modifyYTiframeseektime('15')">0:00:15</a> going to be talking about the  
<a onclick="modifyYTiframeseektime('16')">0:00:16</a> differences between Sunnis and Shia and  
<a onclick="modifyYTiframeseektime('18')">0:00:18</a> this is something which people need to  
<a onclick="modifyYTiframeseektime('20')">0:00:20</a> know the educate about be informed about  
<a onclick="modifyYTiframeseektime('22')">0:00:22</a> and also it's an important thing for the  
<a onclick="modifyYTiframeseektime('25')">0:00:25</a> truth seeker to be able to have access  
<a onclick="modifyYTiframeseektime('27')">0:00:27</a> to so without further ado do I'm going  
<a onclick="modifyYTiframeseektime('31')">0:00:31</a> to talk about something that the Sunnis  
<a onclick="modifyYTiframeseektime('32')">0:00:32</a> or other people from maybe a non-muslim  
<a onclick="modifyYTiframeseektime('35')">0:00:35</a> perspective would think about when they  
<a onclick="modifyYTiframeseektime('37')">0:00:37</a> think about yes or they think about as  
<a onclick="modifyYTiframeseektime('39')">0:00:39</a> things like motor marriages may be  
<a onclick="modifyYTiframeseektime('41')">0:00:41</a> temporary marriage  
<a onclick="modifyYTiframeseektime('43')">0:00:43</a> Takia which is the ability for or the  
<a onclick="modifyYTiframeseektime('45')">0:00:45</a> allowance for share to be able to lie  
<a onclick="modifyYTiframeseektime('47')">0:00:47</a> any in sense situations and maybe  
<a onclick="modifyYTiframeseektime('50')">0:00:50</a> potentially the damaja D de Maddie for  
<a onclick="modifyYTiframeseektime('54')">0:00:54</a> the share is obviously different in  
<a onclick="modifyYTiframeseektime('55')">0:00:55</a> character in description and the  
<a onclick="modifyYTiframeseektime('58')">0:00:58</a> metaphor the Sunnis and potentially they  
<a onclick="modifyYTiframeseektime('62')">0:01:02</a> might be acquainted with the fact that  
<a onclick="modifyYTiframeseektime('65')">0:01:05</a> you know she has believed that Ali  
<a onclick="modifyYTiframeseektime('67')">0:01:07</a> should have been the successor to the  
<a onclick="modifyYTiframeseektime('69')">0:01:09</a> Prophet and Sunnis believe that the buck  
<a onclick="modifyYTiframeseektime('72')">0:01:12</a> should have been a successful project  
<a onclick="modifyYTiframeseektime('73')">0:01:13</a> when people think about the differences  
<a onclick="modifyYTiframeseektime('75')">0:01:15</a> between Sunni and Shia these are the  
<a onclick="modifyYTiframeseektime('77')">0:01:17</a> kind of things that come into or crop  
<a onclick="modifyYTiframeseektime('78')">0:01:18</a> into your mind I want to say something  
<a onclick="modifyYTiframeseektime('81')">0:01:21</a> to you guys I think these are not  
<a onclick="modifyYTiframeseektime('83')">0:01:23</a> actually the primary differences between  
<a onclick="modifyYTiframeseektime('86')">0:01:26</a> Sunni and Shiah the primary differences  
<a onclick="modifyYTiframeseektime('89')">0:01:29</a> between Sunni and Shia I would say hola  
<a onclick="modifyYTiframeseektime('93')">0:01:33</a> alum are three number one is the status  
<a onclick="modifyYTiframeseektime('97')">0:01:37</a> of the Quran number two is the Sahaba  
<a onclick="modifyYTiframeseektime('102')">0:01:42</a> and number three or the Companions the  
<a onclick="modifyYTiframeseektime('104')">0:01:44</a> profitable through is Amana these are  
<a onclick="modifyYTiframeseektime('106')">0:01:46</a> three things which I would say are the  
<a onclick="modifyYTiframeseektime('109')">0:01:49</a> pillars of difference between Sunnis and  
<a onclick="modifyYTiframeseektime('111')">0:01:51</a> Shia so I'm mentioning these things not  
<a onclick="modifyYTiframeseektime('114')">0:01:54</a> to cause a fitna or corruption in the  
<a onclick="modifyYTiframeseektime('116')">0:01:56</a> land or something like this I mention  
<a onclick="modifyYTiframeseektime('118')">0:01:58</a> these things because it's the right of  
<a onclick="modifyYTiframeseektime('119')">0:01:59</a> the consumer to understand these  
<a onclick="modifyYTiframeseektime('122')">0:02:02</a> differences when conceptualizing Islam  
<a onclick="modifyYTiframeseektime('124')">0:02:04</a> in general now the first thing we can  
<a onclick="modifyYTiframeseektime('127')">0:02:07</a> talk about quickly is a Quran now the  
<a onclick="modifyYTiframeseektime('130')">0:02:10</a> Quran clearly is Muslims believe send  
<a onclick="modifyYTiframeseektime('133')">0:02:13</a> on top of mohammed by the angel gabriel  
<a onclick="modifyYTiframeseektime('135')">0:02:15</a> etc but being honest here I have to be  
<a onclick="modifyYTiframeseektime('139')">0:02:19</a> honest that when you look into the  
<a onclick="modifyYTiframeseektime('141')">0:02:21</a> classical Shia scholarship it's very  
<a onclick="modifyYTiframeseektime('144')">0:02:24</a> clear that there's a difference of  
<a onclick="modifyYTiframeseektime('145')">0:02:25</a> opinion between the scholars in Shia and  
<a onclick="modifyYTiframeseektime('147')">0:02:27</a> the shear school reform especially the  
<a onclick="modifyYTiframeseektime('150')">0:02:30</a> 12 she at school of thought as it  
<a onclick="modifyYTiframeseektime('152')">0:02:32</a> relates to the preservation of the Quran  
<a onclick="modifyYTiframeseektime('154')">0:02:34</a> so there are these who take the the  
<a onclick="modifyYTiframeseektime('157')">0:02:37</a> Islamic position that darkness preserves  
<a onclick="modifyYTiframeseektime('159')">0:02:39</a> its and under Prophet and the things  
<a onclick="modifyYTiframeseektime('161')">0:02:41</a> that we've been reiterating and this on  
<a onclick="modifyYTiframeseektime('163')">0:02:43</a> our channel so you can refer to it and  
<a onclick="modifyYTiframeseektime('164')">0:02:44</a> those Shia who basically don't take this  
<a onclick="modifyYTiframeseektime('167')">0:02:47</a> large position and this is in this  
<a onclick="modifyYTiframeseektime('170')">0:02:50</a> scholarship and they don't basically  
<a onclick="modifyYTiframeseektime('171')">0:02:51</a> believe it before honest preserved  
<a onclick="modifyYTiframeseektime('173')">0:02:53</a> because they don't see that the Sahaba  
<a onclick="modifyYTiframeseektime('174')">0:02:54</a> or the Companions have done a good job  
<a onclick="modifyYTiframeseektime('177')">0:02:57</a> in preserving the Quran and of course  
<a onclick="modifyYTiframeseektime('180')">0:03:00</a> some of the it's the classical scholars  
<a onclick="modifyYTiframeseektime('183')">0:03:03</a> I can call them are people like a table  
<a onclick="modifyYTiframeseektime('185')">0:03:05</a> row see who actually wrote a book called  
<a onclick="modifyYTiframeseektime('188')">0:03:08</a> in translation the fossil clipper first  
<a onclick="modifyYTiframeseektime('192')">0:03:12</a> of all Qatar basically the final say  
<a onclick="modifyYTiframeseektime('194')">0:03:14</a> Fattah leaf kitab ruble are bad they  
<a onclick="modifyYTiframeseektime('198')">0:03:18</a> envy in the lack of pro the corruption  
<a onclick="modifyYTiframeseektime('201')">0:03:21</a> of the book of the lord of the Lord's  
<a onclick="modifyYTiframeseektime('203')">0:03:23</a> which here means obviously Allah so this  
<a onclick="modifyYTiframeseektime('207')">0:03:27</a> is one example  
<a onclick="modifyYTiframeseektime('208')">0:03:28</a> Romanian in his book cash alisov he also  
<a onclick="modifyYTiframeseektime('213')">0:03:33</a> mentions the fact in page 117 that the  
<a onclick="modifyYTiframeseektime('217')">0:03:37</a> he believes that the Quran is not  
<a onclick="modifyYTiframeseektime('219')">0:03:39</a> present however this shouldn't be said  
<a onclick="modifyYTiframeseektime('223')">0:03:43</a> without also saying that there are other  
<a onclick="modifyYTiframeseektime('226')">0:03:46</a> people like Ali kami one of the one of  
<a onclick="modifyYTiframeseektime('229')">0:03:49</a> the air Kamel sorry Ally can read one of  
<a onclick="modifyYTiframeseektime('232')">0:03:52</a> the shoe one of the Shia she you have  
<a onclick="modifyYTiframeseektime('235')">0:03:55</a> said that the Quran is preserved so  
<a onclick="modifyYTiframeseektime('237')">0:03:57</a> there are two different of repeater two  
<a onclick="modifyYTiframeseektime('240')">0:04:00</a> kinds of opinions exist within she has  
<a onclick="modifyYTiframeseektime('242')">0:04:02</a> clearly now those who have the opinion  
<a onclick="modifyYTiframeseektime('245')">0:04:05</a> that Quran to preserve which I genuinely  
<a onclick="modifyYTiframeseektime('248')">0:04:08</a> believe are the majority I genuinely  
<a onclick="modifyYTiframeseektime('251')">0:04:11</a> believe I personally believe are the  
<a onclick="modifyYTiframeseektime('253')">0:04:13</a> overwhelming majority but because I  
<a onclick="modifyYTiframeseektime('257')">0:04:17</a> would love to believe that and I think  
<a onclick="modifyYTiframeseektime('259')">0:04:19</a> that is true but it's very difficult to  
<a onclick="modifyYTiframeseektime('260')">0:04:20</a> find out through sociological studies of  
<a onclick="modifyYTiframeseektime('263')">0:04:23</a> mr. Ono  
<a onclick="modifyYTiframeseektime('264')">0:04:24</a> those who do believe that  
<a onclick="modifyYTiframeseektime('266')">0:04:26</a> and is preserved and the Quran is the  
<a onclick="modifyYTiframeseektime('268')">0:04:28</a> word of Allah subhana Allah and this be  
<a onclick="modifyYTiframeseektime('270')">0:04:30</a> sent down to mohammed salah salem which  
<a onclick="modifyYTiframeseektime('272')">0:04:32</a> is the normative islamic position those  
<a onclick="modifyYTiframeseektime('275')">0:04:35</a> who have that islamic position we can  
<a onclick="modifyYTiframeseektime('277')">0:04:37</a> then talk about the second thing which  
<a onclick="modifyYTiframeseektime('280')">0:04:40</a> we're going to segue into now it with a  
<a onclick="modifyYTiframeseektime('283')">0:04:43</a> bit more conviction number two here  
<a onclick="modifyYTiframeseektime('285')">0:04:45</a> which is what we said we're going to  
<a onclick="modifyYTiframeseektime('287')">0:04:47</a> talk about in terms of the steps is the  
<a onclick="modifyYTiframeseektime('290')">0:04:50</a> status of the Sahaba the Sahaba  
<a onclick="modifyYTiframeseektime('293')">0:04:53</a> what is the sir what are who others have  
<a onclick="modifyYTiframeseektime('295')">0:04:55</a> a Sahab are basically the Companions of  
<a onclick="modifyYTiframeseektime('297')">0:04:57</a> the Prophet the Companions of the  
<a onclick="modifyYTiframeseektime('299')">0:04:59</a> Prophet asahi V is a companion the  
<a onclick="modifyYTiframeseektime('302')">0:05:02</a> Sahaba other companions endless Elohim  
<a onclick="modifyYTiframeseektime('306')">0:05:06</a> are described as a hobby as someone who  
<a onclick="modifyYTiframeseektime('309')">0:05:09</a> has met the Prophet Malachi and Nabi  
<a onclick="modifyYTiframeseektime('311')">0:05:11</a> whoever has let the pro met the prophet  
<a onclick="modifyYTiframeseektime('313')">0:05:13</a> and he's a what kind of walk me learn  
<a onclick="modifyYTiframeseektime('315')">0:05:15</a> and he's a more he was a Muslim or she  
<a onclick="modifyYTiframeseektime('317')">0:05:17</a> was a Muslim and were metal eidetic and  
<a onclick="modifyYTiframeseektime('320')">0:05:20</a> then died upon this idea slam so as a  
<a onclick="modifyYTiframeseektime('324')">0:05:24</a> hobby according to Islamic the Islamic  
<a onclick="modifyYTiframeseektime('326')">0:05:26</a> tradition of the sorry the Anderson of  
<a onclick="modifyYTiframeseektime('327')">0:05:27</a> Jamaat tradition is someone who's met  
<a onclick="modifyYTiframeseektime('330')">0:05:30</a> the Prophet died upon Islam and there's  
<a onclick="modifyYTiframeseektime('331')">0:05:31</a> nothing to show that he is not a Muslim  
<a onclick="modifyYTiframeseektime('333')">0:05:33</a> now from a Sunni perspective the Sahaba  
<a onclick="modifyYTiframeseektime('338')">0:05:38</a> are seen as the transmitters of the  
<a onclick="modifyYTiframeseektime('342')">0:05:42</a> revelation by both the Quran and the  
<a onclick="modifyYTiframeseektime('344')">0:05:44</a> Sunnah now if if we do take the Shia  
<a onclick="modifyYTiframeseektime('348')">0:05:48</a> position which I'm going to outline in a  
<a onclick="modifyYTiframeseektime('350')">0:05:50</a> second then we would if we take our  
<a onclick="modifyYTiframeseektime('353')">0:05:53</a> skeptical extreme to its max we could  
<a onclick="modifyYTiframeseektime('356')">0:05:56</a> actually say that the Quran would be  
<a onclick="modifyYTiframeseektime('358')">0:05:58</a> corrupted by having said this what do  
<a onclick="modifyYTiframeseektime('362')">0:06:02</a> the see a sec I mean if you look at  
<a onclick="modifyYTiframeseektime('364')">0:06:04</a> Kathy which is the second most  
<a onclick="modifyYTiframeseektime('365')">0:06:05</a> authoritative book or salute Kathy and  
<a onclick="modifyYTiframeseektime('368')">0:06:08</a> it's actually three sections and Kathy  
<a onclick="modifyYTiframeseektime('370')">0:06:10</a> is about 83 for this year or sulfur on  
<a onclick="modifyYTiframeseektime('374')">0:06:14</a> cetera if you look at carefully which is  
<a onclick="modifyYTiframeseektime('376')">0:06:16</a> the second most authoritative book for  
<a onclick="modifyYTiframeseektime('378')">0:06:18</a> the four she ad you'll find that it says  
<a onclick="modifyYTiframeseektime('381')">0:06:21</a> in caffeine and I'll put the references  
<a onclick="modifyYTiframeseektime('383')">0:06:23</a> maybe in the description box that can  
<a onclick="modifyYTiframeseektime('387')">0:06:27</a> basically the Companions of the Prophet  
<a onclick="modifyYTiframeseektime('390')">0:06:30</a> were as hub rid their Aleph Alessa that  
<a onclick="modifyYTiframeseektime('394')">0:06:34</a> they were apostates except for three and  
<a onclick="modifyYTiframeseektime('398')">0:06:38</a> they mentioned who  
<a onclick="modifyYTiframeseektime('399')">0:06:39</a> 3r and they say it was mcdead and it was  
<a onclick="modifyYTiframeseektime('403')">0:06:43</a> with a brother Valley  
<a onclick="modifyYTiframeseektime('405')">0:06:45</a> and it was Samantha see these are the  
<a onclick="modifyYTiframeseektime('407')">0:06:47</a> three companions which are not apostates  
<a onclick="modifyYTiframeseektime('410')">0:06:50</a> according to the Shia tradition of  
<a onclick="modifyYTiframeseektime('412')">0:06:52</a> course in addition to elevate who who  
<a onclick="modifyYTiframeseektime('416')">0:06:56</a> are the compacted the family the  
<a onclick="modifyYTiframeseektime('417')">0:06:57</a> immediate family of the Prophet who they  
<a onclick="modifyYTiframeseektime('420')">0:07:00</a> would say is Hassan Hassan fathom etc  
<a onclick="modifyYTiframeseektime('422')">0:07:02</a> now these are big differences here  
<a onclick="modifyYTiframeseektime('425')">0:07:05</a> because once again if you concede that  
<a onclick="modifyYTiframeseektime('429')">0:07:09</a> the Sahaba aquifer and this is exactly  
<a onclick="modifyYTiframeseektime('433')">0:07:13</a> what one of the Shia scholar says in one  
<a onclick="modifyYTiframeseektime('435')">0:07:15</a> of his books he actually wrote a book  
<a onclick="modifyYTiframeseektime('439')">0:07:19</a> and he entitled one of the the chapters  
<a onclick="modifyYTiframeseektime('444')">0:07:24</a> cough celesta or basically not only do  
<a onclick="modifyYTiframeseektime('452')">0:07:32</a> we talk about the disbelief of the  
<a onclick="modifyYTiframeseektime('454')">0:07:34</a> Sahaba in general but the she has make  
<a onclick="modifyYTiframeseektime('455')">0:07:35</a> specific intentions specific takfeer or  
<a onclick="modifyYTiframeseektime('458')">0:07:38</a> specific some she admits specific fears  
<a onclick="modifyYTiframeseektime('461')">0:07:41</a> to walk Rahman Ali and I know gnarly  
<a onclick="modifyYTiframeseektime('464')">0:07:44</a> robot arm on and off men  
<a onclick="modifyYTiframeseektime('468')">0:07:48</a> they make specific tech fit to these  
<a onclick="modifyYTiframeseektime('469')">0:07:49</a> three mean meaning that they say that  
<a onclick="modifyYTiframeseektime('471')">0:07:51</a> these people are not Muslims because  
<a onclick="modifyYTiframeseektime('473')">0:07:53</a> they use sub tally from his rightful  
<a onclick="modifyYTiframeseektime('476')">0:07:56</a> right to have you know the successorship  
<a onclick="modifyYTiframeseektime('482')">0:08:02</a> of the Prophet this is basically the  
<a onclick="modifyYTiframeseektime('486')">0:08:06</a> Shia position so once again if you take  
<a onclick="modifyYTiframeseektime('488')">0:08:08</a> this position you could fall into the  
<a onclick="modifyYTiframeseektime('490')">0:08:10</a> the first category of people who denied  
<a onclick="modifyYTiframeseektime('493')">0:08:13</a> the Quran preservation but in addition  
<a onclick="modifyYTiframeseektime('495')">0:08:15</a> to that there are lots of the problems  
<a onclick="modifyYTiframeseektime('497')">0:08:17</a> that for example if you look at the life  
<a onclick="modifyYTiframeseektime('499')">0:08:19</a> of values near batalov he didn't come  
<a onclick="modifyYTiframeseektime('501')">0:08:21</a> out and say to to to these three  
<a onclick="modifyYTiframeseektime('505')">0:08:25</a> successes to a rock rock Alan robock arm  
<a onclick="modifyYTiframeseektime('509')">0:08:29</a> up and off men that I believe you were  
<a onclick="modifyYTiframeseektime('512')">0:08:32</a> cuckoo far and this is not in their  
<a onclick="modifyYTiframeseektime('514')">0:08:34</a> screen in their books and neither is  
<a onclick="modifyYTiframeseektime('516')">0:08:36</a> enables he doesn't I mean if you look  
<a onclick="modifyYTiframeseektime('519')">0:08:39</a> carefully he actually praised behind  
<a onclick="modifyYTiframeseektime('521')">0:08:41</a> those people and in Islam if you play  
<a onclick="modifyYTiframeseektime('523')">0:08:43</a> behind the disbeliever your prayer is  
<a onclick="modifyYTiframeseektime('525')">0:08:45</a> invalid in fact more than that he ali  
<a onclick="modifyYTiframeseektime('528')">0:08:48</a> had two sons one of them he named he had  
<a onclick="modifyYTiframeseektime('531')">0:08:51</a> more than two sons  
<a onclick="modifyYTiframeseektime('532')">0:08:52</a> I mean two sons who he specifically  
<a onclick="modifyYTiframeseektime('534')">0:08:54</a> named Abu Bakr and Armour  
<a onclick="modifyYTiframeseektime('538')">0:08:58</a> in addition to that you know Ali had  
<a onclick="modifyYTiframeseektime('541')">0:09:01</a> married his daughter to armor will hot  
<a onclick="modifyYTiframeseektime('544')">0:09:04</a> tub or Mukul Phu so he married her off  
<a onclick="modifyYTiframeseektime('546')">0:09:06</a> to this man and clearly if this was a  
<a onclick="modifyYTiframeseektime('550')">0:09:10</a> disbeliever then it wouldn't be a  
<a onclick="modifyYTiframeseektime('553')">0:09:13</a> legitimate marriage in Islam so this  
<a onclick="modifyYTiframeseektime('555')">0:09:15</a> would mean that he's doing something in  
<a onclick="modifyYTiframeseektime('557')">0:09:17</a> Islam which is considered basically  
<a onclick="modifyYTiframeseektime('560')">0:09:20</a> allowing his daughter to do something  
<a onclick="modifyYTiframeseektime('563')">0:09:23</a> which is completely how these are some  
<a onclick="modifyYTiframeseektime('566')">0:09:26</a> things which Sunnis would reply say look  
<a onclick="modifyYTiframeseektime('567')">0:09:27</a> this is what you're doing the issue with  
<a onclick="modifyYTiframeseektime('569')">0:09:29</a> your thesis yeah or the thesis that the  
<a onclick="modifyYTiframeseektime('572')">0:09:32</a> Sahaba are not basically Muslim but  
<a onclick="modifyYTiframeseektime('579')">0:09:39</a> having said this also the Quran Mexico  
<a onclick="modifyYTiframeseektime('581')">0:09:41</a> the Quran itself makes it a if we look  
<a onclick="modifyYTiframeseektime('584')">0:09:44</a> at certain fan chapters amber forty a of  
<a onclick="modifyYTiframeseektime('586')">0:09:46</a> the Quran a loss of her Lata himself he  
<a onclick="modifyYTiframeseektime('588')">0:09:48</a> says Lockhart around Yolo and what we  
<a onclick="modifyYTiframeseektime('590')">0:09:50</a> need a IDEO Bayona katate shardana well  
<a onclick="modifyYTiframeseektime('592')">0:09:52</a> you know if equal over him well John I  
<a onclick="modifyYTiframeseektime('594')">0:09:54</a> mean do need a deacon fat hankering they  
<a onclick="modifyYTiframeseektime('596')">0:09:56</a> said that's so Allah has low he knows  
<a onclick="modifyYTiframeseektime('599')">0:09:59</a> the Sydney would argue he knows that  
<a onclick="modifyYTiframeseektime('604')">0:10:04</a> colada rowdy Allah sorry Allah is  
<a onclick="modifyYTiframeseektime('606')">0:10:06</a> pleased with those people who have made  
<a onclick="modifyYTiframeseektime('608')">0:10:08</a> by a to you under the tree may I means  
<a onclick="modifyYTiframeseektime('611')">0:10:11</a> the Pledge of Allegiance and there's no  
<a onclick="modifyYTiframeseektime('613')">0:10:13</a> difference of opinion that these  
<a onclick="modifyYTiframeseektime('614')">0:10:14</a> individuals included off man and  
<a onclick="modifyYTiframeseektime('616')">0:10:16</a> included included of Oakland and these  
<a onclick="modifyYTiframeseektime('620')">0:10:20</a> big names that basically the Sunnis take  
<a onclick="modifyYTiframeseektime('623')">0:10:23</a> as big names in the shares some of them  
<a onclick="modifyYTiframeseektime('625')">0:10:25</a> I would say quite openly excommunicate  
<a onclick="modifyYTiframeseektime('628')">0:10:28</a> from the faith altogether so if we look  
<a onclick="modifyYTiframeseektime('630')">0:10:30</a> at the Quran the Quran makes it very  
<a onclick="modifyYTiframeseektime('632')">0:10:32</a> clear and other verses like at the final  
<a onclick="modifyYTiframeseektime('634')">0:10:34</a> verse of that very chapter chapter forty  
<a onclick="modifyYTiframeseektime('637')">0:10:37</a> eight it says Muhammad Rasul Allah we're  
<a onclick="modifyYTiframeseektime('639')">0:10:39</a> letting Amon Amarth  
<a onclick="modifyYTiframeseektime('640')">0:10:40</a> wears you down a little far behind a  
<a onclick="modifyYTiframeseektime('641')">0:10:41</a> better home and it continues the verses  
<a onclick="modifyYTiframeseektime('643')">0:10:43</a> continue so it says that Prophet  
<a onclick="modifyYTiframeseektime('644')">0:10:44</a> Muhammad is the soul of Allah so Allah  
<a onclick="modifyYTiframeseektime('646')">0:10:46</a> and the ones who are bullied with him  
<a onclick="modifyYTiframeseektime('647')">0:10:47</a> are basically a details of so many  
<a onclick="modifyYTiframeseektime('650')">0:10:50</a> different things good traits would say  
<a onclick="modifyYTiframeseektime('653')">0:10:53</a> of the Sahara now having said that  
<a onclick="modifyYTiframeseektime('657')">0:10:57</a> having spoken about the second major  
<a onclick="modifyYTiframeseektime('658')">0:10:58</a> difference I'll talk about about the  
<a onclick="modifyYTiframeseektime('660')">0:11:00</a> third major difference the third major  
<a onclick="modifyYTiframeseektime('661')">0:11:01</a> difference is and it's a very big one  
<a onclick="modifyYTiframeseektime('663')">0:11:03</a> mmm now mmm  
<a onclick="modifyYTiframeseektime('665')">0:11:05</a> if you look at the Islamic tradition  
<a onclick="modifyYTiframeseektime('667')">0:11:07</a> yeah if you look at the Islamic  
<a onclick="modifyYTiframeseektime('669')">0:11:09</a> tradition you'll find that Muslims all  
<a onclick="modifyYTiframeseektime('672')">0:11:12</a> agree that there are six pillars of Eman  
<a onclick="modifyYTiframeseektime('676')">0:11:16</a> there are five pillars of Islam six  
<a onclick="modifyYTiframeseektime('678')">0:11:18</a> pillars of Eman and took them below  
<a onclick="modifyYTiframeseektime('680')">0:11:20</a> Malaika too because we Rosalee William  
<a onclick="modifyYTiframeseektime('681')">0:11:21</a> laughing we'll call the fella who shot  
<a onclick="modifyYTiframeseektime('683')">0:11:23</a> that you believe in Allah and his  
<a onclick="modifyYTiframeseektime('684')">0:11:24</a> messengers and his messengers etc etc  
<a onclick="modifyYTiframeseektime('687')">0:11:27</a> etc there are six pillars of Eman which  
<a onclick="modifyYTiframeseektime('689')">0:11:29</a> is faith now we would consider these six  
<a onclick="modifyYTiframeseektime('693')">0:11:33</a> pillars of faith as they would say the  
<a onclick="modifyYTiframeseektime('694')">0:11:34</a> pillars or the foundation of our creed  
<a onclick="modifyYTiframeseektime('699')">0:11:39</a> or belief all Muslims would say she has  
<a onclick="modifyYTiframeseektime('703')">0:11:43</a> now have in addition to this what they  
<a onclick="modifyYTiframeseektime('705')">0:11:45</a> say is that we believe in Amana Amana is  
<a onclick="modifyYTiframeseektime('708')">0:11:48</a> the idea that there are 12 mm mm means  
<a onclick="modifyYTiframeseektime('712')">0:11:52</a> kind of linguistically means leaders or  
<a onclick="modifyYTiframeseektime('715')">0:11:55</a> people to be followed that's all we must  
<a onclick="modifyYTiframeseektime('718')">0:11:58</a> beginning with Ali ibn ABI Talib and  
<a onclick="modifyYTiframeseektime('720')">0:12:00</a> ending with Muhammad has not asked any  
<a onclick="modifyYTiframeseektime('724')">0:12:04</a> that all of these 12 imams are number  
<a onclick="modifyYTiframeseektime('727')">0:12:07</a> one infallible that they incapable of  
<a onclick="modifyYTiframeseektime('729')">0:12:09</a> making mistakes number two that they  
<a onclick="modifyYTiframeseektime('731')">0:12:11</a> have all knowledge number three that  
<a onclick="modifyYTiframeseektime('733')">0:12:13</a> they can some people say that they have  
<a onclick="modifyYTiframeseektime('735')">0:12:15</a> control of the that rod even the atoms  
<a onclick="modifyYTiframeseektime('737')">0:12:17</a> of creation they have control of it and  
<a onclick="modifyYTiframeseektime('740')">0:12:20</a> so on and so forth so these twelve imams  
<a onclick="modifyYTiframeseektime('742')">0:12:22</a> according to the shia are incredibly  
<a onclick="modifyYTiframeseektime('746')">0:12:26</a> basically perfect they are perfect in  
<a onclick="modifyYTiframeseektime('749')">0:12:29</a> every way shape and form and we have to  
<a onclick="modifyYTiframeseektime('754')">0:12:34</a> follow them according to Shia in order  
<a onclick="modifyYTiframeseektime('756')">0:12:36</a> to seek to get salvation in order to get  
<a onclick="modifyYTiframeseektime('759')">0:12:39</a> salvation now the question that's  
<a onclick="modifyYTiframeseektime('761')">0:12:41</a> suddenly supposed to she eyes now is if  
<a onclick="modifyYTiframeseektime('765')">0:12:45</a> we look at the Quran from the beginning  
<a onclick="modifyYTiframeseektime('769')">0:12:49</a> of the Quran to the end of the Quran we  
<a onclick="modifyYTiframeseektime('771')">0:12:51</a> will we will find many mentions not just  
<a onclick="modifyYTiframeseektime('773')">0:12:53</a> one mentioned but many mentions of all  
<a onclick="modifyYTiframeseektime('775')">0:12:55</a> of the foundational elements of of  
<a onclick="modifyYTiframeseektime('777')">0:12:57</a> leader or faith will find many mentions  
<a onclick="modifyYTiframeseektime('781')">0:13:01</a> of like for example the day of judgment  
<a onclick="modifyYTiframeseektime('785')">0:13:05</a> Allah this is all the things I've just  
<a onclick="modifyYTiframeseektime('786')">0:13:06</a> mentioned the things which are the six  
<a onclick="modifyYTiframeseektime('788')">0:13:08</a> pillars of you but when you try and do  
<a onclick="modifyYTiframeseektime('789')">0:13:09</a> the same thing for Iman the question now  
<a onclick="modifyYTiframeseektime('793')">0:13:13</a> is where does the Quran mentioned email  
<a onclick="modifyYTiframeseektime('794')">0:13:14</a> from the beginning of it to the end of  
<a onclick="modifyYTiframeseektime('796')">0:13:16</a> it  
<a onclick="modifyYTiframeseektime('796')">0:13:16</a> now clearly those ancient probably  
<a onclick="modifyYTiframeseektime('799')">0:13:19</a> hopefully they don't adjust the  
<a onclick="modifyYTiframeseektime('801')">0:13:21</a> discipline yin is not present nowadays  
<a onclick="modifyYTiframeseektime('803')">0:13:23</a> but these may be classical minded she  
<a onclick="modifyYTiframeseektime('806')">0:13:26</a> has Orthodox she has or whatever you  
<a onclick="modifyYTiframeseektime('809')">0:13:29</a> want to call them maybe I should call  
<a onclick="modifyYTiframeseektime('811')">0:13:31</a> off the dogs maybe extremists  
<a onclick="modifyYTiframeseektime('813')">0:13:33</a> she has they will save me with the Quran  
<a onclick="modifyYTiframeseektime('815')">0:13:35</a> or preserved the original Quran had  
<a onclick="modifyYTiframeseektime('817')">0:13:37</a> 18,000 verses and you know  
<a onclick="modifyYTiframeseektime('820')">0:13:40</a> therefore yeah those verses that talk  
<a onclick="modifyYTiframeseektime('823')">0:13:43</a> about him and I've been lifted but for  
<a onclick="modifyYTiframeseektime('826')">0:13:46</a> those she has who maintain that the  
<a onclick="modifyYTiframeseektime('829')">0:13:49</a> Quran is preserved and that the Quran  
<a onclick="modifyYTiframeseektime('832')">0:13:52</a> has not been changed which hopefully I  
<a onclick="modifyYTiframeseektime('834')">0:13:54</a> will say is the majority the question  
<a onclick="modifyYTiframeseektime('836')">0:13:56</a> now is how would they respond to the  
<a onclick="modifyYTiframeseektime('838')">0:13:58</a> fact that Eman or the idea of the  
<a onclick="modifyYTiframeseektime('841')">0:14:01</a> leadership of the twelve and it's not  
<a onclick="modifyYTiframeseektime('842')">0:14:02</a> mentioned anywhere in the Quran in any  
<a onclick="modifyYTiframeseektime('844')">0:14:04</a> explicit way at all and this is very  
<a onclick="modifyYTiframeseektime('846')">0:14:06</a> very clear afford to see so this is a  
<a onclick="modifyYTiframeseektime('850')">0:14:10</a> question that Sunnis have been  
<a onclick="modifyYTiframeseektime('851')">0:14:11</a> historically posing - she adds forever a  
<a onclick="modifyYTiframeseektime('853')">0:14:13</a> long time and she has have been  
<a onclick="modifyYTiframeseektime('855')">0:14:15</a> grappling with it and you could say that  
<a onclick="modifyYTiframeseektime('857')">0:14:17</a> they've been referencing somehow yet  
<a onclick="modifyYTiframeseektime('860')">0:14:20</a> maybe a little Merida with some other  
<a onclick="modifyYTiframeseektime('863')">0:14:23</a> places which have vague references or  
<a onclick="modifyYTiframeseektime('865')">0:14:25</a> ambiguous references which are not clear  
<a onclick="modifyYTiframeseektime('868')">0:14:28</a> and definitely don't mention any of the  
<a onclick="modifyYTiframeseektime('870')">0:14:30</a> names of any of the 12 Imams beginning  
<a onclick="modifyYTiframeseektime('872')">0:14:32</a> from Allium nebith all have been ending  
<a onclick="modifyYTiframeseektime('875')">0:14:35</a> with muhammad even has an ascot even by  
<a onclick="modifyYTiframeseektime('878')">0:14:38</a> the way in a book written by a Potosi  
<a onclick="modifyYTiframeseektime('881')">0:14:41</a> who is one of the biggest shia scholars  
<a onclick="modifyYTiframeseektime('884')">0:14:44</a> in this field he says that in page in  
<a onclick="modifyYTiframeseektime('887')">0:14:47</a> the book allah hyper page number 74 he  
<a onclick="modifyYTiframeseektime('890')">0:14:50</a> says that this man has a mascetti who's  
<a onclick="modifyYTiframeseektime('893')">0:14:53</a> the eleventh he man didn't have any  
<a onclick="modifyYTiframeseektime('894')">0:14:54</a> children anyways so there would be 11  
<a onclick="modifyYTiframeseektime('896')">0:14:56</a> imams and this would possible problems  
<a onclick="modifyYTiframeseektime('899')">0:14:59</a> if this if this is true before the fact  
<a onclick="modifyYTiframeseektime('901')">0:15:01</a> that there are 12 and this is obviously  
<a onclick="modifyYTiframeseektime('904')">0:15:04</a> a shock you Scott but having said this  
<a onclick="modifyYTiframeseektime('908')">0:15:08</a> the question now would be where did the  
<a onclick="modifyYTiframeseektime('910')">0:15:10</a> idea come from  
<a onclick="modifyYTiframeseektime('911')">0:15:11</a> and remember if it didn't come from the  
<a onclick="modifyYTiframeseektime('914')">0:15:14</a> Quran if it didn't come from the  
<a onclick="modifyYTiframeseektime('916')">0:15:16</a> prophets himself the Salama if it don't  
<a onclick="modifyYTiframeseektime('919')">0:15:19</a> come from so what are the alternate  
<a onclick="modifyYTiframeseektime('920')">0:15:20</a> theories and there are some  
<a onclick="modifyYTiframeseektime('921')">0:15:21</a> controversial theories other I'm not  
<a onclick="modifyYTiframeseektime('923')">0:15:23</a> saying I subscribe to any one particular  
<a onclick="modifyYTiframeseektime('924')">0:15:24</a> I'm saying I'll put them up there for  
<a onclick="modifyYTiframeseektime('926')">0:15:26</a> education purposes and that one theory  
<a onclick="modifyYTiframeseektime('930')">0:15:30</a> according to  
<a onclick="modifyYTiframeseektime('931')">0:15:31</a> some people she ransom actually Shia  
<a onclick="modifyYTiframeseektime('935')">0:15:35</a> Anson I know substantiate my claim is  
<a onclick="modifyYTiframeseektime('938')">0:15:38</a> that the idea of email actually came  
<a onclick="modifyYTiframeseektime('940')">0:15:40</a> from a human being called Abdul live in  
<a onclick="modifyYTiframeseektime('944')">0:15:44</a> seven and I hope this yeah if you're  
<a onclick="modifyYTiframeseektime('946')">0:15:46</a> watching this you know gonna switch off  
<a onclick="modifyYTiframeseektime('947')">0:15:47</a> and get angry because I know you've had  
<a onclick="modifyYTiframeseektime('949')">0:15:49</a> this family before okay I know you've  
<a onclick="modifyYTiframeseektime('951')">0:15:51</a> heard this before I'm not trying to say  
<a onclick="modifyYTiframeseektime('952')">0:15:52</a> that it's true or false I'm just saying  
<a onclick="modifyYTiframeseektime('954')">0:15:54</a> it's an idea it's in the scholarly works  
<a onclick="modifyYTiframeseektime('956')">0:15:56</a> of Shias and sooner  
<a onclick="modifyYTiframeseektime('957')">0:15:57</a> for example Abdullah bin Sabah is being  
<a onclick="modifyYTiframeseektime('960')">0:16:00</a> said by someone called open me who is a  
<a onclick="modifyYTiframeseektime('963')">0:16:03</a> Shia scholar who wrote a book and and in  
<a onclick="modifyYTiframeseektime('968')">0:16:08</a> that picture is called Philip a Shia and  
<a onclick="modifyYTiframeseektime('970')">0:16:10</a> this book in page 32 of the book it says  
<a onclick="modifyYTiframeseektime('974')">0:16:14</a> that he Abdullah bin Sabah is a woman of  
<a onclick="modifyYTiframeseektime('977')">0:16:17</a> a homework ailment Shahidah he's the  
<a onclick="modifyYTiframeseektime('980')">0:16:20</a> first person to testify be a befall did  
<a onclick="modifyYTiframeseektime('986')">0:16:26</a> he member to highly alehissalaam what of  
<a onclick="modifyYTiframeseektime('989')">0:16:29</a> the Hara el buro attack and there he he  
<a onclick="modifyYTiframeseektime('992')">0:16:32</a> says that he is the food this is exactly  
<a onclick="modifyYTiframeseektime('994')">0:16:34</a> what he says in page 32 he says that he  
<a onclick="modifyYTiframeseektime('998')">0:16:38</a> I be abdullah bin sabah is the first  
<a onclick="modifyYTiframeseektime('1000')">0:16:40</a> person to say that it's obligatory to  
<a onclick="modifyYTiframeseektime('1005')">0:16:45</a> believe in the e mama and he uses  
<a onclick="modifyYTiframeseektime('1006')">0:16:46</a> exactly the word email or valley and he  
<a onclick="modifyYTiframeseektime('1010')">0:16:50</a> says allah he sir because he is a she  
<a onclick="modifyYTiframeseektime('1011')">0:16:51</a> app and have been son is just the same  
<a onclick="modifyYTiframeseektime('1014')">0:16:54</a> thing Ali Salim is not necessarily  
<a onclick="modifyYTiframeseektime('1016')">0:16:56</a> something I'm attacking anyone on of  
<a onclick="modifyYTiframeseektime('1020')">0:17:00</a> Hara el buro attack I mean he says that  
<a onclick="modifyYTiframeseektime('1023')">0:17:03</a> and he is the first person to really  
<a onclick="modifyYTiframeseektime('1026')">0:17:06</a> show animosity yeah against those who  
<a onclick="modifyYTiframeseektime('1030')">0:17:10</a> people who he says are the enemies of  
<a onclick="modifyYTiframeseektime('1032')">0:17:12</a> Ali who he's referring to obviously arm  
<a onclick="modifyYTiframeseektime('1035')">0:17:15</a> honorable doctor etc so the there are  
<a onclick="modifyYTiframeseektime('1039')">0:17:19</a> competing theories of how this idea of  
<a onclick="modifyYTiframeseektime('1042')">0:17:22</a> Imam has actually entered the Islamic  
<a onclick="modifyYTiframeseektime('1045')">0:17:25</a> framework or has entered the minds of  
<a onclick="modifyYTiframeseektime('1049')">0:17:29</a> people who promote the idea and this is  
<a onclick="modifyYTiframeseektime('1053')">0:17:33</a> one theory and certainly it's been  
<a onclick="modifyYTiframeseektime('1054')">0:17:34</a> mentioned by Sunnis and Shia but there  
<a onclick="modifyYTiframeseektime('1058')">0:17:38</a> are the theories and I'm not here to  
<a onclick="modifyYTiframeseektime('1061')">0:17:41</a> make you have you know how complete  
<a onclick="modifyYTiframeseektime('1062')">0:17:42</a> discussion about that but it's important  
<a onclick="modifyYTiframeseektime('1064')">0:17:44</a> for us to know  
<a onclick="modifyYTiframeseektime('1065')">0:17:45</a> not only the differences but perhaps  
<a onclick="modifyYTiframeseektime('1067')">0:17:47</a> where the differences came from as well  
<a onclick="modifyYTiframeseektime('1070')">0:17:50</a> one of the issues really what we've  
<a onclick="modifyYTiframeseektime('1073')">0:17:53</a> talked about one issue which is that you  
<a onclick="modifyYTiframeseektime('1076')">0:17:56</a> wouldn't be able to find a verse which  
<a onclick="modifyYTiframeseektime('1079')">0:17:59</a> is unequivocal and unambiguous that  
<a onclick="modifyYTiframeseektime('1080')">0:18:00</a> talks about the Imams in a certain way  
<a onclick="modifyYTiframeseektime('1083')">0:18:03</a> and the other so that's one key issue  
<a onclick="modifyYTiframeseektime('1086')">0:18:06</a> but another issue is really a credo if  
<a onclick="modifyYTiframeseektime('1089')">0:18:09</a> we say that as many have said and I'll  
<a onclick="modifyYTiframeseektime('1091')">0:18:11</a> put some references in the description  
<a onclick="modifyYTiframeseektime('1092')">0:18:12</a> box for those who really wanted to  
<a onclick="modifyYTiframeseektime('1094')">0:18:14</a> research that the amount for example  
<a onclick="modifyYTiframeseektime('1097')">0:18:17</a> knows everything if we say that the  
<a onclick="modifyYTiframeseektime('1100')">0:18:20</a> Imams know everything they know  
<a onclick="modifyYTiframeseektime('1102')">0:18:22</a> everything  
<a onclick="modifyYTiframeseektime('1102')">0:18:22</a> this is welcome any says this is what  
<a onclick="modifyYTiframeseektime('1104')">0:18:24</a> many of the scholars classical and  
<a onclick="modifyYTiframeseektime('1106')">0:18:26</a> contemporary have said about the amounts  
<a onclick="modifyYTiframeseektime('1107')">0:18:27</a> they know everything if this is the case  
<a onclick="modifyYTiframeseektime('1110')">0:18:30</a> and some sunnis have argued if this is  
<a onclick="modifyYTiframeseektime('1113')">0:18:33</a> the case that you're saying that the  
<a onclick="modifyYTiframeseektime('1114')">0:18:34</a> imams know everything then would that  
<a onclick="modifyYTiframeseektime('1118')">0:18:38</a> suggest that they are more knowledge in  
<a onclick="modifyYTiframeseektime('1120')">0:18:40</a> the Prophet Mohammed said I'll say no in  
<a onclick="modifyYTiframeseektime('1121')">0:18:41</a> fact the Prophet Mohammed knows  
<a onclick="modifyYTiframeseektime('1122')">0:18:42</a> everything as well say okay fine let's  
<a onclick="modifyYTiframeseektime('1126')">0:18:46</a> take this and let's put it to the  
<a onclick="modifyYTiframeseektime('1127')">0:18:47</a> standard of the Koran you see the Quran  
<a onclick="modifyYTiframeseektime('1130')">0:18:50</a> in Chapter number 46 verse number 8 it  
<a onclick="modifyYTiframeseektime('1132')">0:18:52</a> says to the Prophet Muhammad a lost  
<a onclick="modifyYTiframeseektime('1134')">0:18:54</a> pantera he says cool murkland  
<a onclick="modifyYTiframeseektime('1136')">0:18:56</a> cool Malcolm tuba diamond little city  
<a onclick="modifyYTiframeseektime('1138')">0:18:58</a> welcome to edit email file be well  
<a onclick="modifyYTiframeseektime('1140')">0:19:00</a> epical he says to the Prophet Muhammad  
<a onclick="modifyYTiframeseektime('1144')">0:19:04</a> say I'm not an innovation of the  
<a onclick="modifyYTiframeseektime('1146')">0:19:06</a> prophets I'm not something new looking  
<a onclick="modifyYTiframeseektime('1147')">0:19:07</a> with a new message and that I was gonna  
<a onclick="modifyYTiframeseektime('1150')">0:19:10</a> happen to me and Donald's gonna happen  
<a onclick="modifyYTiframeseektime('1151')">0:19:11</a> to you so he said I don't know something  
<a onclick="modifyYTiframeseektime('1155')">0:19:15</a> yeah so the Prophet Muhammad has been  
<a onclick="modifyYTiframeseektime('1158')">0:19:18</a> told I don't know something in other  
<a onclick="modifyYTiframeseektime('1159')">0:19:19</a> words if you're saying they know  
<a onclick="modifyYTiframeseektime('1161')">0:19:21</a> everything how comes under the Prophet  
<a onclick="modifyYTiframeseektime('1162')">0:19:22</a> Muhammad is not exempt from this  
<a onclick="modifyYTiframeseektime('1163')">0:19:23</a> knowledge of everything that how comes  
<a onclick="modifyYTiframeseektime('1165')">0:19:25</a> in the Quran it says that he doesn't  
<a onclick="modifyYTiframeseektime('1168')">0:19:28</a> know certain things yes alone I can t  
<a onclick="modifyYTiframeseektime('1170')">0:19:30</a> say ITA animal so happy madam in the  
<a onclick="modifyYTiframeseektime('1172')">0:19:32</a> Quran for example chapter 79 the Quran  
<a onclick="modifyYTiframeseektime('1174')">0:19:34</a> the last couple of verses are lost panel  
<a onclick="modifyYTiframeseektime('1177')">0:19:37</a> terraces they ask you about the hour one  
<a onclick="modifyYTiframeseektime('1179')">0:19:39</a> will it be pegged say who are you who  
<a onclick="modifyYTiframeseektime('1182')">0:19:42</a> are you  
<a onclick="modifyYTiframeseektime('1183')">0:19:43</a> or Prophet Muhammad SAW said enough to  
<a onclick="modifyYTiframeseektime('1186')">0:19:46</a> know this kind of information and this  
<a onclick="modifyYTiframeseektime('1188')">0:19:48</a> thing is mentioned lots of things or may  
<a onclick="modifyYTiframeseektime('1190')">0:19:50</a> I live now who shadow my neighbor  
<a onclick="modifyYTiframeseektime('1192')">0:19:52</a> well I am Barilla it says that we  
<a onclick="modifyYTiframeseektime('1195')">0:19:55</a> haven't taught him share which means  
<a onclick="modifyYTiframeseektime('1197')">0:19:57</a> Audrey so  
<a onclick="modifyYTiframeseektime('1198')">0:19:58</a> there's lots of things the prophet  
<a onclick="modifyYTiframeseektime('1199')">0:19:59</a> doesn't know here we're not saying the  
<a onclick="modifyYTiframeseektime('1201')">0:20:01</a> Prophet Muhammad SAS Allah that's the  
<a onclick="modifyYTiframeseektime('1203')">0:20:03</a> normative position knows everything and  
<a onclick="modifyYTiframeseektime('1204')">0:20:04</a> if we did would be we'd have real  
<a onclick="modifyYTiframeseektime('1206')">0:20:06</a> trouble justifying that position in the  
<a onclick="modifyYTiframeseektime('1210')">0:20:10</a> light of the verses of the Quran but the  
<a onclick="modifyYTiframeseektime('1213')">0:20:13</a> question would then remain another  
<a onclick="modifyYTiframeseektime('1215')">0:20:15</a> question would remain if we're saying  
<a onclick="modifyYTiframeseektime('1217')">0:20:17</a> that the Imams know everything and that  
<a onclick="modifyYTiframeseektime('1219')">0:20:19</a> Allah knows everything then does that  
<a onclick="modifyYTiframeseektime('1224')">0:20:24</a> mean that the Imams have the same  
<a onclick="modifyYTiframeseektime('1225')">0:20:25</a> knowledge is Allah  
<a onclick="modifyYTiframeseektime('1226')">0:20:26</a> oh no this is another argument that that  
<a onclick="modifyYTiframeseektime('1229')">0:20:29</a> Sunnis before if you say that Allah  
<a onclick="modifyYTiframeseektime('1232')">0:20:32</a> knows everything because there's nothing  
<a onclick="modifyYTiframeseektime('1233')">0:20:33</a> more than everything to know and that  
<a onclick="modifyYTiframeseektime('1235')">0:20:35</a> the Amman know everything that would  
<a onclick="modifyYTiframeseektime('1237')">0:20:37</a> suggest that the Imams and Allah had the  
<a onclick="modifyYTiframeseektime('1239')">0:20:39</a> same College now the Shia does have a  
<a onclick="modifyYTiframeseektime('1241')">0:20:41</a> counter to this just to be clear and rub  
<a onclick="modifyYTiframeseektime('1243')">0:20:43</a> this in education video I know it's a  
<a onclick="modifyYTiframeseektime('1245')">0:20:45</a> very biased one but obviously I'm  
<a onclick="modifyYTiframeseektime('1246')">0:20:46</a> suddenly so I'm going to be very but the  
<a onclick="modifyYTiframeseektime('1248')">0:20:48</a> truth is guys I'll be honest with you  
<a onclick="modifyYTiframeseektime('1250')">0:20:50</a> bias is always going to be a part of  
<a onclick="modifyYTiframeseektime('1251')">0:20:51</a> discussion yeah I'm not gonna lie to you  
<a onclick="modifyYTiframeseektime('1254')">0:20:54</a> here and say I'm not biased I'm biased  
<a onclick="modifyYTiframeseektime('1255')">0:20:55</a> right but why it doesn't mean that it's  
<a onclick="modifyYTiframeseektime('1258')">0:20:58</a> not going to be true why I say because  
<a onclick="modifyYTiframeseektime('1260')">0:21:00</a> you can have a bias which is true the  
<a onclick="modifyYTiframeseektime('1262')">0:21:02</a> point is if we say that Allah knows  
<a onclick="modifyYTiframeseektime('1267')">0:21:07</a> everything and that the amounts know  
<a onclick="modifyYTiframeseektime('1268')">0:21:08</a> everything that would suggest that they  
<a onclick="modifyYTiframeseektime('1270')">0:21:10</a> have the same knowledge  
<a onclick="modifyYTiframeseektime('1271')">0:21:11</a> okay now this Shia would come around and  
<a onclick="modifyYTiframeseektime('1274')">0:21:14</a> say look actually that's not true  
<a onclick="modifyYTiframeseektime('1276')">0:21:16</a> your conceptualising incorrectly say why  
<a onclick="modifyYTiframeseektime('1278')">0:21:18</a> there's a reason why is because if  
<a onclick="modifyYTiframeseektime('1282')">0:21:22</a> actually there's something that the  
<a onclick="modifyYTiframeseektime('1284')">0:21:24</a> allah has that the imams don't have  
<a onclick="modifyYTiframeseektime('1286')">0:21:26</a> which is y equals somebody you know call  
<a onclick="modifyYTiframeseektime('1290')">0:21:30</a> allah i had the love the long summer  
<a onclick="modifyYTiframeseektime('1292')">0:21:32</a> summit means that everything relies upon  
<a onclick="modifyYTiframeseektime('1294')">0:21:34</a> allah and allah doesn't rely upon anyone  
<a onclick="modifyYTiframeseektime('1296')">0:21:36</a> whereas the imams all rely upon Allah  
<a onclick="modifyYTiframeseektime('1298')">0:21:38</a> and Allah does not rely upon the emails  
<a onclick="modifyYTiframeseektime('1301')">0:21:41</a> that's why they say they said this is a  
<a onclick="modifyYTiframeseektime('1302')">0:21:42</a> clear difference this is what  
<a onclick="modifyYTiframeseektime('1304')">0:21:44</a> differentiates the emails from the  
<a onclick="modifyYTiframeseektime('1305')">0:21:45</a> Prophet Muhammad from the e Maps say  
<a onclick="modifyYTiframeseektime('1308')">0:21:48</a> fine but that does not negate the shout  
<a onclick="modifyYTiframeseektime('1312')">0:21:52</a> then I listen you would then argue the  
<a onclick="modifyYTiframeseektime('1314')">0:21:54</a> fact that you are saying that they have  
<a onclick="modifyYTiframeseektime('1315')">0:21:55</a> the same knowledge just just because one  
<a onclick="modifyYTiframeseektime('1319')">0:21:59</a> is more light than the other or one is  
<a onclick="modifyYTiframeseektime('1321')">0:22:01</a> relying on the other than the others not  
<a onclick="modifyYTiframeseektime('1323')">0:22:03</a> relying on one does it mean that they  
<a onclick="modifyYTiframeseektime('1324')">0:22:04</a> don't have the same knowledge if you  
<a onclick="modifyYTiframeseektime('1325')">0:22:05</a> subscribe to this belief so this is the  
<a onclick="modifyYTiframeseektime('1328')">0:22:08</a> kind of discussion you'll find between  
<a onclick="modifyYTiframeseektime('1330')">0:22:10</a> Sunni and Shia this is the tradition  
<a onclick="modifyYTiframeseektime('1332')">0:22:12</a> discussion that's been going on for many  
<a onclick="modifyYTiframeseektime('1333')">0:22:13</a> many hundreds of thousand years now  
<a onclick="modifyYTiframeseektime('1336')">0:22:16</a> thousand four hundred years or thousand  
<a onclick="modifyYTiframeseektime('1337')">0:22:17</a> three hundred whatever it is yes and and  
<a onclick="modifyYTiframeseektime('1340')">0:22:20</a> it's important for us as consumers of  
<a onclick="modifyYTiframeseektime('1343')">0:22:23</a> the truth to have an understanding of  
<a onclick="modifyYTiframeseektime('1345')">0:22:25</a> that and because it is the occasion of  
<a onclick="modifyYTiframeseektime('1348')">0:22:28</a> Ashura today is basically the tenth day  
<a onclick="modifyYTiframeseektime('1351')">0:22:31</a> of Muharram unless this video has been  
<a onclick="modifyYTiframeseektime('1353')">0:22:33</a> recorded or you're watching it some  
<a onclick="modifyYTiframeseektime('1354')">0:22:34</a> other time which is very very possible  
<a onclick="modifyYTiframeseektime('1356')">0:22:36</a> but it's the tenth day of Muharram  
<a onclick="modifyYTiframeseektime('1359')">0:22:39</a> Joshua and so on this occasion I thought  
<a onclick="modifyYTiframeseektime('1362')">0:22:42</a> I would make it elucidate on the  
<a onclick="modifyYTiframeseektime('1363')">0:22:43</a> differences between so people do not  
<a onclick="modifyYTiframeseektime('1367')">0:22:47</a> understand like you know understand what  
<a onclick="modifyYTiframeseektime('1368')">0:22:48</a> is exactly the main what what is  
<a onclick="modifyYTiframeseektime('1371')">0:22:51</a> differentiating is it really the fact  
<a onclick="modifyYTiframeseektime('1372')">0:22:52</a> that it was only the successor of the  
<a onclick="modifyYTiframeseektime('1373')">0:22:53</a> professor it's not that it isn't that  
<a onclick="modifyYTiframeseektime('1376')">0:22:56</a> these are the main differences between  
<a onclick="modifyYTiframeseektime('1378')">0:22:58</a> Sunni and Shiah and I want to add just  
<a onclick="modifyYTiframeseektime('1381')">0:23:01</a> one more thing before and end since it  
<a onclick="modifyYTiframeseektime('1383')">0:23:03</a> is the since it is basically actual rot  
<a onclick="modifyYTiframeseektime('1386')">0:23:06</a> and stuff like that some of my ask what  
<a onclick="modifyYTiframeseektime('1389')">0:23:09</a> is a Shura as a suddenly what you're  
<a onclick="modifyYTiframeseektime('1391')">0:23:11</a> meant to do is fast fasting natural are  
<a onclick="modifyYTiframeseektime('1393')">0:23:13</a> it cleanses your sins for the previous  
<a onclick="modifyYTiframeseektime('1396')">0:23:16</a> of the etc there's lots of good things  
<a onclick="modifyYTiframeseektime('1397')">0:23:17</a> for you for the Shia is clear that I  
<a onclick="modifyYTiframeseektime('1401')">0:23:21</a> think there is evidence historical  
<a onclick="modifyYTiframeseektime('1402')">0:23:22</a> evidence that basically saying he died  
<a onclick="modifyYTiframeseektime('1405')">0:23:25</a> in a genre on this day and so they they  
<a onclick="modifyYTiframeseektime('1408')">0:23:28</a> what they're doing when they cut  
<a onclick="modifyYTiframeseektime('1409')">0:23:29</a> themselves and just to be clear to the  
<a onclick="modifyYTiframeseektime('1411')">0:23:31</a> people is that she has in particular are  
<a onclick="modifyYTiframeseektime('1413')">0:23:33</a> mourning the death of how same or they  
<a onclick="modifyYTiframeseektime('1417')">0:23:37</a> believe that this is a martyrdom that  
<a onclick="modifyYTiframeseektime('1418')">0:23:38</a> deserves to be a Monde but the question  
<a onclick="modifyYTiframeseektime('1421')">0:23:41</a> would then remain who is the ones who  
<a onclick="modifyYTiframeseektime('1423')">0:23:43</a> are the ones who killed and for sane and  
<a onclick="modifyYTiframeseektime('1426')">0:23:46</a> I want to just read a couple of things  
<a onclick="modifyYTiframeseektime('1428')">0:23:48</a> here because I think it is an  
<a onclick="modifyYTiframeseektime('1430')">0:23:50</a> interesting thing I'm not saying this  
<a onclick="modifyYTiframeseektime('1431')">0:23:51</a> again once against me polemical I'm just  
<a onclick="modifyYTiframeseektime('1433')">0:23:53</a> saying this because it's something I've  
<a onclick="modifyYTiframeseektime('1435')">0:23:55</a> come across and Moussaoui is one of the  
<a onclick="modifyYTiframeseektime('1438')">0:23:58</a> share scholars and he says we'll have  
<a onclick="modifyYTiframeseektime('1440')">0:24:00</a> the Hindu so see and he mentions a  
<a onclick="modifyYTiframeseektime('1441')">0:24:01</a> couple of verses some verses and sorry  
<a onclick="modifyYTiframeseektime('1444')">0:24:04</a> some Arthur Samadhi then says were  
<a onclick="modifyYTiframeseektime('1447')">0:24:07</a> heading in the sauce to be in a moment  
<a onclick="modifyYTiframeseektime('1449')">0:24:09</a> home but a little Husein haka theone in  
<a onclick="modifyYTiframeseektime('1452')">0:24:12</a> home Shia to who a edge daytona valley  
<a onclick="modifyYTiframeseektime('1455')">0:24:15</a> mother  
<a onclick="modifyYTiframeseektime('1456')">0:24:16</a> Nahum Mill Arizona and Missoula he says  
<a onclick="modifyYTiframeseektime('1459')">0:24:19</a> that certainly these evidences with  
<a onclick="modifyYTiframeseektime('1461')">0:24:21</a> these things show to us  
<a onclick="modifyYTiframeseektime('1464')">0:24:24</a> who are the the true killers of Hossein  
<a onclick="modifyYTiframeseektime('1468')">0:24:28</a> and he says that it was our grandfather  
<a onclick="modifyYTiframeseektime('1471')">0:24:31</a> or go smoke refer our grandfathers or  
<a onclick="modifyYTiframeseektime('1474')">0:24:34</a> our forefathers yeah so there's no  
<a onclick="modifyYTiframeseektime('1476')">0:24:36</a> reason to to to basically blame man so  
<a onclick="modifyYTiframeseektime('1481')">0:24:41</a> no the Zuni people for that and he said  
<a onclick="modifyYTiframeseektime('1484')">0:24:44</a> and someone else his name as a same  
<a onclick="modifyYTiframeseektime('1485')">0:24:45</a> awesome I mean he says by am saying line  
<a onclick="modifyYTiframeseektime('1489')">0:24:49</a> rock a Sharona elfin brother will be  
<a onclick="modifyYTiframeseektime('1493')">0:24:53</a> maharaja la la la jolla you buy a way  
<a onclick="modifyYTiframeseektime('1497')">0:24:57</a> after him Fionna pima cotton and this is  
<a onclick="modifyYTiframeseektime('1501')">0:25:01</a> in book called again a Shia help is  
<a onclick="modifyYTiframeseektime('1505')">0:25:05</a> Manohar the first just and the page no  
<a onclick="modifyYTiframeseektime('1510')">0:25:10</a> matter history so the point is there's a  
<a onclick="modifyYTiframeseektime('1514')">0:25:14</a> question of who killed him then this is  
<a onclick="modifyYTiframeseektime('1515')">0:25:15</a> one ongoing debate I'm just giving you  
<a onclick="modifyYTiframeseektime('1517')">0:25:17</a> two sources just to give you a taste of  
<a onclick="modifyYTiframeseektime('1519')">0:25:19</a> some competing opinions within she a  
<a onclick="modifyYTiframeseektime('1522')">0:25:22</a> school of thought as to who killed  
<a onclick="modifyYTiframeseektime('1525')">0:25:25</a> saying the point is he he was martyred  
<a onclick="modifyYTiframeseektime('1527')">0:25:27</a> we believe and the thing is I don't want  
<a onclick="modifyYTiframeseektime('1529')">0:25:29</a> anyone to think in their mind that  
<a onclick="modifyYTiframeseektime('1531')">0:25:31</a> Sunnis don't love a debate as long as  
<a onclick="modifyYTiframeseektime('1534')">0:25:34</a> the thing is we have a positive you have  
<a onclick="modifyYTiframeseektime('1538')">0:25:38</a> a beautiful love for elevator for Ali  
<a onclick="modifyYTiframeseektime('1541')">0:25:41</a> has somehow sane and all of we have  
<a onclick="modifyYTiframeseektime('1545')">0:25:45</a> tremendous respect for their i'ma even  
<a onclick="modifyYTiframeseektime('1547')">0:25:47</a> that they refer to because there was  
<a onclick="modifyYTiframeseektime('1548')">0:25:48</a> talk some of our circle character except  
<a onclick="modifyYTiframeseektime('1550')">0:25:50</a> for obviously something that I've just  
<a onclick="modifyYTiframeseektime('1551')">0:25:51</a> mentioned or not some of them are not  
<a onclick="modifyYTiframeseektime('1553')">0:25:53</a> historical characters but some of them  
<a onclick="modifyYTiframeseektime('1554')">0:25:54</a> are historical characters like a Jaffa  
<a onclick="modifyYTiframeseektime('1555')">0:25:55</a> Sadiq we believe that we are attitude  
<a onclick="modifyYTiframeseektime('1558')">0:25:58</a> towards their members of that ever  
<a onclick="modifyYTiframeseektime('1559')">0:25:59</a> positive we think that these were  
<a onclick="modifyYTiframeseektime('1560')">0:26:00</a> knowledgeable human beings but we don't  
<a onclick="modifyYTiframeseektime('1561')">0:26:01</a> believe that those Imams ever claimed  
<a onclick="modifyYTiframeseektime('1563')">0:26:03</a> infallibility or in divine or  
<a onclick="modifyYTiframeseektime('1566')">0:26:06</a> supernatural metaphysical kind of thing  
<a onclick="modifyYTiframeseektime('1571')">0:26:11</a> any traits watching news with that I do  
<a onclick="modifyYTiframeseektime('1576')">0:26:16</a> conclude and I hope that you're going to  
<a onclick="modifyYTiframeseektime('1577')">0:26:17</a> subscribe and I hope that you're going  
<a onclick="modifyYTiframeseektime('1579')">0:26:19</a> to listen if any shy wants to get in  
<a onclick="modifyYTiframeseektime('1581')">0:26:21</a> contact with me to ask me questions you  
<a onclick="modifyYTiframeseektime('1583')">0:26:23</a> can Facebook me because I don't mind  
<a onclick="modifyYTiframeseektime('1587')">0:26:27</a> answering messengers from anyone and  
<a onclick="modifyYTiframeseektime('1589')">0:26:29</a> this is not just a Christian Jewish any  
<a onclick="modifyYTiframeseektime('1592')">0:26:32</a> human being wants to get in contact with  
<a onclick="modifyYTiframeseektime('1594')">0:26:34</a> us you can message us on Facebook my  
<a onclick="modifyYTiframeseektime('1596')">0:26:36</a> things on top of the  
<a onclick="modifyYTiframeseektime('1597')">0:26:37</a> on my channel self-education you can  
<a onclick="modifyYTiframeseektime('1600')">0:26:40</a> come on and message me channel I'll be  
<a onclick="modifyYTiframeseektime('1601')">0:26:41</a> very happy to answer any of your  
<a onclick="modifyYTiframeseektime('1603')">0:26:43</a> questions and I hope you haven't  
<a onclick="modifyYTiframeseektime('1605')">0:26:45</a> offended anybody I just genuinely did  
<a onclick="modifyYTiframeseektime('1607')">0:26:47</a> this because I thought there was a need  
<a onclick="modifyYTiframeseektime('1609')">0:26:49</a> to educate people I wanted to bring  
<a onclick="modifyYTiframeseektime('1614')">0:26:54</a> maybe a more specialist person in she  
<a onclick="modifyYTiframeseektime('1616')">0:26:56</a> Azzam to talk about this but then I've  
<a onclick="modifyYTiframeseektime('1621')">0:27:01</a> gotten content with a few of them and  
<a onclick="modifyYTiframeseektime('1623')">0:27:03</a> told them daily client but Allah Allah  
<a onclick="modifyYTiframeseektime('1626')">0:27:06</a> Allen he maybe this is going to be  
<a onclick="modifyYTiframeseektime('1630')">0:27:10</a> beneficial to you guys and hopefully  
<a onclick="modifyYTiframeseektime('1632')">0:27:12</a> I'll see you soon  
</details>