# Theologian Shocks Muslims With... (2017-09-05)

<iframe loading='lazy' src='https://www.youtube.com/embed/RsLrT1CFyuU'></iframe>

## Description

A brief discussion between Muslim and empirical theologian. Watch what happens!

Subscribe to SCDawah for more great videos like these!
https://www.youtube.com/watch?v=ZKa9hYzpObE

## Summary of [Theologian Shocks Muslims With...](https://www.youtube.com/watch?v=RsLrT1CFyuU)


*<span style="color:red; font-size:125%">This summary is AI generated - there may be inaccuracies</span>. [](/)*

### <a onclick="modifyYTiframeseektime('0')">00:00:00</a> - <a onclick="modifyYTiframeseektime('1200')">00:20:00</a>

The theologian in the video discusses various aspects of Islam and how they compare to other religions. He argues that living in harmony with God is the most appropriate relationship, and that this can be done through following the guidelines in the Quran and the Sunnah. He offers his phone number to the viewer so that they can learn more about Islam.

**<a onclick="modifyYTiframeseektime('0')">00:00:00</a>** The theologian discusses the different attributes of God, and how living in harmony with Him is the most appropriate relationship. He then asks a question about how to be in harmony with God, and discusses how it can be done through living in accordance with His will.
* **<a onclick="modifyYTiframeseektime('300')">00:05:00</a>** The theologian shocks Muslims with the Islamic narrative that the way God communicates with human beings is through prophets who have come a full time. The prophets provide evidence for the message of submission and miracles.
* **<a onclick="modifyYTiframeseektime('600')">00:10:00</a>** The theologian discusses various evidences that human beings were created for a purpose, and that their purpose is to know and submit to God. He argues that these evidences make it difficult to claim that the Quranic revelations could have been guessed by a human.
* **<a onclick="modifyYTiframeseektime('900')">00:15:00</a>** The theologian argues that the Quran is a book that claims to be the Word of God, and that it has never had a controversy. He also argues that Christianity has been violent in comparison to other religions.
* **<a onclick="modifyYTiframeseektime('1200')">00:20:00</a>** The theologian discusses the purpose of life and how it can be achieved by following the guidelines in the Quran and the Sunnah. He then offers his phone number to the viewer so that they can learn more about Islam.

<details><summary><h2>Full transcript with timestamps: CLICK TO EXPAND</h2></summary>

<a onclick="modifyYTiframeseektime('0')">0:00:00</a> look you said that you're looking at all  
<a onclick="modifyYTiframeseektime('2')">0:00:02</a> the different religions yeah once again  
<a onclick="modifyYTiframeseektime('4')">0:00:04</a> you said you don't accept idolatry and  
<a onclick="modifyYTiframeseektime('6')">0:00:06</a> stuff I accept I accept I believe in  
<a onclick="modifyYTiframeseektime('8')">0:00:08</a> that as well I agree with you look the  
<a onclick="modifyYTiframeseektime('10')">0:00:10</a> first thing I want to say to you is from  
<a onclick="modifyYTiframeseektime('12')">0:00:12</a> a Muslim perspective from an Islamic  
<a onclick="modifyYTiframeseektime('13')">0:00:13</a> perspective yeah is that we would say  
<a onclick="modifyYTiframeseektime('15')">0:00:15</a> the starting point for us is a very  
<a onclick="modifyYTiframeseektime('19')">0:00:19</a> strict monotheism yeah so for us and the  
<a onclick="modifyYTiframeseektime('23')">0:00:23</a> sign point is like a monotheism when we  
<a onclick="modifyYTiframeseektime('25')">0:00:25</a> believe that there is an ultimate  
<a onclick="modifyYTiframeseektime('27')">0:00:27</a> creator sustainer an ultimate power that  
<a onclick="modifyYTiframeseektime('30')">0:00:30</a> initiated the universe if that makes  
<a onclick="modifyYTiframeseektime('33')">0:00:33</a> sense  
<a onclick="modifyYTiframeseektime('33')">0:00:33</a> now how feasible does that sounded oh  
<a onclick="modifyYTiframeseektime('36')">0:00:36</a> well Russia was a sign of your mind  
<a onclick="modifyYTiframeseektime('38')">0:00:38</a> yeah I believe that the Creator is what  
<a onclick="modifyYTiframeseektime('42')">0:00:42</a> brings life to the material realm to  
<a onclick="modifyYTiframeseektime('44')">0:00:44</a> Rome is this an illusion yeah we can't  
<a onclick="modifyYTiframeseektime('46')">0:00:46</a> take any of this stuff with us when we  
<a onclick="modifyYTiframeseektime('48')">0:00:48</a> go so the idea of an immortal God from  
<a onclick="modifyYTiframeseektime('51')">0:00:51</a> which we all originated gives us purpose  
<a onclick="modifyYTiframeseektime('53')">0:00:53</a> so you agree with that idea you accept a  
<a onclick="modifyYTiframeseektime('56')">0:00:56</a> lemon you believe in it their creator  
<a onclick="modifyYTiframeseektime('58')">0:00:58</a> yeah mate it hits life to existence yeah  
<a onclick="modifyYTiframeseektime('76')">0:01:16</a> it's different in a create and  
<a onclick="modifyYTiframeseektime('78')">0:01:18</a> creationism creationism you're saying  
<a onclick="modifyYTiframeseektime('83')">0:01:23</a> you reject kind of like the biblical  
<a onclick="modifyYTiframeseektime('84')">0:01:24</a> narrative by at the same time you don't  
<a onclick="modifyYTiframeseektime('87')">0:01:27</a> reject the idea of an all-knowing  
<a onclick="modifyYTiframeseektime('88')">0:01:28</a> all-powerful creator force that side of  
<a onclick="modifyYTiframeseektime('90')">0:01:30</a> the universe yeah okay it's all right so  
<a onclick="modifyYTiframeseektime('93')">0:01:33</a> what I was going to say now since that's  
<a onclick="modifyYTiframeseektime('94')">0:01:34</a> the case now we have to define some of  
<a onclick="modifyYTiframeseektime('96')">0:01:36</a> the attributes of this creator yeah  
<a onclick="modifyYTiframeseektime('98')">0:01:38</a> would you accept that some of the  
<a onclick="modifyYTiframeseektime('99')">0:01:39</a> attributes are creative capacity or  
<a onclick="modifyYTiframeseektime('102')">0:01:42</a> power or knowledge would you say that  
<a onclick="modifyYTiframeseektime('105')">0:01:45</a> these are fundamental to to such a  
<a onclick="modifyYTiframeseektime('108')">0:01:48</a> creativity  
<a onclick="modifyYTiframeseektime('114')">0:01:54</a> yes yeah you're saying is creative the  
<a onclick="modifyYTiframeseektime('125')">0:02:05</a> creative essence of the universe and of  
<a onclick="modifyYTiframeseektime('127')">0:02:07</a> individual souls yeah yes God I too  
<a onclick="modifyYTiframeseektime('129')">0:02:09</a> completely agree  
<a onclick="modifyYTiframeseektime('131')">0:02:11</a> how can we out your intuition for  
<a onclick="modifyYTiframeseektime('133')">0:02:13</a> example it is a fundamental metaphysical  
<a onclick="modifyYTiframeseektime('135')">0:02:15</a> function of all of our personality our  
<a onclick="modifyYTiframeseektime('138')">0:02:18</a> soul how come you know how can we we  
<a onclick="modifyYTiframeseektime('140')">0:02:20</a> can't prove we can't program a machine  
<a onclick="modifyYTiframeseektime('143')">0:02:23</a> for example to do these things so how  
<a onclick="modifyYTiframeseektime('144')">0:02:24</a> can we ever prove that this is I exist  
<a onclick="modifyYTiframeseektime('147')">0:02:27</a> outside yeah it's good all right so  
<a onclick="modifyYTiframeseektime('149')">0:02:29</a> having said that I wanna ask you a  
<a onclick="modifyYTiframeseektime('151')">0:02:31</a> question what's the most appropriate  
<a onclick="modifyYTiframeseektime('153')">0:02:33</a> relationship you can have with such an  
<a onclick="modifyYTiframeseektime('156')">0:02:36</a> entity the most appropriate relationship  
<a onclick="modifyYTiframeseektime('159')">0:02:39</a> is one harmony essentially when you live  
<a onclick="modifyYTiframeseektime('164')">0:02:44</a> in harmony with mankind and with the  
<a onclick="modifyYTiframeseektime('166')">0:02:46</a> planet you are living in harmony with  
<a onclick="modifyYTiframeseektime('168')">0:02:48</a> God there is no separation between the  
<a onclick="modifyYTiframeseektime('171')">0:02:51</a> effects that you enact upon the world  
<a onclick="modifyYTiframeseektime('173')">0:02:53</a> and what comes to you what more moral  
<a onclick="modifyYTiframeseektime('176')">0:02:56</a> consequences okay I accept that to a  
<a onclick="modifyYTiframeseektime('179')">0:02:59</a> certain extent let me show you something  
<a onclick="modifyYTiframeseektime('180')">0:03:00</a> we have our own version of that right so  
<a onclick="modifyYTiframeseektime('182')">0:03:02</a> we say because if you look at these in  
<a onclick="modifyYTiframeseektime('185')">0:03:05</a> traditions they do reference how to be  
<a onclick="modifyYTiframeseektime('187')">0:03:07</a> one with God and these kinds of things  
<a onclick="modifyYTiframeseektime('188')">0:03:08</a> from our perspective we say there is a  
<a onclick="modifyYTiframeseektime('190')">0:03:10</a> way to basically be harmonious with the  
<a onclick="modifyYTiframeseektime('194')">0:03:14</a> will of the creator and the way that  
<a onclick="modifyYTiframeseektime('196')">0:03:16</a> works is basically the Creator has  
<a onclick="modifyYTiframeseektime('199')">0:03:19</a> maintains created the creation and in  
<a onclick="modifyYTiframeseektime('202')">0:03:22</a> the creation you have anima an inanimate  
<a onclick="modifyYTiframeseektime('204')">0:03:24</a> right as for the inanimate objects  
<a onclick="modifyYTiframeseektime('207')">0:03:27</a> around us they are forcibly or obliged  
<a onclick="modifyYTiframeseektime('211')">0:03:31</a> to kind of submit to the will of the of  
<a onclick="modifyYTiframeseektime('214')">0:03:34</a> the Creator right so basically in other  
<a onclick="modifyYTiframeseektime('217')">0:03:37</a> words in order to be one with creation  
<a onclick="modifyYTiframeseektime('219')">0:03:39</a> in that sense not in the sense of actual  
<a onclick="modifyYTiframeseektime('222')">0:03:42</a> physicality but we're talking in that  
<a onclick="modifyYTiframeseektime('224')">0:03:44</a> figurative sense the way to do that  
<a onclick="modifyYTiframeseektime('227')">0:03:47</a> would be to do where everything else  
<a onclick="modifyYTiframeseektime('228')">0:03:48</a> around you is doing so everything around  
<a onclick="modifyYTiframeseektime('230')">0:03:50</a> us if you accept the premise of them an  
<a onclick="modifyYTiframeseektime('233')">0:03:53</a> all-powerful creator is submissive to  
<a onclick="modifyYTiframeseektime('236')">0:03:56</a> that creator we will say by extension it  
<a onclick="modifyYTiframeseektime('238')">0:03:58</a> makes sense to also be submissive to the  
<a onclick="modifyYTiframeseektime('241')">0:04:01</a> creator in the same way that everything  
<a onclick="modifyYTiframeseektime('244')">0:04:04</a> honestly submissives it doesn't make  
<a onclick="modifyYTiframeseektime('245')">0:04:05</a> sense I completely agree yeah submissive  
<a onclick="modifyYTiframeseektime('248')">0:04:08</a> to you know will of the creator exactly  
<a onclick="modifyYTiframeseektime('250')">0:04:10</a> the will of the creator but never to an  
<a onclick="modifyYTiframeseektime('252')">0:04:12</a> authoritarian figure that's why I'm so  
<a onclick="modifyYTiframeseektime('254')">0:04:14</a> against idolatry because anyone these  
<a onclick="modifyYTiframeseektime('256')">0:04:16</a> false prophets are these dogmatic  
<a onclick="modifyYTiframeseektime('259')">0:04:19</a> beliefs these are these are not  
<a onclick="modifyYTiframeseektime('260')">0:04:20</a> following these are not creations of  
<a onclick="modifyYTiframeseektime('261')">0:04:21</a> gods but their creations of human beings  
<a onclick="modifyYTiframeseektime('263')">0:04:23</a> and so never listen to a boss or  
<a onclick="modifyYTiframeseektime('267')">0:04:27</a> something that doesn't agree with your  
<a onclick="modifyYTiframeseektime('269')">0:04:29</a> own sense of morality that comes from  
<a onclick="modifyYTiframeseektime('270')">0:04:30</a> within but live in harmony with with  
<a onclick="modifyYTiframeseektime('273')">0:04:33</a> that that intuition which comes  
<a onclick="modifyYTiframeseektime('275')">0:04:35</a> essentially from God all right so let me  
<a onclick="modifyYTiframeseektime('277')">0:04:37</a> ask you a question because the thing is  
<a onclick="modifyYTiframeseektime('279')">0:04:39</a> it becomes very subjective when it  
<a onclick="modifyYTiframeseektime('280')">0:04:40</a> becomes clouded in that kind of  
<a onclick="modifyYTiframeseektime('282')">0:04:42</a> terminology I'll be honest with you  
<a onclick="modifyYTiframeseektime('283')">0:04:43</a> because what we will say is that if our  
<a onclick="modifyYTiframeseektime('287')">0:04:47</a> essentially our aim in life is to be  
<a onclick="modifyYTiframeseektime('289')">0:04:49</a> submissive to God right in the sense of  
<a onclick="modifyYTiframeseektime('293')">0:04:53</a> the aforementioned if that's the the aim  
<a onclick="modifyYTiframeseektime('296')">0:04:56</a> of life for the purpose of life surely  
<a onclick="modifyYTiframeseektime('298')">0:04:58</a> there should be a uniform way a  
<a onclick="modifyYTiframeseektime('301')">0:05:01</a> universal way that God has allowed human  
<a onclick="modifyYTiframeseektime('304')">0:05:04</a> beings to be able to do that a uniform I  
<a onclick="modifyYTiframeseektime('307')">0:05:07</a> agree yeah so now there we would say  
<a onclick="modifyYTiframeseektime('310')">0:05:10</a> this is the Islamic narrative I've been  
<a onclick="modifyYTiframeseektime('311')">0:05:11</a> completely straightforward with you yeah  
<a onclick="modifyYTiframeseektime('313')">0:05:13</a> the Islamic narrative is that the way  
<a onclick="modifyYTiframeseektime('315')">0:05:15</a> that happens is that the Creator  
<a onclick="modifyYTiframeseektime('317')">0:05:17</a> communicates with the creation and he  
<a onclick="modifyYTiframeseektime('320')">0:05:20</a> does so through prophets who have come a  
<a onclick="modifyYTiframeseektime('322')">0:05:22</a> full time yeah so prophets are a  
<a onclick="modifyYTiframeseektime('324')">0:05:24</a> necessary extension of what is necessary  
<a onclick="modifyYTiframeseektime('327')">0:05:27</a> to happen on appropriate between the  
<a onclick="modifyYTiframeseektime('331')">0:05:31</a> creator and the creation or in this case  
<a onclick="modifyYTiframeseektime('333')">0:05:33</a> human being specifically who are  
<a onclick="modifyYTiframeseektime('334')">0:05:34</a> sentient beings and able to make their  
<a onclick="modifyYTiframeseektime('338')">0:05:38</a> own decisions on free world creatures so  
<a onclick="modifyYTiframeseektime('342')">0:05:42</a> there was a need for prophets there was  
<a onclick="modifyYTiframeseektime('344')">0:05:44</a> a need for the communication between the  
<a onclick="modifyYTiframeseektime('347')">0:05:47</a> creator and the creation and so prophets  
<a onclick="modifyYTiframeseektime('351')">0:05:51</a> came up for salmon Islamic narrative is  
<a onclick="modifyYTiframeseektime('352')">0:05:52</a> that so long as humans were on earth  
<a onclick="modifyYTiframeseektime('354')">0:05:54</a> there were prophets preaching the  
<a onclick="modifyYTiframeseektime('356')">0:05:56</a> message of what we'd call submission  
<a onclick="modifyYTiframeseektime('358')">0:05:58</a> yeah so people like Adam you might have  
<a onclick="modifyYTiframeseektime('361')">0:06:01</a> heard of these kind of biblical names  
<a onclick="modifyYTiframeseektime('363')">0:06:03</a> Adam and Noah and Moses and Jesus all of  
<a onclick="modifyYTiframeseektime('366')">0:06:06</a> those are prophets that came to their  
<a onclick="modifyYTiframeseektime('369')">0:06:09</a> respective peoples and their respective  
<a onclick="modifyYTiframeseektime('370')">0:06:10</a> times and preached the message of  
<a onclick="modifyYTiframeseektime('373')">0:06:13</a> submission to their peoples  
<a onclick="modifyYTiframeseektime('375')">0:06:15</a> does that make sense right so what we  
<a onclick="modifyYTiframeseektime('378')">0:06:18</a> would say is that the messengers came  
<a onclick="modifyYTiframeseektime('380')">0:06:20</a> fundamentally with two different things  
<a onclick="modifyYTiframeseektime('382')">0:06:22</a> they came with a message and they came  
<a onclick="modifyYTiframeseektime('383')">0:06:23</a> with a and evidence-based to  
<a onclick="modifyYTiframeseektime('386')">0:06:26</a> substantiate that message so in the case  
<a onclick="modifyYTiframeseektime('389')">0:06:29</a> of Moses you might have heard of these  
<a onclick="modifyYTiframeseektime('390')">0:06:30</a> stories of basically you know the sea  
<a onclick="modifyYTiframeseektime('393')">0:06:33</a> splitting and all these kind of  
<a onclick="modifyYTiframeseektime('394')">0:06:34</a> different things yeah it's in the Old  
<a onclick="modifyYTiframeseektime('396')">0:06:36</a> Testament it's also in the Quran  
<a onclick="modifyYTiframeseektime('398')">0:06:38</a> these stories are meant to indicate that  
<a onclick="modifyYTiframeseektime('400')">0:06:40</a> these these are evidences yeah that are  
<a onclick="modifyYTiframeseektime('403')">0:06:43</a> used to prove the message of submission  
<a onclick="modifyYTiframeseektime('406')">0:06:46</a> because there's something which break  
<a onclick="modifyYTiframeseektime('407')">0:06:47</a> the natural capacity of physical reality  
<a onclick="modifyYTiframeseektime('409')">0:06:49</a> around us so there are evidence that  
<a onclick="modifyYTiframeseektime('411')">0:06:51</a> basically God is the author of of the  
<a onclick="modifyYTiframeseektime('414')">0:06:54</a> message that these prophets come with  
<a onclick="modifyYTiframeseektime('417')">0:06:57</a> now whereas all of the prophets and  
<a onclick="modifyYTiframeseektime('419')">0:06:59</a> messengers were sent to their respective  
<a onclick="modifyYTiframeseektime('420')">0:07:00</a> a nasty way yes this is this see  
<a onclick="modifyYTiframeseektime('423')">0:07:03</a> spitting why is that everything I mean  
<a onclick="modifyYTiframeseektime('425')">0:07:05</a> why why does that give evidence that  
<a onclick="modifyYTiframeseektime('427')">0:07:07</a> this is otherwise what I got to do with  
<a onclick="modifyYTiframeseektime('429')">0:07:09</a> Mohammed present disease right so I the  
<a onclick="modifyYTiframeseektime('432')">0:07:12</a> see splitting doesn't have anything to  
<a onclick="modifyYTiframeseektime('433')">0:07:13</a> do specifically with Muhammad's message  
<a onclick="modifyYTiframeseektime('435')">0:07:15</a> but I mean although it is know Quran  
<a onclick="modifyYTiframeseektime('437')">0:07:17</a> we're talking specifically about Moses  
<a onclick="modifyYTiframeseektime('439')">0:07:19</a> so in his time and this is an  
<a onclick="modifyYTiframeseektime('441')">0:07:21</a> interesting thing that must have been  
<a onclick="modifyYTiframeseektime('443')">0:07:23</a> alluded to by some of our scholars in  
<a onclick="modifyYTiframeseektime('444')">0:07:24</a> Islam that depending on the societal  
<a onclick="modifyYTiframeseektime('447')">0:07:27</a> kind of what society popular at the time  
<a onclick="modifyYTiframeseektime('451')">0:07:31</a> the the evidence base that the messages  
<a onclick="modifyYTiframeseektime('454')">0:07:34</a> come with suits that so at the time of  
<a onclick="modifyYTiframeseektime('457')">0:07:37</a> kind of what is it the younger would you  
<a onclick="modifyYTiframeseektime('460')">0:07:40</a> call it the middle Empire whether  
<a onclick="modifyYTiframeseektime('461')">0:07:41</a> whoever is in Egypt when ramesses ii was  
<a onclick="modifyYTiframeseektime('464')">0:07:44</a> there and they say that Ramesses is  
<a onclick="modifyYTiframeseektime('467')">0:07:47</a> linked to Pharaoh or not let's mention  
<a onclick="modifyYTiframeseektime('470')">0:07:50</a> the back at this time they were  
<a onclick="modifyYTiframeseektime('472')">0:07:52</a> fascinated with magic magic and all  
<a onclick="modifyYTiframeseektime('474')">0:07:54</a> those kind of things now Moses came with  
<a onclick="modifyYTiframeseektime('479')">0:07:59</a> a you could call it a miracle really  
<a onclick="modifyYTiframeseektime('481')">0:08:01</a> which basically broke the rules of  
<a onclick="modifyYTiframeseektime('484')">0:08:04</a> physical nature yeah and which which  
<a onclick="modifyYTiframeseektime('487')">0:08:07</a> acted as an evidence for his people so  
<a onclick="modifyYTiframeseektime('489')">0:08:09</a> when people saw it they said okay well  
<a onclick="modifyYTiframeseektime('490')">0:08:10</a> this makes sense you see what I'm saying  
<a onclick="modifyYTiframeseektime('492')">0:08:12</a> alright so for us now you will say was  
<a onclick="modifyYTiframeseektime('495')">0:08:15</a> our miracle right because we need some  
<a onclick="modifyYTiframeseektime('497')">0:08:17</a> evidence as well to be able to  
<a onclick="modifyYTiframeseektime('499')">0:08:19</a> substantiate the claim that Prophet  
<a onclick="modifyYTiframeseektime('502')">0:08:22</a> Muhammad is the final messenger because  
<a onclick="modifyYTiframeseektime('504')">0:08:24</a> that's our claim  
<a onclick="modifyYTiframeseektime('505')">0:08:25</a> our claim is that prophet muhammad  
<a onclick="modifyYTiframeseektime('507')">0:08:27</a> whereas all of the other prophets were  
<a onclick="modifyYTiframeseektime('509')">0:08:29</a> sent to their people and their times  
<a onclick="modifyYTiframeseektime('510')">0:08:30</a> Jesus Moses etc Abraham Mohammed was  
<a onclick="modifyYTiframeseektime('513')">0:08:33</a> sent for all peoples at all times  
<a onclick="modifyYTiframeseektime('514')">0:08:34</a> so that's the Islamic narrative so  
<a onclick="modifyYTiframeseektime('517')">0:08:37</a> here's what he's come with as he's come  
<a onclick="modifyYTiframeseektime('520')">0:08:40</a> with an auditory miracle or an auditory  
<a onclick="modifyYTiframeseektime('525')">0:08:45</a> evidence base whereas all the prophets  
<a onclick="modifyYTiframeseektime('527')">0:08:47</a> came before usually with a visual  
<a onclick="modifyYTiframeseektime('529')">0:08:49</a> evidence base so like for example in the  
<a onclick="modifyYTiframeseektime('531')">0:08:51</a> case of Moses the sea splitting was  
<a onclick="modifyYTiframeseektime('533')">0:08:53</a> something for human beings to visualize  
<a onclick="modifyYTiframeseektime('534')">0:08:54</a> and see whereas what we say is the  
<a onclick="modifyYTiframeseektime('537')">0:08:57</a> evidence base for the Islamic message is  
<a onclick="modifyYTiframeseektime('541')">0:09:01</a> actually the Quran itself which is  
<a onclick="modifyYTiframeseektime('543')">0:09:03</a> something actually which is transmitted  
<a onclick="modifyYTiframeseektime('545')">0:09:05</a> orally although it does have of course  
<a onclick="modifyYTiframeseektime('547')">0:09:07</a> written books as well to cooperate and  
<a onclick="modifyYTiframeseektime('549')">0:09:09</a> triangulate the veracity of the oral  
<a onclick="modifyYTiframeseektime('552')">0:09:12</a> message so here  
<a onclick="modifyYTiframeseektime('554')">0:09:14</a> the Quran has many different things  
<a onclick="modifyYTiframeseektime('557')">0:09:17</a> within it which basically would lead  
<a onclick="modifyYTiframeseektime('559')">0:09:19</a> someone to believe that it couldn't have  
<a onclick="modifyYTiframeseektime('561')">0:09:21</a> been because you were saying use a kind  
<a onclick="modifyYTiframeseektime('562')">0:09:22</a> of like rationalistic approach we're  
<a onclick="modifyYTiframeseektime('565')">0:09:25</a> using a progra list a kind of rush  
<a onclick="modifyYTiframeseektime('566')">0:09:26</a> nursing approach you would I would argue  
<a onclick="modifyYTiframeseektime('569')">0:09:29</a> that the Quranic discourse contains  
<a onclick="modifyYTiframeseektime('571')">0:09:31</a> within it an evidence base I'm actually  
<a onclick="modifyYTiframeseektime('574')">0:09:34</a> not a rationalist I'm an empiricist  
<a onclick="modifyYTiframeseektime('576')">0:09:36</a> okay so yeah Russian isn't it oh yeah I  
<a onclick="modifyYTiframeseektime('579')">0:09:39</a> think I got me something yeah yeah we  
<a onclick="modifyYTiframeseektime('581')">0:09:41</a> can't just question we need to  
<a onclick="modifyYTiframeseektime('582')">0:09:42</a> experience far enough I think you're  
<a onclick="modifyYTiframeseektime('585')">0:09:45</a> right about that as well and that's why  
<a onclick="modifyYTiframeseektime('587')">0:09:47</a> by the way the fundamental thing in  
<a onclick="modifyYTiframeseektime('588')">0:09:48</a> Islam is as follows one of the one of  
<a onclick="modifyYTiframeseektime('590')">0:09:50</a> the fundamental messages Islam comes  
<a onclick="modifyYTiframeseektime('592')">0:09:52</a> with is as follows well as Christianity  
<a onclick="modifyYTiframeseektime('594')">0:09:54</a> says we're born with original sin yeah  
<a onclick="modifyYTiframeseektime('596')">0:09:56</a> aslam says no we're born with something  
<a onclick="modifyYTiframeseektime('598')">0:09:58</a> called the filter the filter is a  
<a onclick="modifyYTiframeseektime('600')">0:10:00</a> predisposition just to basically submit  
<a onclick="modifyYTiframeseektime('603')">0:10:03</a> to God not only to know who he is that  
<a onclick="modifyYTiframeseektime('605')">0:10:05</a> the higher power but to submit to him  
<a onclick="modifyYTiframeseektime('607')">0:10:07</a> automatically so this presupposition is  
<a onclick="modifyYTiframeseektime('610')">0:10:10</a> awakened by the various messages or the  
<a onclick="modifyYTiframeseektime('614')">0:10:14</a> various evidences that human being is  
<a onclick="modifyYTiframeseektime('617')">0:10:17</a> there thereafter exposed to so human  
<a onclick="modifyYTiframeseektime('619')">0:10:19</a> being is for example exposed to the  
<a onclick="modifyYTiframeseektime('621')">0:10:21</a> fine-tuning of the universe and you  
<a onclick="modifyYTiframeseektime('623')">0:10:23</a> don't have to be a physicist to read to  
<a onclick="modifyYTiframeseektime('625')">0:10:25</a> appreciate the fine-tuning of the  
<a onclick="modifyYTiframeseektime('626')">0:10:26</a> universe  
<a onclick="modifyYTiframeseektime('626')">0:10:26</a> you can literally look with your naked  
<a onclick="modifyYTiframeseektime('628')">0:10:28</a> eye at the fact that the universe is in  
<a onclick="modifyYTiframeseektime('630')">0:10:30</a> fact finely tuned right and these kind  
<a onclick="modifyYTiframeseektime('634')">0:10:34</a> of things aim to reawaken you  
<a onclick="modifyYTiframeseektime('637')">0:10:37</a> beings from the say of slumber into and  
<a onclick="modifyYTiframeseektime('640')">0:10:40</a> the recollection of God so that's the  
<a onclick="modifyYTiframeseektime('644')">0:10:44</a> main thing of the Islamic message as  
<a onclick="modifyYTiframeseektime('646')">0:10:46</a> with the Quranic discourse as we've said  
<a onclick="modifyYTiframeseektime('648')">0:10:48</a> before has within it evidences we would  
<a onclick="modifyYTiframeseektime('651')">0:10:51</a> say which are very powerful in  
<a onclick="modifyYTiframeseektime('653')">0:10:53</a> convincing people that this is a  
<a onclick="modifyYTiframeseektime('656')">0:10:56</a> basically something which has to be  
<a onclick="modifyYTiframeseektime('658')">0:10:58</a> extra human in other words it couldn't  
<a onclick="modifyYTiframeseektime('661')">0:11:01</a> have been put together by a human  
<a onclick="modifyYTiframeseektime('665')">0:11:05</a> ability so we were saved for example the  
<a onclick="modifyYTiframeseektime('669')">0:11:09</a> fact that the Quran precisely discusses  
<a onclick="modifyYTiframeseektime('673')">0:11:13</a> events that happens in the future and  
<a onclick="modifyYTiframeseektime('674')">0:11:14</a> I'll give you one example of that there  
<a onclick="modifyYTiframeseektime('677')">0:11:17</a> at a time of the Prophet there were the  
<a onclick="modifyYTiframeseektime('679')">0:11:19</a> Romans in the Persians and the Quran  
<a onclick="modifyYTiframeseektime('680')">0:11:20</a> makes very specific predictions about  
<a onclick="modifyYTiframeseektime('683')">0:11:23</a> who will win wars and the case of  
<a onclick="modifyYTiframeseektime('685')">0:11:25</a> chapter 3 verse 1 to 6 it talks about  
<a onclick="modifyYTiframeseektime('687')">0:11:27</a> the Romans decisively going to beat the  
<a onclick="modifyYTiframeseektime('690')">0:11:30</a> the Persians in three to nine years in a  
<a onclick="modifyYTiframeseektime('692')">0:11:32</a> nearby land now these are this is one of  
<a onclick="modifyYTiframeseektime('695')">0:11:35</a> many different predictions of the future  
<a onclick="modifyYTiframeseektime('696')">0:11:36</a> that the Koran makes and that the Sunda  
<a onclick="modifyYTiframeseektime('699')">0:11:39</a> which is the secondary book of the  
<a onclick="modifyYTiframeseektime('701')">0:11:41</a> corpus that Muslims believe in or the  
<a onclick="modifyYTiframeseektime('703')">0:11:43</a> hadith the strong hand make of the  
<a onclick="modifyYTiframeseektime('706')">0:11:46</a> future from a probabilistic perspective  
<a onclick="modifyYTiframeseektime('709')">0:11:49</a> we can say ok well probably if someone  
<a onclick="modifyYTiframeseektime('712')">0:11:52</a> says one thing or two things they might  
<a onclick="modifyYTiframeseektime('714')">0:11:54</a> have guessed them to be correct but if  
<a onclick="modifyYTiframeseektime('716')">0:11:56</a> we put them all together it becomes very  
<a onclick="modifyYTiframeseektime('718')">0:11:58</a> very difficult to make the argument that  
<a onclick="modifyYTiframeseektime('719')">0:11:59</a> he guessed all of those correct  
<a onclick="modifyYTiframeseektime('721')">0:12:01</a> especially when we consider by the way  
<a onclick="modifyYTiframeseektime('723')">0:12:03</a> did you know let me tell you something  
<a onclick="modifyYTiframeseektime('725')">0:12:05</a> in Jehovah's Witness in the in the in  
<a onclick="modifyYTiframeseektime('728')">0:12:08</a> the church of the Jehovah's Witness you  
<a onclick="modifyYTiframeseektime('729')">0:12:09</a> know they predicted and by the way they  
<a onclick="modifyYTiframeseektime('732')">0:12:12</a> believed in this kind of thing where  
<a onclick="modifyYTiframeseektime('733')">0:12:13</a> people bring a you know divinely  
<a onclick="modifyYTiframeseektime('735')">0:12:15</a> inspired they predicted that the day of  
<a onclick="modifyYTiframeseektime('737')">0:12:17</a> judgment will be on 90 in the year 1977  
<a onclick="modifyYTiframeseektime('739')">0:12:19</a> you know that and when that year did not  
<a onclick="modifyYTiframeseektime('742')">0:12:22</a> when the day of judgment didn't happen  
<a onclick="modifyYTiframeseektime('744')">0:12:24</a> on that year they called it the great  
<a onclick="modifyYTiframeseektime('746')">0:12:26</a> disappointment because I mean I don't  
<a onclick="modifyYTiframeseektime('748')">0:12:28</a> know why anyone would be disappointed  
<a onclick="modifyYTiframeseektime('750')">0:12:30</a> for the Rev judgment not happening but  
<a onclick="modifyYTiframeseektime('751')">0:12:31</a> they called it the greatest appointment  
<a onclick="modifyYTiframeseektime('753')">0:12:33</a> the reason why is because the prediction  
<a onclick="modifyYTiframeseektime('754')">0:12:34</a> didn't materialize and that has  
<a onclick="modifyYTiframeseektime('757')">0:12:37</a> repercussions around vacations for the  
<a onclick="modifyYTiframeseektime('759')">0:12:39</a> message because it couldn't have been  
<a onclick="modifyYTiframeseektime('761')">0:12:41</a> divine if it didn't materialize because  
<a onclick="modifyYTiframeseektime('763')">0:12:43</a> it was meant to be from all-knowing  
<a onclick="modifyYTiframeseektime('764')">0:12:44</a> source  
<a onclick="modifyYTiframeseektime('766')">0:12:46</a> the saying the Quran predicted the  
<a onclick="modifyYTiframeseektime('768')">0:12:48</a> Romans were gonna defeat the Persians  
<a onclick="modifyYTiframeseektime('774')">0:12:54</a> the Roman Empire fell out for you  
<a onclick="modifyYTiframeseektime('777')">0:12:57</a> talking about the holy roman first of  
<a onclick="modifyYTiframeseektime('779')">0:12:59</a> all does two Roman empires right so the  
<a onclick="modifyYTiframeseektime('781')">0:13:01</a> Roman Empire started in the year 31 BC  
<a onclick="modifyYTiframeseektime('783')">0:13:03</a> yeah the gala the Gallic Wars and stuff  
<a onclick="modifyYTiframeseektime('786')">0:13:06</a> like that whatever and it continued on  
<a onclick="modifyYTiframeseektime('788')">0:13:08</a> but then the Holy Roman Empire side okay  
<a onclick="modifyYTiframeseektime('791')">0:13:11</a> now the Byzantine Empire which was what  
<a onclick="modifyYTiframeseektime('794')">0:13:14</a> was around at the time of the Prophet  
<a onclick="modifyYTiframeseektime('795')">0:13:15</a> Mohammed and continued on to Matilda at  
<a onclick="modifyYTiframeseektime('797')">0:13:17</a> 1400s this is what we refer to yeah okay  
<a onclick="modifyYTiframeseektime('801')">0:13:21</a> but the Roman Empire as you would have  
<a onclick="modifyYTiframeseektime('803')">0:13:23</a> known from the history lesson that you  
<a onclick="modifyYTiframeseektime('804')">0:13:24</a> know done were in constant wars with the  
<a onclick="modifyYTiframeseektime('807')">0:13:27</a> Sassanid Empire or they also called the  
<a onclick="modifyYTiframeseektime('809')">0:13:29</a> SAS Amiens emphasis a neosaurus yeah  
<a onclick="modifyYTiframeseektime('811')">0:13:31</a> basically they're the Persians and  
<a onclick="modifyYTiframeseektime('813')">0:13:33</a> they're and this was referred to in the  
<a onclick="modifyYTiframeseektime('815')">0:13:35</a> Western history books as the Roman  
<a onclick="modifyYTiframeseektime('816')">0:13:36</a> sassanid wars now the point is the Roman  
<a onclick="modifyYTiframeseektime('819')">0:13:39</a> Empire as you would have known from from  
<a onclick="modifyYTiframeseektime('821')">0:13:41</a> the Year 400 onwards and the profit came  
<a onclick="modifyYTiframeseektime('824')">0:13:44</a> around six hundred thirty you know  
<a onclick="modifyYTiframeseektime('827')">0:13:47</a> around that time so from the seventh  
<a onclick="modifyYTiframeseektime('828')">0:13:48</a> century but from that year from that  
<a onclick="modifyYTiframeseektime('830')">0:13:50</a> time period it was going down there was  
<a onclick="modifyYTiframeseektime('832')">0:13:52</a> a degeneration of the Roman Empire  
<a onclick="modifyYTiframeseektime('833')">0:13:53</a> anyways and so the Sassanid Empire was  
<a onclick="modifyYTiframeseektime('835')">0:13:55</a> much stronger so wonderful I'll make the  
<a onclick="modifyYTiframeseektime('837')">0:13:57</a> claim that the Roman Empire was going to  
<a onclick="modifyYTiframeseektime('839')">0:13:59</a> beat the Sassanid Empire in three to  
<a onclick="modifyYTiframeseektime('841')">0:14:01</a> nine years and in a pile and all these  
<a onclick="modifyYTiframeseektime('843')">0:14:03</a> different things it wasn't it was a kind  
<a onclick="modifyYTiframeseektime('845')">0:14:05</a> of ridiculous claim if you think about  
<a onclick="modifyYTiframeseektime('846')">0:14:06</a> from a probability perspective it's the  
<a onclick="modifyYTiframeseektime('848')">0:14:08</a> equivalent of betting on a very low team  
<a onclick="modifyYTiframeseektime('851')">0:14:11</a> maybe in the Champions League being a  
<a onclick="modifyYTiframeseektime('853')">0:14:13</a> very high team may be in the top five in  
<a onclick="modifyYTiframeseektime('855')">0:14:15</a> the in the Premier League right  
<a onclick="modifyYTiframeseektime('857')">0:14:17</a> I'm betting that they'll breed them in a  
<a onclick="modifyYTiframeseektime('859')">0:14:19</a> certain way in a certain place in a  
<a onclick="modifyYTiframeseektime('860')">0:14:20</a> certain time period all these different  
<a onclick="modifyYTiframeseektime('862')">0:14:22</a> things so probabilistically the odds are  
<a onclick="modifyYTiframeseektime('864')">0:14:24</a> very low for that and that's one example  
<a onclick="modifyYTiframeseektime('865')">0:14:25</a> but there are many different examples  
<a onclick="modifyYTiframeseektime('866')">0:14:26</a> for example the conquest of Arabia by  
<a onclick="modifyYTiframeseektime('869')">0:14:29</a> the Muslims the fact that other nations  
<a onclick="modifyYTiframeseektime('871')">0:14:31</a> will fall into the hands of the Muslims  
<a onclick="modifyYTiframeseektime('873')">0:14:33</a> like Egypt and Yemen and Syria and  
<a onclick="modifyYTiframeseektime('874')">0:14:34</a> Jordan you know and Pakistan and India a  
<a onclick="modifyYTiframeseektime('877')">0:14:37</a> syndrome they're all these different  
<a onclick="modifyYTiframeseektime('878')">0:14:38</a> places which are now part of the robe  
<a onclick="modifyYTiframeseektime('880')">0:14:40</a> the Islamic empire  
<a onclick="modifyYTiframeseektime('882')">0:14:42</a> have been predicted to be conquered by  
<a onclick="modifyYTiframeseektime('885')">0:14:45</a> them by Muslim hands by basically so all  
<a onclick="modifyYTiframeseektime('888')">0:14:48</a> of this is when we put this into a  
<a onclick="modifyYTiframeseektime('890')">0:14:50</a> probability generator it becomes very  
<a onclick="modifyYTiframeseektime('892')">0:14:52</a> difficult to argue that could this all  
<a onclick="modifyYTiframeseektime('894')">0:14:54</a> could have been guessed and I would  
<a onclick="modifyYTiframeseektime('895')">0:14:55</a> actually argue and make a very daring  
<a onclick="modifyYTiframeseektime('897')">0:14:57</a> claim here  
<a onclick="modifyYTiframeseektime('897')">0:14:57</a> this is this kind of frequency and  
<a onclick="modifyYTiframeseektime('900')">0:15:00</a> accuracy of predictions has never been  
<a onclick="modifyYTiframeseektime('903')">0:15:03</a> able has never been predicted by anyone  
<a onclick="modifyYTiframeseektime('905')">0:15:05</a> I don't know if any human being if you  
<a onclick="modifyYTiframeseektime('907')">0:15:07</a> want to bring Nostradamus or the the job  
<a onclick="modifyYTiframeseektime('910')">0:15:10</a> is wearing this or anyone that you want  
<a onclick="modifyYTiframeseektime('911')">0:15:11</a> to that have made predictions of the  
<a onclick="modifyYTiframeseektime('912')">0:15:12</a> future with this many with this much  
<a onclick="modifyYTiframeseektime('914')">0:15:14</a> frequency and detail which have actually  
<a onclick="modifyYTiframeseektime('917')">0:15:17</a> materialized in the way that they've  
<a onclick="modifyYTiframeseektime('918')">0:15:18</a> been to your life do you see what I'm  
<a onclick="modifyYTiframeseektime('922')">0:15:22</a> saying  
<a onclick="modifyYTiframeseektime('922')">0:15:22</a> so here when we say we have evidence for  
<a onclick="modifyYTiframeseektime('924')">0:15:24</a> the veracity and the truthfulness of  
<a onclick="modifyYTiframeseektime('926')">0:15:26</a> Islam we're not just saying that we have  
<a onclick="modifyYTiframeseektime('929')">0:15:29</a> kind of superfluous evidence or kind of  
<a onclick="modifyYTiframeseektime('931')">0:15:31</a> arbitrary subjective type evidences our  
<a onclick="modifyYTiframeseektime('934')">0:15:34</a> evidences are probably our actually can  
<a onclick="modifyYTiframeseektime('938')">0:15:38</a> be analyzed objectively you see what I'm  
<a onclick="modifyYTiframeseektime('941')">0:15:41</a> saying this is not regarding the fact  
<a onclick="modifyYTiframeseektime('945')">0:15:45</a> that the Quran is also in and of itself  
<a onclick="modifyYTiframeseektime('948')">0:15:48</a> a book that claims that has no  
<a onclick="modifyYTiframeseektime('949')">0:15:49</a> contradictions a book that challenge is  
<a onclick="modifyYTiframeseektime('951')">0:15:51</a> mankind to produce a chapter like it a  
<a onclick="modifyYTiframeseektime('953')">0:15:53</a> book of the we would actually I make the  
<a onclick="modifyYTiframeseektime('956')">0:15:56</a> argument that the only religious ancient  
<a onclick="modifyYTiframeseektime('959')">0:15:59</a> religious book ancient religious book  
<a onclick="modifyYTiframeseektime('960')">0:16:00</a> which has been preserved in terms of its  
<a onclick="modifyYTiframeseektime('963')">0:16:03</a> its material its corpus  
<a onclick="modifyYTiframeseektime('966')">0:16:06</a> we've never the Muslims have never had a  
<a onclick="modifyYTiframeseektime('968')">0:16:08</a> controversy and this can go on the  
<a onclick="modifyYTiframeseektime('970')">0:16:10</a> record and believe me I'm here every  
<a onclick="modifyYTiframeseektime('972')">0:16:12</a> week and people trying they all trying  
<a onclick="modifyYTiframeseektime('973')">0:16:13</a> maybe but I can say this completely  
<a onclick="modifyYTiframeseektime('976')">0:16:16</a> clearly the Muslims have never had a  
<a onclick="modifyYTiframeseektime('978')">0:16:18</a> controversy on what constitutes the  
<a onclick="modifyYTiframeseektime('981')">0:16:21</a> Quran never it's never happened they've  
<a onclick="modifyYTiframeseektime('982')">0:16:22</a> had controversies on everything else but  
<a onclick="modifyYTiframeseektime('984')">0:16:24</a> they've never had a controversy on what  
<a onclick="modifyYTiframeseektime('986')">0:16:26</a> constitutes the Quran the Christians  
<a onclick="modifyYTiframeseektime('988')">0:16:28</a> around the other hand they are differing  
<a onclick="modifyYTiframeseektime('991')">0:16:31</a> on how many how many books on in the  
<a onclick="modifyYTiframeseektime('994')">0:16:34</a> biblical canon the the process say  
<a onclick="modifyYTiframeseektime('996')">0:16:36</a> seventy two books the Catholics say  
<a onclick="modifyYTiframeseektime('998')">0:16:38</a> sorry the Protestants am 66 the  
<a onclick="modifyYTiframeseektime('1000')">0:16:40</a> Catholics say 72 the Eastern Orthodox  
<a onclick="modifyYTiframeseektime('1002')">0:16:42</a> say if you want so here really is not  
<a onclick="modifyYTiframeseektime('1004')">0:16:44</a> how many books are in the in the Bible  
<a onclick="modifyYTiframeseektime('1005')">0:16:45</a> let alone the manuscripts in these  
<a onclick="modifyYTiframeseektime('1007')">0:16:47</a> things so here what we're saying is not  
<a onclick="modifyYTiframeseektime('1008')">0:16:48</a> only do our evidences there are  
<a onclick="modifyYTiframeseektime('1011')">0:16:51</a> analyzable  
<a onclick="modifyYTiframeseektime('1013')">0:16:53</a> just a word but also we have that which  
<a onclick="modifyYTiframeseektime('1016')">0:16:56</a> is necessary for a book to be a Word of  
<a onclick="modifyYTiframeseektime('1019')">0:16:59</a> God a preserved book free from  
<a onclick="modifyYTiframeseektime('1022')">0:17:02</a> contradiction and uneme table so with  
<a onclick="modifyYTiframeseektime('1025')">0:17:05</a> that you see the power of the  
<a onclick="modifyYTiframeseektime('1028')">0:17:08</a> the the argument yeah I believe that  
<a onclick="modifyYTiframeseektime('1031')">0:17:11</a> it's been like you know you when you buy  
<a onclick="modifyYTiframeseektime('1034')">0:17:14</a> a software for the first time and you  
<a onclick="modifyYTiframeseektime('1036')">0:17:16</a> install updates yes like Christianity  
<a onclick="modifyYTiframeseektime('1039')">0:17:19</a> came along that was one update and we've  
<a onclick="modifyYTiframeseektime('1041')">0:17:21</a> had Islam yeah I think that's a good way  
<a onclick="modifyYTiframeseektime('1044')">0:17:24</a> the thing is that we the only problem  
<a onclick="modifyYTiframeseektime('1049')">0:17:29</a> was yeah yeah in any religion is  
<a onclick="modifyYTiframeseektime('1051')">0:17:31</a> violence as you know yes  
<a onclick="modifyYTiframeseektime('1053')">0:17:33</a> we've always seen this violence in all  
<a onclick="modifyYTiframeseektime('1056')">0:17:36</a> religions I'm not yes yes yeah I think  
<a onclick="modifyYTiframeseektime('1060')">0:17:40</a> that the only problem is that the thing  
<a onclick="modifyYTiframeseektime('1062')">0:17:42</a> that people blame Islam for there is why  
<a onclick="modifyYTiframeseektime('1066')">0:17:46</a> are they so violent yeah there is they  
<a onclick="modifyYTiframeseektime('1069')">0:17:49</a> have to kind of look at themselves know  
<a onclick="modifyYTiframeseektime('1071')">0:17:51</a> what the Western intervention we also  
<a onclick="modifyYTiframeseektime('1073')">0:17:53</a> have to exactly exactly know that area  
<a onclick="modifyYTiframeseektime('1076')">0:17:56</a> of the world has been a kind of  
<a onclick="modifyYTiframeseektime('1078')">0:17:58</a> hodgepodge of different civilizations  
<a onclick="modifyYTiframeseektime('1081')">0:18:01</a> but you had Boyd Rome to the west yet  
<a onclick="modifyYTiframeseektime('1082')">0:18:02</a> the Mongoose Arabs were all competing  
<a onclick="modifyYTiframeseektime('1085')">0:18:05</a> and and of course that violence is very  
<a onclick="modifyYTiframeseektime('1089')">0:18:09</a> harmful to them and it causes arguments  
<a onclick="modifyYTiframeseektime('1095')">0:18:15</a> okay I accept what you're saying you're  
<a onclick="modifyYTiframeseektime('1097')">0:18:17</a> right violence is never a good thing but  
<a onclick="modifyYTiframeseektime('1098')">0:18:18</a> that's a in defense of Islam yeah when  
<a onclick="modifyYTiframeseektime('1103')">0:18:23</a> people accuse Islamic world of based on  
<a onclick="modifyYTiframeseektime('1105')">0:18:25</a> violence yeah look at the cultural  
<a onclick="modifyYTiframeseektime('1106')">0:18:26</a> context here yeah exactly I mean if we  
<a onclick="modifyYTiframeseektime('1109')">0:18:29</a> look at the raw data you'll find that in  
<a onclick="modifyYTiframeseektime('1112')">0:18:32</a> terms of population I would actually  
<a onclick="modifyYTiframeseektime('1115')">0:18:35</a> make the argument that it's like Muslim  
<a onclick="modifyYTiframeseektime('1117')">0:18:37</a> people as a proportion of the population  
<a onclick="modifyYTiframeseektime('1119')">0:18:39</a> are probably the least violent and now  
<a onclick="modifyYTiframeseektime('1121')">0:18:41</a> that sounds ridiculous in the last  
<a onclick="modifyYTiframeseektime('1122')">0:18:42</a> hundred years they have proven to be the  
<a onclick="modifyYTiframeseektime('1124')">0:18:44</a> least violent people in the world in  
<a onclick="modifyYTiframeseektime('1126')">0:18:46</a> terms of religion why and this gotta  
<a onclick="modifyYTiframeseektime('1129')">0:18:49</a> sound ridiculous some guys laughing the  
<a onclick="modifyYTiframeseektime('1132')">0:18:52</a> head off in a home there believe me but  
<a onclick="modifyYTiframeseektime('1133')">0:18:53</a> if you count the amount of people that  
<a onclick="modifyYTiframeseektime('1135')">0:18:55</a> have died as a result of the  
<a onclick="modifyYTiframeseektime('1137')">0:18:57</a> imperialistic war world war one world  
<a onclick="modifyYTiframeseektime('1139')">0:18:59</a> war two also if you count the full Wars  
<a onclick="modifyYTiframeseektime('1141')">0:19:01</a> of America and if we consider state  
<a onclick="modifyYTiframeseektime('1143')">0:19:03</a> violence as a kind of violence which we  
<a onclick="modifyYTiframeseektime('1145')">0:19:05</a> should there's no reason for us not to  
<a onclick="modifyYTiframeseektime('1146')">0:19:06</a> we'll come to the conclusion that the  
<a onclick="modifyYTiframeseektime('1148')">0:19:08</a> most violent people have been atheists  
<a onclick="modifyYTiframeseektime('1150')">0:19:10</a> like Stalin others and Christians if you  
<a onclick="modifyYTiframeseektime('1154')">0:19:14</a> consider Hitler or Christian I don't  
<a onclick="modifyYTiframeseektime('1155')">0:19:15</a> know why he considered himself and  
<a onclick="modifyYTiframeseektime('1157')">0:19:17</a> people like him so on and so forth it's  
<a onclick="modifyYTiframeseektime('1160')">0:19:20</a> not actually for  
<a onclick="modifyYTiframeseektime('1161')">0:19:21</a> reasonably and in the grand scheme of  
<a onclick="modifyYTiframeseektime('1163')">0:19:23</a> things as a proportion of the population  
<a onclick="modifyYTiframeseektime('1166')">0:19:26</a> especially if we talk about the colonial  
<a onclick="modifyYTiframeseektime('1168')">0:19:28</a> period because most of the Muslim world  
<a onclick="modifyYTiframeseektime('1169')">0:19:29</a> was subjugated under the colonial or  
<a onclick="modifyYTiframeseektime('1172')">0:19:32</a> Western rule it fares actually quite  
<a onclick="modifyYTiframeseektime('1174')">0:19:34</a> well but having said that because of  
<a onclick="modifyYTiframeseektime('1176')">0:19:36</a> kind of the post Cold War terroristic  
<a onclick="modifyYTiframeseektime('1179')">0:19:39</a> backlash that we've been getting and the  
<a onclick="modifyYTiframeseektime('1182')">0:19:42</a> the focus on terrorism so a lot of  
<a onclick="modifyYTiframeseektime('1185')">0:19:45</a> people now will think of Islam as a  
<a onclick="modifyYTiframeseektime('1187')">0:19:47</a> violent religion but we shouldn't think  
<a onclick="modifyYTiframeseektime('1190')">0:19:50</a> just looking at the raw data of Islam as  
<a onclick="modifyYTiframeseektime('1192')">0:19:52</a> any more or less violent as of the war  
<a onclick="modifyYTiframeseektime('1194')">0:19:54</a> face who have proponents of those face  
<a onclick="modifyYTiframeseektime('1197')">0:19:57</a> actually performing more more violence  
<a onclick="modifyYTiframeseektime('1199')">0:19:59</a> in the in the span of the last 100 150  
<a onclick="modifyYTiframeseektime('1202')">0:20:02</a> years than muslims but going back to  
<a onclick="modifyYTiframeseektime('1205')">0:20:05</a> what i was saying i was saying that look  
<a onclick="modifyYTiframeseektime('1207')">0:20:07</a> we have an argument for basically the  
<a onclick="modifyYTiframeseektime('1211')">0:20:11</a> the truthfulness of islam yeah I'm not  
<a onclick="modifyYTiframeseektime('1214')">0:20:14</a> gonna lie to you I believe I just want  
<a onclick="modifyYTiframeseektime('1216')">0:20:16</a> to be straightforward with you yeah  
<a onclick="modifyYTiframeseektime('1218')">0:20:18</a> because I like you you know you're a  
<a onclick="modifyYTiframeseektime('1219')">0:20:19</a> nice guy he's dressed well you know I  
<a onclick="modifyYTiframeseektime('1221')">0:20:21</a> came here not I didn't even and even  
<a onclick="modifyYTiframeseektime('1223')">0:20:23</a> dressed properly today you know this  
<a onclick="modifyYTiframeseektime('1226')">0:20:26</a> game you know I was gonna I was gonna  
<a onclick="modifyYTiframeseektime('1228')">0:20:28</a> come I wasn't gonna come today but I'm  
<a onclick="modifyYTiframeseektime('1230')">0:20:30</a> happy I did because I had a conversation  
<a onclick="modifyYTiframeseektime('1231')">0:20:31</a> with you yeah listen to me I'm gonna  
<a onclick="modifyYTiframeseektime('1235')">0:20:35</a> tell you directly I believe that the  
<a onclick="modifyYTiframeseektime('1237')">0:20:37</a> purpose of life is to worship God  
<a onclick="modifyYTiframeseektime('1239')">0:20:39</a> through submission not only is that the  
<a onclick="modifyYTiframeseektime('1242')">0:20:42</a> case I believe that the guidelines for  
<a onclick="modifyYTiframeseektime('1245')">0:20:45</a> human beings is therefore the Quran  
<a onclick="modifyYTiframeseektime('1248')">0:20:48</a> because it's the final book for the  
<a onclick="modifyYTiframeseektime('1249')">0:20:49</a> reasons I've mentioned so if you want to  
<a onclick="modifyYTiframeseektime('1252')">0:20:52</a> live a fruitful life which is in  
<a onclick="modifyYTiframeseektime('1253')">0:20:53</a> compliance with the will of God it's got  
<a onclick="modifyYTiframeseektime('1256')">0:20:56</a> to be done through the injunctions of  
<a onclick="modifyYTiframeseektime('1258')">0:20:58</a> the Quran and the Sunnah now I've given  
<a onclick="modifyYTiframeseektime('1262')">0:21:02</a> you the reasons why like I've given you  
<a onclick="modifyYTiframeseektime('1264')">0:21:04</a> some what of an epistemological base as  
<a onclick="modifyYTiframeseektime('1266')">0:21:06</a> to why we believe in what we believe do  
<a onclick="modifyYTiframeseektime('1269')">0:21:09</a> you accept that that epistemological  
<a onclick="modifyYTiframeseektime('1271')">0:21:11</a> base I have given you is an argument  
<a onclick="modifyYTiframeseektime('1274')">0:21:14</a> which can be accepted or should be  
<a onclick="modifyYTiframeseektime('1276')">0:21:16</a> accepted based on the evidences before I  
<a onclick="modifyYTiframeseektime('1280')">0:21:20</a> think that unless someone comes up with  
<a onclick="modifyYTiframeseektime('1283')">0:21:23</a> a more up-to-date version of truth  
<a onclick="modifyYTiframeseektime('1286')">0:21:26</a> the illogic courtroom yes I suppose to  
<a onclick="modifyYTiframeseektime('1290')">0:21:30</a> make sense to accept that as the most  
<a onclick="modifyYTiframeseektime('1293')">0:21:33</a> up-to-date fantastic so what we can do  
<a onclick="modifyYTiframeseektime('1297')">0:21:37</a> is we can do the Shahada  
<a onclick="modifyYTiframeseektime('1299')">0:21:39</a> right now this ad is the declaration of  
<a onclick="modifyYTiframeseektime('1303')">0:21:43</a> faith now you believe in you believe in  
<a onclick="modifyYTiframeseektime('1305')">0:21:45</a> what I've just said you would you agree  
<a onclick="modifyYTiframeseektime('1306')">0:21:46</a> that the Quran is probably the Word of  
<a onclick="modifyYTiframeseektime('1308')">0:21:48</a> God  
<a onclick="modifyYTiframeseektime('1309')">0:21:49</a> based on what I've soldiers okay so what  
<a onclick="modifyYTiframeseektime('1314')">0:21:54</a> do you do now is you is good now to  
<a onclick="modifyYTiframeseektime('1317')">0:21:57</a> become a Muslim and what the word Muslim  
<a onclick="modifyYTiframeseektime('1319')">0:21:59</a> actually means is someone who submits  
<a onclick="modifyYTiframeseektime('1320')">0:22:00</a> their will to God as we've said in the  
<a onclick="modifyYTiframeseektime('1323')">0:22:03</a> beginning that's the whole point of it  
<a onclick="modifyYTiframeseektime('1324')">0:22:04</a> and what I'll do is I'll give you my  
<a onclick="modifyYTiframeseektime('1325')">0:22:05</a> number and then you will discuss more  
<a onclick="modifyYTiframeseektime('1328')">0:22:08</a> like you know how to kind of perform  
<a onclick="modifyYTiframeseektime('1331')">0:22:11</a> your rituals and these kind of things  
<a onclick="modifyYTiframeseektime('1332')">0:22:12</a> and get your a package of things to do  
<a onclick="modifyYTiframeseektime('1336')">0:22:16</a> in watch and so I will take it easy on  
<a onclick="modifyYTiframeseektime('1337')">0:22:17</a> you but how do you feel should go for it  
<a onclick="modifyYTiframeseektime('1340')">0:22:20</a> then I I wouldn't call myself not to  
<a onclick="modifyYTiframeseektime('1343')">0:22:23</a> much already practicing it's nothing new  
<a onclick="modifyYTiframeseektime('1347')">0:22:27</a> for me I was very very much like that  
<a onclick="modifyYTiframeseektime('1349')">0:22:29</a> would you like that okay let's do with  
<a onclick="modifyYTiframeseektime('1351')">0:22:31</a> them so I'm gonna say an hour but you  
<a onclick="modifyYTiframeseektime('1353')">0:22:33</a> you answer or you just kind of follow  
<a onclick="modifyYTiframeseektime('1355')">0:22:35</a> what I say  
<a onclick="modifyYTiframeseektime('1355')">0:22:35</a> and then I'll say you in English okay  
<a onclick="modifyYTiframeseektime('1357')">0:22:37</a> yeah I'll say another person so follow I  
<a onclick="modifyYTiframeseektime('1360')">0:22:40</a> say ash-hadu you have to say yeah I'll  
<a onclick="modifyYTiframeseektime('1364')">0:22:44</a> say in Arabic and then you say Ann Arbor  
<a onclick="modifyYTiframeseektime('1365')">0:22:45</a> and then I'll say English first yeah  
<a onclick="modifyYTiframeseektime('1368')">0:22:48</a> okay so say a shadow I'll say that so  
<a onclick="modifyYTiframeseektime('1378')">0:22:58</a> what you're going to say is I bear  
<a onclick="modifyYTiframeseektime('1379')">0:22:59</a> witness that there's only one God worthy  
<a onclick="modifyYTiframeseektime('1381')">0:23:01</a> of worship being submissive to which is  
<a onclick="modifyYTiframeseektime('1383')">0:23:03</a> we believe that the God that we prefer  
<a onclick="modifyYTiframeseektime('1384')">0:23:04</a> yeah and that the Prophet is the final  
<a onclick="modifyYTiframeseektime('1386')">0:23:06</a> messenger okay okay  
<a onclick="modifyYTiframeseektime('1388')">0:23:08</a> ash hadu an LA ilaha illallah WA ash  
<a onclick="modifyYTiframeseektime('1395')">0:23:15</a> hadu ana muhammadan rasulullah  
<a onclick="modifyYTiframeseektime('1404')">0:23:24</a> 1 million Ryo a family or friends on  
<a onclick="modifyYTiframeseektime('1423')">0:23:43</a> your sleep so now I'm going to give you  
<a onclick="modifyYTiframeseektime('1442')">0:24:02</a> my number  
<a onclick="modifyYTiframeseektime('1442')">0:24:02</a> off-camera this and then you can call me  
<a onclick="modifyYTiframeseektime('1446')">0:24:06</a> for anything you need yeah and by the  
<a onclick="modifyYTiframeseektime('1448')">0:24:08</a> way we're probably going to get  
<a onclick="modifyYTiframeseektime('1448')">0:24:08</a> something to eat afterwards you're  
<a onclick="modifyYTiframeseektime('1449')">0:24:09</a> definitely invite today's eat by the way  
<a onclick="modifyYTiframeseektime('1451')">0:24:11</a> it's one of the exemptions of each so  
<a onclick="modifyYTiframeseektime('1453')">0:24:13</a> you're already in a Muslim celebration  
<a onclick="modifyYTiframeseektime('1455')">0:24:15</a> alright you almost give you my number  
<a onclick="modifyYTiframeseektime('1457')">0:24:17</a> I'm going front of you solutions guys  
<a onclick="modifyYTiframeseektime('1467')">0:24:27</a> please  
</details>