# Why Atheists Don't Believe in God. (2017-11-29)

<iframe loading='lazy' src='https://www.youtube.com/embed/Tx2ZiRQ1luM'></iframe>

## Description

This is an important philosophical question that aims to probe an atheist's insistence for evidence. What kind of evidence is an Atheist actually looking for ?

## Summary of [Why Atheists Don't Believe in God.](https://www.youtube.com/watch?v=Tx2ZiRQ1luM)


*<span style="color:red; font-size:125%">This summary is AI generated - there may be inaccuracies</span>. [](/)*

### <a onclick="modifyYTiframeseektime('0')">00:00:00</a> - <a onclick="modifyYTiframeseektime('600')">00:10:00</a>

Atheists don't believe in God because they think it is unreasonable and there is overwhelming evidence that suggests God does not exist. discusses how atheists are satisfied with evidence that includes mathematical truths and scientific truths, but these truths can only be proven through concepts that can only be experienced in the mind. He argues that, for atheists, the true standard is a probabilistic one, in which we are able to reason that almost anything is likely to be true.

**<a onclick="modifyYTiframeseektime('0')">00:00:00</a>** Atheists don't believe in God because they are satisfied with evidence that includes mathematical truths and scientific truths, but these truths can only be proven through concepts that can only be experienced in the mind.
* **<a onclick="modifyYTiframeseektime('300')">00:05:00</a>* Discusses mathematical inconsistencies and how they imply that God does not exist. He compares this to the life paradox, in which if someone is lying, then their statement is not alive. then goes on to discuss the concept of a "true standard" for determining whether something is true or not. He argues that, for atheists, the true standard is a probabilistic one, in which we are able to reason that almost anything is likely to be true. He finishes by discussing the fine-tuning of the universe and how it suggests that a designer must exist.
* **<a onclick="modifyYTiframeseektime('600')">00:10:00</a>** argues that atheists don't believe in God because it is unreasonable for them to do so and because there is overwhelming probabilistic evidence that God does exist.

<details><summary><h2>Full transcript with timestamps: CLICK TO EXPAND</h2></summary>

<a onclick="modifyYTiframeseektime('24')">0:00:24</a> [Music]  
<a onclick="modifyYTiframeseektime('38')">0:00:38</a> before that even I'm trying to put  
<a onclick="modifyYTiframeseektime('42')">0:00:42</a> myself in the shoes of the Atheist robot  
<a onclick="modifyYTiframeseektime('43')">0:00:43</a> yeah I will go through some exercises  
<a onclick="modifyYTiframeseektime('46')">0:00:46</a> some mental exercises the first thing  
<a onclick="modifyYTiframeseektime('52')">0:00:52</a> that's thought to be asked is when  
<a onclick="modifyYTiframeseektime('55')">0:00:55</a> you're asking a student related say your  
<a onclick="modifyYTiframeseektime('57')">0:00:57</a> nature the question is what is your true  
<a onclick="modifyYTiframeseektime('60')">0:01:00</a> standards I mean that's an important  
<a onclick="modifyYTiframeseektime('63')">0:01:03</a> thing to establish the atheist is an  
<a onclick="modifyYTiframeseektime('66')">0:01:06</a> atheist because she's not satisfied for  
<a onclick="modifyYTiframeseektime('68')">0:01:08</a> the most part with the evidences of  
<a onclick="modifyYTiframeseektime('71')">0:01:11</a> theism so he becomes an atheist and for  
<a onclick="modifyYTiframeseektime('74')">0:01:14</a> the most part most atheists are negative  
<a onclick="modifyYTiframeseektime('77')">0:01:17</a> eighties so there are atheists because  
<a onclick="modifyYTiframeseektime('79')">0:01:19</a> of a lack of belief of something not  
<a onclick="modifyYTiframeseektime('82')">0:01:22</a> because they have a positive argument  
<a onclick="modifyYTiframeseektime('84')">0:01:24</a> again against the existence of God so  
<a onclick="modifyYTiframeseektime('87')">0:01:27</a> for the most part you can say that most  
<a onclick="modifyYTiframeseektime('88')">0:01:28</a> atheists are negative eight years at  
<a onclick="modifyYTiframeseektime('91')">0:01:31</a> some thought were agnostic so then they  
<a onclick="modifyYTiframeseektime('94')">0:01:34</a> wouldn't necessarily say 100% there's  
<a onclick="modifyYTiframeseektime('96')">0:01:36</a> nothing you know  
<a onclick="modifyYTiframeseektime('98')">0:01:38</a> they just say that we're not satisfied  
<a onclick="modifyYTiframeseektime('100')">0:01:40</a> completely with the evidences so the  
<a onclick="modifyYTiframeseektime('104')">0:01:44</a> first thing has to be asked is what kind  
<a onclick="modifyYTiframeseektime('106')">0:01:46</a> of evidence is would you be satisfied  
<a onclick="modifyYTiframeseektime('108')">0:01:48</a> with and just thinking mentally I came  
<a onclick="modifyYTiframeseektime('113')">0:01:53</a> with three possible things  
<a onclick="modifyYTiframeseektime('116')">0:01:56</a> which atheists could not deny right  
<a onclick="modifyYTiframeseektime('119')">0:01:59</a> number one is incorrigibility which  
<a onclick="modifyYTiframeseektime('124')">0:02:04</a> means something which is not changing  
<a onclick="modifyYTiframeseektime('125')">0:02:05</a> yeah so if something is not changing it  
<a onclick="modifyYTiframeseektime('128')">0:02:08</a> becomes a good evidence  
<a onclick="modifyYTiframeseektime('130')">0:02:10</a> number two is eternality which is click  
<a onclick="modifyYTiframeseektime('133')">0:02:13</a> link to incorrigibility and number three  
<a onclick="modifyYTiframeseektime('137')">0:02:17</a> you could say ain't necessarily true so  
<a onclick="modifyYTiframeseektime('141')">0:02:21</a> for example it's contingently true dat  
<a onclick="modifyYTiframeseektime('143')">0:02:23</a> ammonia gray jumpier but it's not  
<a onclick="modifyYTiframeseektime('146')">0:02:26</a> necessarily true that I'm wearing a  
<a onclick="modifyYTiframeseektime('147')">0:02:27</a> chopped-up we're trying not use too much  
<a onclick="modifyYTiframeseektime('151')">0:02:31</a> for the softball jargon but with those  
<a onclick="modifyYTiframeseektime('153')">0:02:33</a> three kinds of evidences and ACS will be  
<a onclick="modifyYTiframeseektime('156')">0:02:36</a> completely satisfied now and ACS might  
<a onclick="modifyYTiframeseektime('159')">0:02:39</a> say that these kinds of things are  
<a onclick="modifyYTiframeseektime('162')">0:02:42</a> satisfied in both maths and science that  
<a onclick="modifyYTiframeseektime('167')">0:02:47</a> mathematics is is incorrigible  
<a onclick="modifyYTiframeseektime('171')">0:02:51</a> number two days eternal number three  
<a onclick="modifyYTiframeseektime('173')">0:02:53</a> that is necessarily true and the Atheist  
<a onclick="modifyYTiframeseektime('178')">0:02:58</a> might say that sight science is quite  
<a onclick="modifyYTiframeseektime('181')">0:03:01</a> similar in that regard that's why  
<a onclick="modifyYTiframeseektime('182')">0:03:02</a> they're true standard it would be a  
<a onclick="modifyYTiframeseektime('184')">0:03:04</a> mathematical truth standard or it could  
<a onclick="modifyYTiframeseektime('187')">0:03:07</a> be a scientific studio true standard  
<a onclick="modifyYTiframeseektime('189')">0:03:09</a> they would consider these things to be  
<a onclick="modifyYTiframeseektime('190')">0:03:10</a> truth for the most part obviously I'm  
<a onclick="modifyYTiframeseektime('193')">0:03:13</a> not generalizing away theists I'll post  
<a onclick="modifyYTiframeseektime('194')">0:03:14</a> modernist out there which don't believe  
<a onclick="modifyYTiframeseektime('196')">0:03:16</a> in this they criticize both mathematics  
<a onclick="modifyYTiframeseektime('198')">0:03:18</a> and science massively but generally  
<a onclick="modifyYTiframeseektime('202')">0:03:22</a> speaking I mean from my experience it's  
<a onclick="modifyYTiframeseektime('204')">0:03:24</a> been the case that atheists are  
<a onclick="modifyYTiframeseektime('205')">0:03:25</a> satisfied with these kinds of true  
<a onclick="modifyYTiframeseektime('207')">0:03:27</a> standards now the question is this the  
<a onclick="modifyYTiframeseektime('209')">0:03:29</a> question is is mathematics as an example  
<a onclick="modifyYTiframeseektime('213')">0:03:33</a> here actually those three things that we  
<a onclick="modifyYTiframeseektime('216')">0:03:36</a> just mentioned now this is something  
<a onclick="modifyYTiframeseektime('217')">0:03:37</a> which has plagued the minds of  
<a onclick="modifyYTiframeseektime('218')">0:03:38</a> philosophers ever since the time of  
<a onclick="modifyYTiframeseektime('220')">0:03:40</a> Plato Plato himself didn't know how to  
<a onclick="modifyYTiframeseektime('223')">0:03:43</a> reason with numbers basic arithmetic he  
<a onclick="modifyYTiframeseektime('227')">0:03:47</a> didn't know because if you think about  
<a onclick="modifyYTiframeseektime('228')">0:03:48</a> it numbers in and of themselves don't  
<a onclick="modifyYTiframeseektime('231')">0:03:51</a> exist  
<a onclick="modifyYTiframeseektime('232')">0:03:52</a> you can't touch a number you can't feel  
<a onclick="modifyYTiframeseektime('235')">0:03:55</a> a number because smellin about numbers  
<a onclick="modifyYTiframeseektime('237')">0:03:57</a> is actually a conceptual abstract  
<a onclick="modifyYTiframeseektime('240')">0:04:00</a> reality  
<a onclick="modifyYTiframeseektime('242')">0:04:02</a> but in logic you have to have a truth in  
<a onclick="modifyYTiframeseektime('246')">0:04:06</a> order for our truth to be true it has to  
<a onclick="modifyYTiframeseektime('248')">0:04:08</a> have a physical reality objective truth  
<a onclick="modifyYTiframeseektime('252')">0:04:12</a> is that which is usually an object so  
<a onclick="modifyYTiframeseektime('256')">0:04:16</a> this poses a problem for Plato so he  
<a onclick="modifyYTiframeseektime('258')">0:04:18</a> says for example that mathematics is  
<a onclick="modifyYTiframeseektime('262')">0:04:22</a> something he has in the forms the world  
<a onclick="modifyYTiframeseektime('267')">0:04:27</a> of forms so is something he struggled  
<a onclick="modifyYTiframeseektime('270')">0:04:30</a> with Immanuel Kant came to 1790  
<a onclick="modifyYTiframeseektime('272')">0:04:32</a> something similar said that mathematics  
<a onclick="modifyYTiframeseektime('274')">0:04:34</a> is not something we take from the world  
<a onclick="modifyYTiframeseektime('277')">0:04:37</a> but it's something we put onto the world  
<a onclick="modifyYTiframeseektime('280')">0:04:40</a> now you'll find that even after this  
<a onclick="modifyYTiframeseektime('283')">0:04:43</a> point mathematics itself had a shaking  
<a onclick="modifyYTiframeseektime('287')">0:04:47</a> up the cat was put with the pigeon so to  
<a onclick="modifyYTiframeseektime('290')">0:04:50</a> speak one cut one cuts Judith came out  
<a onclick="modifyYTiframeseektime('294')">0:04:54</a> with his two incompleteness theorem  
<a onclick="modifyYTiframeseektime('296')">0:04:56</a> theorems and basically these two  
<a onclick="modifyYTiframeseektime('297')">0:04:57</a> incompleteness theorems exposed the  
<a onclick="modifyYTiframeseektime('300')">0:05:00</a> inconsistencies in maths it exposes  
<a onclick="modifyYTiframeseektime('304')">0:05:04</a> these inconsistencies because a flip  
<a onclick="modifyYTiframeseektime('308')">0:05:08</a> into the serums yeah the first theorem  
<a onclick="modifyYTiframeseektime('311')">0:05:11</a> for example was similar to the life  
<a onclick="modifyYTiframeseektime('314')">0:05:14</a> paradox if someone if I come forward or  
<a onclick="modifyYTiframeseektime('317')">0:05:17</a> someone else who's a liar says I'm lying  
<a onclick="modifyYTiframeseektime('320')">0:05:20</a> right there's no way to prove or  
<a onclick="modifyYTiframeseektime('322')">0:05:22</a> disprove this statement because the liar  
<a onclick="modifyYTiframeseektime('323')">0:05:23</a> if he's lying he's telling the truth  
<a onclick="modifyYTiframeseektime('325')">0:05:25</a> which means it's not alive and if he's  
<a onclick="modifyYTiframeseektime('327')">0:05:27</a> telling the truth  
<a onclick="modifyYTiframeseektime('328')">0:05:28</a> then that contradicts the fact that he's  
<a onclick="modifyYTiframeseektime('330')">0:05:30</a> saying that his line now something  
<a onclick="modifyYTiframeseektime('332')">0:05:32</a> similar was put in a mathematic format  
<a onclick="modifyYTiframeseektime('334')">0:05:34</a> and from that perspective this is called  
<a onclick="modifyYTiframeseektime('337')">0:05:37</a> incompleteness theorem mathematics was  
<a onclick="modifyYTiframeseektime('339')">0:05:39</a> seen to be inconsistent and inconsistent  
<a onclick="modifyYTiframeseektime('343')">0:05:43</a> model and by the way math the philosophy  
<a onclick="modifyYTiframeseektime('346')">0:05:46</a> of maths or meta mathematic narratives  
<a onclick="modifyYTiframeseektime('348')">0:05:48</a> or for a philosophy of maths  
<a onclick="modifyYTiframeseektime('351')">0:05:51</a> this is a big thing and still unresolved  
<a onclick="modifyYTiframeseektime('353')">0:05:53</a> to this day it's unresolved yet people  
<a onclick="modifyYTiframeseektime('356')">0:05:56</a> still do mess yet people still do maths  
<a onclick="modifyYTiframeseektime('363')">0:06:03</a> maths have axioms which cannot be proven  
<a onclick="modifyYTiframeseektime('366')">0:06:06</a> they're only self-evident  
<a onclick="modifyYTiframeseektime('369')">0:06:09</a> they're self-evident axioms which means  
<a onclick="modifyYTiframeseektime('372')">0:06:12</a> to believe in such axioms you have to  
<a onclick="modifyYTiframeseektime('374')">0:06:14</a> have faith because there's no evidence  
<a onclick="modifyYTiframeseektime('377')">0:06:17</a> of those axioms there's no evidence  
<a onclick="modifyYTiframeseektime('379')">0:06:19</a> these things these axioms in terms are  
<a onclick="modifyYTiframeseektime('383')">0:06:23</a> based on assumptions not concrete  
<a onclick="modifyYTiframeseektime('388')">0:06:28</a> evidence science is much more flimsy  
<a onclick="modifyYTiframeseektime('391')">0:06:31</a> than mass and so much has has changed  
<a onclick="modifyYTiframeseektime('393')">0:06:33</a> much more and it's ever changing and  
<a onclick="modifyYTiframeseektime('396')">0:06:36</a> this is something which is documented  
<a onclick="modifyYTiframeseektime('399')">0:06:39</a> well by Thomas Kuhn in his book  
<a onclick="modifyYTiframeseektime('401')">0:06:41</a> structures of scientific revolution but  
<a onclick="modifyYTiframeseektime('403')">0:06:43</a> not only the science change in  
<a onclick="modifyYTiframeseektime('405')">0:06:45</a> scientific facts change but the whole  
<a onclick="modifyYTiframeseektime('407')">0:06:47</a> framework within which science operates  
<a onclick="modifyYTiframeseektime('411')">0:06:51</a> and now why am I telling you this  
<a onclick="modifyYTiframeseektime('414')">0:06:54</a> because you have to understand that one  
<a onclick="modifyYTiframeseektime('418')">0:06:58</a> da is the skeptical with the eminences  
<a onclick="modifyYTiframeseektime('423')">0:07:03</a> then you have to ask yourself what kind  
<a onclick="modifyYTiframeseektime('426')">0:07:06</a> of evidences are you're not going to be  
<a onclick="modifyYTiframeseektime('428')">0:07:08</a> skeptical but those truths stand aside  
<a onclick="modifyYTiframeseektime('431')">0:07:11</a> for mentioned at the beginning of this  
<a onclick="modifyYTiframeseektime('432')">0:07:12</a> talk if they're applied to almost any  
<a onclick="modifyYTiframeseektime('435')">0:07:15</a> discipline you would not have faith in  
<a onclick="modifyYTiframeseektime('438')">0:07:18</a> anything you would not believe in  
<a onclick="modifyYTiframeseektime('440')">0:07:20</a> anything you couldn't do anything you  
<a onclick="modifyYTiframeseektime('442')">0:07:22</a> couldn't prove anything therefore the  
<a onclick="modifyYTiframeseektime('446')">0:07:26</a> true standard wouldn't work for the  
<a onclick="modifyYTiframeseektime('449')">0:07:29</a> Atheist that particular true standard  
<a onclick="modifyYTiframeseektime('451')">0:07:31</a> couldn't and wouldn't work rather if  
<a onclick="modifyYTiframeseektime('454')">0:07:34</a> we're honest with ourselves atheistic  
<a onclick="modifyYTiframeseektime('458')">0:07:38</a> true standard is a true standard which  
<a onclick="modifyYTiframeseektime('460')">0:07:40</a> is probabilistic is it true standard  
<a onclick="modifyYTiframeseektime('465')">0:07:45</a> which is probabilistic we as human  
<a onclick="modifyYTiframeseektime('468')">0:07:48</a> beings welcome to ability reasoning  
<a onclick="modifyYTiframeseektime('469')">0:07:49</a> almost every single day if something is  
<a onclick="modifyYTiframeseektime('472')">0:07:52</a> 99 percent assured we're happy if  
<a onclick="modifyYTiframeseektime('475')">0:07:55</a> something is 99 percent sure we can say  
<a onclick="modifyYTiframeseektime('477')">0:07:57</a> we're certain of it almost what we can  
<a onclick="modifyYTiframeseektime('480')">0:08:00</a> definitely say we're certain of it and  
<a onclick="modifyYTiframeseektime('482')">0:08:02</a> if it all piles up in front of us as a  
<a onclick="modifyYTiframeseektime('484')">0:08:04</a> big heap of evidence then this assures  
<a onclick="modifyYTiframeseektime('486')">0:08:06</a> us this is where the arguments put  
<a onclick="modifyYTiframeseektime('492')">0:08:12</a> forward by the atheist or the lack of  
<a onclick="modifyYTiframeseektime('495')">0:08:15</a> belief  
<a onclick="modifyYTiframeseektime('496')">0:08:16</a> that the atheist has I would say is  
<a onclick="modifyYTiframeseektime('498')">0:08:18</a> unsubstantiated because if you use a  
<a onclick="modifyYTiframeseektime('502')">0:08:22</a> probabilistic reasoning okay there is no  
<a onclick="modifyYTiframeseektime('506')">0:08:26</a> doubt in almost anyone's mind that you  
<a onclick="modifyYTiframeseektime('510')">0:08:30</a> will come to very many conclusions about  
<a onclick="modifyYTiframeseektime('512')">0:08:32</a> this universe the fact that is  
<a onclick="modifyYTiframeseektime('514')">0:08:34</a> fine-tuned and when I say it's finely  
<a onclick="modifyYTiframeseektime('515')">0:08:35</a> tuned I'm not saying that it's  
<a onclick="modifyYTiframeseektime('518')">0:08:38</a> aesthetically pleasing I'm not saying  
<a onclick="modifyYTiframeseektime('521')">0:08:41</a> that that's not what fine-tuning means  
<a onclick="modifyYTiframeseektime('523')">0:08:43</a> fine-tuning means is fine-tuned to allow  
<a onclick="modifyYTiframeseektime('527')">0:08:47</a> any kind of life to exist within it  
<a onclick="modifyYTiframeseektime('530')">0:08:50</a> this is fine-tuning atheist and  
<a onclick="modifyYTiframeseektime('533')">0:08:53</a> non-obviousness muslims christians jews  
<a onclick="modifyYTiframeseektime('536')">0:08:56</a> anyone who's done science agrees with  
<a onclick="modifyYTiframeseektime('539')">0:08:59</a> this i'm not saying there isn't any  
<a onclick="modifyYTiframeseektime('542')">0:09:02</a> rogue opinion why i am saying this is  
<a onclick="modifyYTiframeseektime('545')">0:09:05</a> the normal approach to the cosmological  
<a onclick="modifyYTiframeseektime('549')">0:09:09</a> environment around us Martin Rees Robert  
<a onclick="modifyYTiframeseektime('552')">0:09:12</a> Ford just six numbers and he said that  
<a onclick="modifyYTiframeseektime('555')">0:09:15</a> any of those six numbers had they been  
<a onclick="modifyYTiframeseektime('557')">0:09:17</a> different the universe would not be as  
<a onclick="modifyYTiframeseektime('559')">0:09:19</a> it is and it will not allow human life  
<a onclick="modifyYTiframeseektime('561')">0:09:21</a> to exist even Stephen Hawkins in a brief  
<a onclick="modifyYTiframeseektime('565')">0:09:25</a> history of time an atheist and Arden  
<a onclick="modifyYTiframeseektime('568')">0:09:28</a> atheist he admits to the fine-tuning the  
<a onclick="modifyYTiframeseektime('571')">0:09:31</a> fine-tuning is something which is  
<a onclick="modifyYTiframeseektime('572')">0:09:32</a> probabilistically indicating a design if  
<a onclick="modifyYTiframeseektime('576')">0:09:36</a> that is the case and the question is who  
<a onclick="modifyYTiframeseektime('580')">0:09:40</a> or what designed this universe and from  
<a onclick="modifyYTiframeseektime('586')">0:09:46</a> this perspective is quite a  
<a onclick="modifyYTiframeseektime('588')">0:09:48</a> straightforward answer the one would a  
<a onclick="modifyYTiframeseektime('594')">0:09:54</a> thing that has designed this universe is  
<a onclick="modifyYTiframeseektime('596')">0:09:56</a> that one would not think that was able  
<a onclick="modifyYTiframeseektime('600')">0:10:00</a> to do so and who them what who or what  
<a onclick="modifyYTiframeseektime('605')">0:10:05</a> could be able to do so so we employ  
<a onclick="modifyYTiframeseektime('609')">0:10:09</a> basic reason and we realize that it must  
<a onclick="modifyYTiframeseektime('613')">0:10:13</a> have been something or someone with  
<a onclick="modifyYTiframeseektime('616')">0:10:16</a> certain characteristics must have had  
<a onclick="modifyYTiframeseektime('619')">0:10:19</a> knowledge  
<a onclick="modifyYTiframeseektime('620')">0:10:20</a> it must have had power it must have had  
<a onclick="modifyYTiframeseektime('624')">0:10:24</a> the ability to change the situation it  
<a onclick="modifyYTiframeseektime('628')">0:10:28</a> must be one had it not been one there  
<a onclick="modifyYTiframeseektime('631')">0:10:31</a> would have been a conflict of interest  
<a onclick="modifyYTiframeseektime('633')">0:10:33</a> between the many parties that there  
<a onclick="modifyYTiframeseektime('635')">0:10:35</a> would be this is good the evidence of  
<a onclick="modifyYTiframeseektime('641')">0:10:41</a> God is not just evidence  
<a onclick="modifyYTiframeseektime('642')">0:10:42</a> it's overwhelming probabilistic evidence  
<a onclick="modifyYTiframeseektime('646')">0:10:46</a> we don't have faith in that which is  
<a onclick="modifyYTiframeseektime('648')">0:10:48</a> unreasonable we have faith in that which  
<a onclick="modifyYTiframeseektime('652')">0:10:52</a> is clear and what I personally believe  
<a onclick="modifyYTiframeseektime('656')">0:10:56</a> is that the Atheist has to in order to  
<a onclick="modifyYTiframeseektime('659')">0:10:59</a> avoid this born in his or her sight they  
<a onclick="modifyYTiframeseektime('662')">0:11:02</a> must employ a double standard approach  
<a onclick="modifyYTiframeseektime('664')">0:11:04</a> they have to the way they live their  
<a onclick="modifyYTiframeseektime('667')">0:11:07</a> lives is different to the way they want  
<a onclick="modifyYTiframeseektime('669')">0:11:09</a> to conceptualize the theological and  
<a onclick="modifyYTiframeseektime('670')">0:11:10</a> philosophical reality of God that must  
<a onclick="modifyYTiframeseektime('673')">0:11:13</a> happen other than that  
<a onclick="modifyYTiframeseektime('676')">0:11:16</a> the atheist must think the atheist must  
<a onclick="modifyYTiframeseektime('680')">0:11:20</a> dare to think  
</details>