# 'Nope. Jesus is Not Yahweh' ~ Dr Bart Ehrman (2021-04-19)

<iframe loading='lazy' src='https://www.youtube.com/embed/zfQ6bU6GYDw'></iframe>

## Description

I read the article by Professor Bart Ehrman on his blog:  https://ehrmanblog.org/nope-jesus-is-not-yahweh/

## Summary of ['Nope. Jesus is Not Yahweh' ~ Dr Bart Ehrman](https://www.youtube.com/watch?v=zfQ6bU6GYDw)


*<span style="color:red; font-size:125%">This summary is AI generated - there may be inaccuracies</span>. [](/)*

### <a onclick="modifyYTiframeseektime('0')">00:00:00</a> - <a onclick="modifyYTiframeseektime('600')">00:10:00</a>

Dr. Bart Ehrman discusses how some modern Christians may misinterpret verses in the Bible regarding Christ's authority. He points out that while Christ had equal authority as God himself, he did not have the same authority as Yahweh before his incarnation. discusses how Paul, the author of Philippians, did not believe in a trinity of God the Father, Son, and Holy Spirit as understood later in Christianity. He argues that this doctrine developed later, and that it is an evolution into a new species of theology that did not exist in the New Testament.

**<a onclick="modifyYTiframeseektime('0')">00:00:00</a>** In this article, Bart Ehrman explains why traditional Christian theology does not believe that Jesus is actually Yahweh, the god of the Hebrew Bible. Rather, Yahweh is a holy name that is only used by the high priest during the Jewish holiday of Yom Kippur. Christians who read the Old Testament saw Jesus as his son whom he exalted to his right hand.
* **<a onclick="modifyYTiframeseektime('300')">00:05:00</a>**  Dr. Bart Ehrman discusses how some modern Christians may misinterpret verses in the Bible regarding Christ's authority. He points out that while Christ had equal authority as God himself, he did not have the same authority as Yahweh before his incarnation.
* **<a onclick="modifyYTiframeseektime('600')">00:10:00</a>* Discusses how Paul, the author of Philippians, did not believe in a trinity of God the Father, Son, and Holy Spirit as understood later in Christianity. He argues that this doctrine developed later, and that it is an evolution into a new species of theology that did not exist in the New Testament.

<details><summary><h2>Full transcript with timestamps: CLICK TO EXPAND</h2></summary>

<a onclick="modifyYTiframeseektime('1')">0:00:01</a> nope jesus is  
<a onclick="modifyYTiframeseektime('3')">0:00:03</a> not yahweh this is the title of an  
<a onclick="modifyYTiframeseektime('6')">0:00:06</a> article  
<a onclick="modifyYTiframeseektime('7')">0:00:07</a> just published two days ago uh on bart  
<a onclick="modifyYTiframeseektime('10')">0:00:10</a> ehrman's blog  
<a onclick="modifyYTiframeseektime('11')">0:00:11</a> um and it's really very good and i  
<a onclick="modifyYTiframeseektime('13')">0:00:13</a> wanted just to read it to you and offer  
<a onclick="modifyYTiframeseektime('15')">0:00:15</a> a few comments  
<a onclick="modifyYTiframeseektime('16')">0:00:16</a> for those few of you who still don't  
<a onclick="modifyYTiframeseektime('17')">0:00:17</a> know who bart ehrman is  
<a onclick="modifyYTiframeseektime('19')">0:00:19</a> he is currently the james a gray  
<a onclick="modifyYTiframeseektime('21')">0:00:21</a> distinguished professor  
<a onclick="modifyYTiframeseektime('23')">0:00:23</a> of religious studies at the university  
<a onclick="modifyYTiframeseektime('24')">0:00:24</a> of north carolina  
<a onclick="modifyYTiframeseektime('26')">0:00:26</a> at chapel hill he's an american and he's  
<a onclick="modifyYTiframeseektime('29')">0:00:29</a> one of the world's if not the world's  
<a onclick="modifyYTiframeseektime('30')">0:00:30</a> leaders  
<a onclick="modifyYTiframeseektime('31')">0:00:31</a> leading textual critic and uh a new  
<a onclick="modifyYTiframeseektime('34')">0:00:34</a> testament scholar as well  
<a onclick="modifyYTiframeseektime('36')">0:00:36</a> um he is a prodigious writer uh and he  
<a onclick="modifyYTiframeseektime('39')">0:00:39</a> uh virtually every day something new  
<a onclick="modifyYTiframeseektime('41')">0:00:41</a> comes out and it's very he's very  
<a onclick="modifyYTiframeseektime('43')">0:00:43</a> readable  
<a onclick="modifyYTiframeseektime('44')">0:00:44</a> and um this article nope jesus is not uh  
<a onclick="modifyYTiframeseektime('46')">0:00:46</a> yahweh i just wanted to share it with  
<a onclick="modifyYTiframeseektime('48')">0:00:48</a> you  
<a onclick="modifyYTiframeseektime('48')">0:00:48</a> published uh just two days ago uh on the  
<a onclick="modifyYTiframeseektime('51')">0:00:51</a> 17th of april  
<a onclick="modifyYTiframeseektime('52')">0:00:52</a> and he says in my last post i pointed  
<a onclick="modifyYTiframeseektime('55')">0:00:55</a> out that  
<a onclick="modifyYTiframeseektime('56')">0:00:56</a> some conservative evangelical christians  
<a onclick="modifyYTiframeseektime('59')">0:00:59</a> claim  
<a onclick="modifyYTiframeseektime('59')">0:00:59</a> that jesus in the bible is actually to  
<a onclick="modifyYTiframeseektime('62')">0:01:02</a> be understood as  
<a onclick="modifyYTiframeseektime('63')">0:01:03</a> yahweh i think that's completely wrong  
<a onclick="modifyYTiframeseektime('67')">0:01:07</a> and in this post i want to explain why  
<a onclick="modifyYTiframeseektime('70')">0:01:10</a> of course yahweh is the name of god in  
<a onclick="modifyYTiframeseektime('72')">0:01:12</a> the jewish bible so christians are  
<a onclick="modifyYTiframeseektime('73')">0:01:13</a> saying or many christians are saying  
<a onclick="modifyYTiframeseektime('75')">0:01:15</a> that jesus is this god jesus is god  
<a onclick="modifyYTiframeseektime('79')">0:01:19</a> he continues it is not the view of  
<a onclick="modifyYTiframeseektime('82')">0:01:22</a> traditional  
<a onclick="modifyYTiframeseektime('83')">0:01:23</a> christian theology at least as i learned  
<a onclick="modifyYTiframeseektime('85')">0:01:25</a> it once upon a time  
<a onclick="modifyYTiframeseektime('87')">0:01:27</a> it was certainly not the view of the  
<a onclick="modifyYTiframeseektime('89')">0:01:29</a> earliest christians  
<a onclick="modifyYTiframeseektime('91')">0:01:31</a> and it is not a view set forth in the  
<a onclick="modifyYTiframeseektime('93')">0:01:33</a> bible  
<a onclick="modifyYTiframeseektime('94')">0:01:34</a> the bible of course does not have the  
<a onclick="modifyYTiframeseektime('96')">0:01:36</a> trinity  
<a onclick="modifyYTiframeseektime('97')">0:01:37</a> but when christianity formulated the  
<a onclick="modifyYTiframeseektime('99')">0:01:39</a> doctrine of the trinity  
<a onclick="modifyYTiframeseektime('101')">0:01:41</a> the father was yahweh and christ was his  
<a onclick="modifyYTiframeseektime('104')">0:01:44</a> son  
<a onclick="modifyYTiframeseektime('104')">0:01:44</a> at least that's what christians who read  
<a onclick="modifyYTiframeseektime('106')">0:01:46</a> the old testament said  
<a onclick="modifyYTiframeseektime('108')">0:01:48</a> of course the name yahweh is not found  
<a onclick="modifyYTiframeseektime('111')">0:01:51</a> in the new testament at all  
<a onclick="modifyYTiframeseektime('113')">0:01:53</a> since it's a hebrew word and the greek  
<a onclick="modifyYTiframeseektime('115')">0:01:55</a> is in new testament is in greek  
<a onclick="modifyYTiframeseektime('117')">0:01:57</a> the new testament does not give god a  
<a onclick="modifyYTiframeseektime('119')">0:01:59</a> personal name  
<a onclick="modifyYTiframeseektime('122')">0:02:02</a> when christians want to find another  
<a onclick="modifyYTiframeseektime('124')">0:02:04</a> divine being in the old testament to  
<a onclick="modifyYTiframeseektime('126')">0:02:06</a> identify as christ  
<a onclick="modifyYTiframeseektime('128')">0:02:08</a> they went to passages like psalm 110  
<a onclick="modifyYTiframeseektime('131')">0:02:11</a> which begins the lord said to my lord  
<a onclick="modifyYTiframeseektime('134')">0:02:14</a> sit at my right hand until i make your  
<a onclick="modifyYTiframeseektime('137')">0:02:17</a> enemies  
<a onclick="modifyYTiframeseektime('138')">0:02:18</a> your footstool based on what i said in  
<a onclick="modifyYTiframeseektime('141')">0:02:21</a> my  
<a onclick="modifyYTiframeseektime('142')">0:02:22</a> previous post you can reconstruct uh  
<a onclick="modifyYTiframeseektime('145')">0:02:25</a> who is talking to whom here notice that  
<a onclick="modifyYTiframeseektime('148')">0:02:28</a> the first lord  
<a onclick="modifyYTiframeseektime('149')">0:02:29</a> is in capital letters and the second is  
<a onclick="modifyYTiframeseektime('153')">0:02:33</a> not so another way of putting this would  
<a onclick="modifyYTiframeseektime('155')">0:02:35</a> be yahweh  
<a onclick="modifyYTiframeseektime('156')">0:02:36</a> said to adonai the point here just to  
<a onclick="modifyYTiframeseektime('160')">0:02:40</a> break from the reading for a second is  
<a onclick="modifyYTiframeseektime('162')">0:02:42</a> that the the name of god yahweh was a  
<a onclick="modifyYTiframeseektime('164')">0:02:44</a> holy name  
<a onclick="modifyYTiframeseektime('165')">0:02:45</a> but he really uttered by the high priest  
<a onclick="modifyYTiframeseektime('168')">0:02:48</a> yom kippur and was not mentioned by  
<a onclick="modifyYTiframeseektime('171')">0:02:51</a> israelites normally at all so they use  
<a onclick="modifyYTiframeseektime('173')">0:02:53</a> another word adonai  
<a onclick="modifyYTiframeseektime('175')">0:02:55</a> which means lord to refer to god  
<a onclick="modifyYTiframeseektime('178')">0:02:58</a> so whenever in english translations it's  
<a onclick="modifyYTiframeseektime('180')">0:03:00</a> still the convention today when the word  
<a onclick="modifyYTiframeseektime('182')">0:03:02</a> yahweh  
<a onclick="modifyYTiframeseektime('182')">0:03:02</a> is in the hebrew they  
<a onclick="modifyYTiframeseektime('186')">0:03:06</a> write l-o-r-d in block capitals and that  
<a onclick="modifyYTiframeseektime('189')">0:03:09</a> indicates  
<a onclick="modifyYTiframeseektime('189')">0:03:09</a> in the original hebrew it's yahweh has  
<a onclick="modifyYTiframeseektime('191')">0:03:11</a> been referred to  
<a onclick="modifyYTiframeseektime('193')">0:03:13</a> excuse me adonai simply means lord and  
<a onclick="modifyYTiframeseektime('196')">0:03:16</a> can refer to  
<a onclick="modifyYTiframeseektime('196')">0:03:16</a> people you know if you'd be a a king a  
<a onclick="modifyYTiframeseektime('199')">0:03:19</a> lord or  
<a onclick="modifyYTiframeseektime('200')">0:03:20</a> or a father figure so um he's saying  
<a onclick="modifyYTiframeseektime('203')">0:03:23</a> psalm 110 if you actually look at the  
<a onclick="modifyYTiframeseektime('205')">0:03:25</a> hebrew it says  
<a onclick="modifyYTiframeseektime('206')">0:03:26</a> yahweh said to adonai so it's not two  
<a onclick="modifyYTiframeseektime('209')">0:03:29</a> divine beings it's one and obviously the  
<a onclick="modifyYTiframeseektime('211')">0:03:31</a> one is god  
<a onclick="modifyYTiframeseektime('212')">0:03:32</a> yahweh in interpreting that passage  
<a onclick="modifyYTiframeseektime('214')">0:03:34</a> christians asked  
<a onclick="modifyYTiframeseektime('216')">0:03:36</a> who is that elevated christ our lord  
<a onclick="modifyYTiframeseektime('219')">0:03:39</a> to his right hand obviously god the  
<a onclick="modifyYTiframeseektime('222')">0:03:42</a> father  
<a onclick="modifyYTiframeseektime('222')">0:03:42</a> elevated christ and so god the father is  
<a onclick="modifyYTiframeseektime('225')">0:03:45</a> yahweh  
<a onclick="modifyYTiframeseektime('226')">0:03:46</a> and the one elevated to his right hand  
<a onclick="modifyYTiframeseektime('228')">0:03:48</a> is the lord jesus  
<a onclick="modifyYTiframeseektime('231')">0:03:51</a> christians appeal to this verse in  
<a onclick="modifyYTiframeseektime('232')">0:03:52</a> reference to christ a good  
<a onclick="modifyYTiframeseektime('234')">0:03:54</a> deal and indeed he mentions a number of  
<a onclick="modifyYTiframeseektime('237')">0:03:57</a> times  
<a onclick="modifyYTiframeseektime('238')">0:03:58</a> when it occurs these christians were not  
<a onclick="modifyYTiframeseektime('241')">0:04:01</a> seeing jesus as  
<a onclick="modifyYTiframeseektime('242')">0:04:02</a> yahweh but as his son whom he  
<a onclick="modifyYTiframeseektime('245')">0:04:05</a> exalted to his right hand this is a  
<a onclick="modifyYTiframeseektime('248')">0:04:08</a> really important point  
<a onclick="modifyYTiframeseektime('249')">0:04:09</a> this is there's a thing about new  
<a onclick="modifyYTiframeseektime('250')">0:04:10</a> testament scholarship really good  
<a onclick="modifyYTiframeseektime('252')">0:04:12</a> scholarship  
<a onclick="modifyYTiframeseektime('253')">0:04:13</a> is it pays very careful and meticulous  
<a onclick="modifyYTiframeseektime('256')">0:04:16</a> attention to what's actually been stated  
<a onclick="modifyYTiframeseektime('258')">0:04:18</a> in the text  
<a onclick="modifyYTiframeseektime('260')">0:04:20</a> rather than reading it through a later  
<a onclick="modifyYTiframeseektime('262')">0:04:22</a> christian tradition or any tradition  
<a onclick="modifyYTiframeseektime('264')">0:04:24</a> church tradition it covers it takes all  
<a onclick="modifyYTiframeseektime('267')">0:04:27</a> that away  
<a onclick="modifyYTiframeseektime('268')">0:04:28</a> and focuses just on the text read in its  
<a onclick="modifyYTiframeseektime('270')">0:04:30</a> historical and cultural  
<a onclick="modifyYTiframeseektime('272')">0:04:32</a> context and often that gives readings of  
<a onclick="modifyYTiframeseektime('275')">0:04:35</a> the bible which are quite different  
<a onclick="modifyYTiframeseektime('277')">0:04:37</a> from uh christian later christian  
<a onclick="modifyYTiframeseektime('279')">0:04:39</a> readings  
<a onclick="modifyYTiframeseektime('281')">0:04:41</a> so he continues christians such as the  
<a onclick="modifyYTiframeseektime('283')">0:04:43</a> 2nd century  
<a onclick="modifyYTiframeseektime('284')">0:04:44</a> justin martyr also found references to  
<a onclick="modifyYTiframeseektime('288')">0:04:48</a> the pre-incarnate christ  
<a onclick="modifyYTiframeseektime('289')">0:04:49</a> in the old testament traditions of the  
<a onclick="modifyYTiframeseektime('292')">0:04:52</a> angel of the lord  
<a onclick="modifyYTiframeseektime('293')">0:04:53</a> who was gods yahweh's chief  
<a onclick="modifyYTiframeseektime('296')">0:04:56</a> representative  
<a onclick="modifyYTiframeseektime('297')">0:04:57</a> on earth delivering god's message with  
<a onclick="modifyYTiframeseektime('300')">0:05:00</a> god's  
<a onclick="modifyYTiframeseektime('300')">0:05:00</a> full authority in the stories of the  
<a onclick="modifyYTiframeseektime('302')">0:05:02</a> patriarchs for example in genesis  
<a onclick="modifyYTiframeseektime('305')">0:05:05</a> and exodus who was this mysterious  
<a onclick="modifyYTiframeseektime('308')">0:05:08</a> angel for christians he was christ  
<a onclick="modifyYTiframeseektime('311')">0:05:11</a> before he was born of the virgin mary  
<a onclick="modifyYTiframeseektime('314')">0:05:14</a> i wonder if the confusion among  
<a onclick="modifyYTiframeseektime('316')">0:05:16</a> evangelicals about the christian  
<a onclick="modifyYTiframeseektime('317')">0:05:17</a> understanding of christ  
<a onclick="modifyYTiframeseektime('319')">0:05:19</a> when they say he is yahweh is because  
<a onclick="modifyYTiframeseektime('321')">0:05:21</a> the angel of the lord  
<a onclick="modifyYTiframeseektime('323')">0:05:23</a> is so fully representative of yahweh  
<a onclick="modifyYTiframeseektime('326')">0:05:26</a> himself  
<a onclick="modifyYTiframeseektime('327')">0:05:27</a> that he is sometimes called yahweh after  
<a onclick="modifyYTiframeseektime('331')">0:05:31</a> he has clearly identified  
<a onclick="modifyYTiframeseektime('333')">0:05:33</a> not as yahweh but his angel  
<a onclick="modifyYTiframeseektime('336')">0:05:36</a> why would he be called yahweh if he was  
<a onclick="modifyYTiframeseektime('338')">0:05:38</a> yahweh's messenger  
<a onclick="modifyYTiframeseektime('340')">0:05:40</a> because by the way angel means messenger  
<a onclick="modifyYTiframeseektime('342')">0:05:42</a> uh in the bible  
<a onclick="modifyYTiframeseektime('344')">0:05:44</a> it would be kind of like if a messenger  
<a onclick="modifyYTiframeseektime('346')">0:05:46</a> of the king comes to you and orders you  
<a onclick="modifyYTiframeseektime('348')">0:05:48</a> to do something  
<a onclick="modifyYTiframeseektime('349')">0:05:49</a> you tell your neighbors that the king  
<a onclick="modifyYTiframeseektime('351')">0:05:51</a> has told you to do something  
<a onclick="modifyYTiframeseektime('353')">0:05:53</a> well actually his messenger did but he  
<a onclick="modifyYTiframeseektime('356')">0:05:56</a> was so  
<a onclick="modifyYTiframeseektime('357')">0:05:57</a> fully representative of the king that  
<a onclick="modifyYTiframeseektime('360')">0:06:00</a> his words  
<a onclick="modifyYTiframeseektime('361')">0:06:01</a> were the kings this happens when the  
<a onclick="modifyYTiframeseektime('364')">0:06:04</a> angel of the lord speaks to moses from  
<a onclick="modifyYTiframeseektime('366')">0:06:06</a> the burning bush  
<a onclick="modifyYTiframeseektime('367')">0:06:07</a> in the famous passage of exodus 3 as you  
<a onclick="modifyYTiframeseektime('370')">0:06:10</a> can see  
<a onclick="modifyYTiframeseektime('371')">0:06:11</a> this by the way is a favorite passage of  
<a onclick="modifyYTiframeseektime('373')">0:06:13</a> christian apologists trying to prove  
<a onclick="modifyYTiframeseektime('374')">0:06:14</a> that jesus is god  
<a onclick="modifyYTiframeseektime('376')">0:06:16</a> but the early christians so far as i  
<a onclick="modifyYTiframeseektime('378')">0:06:18</a> know were clear on this matter  
<a onclick="modifyYTiframeseektime('381')">0:06:21</a> this was christ coming in his  
<a onclick="modifyYTiframeseektime('383')">0:06:23</a> pre-incarnate state  
<a onclick="modifyYTiframeseektime('384')">0:06:24</a> as god's chief representative the angel  
<a onclick="modifyYTiframeseektime('387')">0:06:27</a> of the lord  
<a onclick="modifyYTiframeseektime('388')">0:06:28</a> who was given such authority that he  
<a onclick="modifyYTiframeseektime('391')">0:06:31</a> could be considered as  
<a onclick="modifyYTiframeseektime('392')">0:06:32</a> having the full status of the lord  
<a onclick="modifyYTiframeseektime('395')">0:06:35</a> capital lord  
<a onclick="modifyYTiframeseektime('396')">0:06:36</a> even though he was merely his angel  
<a onclick="modifyYTiframeseektime('400')">0:06:40</a> the view that christians took of christ  
<a onclick="modifyYTiframeseektime('403')">0:06:43</a> some modern christians may misinterpret  
<a onclick="modifyYTiframeseektime('406')">0:06:46</a> the christ poem  
<a onclick="modifyYTiframeseektime('407')">0:06:47</a> in philippians 2 in this way philippians  
<a onclick="modifyYTiframeseektime('410')">0:06:50</a> 2  
<a onclick="modifyYTiframeseektime('410')">0:06:50</a> is the letter that paul wrote to the  
<a onclick="modifyYTiframeseektime('412')">0:06:52</a> philippians in the second chapter  
<a onclick="modifyYTiframeseektime('414')">0:06:54</a> is an absolute favorite of christian  
<a onclick="modifyYTiframeseektime('416')">0:06:56</a> evangelists i i have it constantly  
<a onclick="modifyYTiframeseektime('419')">0:06:59</a> read to me as if this proves something  
<a onclick="modifyYTiframeseektime('421')">0:07:01</a> to me as if i've never read the passage  
<a onclick="modifyYTiframeseektime('423')">0:07:03</a> before  
<a onclick="modifyYTiframeseektime('423')">0:07:03</a> anyway bartoman says this about it i  
<a onclick="modifyYTiframeseektime('426')">0:07:06</a> talked about the poem at length a month  
<a onclick="modifyYTiframeseektime('427')">0:07:07</a> or so ago  
<a onclick="modifyYTiframeseektime('428')">0:07:08</a> on the blog when christ is exalted  
<a onclick="modifyYTiframeseektime('432')">0:07:12</a> after his death god gives him  
<a onclick="modifyYTiframeseektime('435')">0:07:15</a> the name that is above every name so  
<a onclick="modifyYTiframeseektime('438')">0:07:18</a> that all creation will worship and  
<a onclick="modifyYTiframeseektime('440')">0:07:20</a> confess him  
<a onclick="modifyYTiframeseektime('441')">0:07:21</a> that is a reference to isaiah 45 where  
<a onclick="modifyYTiframeseektime('444')">0:07:24</a> yahweh alone  
<a onclick="modifyYTiframeseektime('445')">0:07:25</a> has the name above every name so that  
<a onclick="modifyYTiframeseektime('448')">0:07:28</a> all worship  
<a onclick="modifyYTiframeseektime('449')">0:07:29</a> and confess him alone possibly these  
<a onclick="modifyYTiframeseektime('452')">0:07:32</a> modern christians are thinking  
<a onclick="modifyYTiframeseektime('454')">0:07:34</a> that christ before must have been given  
<a onclick="modifyYTiframeseektime('457')">0:07:37</a> the name  
<a onclick="modifyYTiframeseektime('458')">0:07:38</a> yahweh and therefore he is  
<a onclick="modifyYTiframeseektime('461')">0:07:41</a> yahweh but the passage doesn't seem to  
<a onclick="modifyYTiframeseektime('464')">0:07:44</a> mean  
<a onclick="modifyYTiframeseektime('464')">0:07:44</a> that the ultimate lord of all yahweh is  
<a onclick="modifyYTiframeseektime('467')">0:07:47</a> the one who gives jesus that name  
<a onclick="modifyYTiframeseektime('470')">0:07:50</a> above all others now obviously stepping  
<a onclick="modifyYTiframeseektime('472')">0:07:52</a> aside from bar here  
<a onclick="modifyYTiframeseektime('474')">0:07:54</a> who has the ultimate authority the  
<a onclick="modifyYTiframeseektime('475')">0:07:55</a> universe god  
<a onclick="modifyYTiframeseektime('477')">0:07:57</a> no one gives god authority if god gives  
<a onclick="modifyYTiframeseektime('480')">0:08:00</a> authority to another entity another  
<a onclick="modifyYTiframeseektime('482')">0:08:02</a> person another being  
<a onclick="modifyYTiframeseektime('484')">0:08:04</a> that person is not god from all eternity  
<a onclick="modifyYTiframeseektime('487')">0:08:07</a> they receive that authority from yahweh  
<a onclick="modifyYTiframeseektime('490')">0:08:10</a> so this language of receiving is really  
<a onclick="modifyYTiframeseektime('492')">0:08:12</a> important god doesn't receive authority  
<a onclick="modifyYTiframeseektime('494')">0:08:14</a> from anyone else at least not the god of  
<a onclick="modifyYTiframeseektime('497')">0:08:17</a> uh abraham moses jesus and muhammad  
<a onclick="modifyYTiframeseektime('501')">0:08:21</a> so it's worth noting that in this very  
<a onclick="modifyYTiframeseektime('503')">0:08:23</a> passage this is in  
<a onclick="modifyYTiframeseektime('504')">0:08:24</a> philippians 2 when god gives jesus his  
<a onclick="modifyYTiframeseektime('507')">0:08:27</a> name  
<a onclick="modifyYTiframeseektime('508')">0:08:28</a> it does not mean that he has made a name  
<a onclick="modifyYTiframeseektime('510')">0:08:30</a> switch for jesus  
<a onclick="modifyYTiframeseektime('512')">0:08:32</a> on the contrary the passage says that  
<a onclick="modifyYTiframeseektime('514')">0:08:34</a> the name to which  
<a onclick="modifyYTiframeseektime('515')">0:08:35</a> everyone will bow in worship and confess  
<a onclick="modifyYTiframeseektime('517')">0:08:37</a> is jesus  
<a onclick="modifyYTiframeseektime('519')">0:08:39</a> not yahweh that at the name of jesus  
<a onclick="modifyYTiframeseektime('522')">0:08:42</a> every knee shall bow and every tongue  
<a onclick="modifyYTiframeseektime('524')">0:08:44</a> confess and quote  
<a onclick="modifyYTiframeseektime('526')">0:08:46</a> jesus own name is exalted  
<a onclick="modifyYTiframeseektime('530')">0:08:50</a> so how did yahweh give him a name  
<a onclick="modifyYTiframeseektime('534')">0:08:54</a> above all others surely that would mean  
<a onclick="modifyYTiframeseektime('537')">0:08:57</a> that would be yahweh's own name right  
<a onclick="modifyYTiframeseektime('540')">0:09:00</a> well  
<a onclick="modifyYTiframeseektime('540')">0:09:00</a> yes and no says bart ehrman he did give  
<a onclick="modifyYTiframeseektime('543')">0:09:03</a> him  
<a onclick="modifyYTiframeseektime('544')">0:09:04</a> the name but not in the literal sense of  
<a onclick="modifyYTiframeseektime('547')">0:09:07</a> now you  
<a onclick="modifyYTiframeseektime('547')">0:09:07</a> are yahweh but in the biblical sense  
<a onclick="modifyYTiframeseektime('550')">0:09:10</a> i've been describing you now have the  
<a onclick="modifyYTiframeseektime('553')">0:09:13</a> full authority of yahweh  
<a onclick="modifyYTiframeseektime('555')">0:09:15</a> what you say and do is equal to the  
<a onclick="modifyYTiframeseektime('558')">0:09:18</a> authority of yahweh  
<a onclick="modifyYTiframeseektime('559')">0:09:19</a> saying and doing it jesus now  
<a onclick="modifyYTiframeseektime('563')">0:09:23</a> at his exaltation not before  
<a onclick="modifyYTiframeseektime('566')">0:09:26</a> really important point in my view is  
<a onclick="modifyYTiframeseektime('569')">0:09:29</a> given equal authority as the lord  
<a onclick="modifyYTiframeseektime('571')">0:09:31</a> himself  
<a onclick="modifyYTiframeseektime('572')">0:09:32</a> he now has the highest name dash  
<a onclick="modifyYTiframeseektime('575')">0:09:35</a> authority equal to god  
<a onclick="modifyYTiframeseektime('578')">0:09:38</a> but that does not mean he is god slash  
<a onclick="modifyYTiframeseektime('580')">0:09:40</a> yahweh  
<a onclick="modifyYTiframeseektime('581')">0:09:41</a> being equal is different from being  
<a onclick="modifyYTiframeseektime('585')">0:09:45</a> identical being equal is different  
<a onclick="modifyYTiframeseektime('588')">0:09:48</a> from being identical i just want to just  
<a onclick="modifyYTiframeseektime('590')">0:09:50</a> go back here a few  
<a onclick="modifyYTiframeseektime('592')">0:09:52</a> sentences um where he says  
<a onclick="modifyYTiframeseektime('596')">0:09:56</a> jesus now at his exaltation not before  
<a onclick="modifyYTiframeseektime('599')">0:09:59</a> so jesus didn't have this authority  
<a onclick="modifyYTiframeseektime('602')">0:10:02</a> before his exaltation he was given it  
<a onclick="modifyYTiframeseektime('605')">0:10:05</a> after his exaltation so he wasn't god  
<a onclick="modifyYTiframeseektime('607')">0:10:07</a> before he wasn't in any sense  
<a onclick="modifyYTiframeseektime('609')">0:10:09</a> as the name or as ontologically or  
<a onclick="modifyYTiframeseektime('612')">0:10:12</a> metaphysically  
<a onclick="modifyYTiframeseektime('613')">0:10:13</a> it was something that god gave to him  
<a onclick="modifyYTiframeseektime('615')">0:10:15</a> therefore he could not have been god  
<a onclick="modifyYTiframeseektime('618')">0:10:18</a> and the penultimate paragraph is another  
<a onclick="modifyYTiframeseektime('620')">0:10:20</a> analogy  
<a onclick="modifyYTiframeseektime('621')">0:10:21</a> when someone says to you open up in the  
<a onclick="modifyYTiframeseektime('624')">0:10:24</a> name of the king  
<a onclick="modifyYTiframeseektime('625')">0:10:25</a> or in the name of the law the name  
<a onclick="modifyYTiframeseektime('628')">0:10:28</a> means the authority and that must be  
<a onclick="modifyYTiframeseektime('632')">0:10:32</a> what  
<a onclick="modifyYTiframeseektime('632')">0:10:32</a> is meant in philippians 2. since  
<a onclick="modifyYTiframeseektime('636')">0:10:36</a> the literal name is still jesus but the  
<a onclick="modifyYTiframeseektime('638')">0:10:38</a> authority  
<a onclick="modifyYTiframeseektime('639')">0:10:39</a> the name has is now the authority of god  
<a onclick="modifyYTiframeseektime('643')">0:10:43</a> almighty yahweh himself so  
<a onclick="modifyYTiframeseektime('646')">0:10:46</a> i simply don't think it's right that  
<a onclick="modifyYTiframeseektime('648')">0:10:48</a> christian theology understands jesus as  
<a onclick="modifyYTiframeseektime('650')">0:10:50</a> yahweh well i guess some christians do  
<a onclick="modifyYTiframeseektime('653')">0:10:53</a> since that appears to be what they think  
<a onclick="modifyYTiframeseektime('656')">0:10:56</a> i wonder when they started thinking it  
<a onclick="modifyYTiframeseektime('658')">0:10:58</a> dot dot end quote end of the passage  
<a onclick="modifyYTiframeseektime('662')">0:11:02</a> so i think that's um actually quite  
<a onclick="modifyYTiframeseektime('663')">0:11:03</a> quite helpful and  
<a onclick="modifyYTiframeseektime('665')">0:11:05</a> uh i love the forensic way he analyzes  
<a onclick="modifyYTiframeseektime('667')">0:11:07</a> uh these passages  
<a onclick="modifyYTiframeseektime('669')">0:11:09</a> um and uh he makes clear that uh well  
<a onclick="modifyYTiframeseektime('672')">0:11:12</a> firstly  
<a onclick="modifyYTiframeseektime('673')">0:11:13</a> what do we conclude what can i conclude  
<a onclick="modifyYTiframeseektime('675')">0:11:15</a> that paul the apostle paul who wrote  
<a onclick="modifyYTiframeseektime('677')">0:11:17</a> philippians was not a trinitarian  
<a onclick="modifyYTiframeseektime('679')">0:11:19</a> he didn't believe in god the father got  
<a onclick="modifyYTiframeseektime('680')">0:11:20</a> the son and got the holy spirit  
<a onclick="modifyYTiframeseektime('683')">0:11:23</a> uh when he speaks of god he means the  
<a onclick="modifyYTiframeseektime('685')">0:11:25</a> father  
<a onclick="modifyYTiframeseektime('686')">0:11:26</a> the father certainly gives his son jesus  
<a onclick="modifyYTiframeseektime('689')">0:11:29</a> authority but there's no sense of an  
<a onclick="modifyYTiframeseektime('691')">0:11:31</a> eternal  
<a onclick="modifyYTiframeseektime('692')">0:11:32</a> trinity from all eternity there was  
<a onclick="modifyYTiframeseektime('694')">0:11:34</a> father son and holy spirit  
<a onclick="modifyYTiframeseektime('695')">0:11:35</a> that is absent from paul's thinking so  
<a onclick="modifyYTiframeseektime('698')">0:11:38</a> the doctrine of the trinity that  
<a onclick="modifyYTiframeseektime('699')">0:11:39</a> developed later is very much an  
<a onclick="modifyYTiframeseektime('701')">0:11:41</a> evolution into a new species  
<a onclick="modifyYTiframeseektime('704')">0:11:44</a> of uh theology really that didn't exist  
<a onclick="modifyYTiframeseektime('708')">0:11:48</a> in the new testament um i just wanted to  
<a onclick="modifyYTiframeseektime('711')">0:11:51</a> share that with you i will put  
<a onclick="modifyYTiframeseektime('712')">0:11:52</a> the link to the bar ehrman blog in the  
<a onclick="modifyYTiframeseektime('715')">0:11:55</a> description below  
<a onclick="modifyYTiframeseektime('717')">0:11:57</a> it's worth a read and worth chewing over  
<a onclick="modifyYTiframeseektime('720')">0:12:00</a> i think it's very interesting until next  
<a onclick="modifyYTiframeseektime('722')">0:12:02</a> time  
</details>