# How the Bible was changed... (2022-02-21)

<iframe loading='lazy' src='https://www.youtube.com/embed/F_46_1i4CQ0'></iframe>

## Description

You Can Support My Work on Patreon:
https://www.patreon.com/Bloggingtheology

My Paypal Link: 
https://www.paypal.com/paypalme/bloggingtheology?locale.x=en_GB

## Summary of [How the Bible was changed...](https://www.youtube.com/watch?v=F_46_1i4CQ0)


*<span style="color:red; font-size:125%">This summary is AI generated - there may be inaccuracies</span>. [](/)*

### <a onclick="modifyYTiframeseektime('0')">00:00:00</a> - <a onclick="modifyYTiframeseektime('600')">00:10:00</a>

The video discusses how the Bible was changed over time, specifically referring to how the new Testament writers quoted from a translation which had altered the text of the Hebrew Bible. He also discusses how the English translation of the Bible is a translation of multiple translations of the Hebrew Bible.

**<a onclick="modifyYTiframeseektime('0')">00:00:00</a>**  a professor discusses how the Bible was changed over time, specifically citing translations from the Greek into English. He notes that the translators of the Bible made adjustments to keep the text consistent, addressing various cultural challenges faced by the author's various audience.
* **<a onclick="modifyYTiframeseektime('300')">00:05:00</a>** The video discusses how the Bible was changed to make it more palatable to people in the Hellenistic world. It highlights examples of how the Greek translation alters the words of the original Bible. Peter argues that this is done in order to make God seem more like a rational being and in control of the process. He also points out that this is the Bible that is quoted in the New Testament, not the original Hebrew. Christians today may have more in common with Jews living in a Greek world than the Israelites of the time of David and Solomon.
* **<a onclick="modifyYTiframeseektime('600')">00:10:00</a>** of the video discusses how the Bible was changed over time, specifically referring to how the new Testament writers quoted from a translation which had altered the text of the Hebrew Bible. He also discusses how the English translation of the Bible is a translation of multiple translations of the Hebrew Bible.

<details><summary><h2>Full transcript with timestamps: CLICK TO EXPAND</h2></summary>

<a onclick="modifyYTiframeseektime('2')">0:00:02</a> now in this video i want to share with  
<a onclick="modifyYTiframeseektime('4')">0:00:04</a> you some insights into the christian  
<a onclick="modifyYTiframeseektime('7')">0:00:07</a> bible things that are not usually known  
<a onclick="modifyYTiframeseektime('10')">0:00:10</a> and i'm going to be drawing on this book  
<a onclick="modifyYTiframeseektime('12')">0:00:12</a> how the bible actually works by peter  
<a onclick="modifyYTiframeseektime('16')">0:00:16</a> enz who is a professor of  
<a onclick="modifyYTiframeseektime('18')">0:00:18</a> biblical studies in the u.s  
<a onclick="modifyYTiframeseektime('21')">0:00:21</a> and i just want to read a few paragraphs  
<a onclick="modifyYTiframeseektime('23')">0:00:23</a> from a chapter where he talks about  
<a onclick="modifyYTiframeseektime('25')">0:00:25</a> something which is not really understood  
<a onclick="modifyYTiframeseektime('27')">0:00:27</a> at all well and it's this that the new  
<a onclick="modifyYTiframeseektime('30')">0:00:30</a> testament writers whether they be the  
<a onclick="modifyYTiframeseektime('32')">0:00:32</a> gospel writers or paul or james or peter  
<a onclick="modifyYTiframeseektime('35')">0:00:35</a> whoever they are  
<a onclick="modifyYTiframeseektime('36')">0:00:36</a> when they quote from the jewish bible  
<a onclick="modifyYTiframeseektime('38')">0:00:38</a> the old testament  
<a onclick="modifyYTiframeseektime('40')">0:00:40</a> usually or that virtually always quote  
<a onclick="modifyYTiframeseektime('42')">0:00:42</a> from a greek translation of the hebrew  
<a onclick="modifyYTiframeseektime('45')">0:00:45</a> bibles they're not quoting from the  
<a onclick="modifyYTiframeseektime('46')">0:00:46</a> hebrew bible with the original language  
<a onclick="modifyYTiframeseektime('48')">0:00:48</a> but from a translation now why are they  
<a onclick="modifyYTiframeseektime('51')">0:00:51</a> doing this well the jews who were living  
<a onclick="modifyYTiframeseektime('54')">0:00:54</a> uh second third century bc when they  
<a onclick="modifyYTiframeseektime('57')">0:00:57</a> produced this greek translation  
<a onclick="modifyYTiframeseektime('59')">0:00:59</a> were living in a world that had been  
<a onclick="modifyYTiframeseektime('60')">0:01:00</a> conquered by alexander the great in the  
<a onclick="modifyYTiframeseektime('63')">0:01:03</a> fourth century and he had basically  
<a onclick="modifyYTiframeseektime('65')">0:01:05</a> conquered most of the mediterranean  
<a onclick="modifyYTiframeseektime('67')">0:01:07</a> world introduced and spread greek ideas  
<a onclick="modifyYTiframeseektime('70')">0:01:10</a> of greek philosophy greek reason culture  
<a onclick="modifyYTiframeseektime('73')">0:01:13</a> and language and the jews many of whom  
<a onclick="modifyYTiframeseektime('75')">0:01:15</a> were living in the diaspora around the  
<a onclick="modifyYTiframeseektime('77')">0:01:17</a> mediterranean  
<a onclick="modifyYTiframeseektime('80')">0:01:20</a> obviously wanted to translate their  
<a onclick="modifyYTiframeseektime('82')">0:01:22</a> bible into their own language so they  
<a onclick="modifyYTiframeseektime('84')">0:01:24</a> translated it into the sceptre again as  
<a onclick="modifyYTiframeseektime('86')">0:01:26</a> it's called  
<a onclick="modifyYTiframeseektime('88')">0:01:28</a> but there's some interesting points here  
<a onclick="modifyYTiframeseektime('90')">0:01:30</a> that peter ends brings up and i want to  
<a onclick="modifyYTiframeseektime('92')">0:01:32</a> share them with you  
<a onclick="modifyYTiframeseektime('93')">0:01:33</a> so he talks about the jews living in the  
<a onclick="modifyYTiframeseektime('96')">0:01:36</a> greek period and the challenges they  
<a onclick="modifyYTiframeseektime('98')">0:01:38</a> face because these are monotheistic  
<a onclick="modifyYTiframeseektime('99')">0:01:39</a> people living in a pagan environment  
<a onclick="modifyYTiframeseektime('103')">0:01:43</a> and they address these challenges that  
<a onclick="modifyYTiframeseektime('105')">0:01:45</a> they face in a number of ways he writes  
<a onclick="modifyYTiframeseektime('108')">0:01:48</a> one of which is the greek translation of  
<a onclick="modifyYTiframeseektime('110')">0:01:50</a> the hebrew old testament called the  
<a onclick="modifyYTiframeseektime('113')">0:01:53</a> septuagint the little footnote at the  
<a onclick="modifyYTiframeseektime('115')">0:01:55</a> bottom here which is quite helpful the  
<a onclick="modifyYTiframeseektime('117')">0:01:57</a> sexually it means in english 70 and the  
<a onclick="modifyYTiframeseektime('121')">0:02:01</a> name is based on a jewish legend that  
<a onclick="modifyYTiframeseektime('124')">0:02:04</a> six members of each of the 12 tribes so  
<a onclick="modifyYTiframeseektime('127')">0:02:07</a> 72  
<a onclick="modifyYTiframeseektime('129')">0:02:09</a> were sequestered on an island and  
<a onclick="modifyYTiframeseektime('131')">0:02:11</a> miraculously cranked out the translation  
<a onclick="modifyYTiframeseektime('135')">0:02:15</a> in short order but the historical truth  
<a onclick="modifyYTiframeseektime('138')">0:02:18</a> he says is more complicated the greek  
<a onclick="modifyYTiframeseektime('140')">0:02:20</a> translations were probably grassroots  
<a onclick="modifyYTiframeseektime('143')">0:02:23</a> efforts made in many different places  
<a onclick="modifyYTiframeseektime('146')">0:02:26</a> over time after the greek conquest  
<a onclick="modifyYTiframeseektime('149')">0:02:29</a> but the important point here is the new  
<a onclick="modifyYTiframeseektime('151')">0:02:31</a> testament writers almost always relied  
<a onclick="modifyYTiframeseektime('154')">0:02:34</a> on this translation this sceptre again  
<a onclick="modifyYTiframeseektime('157')">0:02:37</a> so it's not a minor point this  
<a onclick="modifyYTiframeseektime('159')">0:02:39</a> now he goes on and says translations are  
<a onclick="modifyYTiframeseektime('162')">0:02:42</a> great places for religious groups  
<a onclick="modifyYTiframeseektime('165')">0:02:45</a> ancient and modern to introduce course  
<a onclick="modifyYTiframeseektime('168')">0:02:48</a> correctives to some things that might  
<a onclick="modifyYTiframeseektime('170')">0:02:50</a> cause embarrassment now he doesn't  
<a onclick="modifyYTiframeseektime('173')">0:02:53</a> mention it in this book but some very  
<a onclick="modifyYTiframeseektime('175')">0:02:55</a> recent very good  
<a onclick="modifyYTiframeseektime('177')">0:02:57</a> translations of the bible have  
<a onclick="modifyYTiframeseektime('179')">0:02:59</a> introduced uh more shall we say  
<a onclick="modifyYTiframeseektime('182')">0:03:02</a> culturally sensitive language for the  
<a onclick="modifyYTiframeseektime('184')">0:03:04</a> western audience there's you know the  
<a onclick="modifyYTiframeseektime('186')">0:03:06</a> language is changing and adjusting  
<a onclick="modifyYTiframeseektime('188')">0:03:08</a> itself to the latest cultural fashions  
<a onclick="modifyYTiframeseektime('191')">0:03:11</a> we still see that going on today  
<a onclick="modifyYTiframeseektime('193')">0:03:13</a> but back to peter ends you give some  
<a onclick="modifyYTiframeseektime('196')">0:03:16</a> examples  
<a onclick="modifyYTiframeseektime('198')">0:03:18</a> now in genesis chapter 2 verse 2 in  
<a onclick="modifyYTiframeseektime('201')">0:03:21</a> hebrew  
<a onclick="modifyYTiframeseektime('202')">0:03:22</a> it says that god finished the work of  
<a onclick="modifyYTiframeseektime('205')">0:03:25</a> creation on the seventh day now peter  
<a onclick="modifyYTiframeseektime('208')">0:03:28</a> ends being a biblical scholar he can  
<a onclick="modifyYTiframeseektime('210')">0:03:30</a> read the hebrew you can read the greek  
<a onclick="modifyYTiframeseektime('212')">0:03:32</a> and he says in hebrew it says god  
<a onclick="modifyYTiframeseektime('214')">0:03:34</a> finished the work of creation on the  
<a onclick="modifyYTiframeseektime('216')">0:03:36</a> seventh day that sound a bit odd  
<a onclick="modifyYTiframeseektime('218')">0:03:38</a> which if you think about it suggests  
<a onclick="modifyYTiframeseektime('220')">0:03:40</a> that god actually did some work on the  
<a onclick="modifyYTiframeseektime('223')">0:03:43</a> seventh day  
<a onclick="modifyYTiframeseektime('224')">0:03:44</a> and then took the afternoon off  
<a onclick="modifyYTiframeseektime('227')">0:03:47</a> but that would imply that god broke on  
<a onclick="modifyYTiframeseektime('230')">0:03:50</a> page one of the bible his own  
<a onclick="modifyYTiframeseektime('232')">0:03:52</a> commandment to do no work on the sabbath  
<a onclick="modifyYTiframeseektime('236')">0:03:56</a> the greek translators saw the problem  
<a onclick="modifyYTiframeseektime('239')">0:03:59</a> and made a minor adjustment  
<a onclick="modifyYTiframeseektime('242')">0:04:02</a> and they wrote translating into english  
<a onclick="modifyYTiframeseektime('244')">0:04:04</a> he finished on the sixth day his works  
<a onclick="modifyYTiframeseektime('249')">0:04:09</a> now god doesn't contradict himself  
<a onclick="modifyYTiframeseektime('251')">0:04:11</a> problem  
<a onclick="modifyYTiframeseektime('252')">0:04:12</a> solved another example  
<a onclick="modifyYTiframeseektime('255')">0:04:15</a> the hebrew word for a sacrificial altar  
<a onclick="modifyYTiframeseektime('259')">0:04:19</a> mizbeach if i pronounce that correctly  
<a onclick="modifyYTiframeseektime('261')">0:04:21</a> in hebrew nisbet  
<a onclick="modifyYTiframeseektime('262')">0:04:22</a> is used pretty much across the board in  
<a onclick="modifyYTiframeseektime('264')">0:04:24</a> the old testament no matter whose alter  
<a onclick="modifyYTiframeseektime('267')">0:04:27</a> it is  
<a onclick="modifyYTiframeseektime('269')">0:04:29</a> whether it be a pagan or a jewish altar  
<a onclick="modifyYTiframeseektime('271')">0:04:31</a> it doesn't matter it's the same words  
<a onclick="modifyYTiframeseektime('272')">0:04:32</a> used the greek translators however like  
<a onclick="modifyYTiframeseektime('276')">0:04:36</a> to use two different words in their  
<a onclick="modifyYTiframeseektime('278')">0:04:38</a> translation  
<a onclick="modifyYTiframeseektime('279')">0:04:39</a> depending on whether the altar was  
<a onclick="modifyYTiframeseektime('281')">0:04:41</a> israelite or pagan  
<a onclick="modifyYTiframeseektime('284')">0:04:44</a> that change helped clarify that  
<a onclick="modifyYTiframeseektime('286')">0:04:46</a> sacrificing to god is nothing like  
<a onclick="modifyYTiframeseektime('289')">0:04:49</a> sacrificing to other gods  
<a onclick="modifyYTiframeseektime('291')">0:04:51</a> not a bad adjustment for jews living in  
<a onclick="modifyYTiframeseektime('294')">0:04:54</a> greek polytheistic culture  
<a onclick="modifyYTiframeseektime('296')">0:04:56</a> trying to maintain their identity amid  
<a onclick="modifyYTiframeseektime('299')">0:04:59</a> the temples and strange gods all around  
<a onclick="modifyYTiframeseektime('303')">0:05:03</a> them  
<a onclick="modifyYTiframeseektime('304')">0:05:04</a> so what peter is  
<a onclick="modifyYTiframeseektime('306')">0:05:06</a> doing here is giving us a number of  
<a onclick="modifyYTiframeseektime('307')">0:05:07</a> examples of how this greek translation  
<a onclick="modifyYTiframeseektime('311')">0:05:11</a> subtly or not so subtly alters the words  
<a onclick="modifyYTiframeseektime('314')">0:05:14</a> of the original bible to make it more  
<a onclick="modifyYTiframeseektime('316')">0:05:16</a> up-to-date more acceptable to people in  
<a onclick="modifyYTiframeseektime('320')">0:05:20</a> the hellenistic world  
<a onclick="modifyYTiframeseektime('322')">0:05:22</a> and um this matters because this greek  
<a onclick="modifyYTiframeseektime('325')">0:05:25</a> translation  
<a onclick="modifyYTiframeseektime('326')">0:05:26</a> is the very translation used by new  
<a onclick="modifyYTiframeseektime('328')">0:05:28</a> testament writers they're not quoting  
<a onclick="modifyYTiframeseektime('330')">0:05:30</a> from the original  
<a onclick="modifyYTiframeseektime('331')">0:05:31</a> another example  
<a onclick="modifyYTiframeseektime('333')">0:05:33</a> in hebrew in exodus 24 10  
<a onclick="modifyYTiframeseektime('336')">0:05:36</a> says rather casually  
<a onclick="modifyYTiframeseektime('339')">0:05:39</a> that moses and a party and of more than  
<a onclick="modifyYTiframeseektime('342')">0:05:42</a> 70 israelites  
<a onclick="modifyYTiframeseektime('344')">0:05:44</a> saw the god of israel so it says in the  
<a onclick="modifyYTiframeseektime('347')">0:05:47</a> hebrew they saw the god of israel which  
<a onclick="modifyYTiframeseektime('349')">0:05:49</a> is a problem because no one is actually  
<a onclick="modifyYTiframeseektime('351')">0:05:51</a> supposed to be able to see god  
<a onclick="modifyYTiframeseektime('355')">0:05:55</a> the greek translation  
<a onclick="modifyYTiframeseektime('357')">0:05:57</a> shifts the focus literally  
<a onclick="modifyYTiframeseektime('360')">0:06:00</a> they quote saw the place where the god  
<a onclick="modifyYTiframeseektime('363')">0:06:03</a> of israel stood they saw the place where  
<a onclick="modifyYTiframeseektime('366')">0:06:06</a> the god of it let's look and see god  
<a onclick="modifyYTiframeseektime('367')">0:06:07</a> they just saw the place where he stood  
<a onclick="modifyYTiframeseektime('370')">0:06:10</a> likewise  
<a onclick="modifyYTiframeseektime('372')">0:06:12</a> after instructions for building the  
<a onclick="modifyYTiframeseektime('374')">0:06:14</a> mercy seat atop the ark of the covenant  
<a onclick="modifyYTiframeseektime('377')">0:06:17</a> god says  
<a onclick="modifyYTiframeseektime('378')">0:06:18</a> there i will meet with you exodus 25 22.  
<a onclick="modifyYTiframeseektime('384')">0:06:24</a> in the scepter again god says i will  
<a onclick="modifyYTiframeseektime('386')">0:06:26</a> make myself known to you  
<a onclick="modifyYTiframeseektime('390')">0:06:30</a> which avoids the possibility of god's  
<a onclick="modifyYTiframeseektime('392')">0:06:32</a> physically appearing to moses  
<a onclick="modifyYTiframeseektime('395')">0:06:35</a> a subtle but important change and again  
<a onclick="modifyYTiframeseektime('398')">0:06:38</a> in numbers 3 16  
<a onclick="modifyYTiframeseektime('400')">0:06:40</a> it's a book in the bible  
<a onclick="modifyYTiframeseektime('402')">0:06:42</a> where the hebrew refers to god's very  
<a onclick="modifyYTiframeseektime('405')">0:06:45</a> human-like mouth  
<a onclick="modifyYTiframeseektime('407')">0:06:47</a> the greek translation replaces mouth  
<a onclick="modifyYTiframeseektime('410')">0:06:50</a> with god's voice  
<a onclick="modifyYTiframeseektime('412')">0:06:52</a> yes humans have voices too but at least  
<a onclick="modifyYTiframeseektime('415')">0:06:55</a> now god doesn't have a body so he's  
<a onclick="modifyYTiframeseektime('417')">0:06:57</a> suggesting here that the greek  
<a onclick="modifyYTiframeseektime('419')">0:06:59</a> translators change the language used to  
<a onclick="modifyYTiframeseektime('422')">0:07:02</a> describe god to make it fit in with  
<a onclick="modifyYTiframeseektime('425')">0:07:05</a> greek philosophical ideas about god not  
<a onclick="modifyYTiframeseektime('427')">0:07:07</a> having a body being being an abstraction  
<a onclick="modifyYTiframeseektime('430')">0:07:10</a> being eternal and not being this quite  
<a onclick="modifyYTiframeseektime('432')">0:07:12</a> anthropomorphic figure we see often in  
<a onclick="modifyYTiframeseektime('435')">0:07:15</a> biblical passages  
<a onclick="modifyYTiframeseektime('438')">0:07:18</a> the septuagint he says this is the greek  
<a onclick="modifyYTiframeseektime('440')">0:07:20</a> translation really wants to make god  
<a onclick="modifyYTiframeseektime('442')">0:07:22</a> seem more well  
<a onclick="modifyYTiframeseektime('444')">0:07:24</a> god-like  
<a onclick="modifyYTiframeseektime('445')">0:07:25</a> god like to a greek jewish audience that  
<a onclick="modifyYTiframeseektime('448')">0:07:28</a> is  
<a onclick="modifyYTiframeseektime('449')">0:07:29</a> another example in genesis 6 6 chapter 6  
<a onclick="modifyYTiframeseektime('453')">0:07:33</a> verse 6  
<a onclick="modifyYTiframeseektime('454')">0:07:34</a> which still troubles some readers today  
<a onclick="modifyYTiframeseektime('458')">0:07:38</a> yahweh it says  
<a onclick="modifyYTiframeseektime('460')">0:07:40</a> says he was sorry he created humans so  
<a onclick="modifyYTiframeseektime('463')">0:07:43</a> god is sorry he created humans in  
<a onclick="modifyYTiframeseektime('467')">0:07:47</a> genesis 6 6.  
<a onclick="modifyYTiframeseektime('468')">0:07:48</a> and it says it grieved him to his heart  
<a onclick="modifyYTiframeseektime('472')">0:07:52</a> it grieved him god was grieved because  
<a onclick="modifyYTiframeseektime('475')">0:07:55</a> they kept sinning which led god to drown  
<a onclick="modifyYTiframeseektime('477')">0:07:57</a> everyone  
<a onclick="modifyYTiframeseektime('479')">0:07:59</a> how can someone the jews claim to be the  
<a onclick="modifyYTiframeseektime('482')">0:08:02</a> true god seem so indecisive not to  
<a onclick="modifyYTiframeseektime('486')">0:08:06</a> mention prone to reactive human-like  
<a onclick="modifyYTiframeseektime('488')">0:08:08</a> emotions peter enz asks so the greek  
<a onclick="modifyYTiframeseektime('492')">0:08:12</a> translation  
<a onclick="modifyYTiframeseektime('494')">0:08:14</a> simply gets rid of our idea altogether  
<a onclick="modifyYTiframeseektime('496')">0:08:16</a> instead of being sorry  
<a onclick="modifyYTiframeseektime('499')">0:08:19</a> the lord thought deeply that's what the  
<a onclick="modifyYTiframeseektime('501')">0:08:21</a> greek says the lord thought deeply  
<a onclick="modifyYTiframeseektime('504')">0:08:24</a> instead of grieving  
<a onclick="modifyYTiframeseektime('506')">0:08:26</a> god pondered  
<a onclick="modifyYTiframeseektime('508')">0:08:28</a> yeah so god does it's not sorry he  
<a onclick="modifyYTiframeseektime('510')">0:08:30</a> thought deeply he's not grieving he  
<a onclick="modifyYTiframeseektime('513')">0:08:33</a> pondered  
<a onclick="modifyYTiframeseektime('514')">0:08:34</a> now god is very a very greek like  
<a onclick="modifyYTiframeseektime('517')">0:08:37</a> rational he's in control of the whole  
<a onclick="modifyYTiframeseektime('520')">0:08:40</a> process god isn't taken off god and  
<a onclick="modifyYTiframeseektime('522')">0:08:42</a> doesn't change his mind  
<a onclick="modifyYTiframeseektime('525')">0:08:45</a> remember this is the bible the greek  
<a onclick="modifyYTiframeseektime('527')">0:08:47</a> bible that's quoted in the new testament  
<a onclick="modifyYTiframeseektime('529')">0:08:49</a> not the not the original hebrew  
<a onclick="modifyYTiframeseektime('531')">0:08:51</a> just to make a point  
<a onclick="modifyYTiframeseektime('533')">0:08:53</a> apparently the ancient israelites  
<a onclick="modifyYTiframeseektime('535')">0:08:55</a> weren't bothered by genesis 6 6  
<a onclick="modifyYTiframeseektime('538')">0:08:58</a> but we are he says  
<a onclick="modifyYTiframeseektime('540')">0:09:00</a> we should let that sink in  
<a onclick="modifyYTiframeseektime('543')">0:09:03</a> christians today and by the way this  
<a onclick="modifyYTiframeseektime('545')">0:09:05</a> book is really written with an eye to  
<a onclick="modifyYTiframeseektime('546')">0:09:06</a> christians today and how christians  
<a onclick="modifyYTiframeseektime('549')">0:09:09</a> particularly american christians deal  
<a onclick="modifyYTiframeseektime('550')">0:09:10</a> with the biblical texts  
<a onclick="modifyYTiframeseektime('552')">0:09:12</a> christians today perhaps have more in  
<a onclick="modifyYTiframeseektime('554')">0:09:14</a> common with jews living in a greek world  
<a onclick="modifyYTiframeseektime('557')">0:09:17</a> than we would with the the israelites of  
<a onclick="modifyYTiframeseektime('560')">0:09:20</a> the time of david and solomon  
<a onclick="modifyYTiframeseektime('563')">0:09:23</a> we expect certain things of god  
<a onclick="modifyYTiframeseektime('566')">0:09:26</a> and are bothered when we don't see them  
<a onclick="modifyYTiframeseektime('568')">0:09:28</a> in the bible so he's talking about how  
<a onclick="modifyYTiframeseektime('571')">0:09:31</a> many average christians in america  
<a onclick="modifyYTiframeseektime('573')">0:09:33</a> particularly they read the old testament  
<a onclick="modifyYTiframeseektime('575')">0:09:35</a> for the first time and they see  
<a onclick="modifyYTiframeseektime('576')">0:09:36</a> depictions of god that disturb them  
<a onclick="modifyYTiframeseektime('579')">0:09:39</a> and the greek translators  
<a onclick="modifyYTiframeseektime('582')">0:09:42</a> change the wording very often to kind of  
<a onclick="modifyYTiframeseektime('584')">0:09:44</a> soften that or to take away the problem  
<a onclick="modifyYTiframeseektime('588')">0:09:48</a> and he basically approves of this by the  
<a onclick="modifyYTiframeseektime('590')">0:09:50</a> way  
<a onclick="modifyYTiframeseektime('591')">0:09:51</a> so another example likewise according to  
<a onclick="modifyYTiframeseektime('593')">0:09:53</a> exodus 4 24  
<a onclick="modifyYTiframeseektime('596')">0:09:56</a> in the hebrew of course  
<a onclick="modifyYTiframeseektime('598')">0:09:58</a> yahweh is waiting for moses by the side  
<a onclick="modifyYTiframeseektime('601')">0:10:01</a> of the road to somewhat shockingly kill  
<a onclick="modifyYTiframeseektime('604')">0:10:04</a> him  
<a onclick="modifyYTiframeseektime('605')">0:10:05</a> when he had just gotten done convincing  
<a onclick="modifyYTiframeseektime('608')">0:10:08</a> moses to go back to egypt and deliver  
<a onclick="modifyYTiframeseektime('611')">0:10:11</a> the israelite slaves  
<a onclick="modifyYTiframeseektime('613')">0:10:13</a> the greek translation clearly concerned  
<a onclick="modifyYTiframeseektime('616')">0:10:16</a> with such a painful ungodlike about face  
<a onclick="modifyYTiframeseektime('619')">0:10:19</a> god suddenly changing his mind  
<a onclick="modifyYTiframeseektime('621')">0:10:21</a> says that the angel of the lord was  
<a onclick="modifyYTiframeseektime('625')">0:10:25</a> waiting for moses so it's not god  
<a onclick="modifyYTiframeseektime('627')">0:10:27</a> anymore it's an angel sure that doesn't  
<a onclick="modifyYTiframeseektime('630')">0:10:30</a> solve the problem entirely he writes but  
<a onclick="modifyYTiframeseektime('632')">0:10:32</a> at least god has a buffer so god now is  
<a onclick="modifyYTiframeseektime('636')">0:10:36</a> not directly implicated in killing one  
<a onclick="modifyYTiframeseektime('638')">0:10:38</a> of his prophets or trying to kill one of  
<a onclick="modifyYTiframeseektime('640')">0:10:40</a> his prophets having just convinced moses  
<a onclick="modifyYTiframeseektime('642')">0:10:42</a> to go back to egypt and deliver the  
<a onclick="modifyYTiframeseektime('645')">0:10:45</a> israelite slaves  
<a onclick="modifyYTiframeseektime('647')">0:10:47</a> these examples peter n says illustrate a  
<a onclick="modifyYTiframeseektime('650')">0:10:50</a> vital concept for us  
<a onclick="modifyYTiframeseektime('653')">0:10:53</a> jews at the time changed their sacred  
<a onclick="modifyYTiframeseektime('656')">0:10:56</a> texts to clarify an inverted commas in  
<a onclick="modifyYTiframeseektime('660')">0:11:00</a> their time and place what god is like  
<a onclick="modifyYTiframeseektime('663')">0:11:03</a> they change the bible to accommodate  
<a onclick="modifyYTiframeseektime('666')">0:11:06</a> their culture now this is a really  
<a onclick="modifyYTiframeseektime('668')">0:11:08</a> important point i think it's pretty much  
<a onclick="modifyYTiframeseektime('670')">0:11:10</a> irrefutable the evidence is there in the  
<a onclick="modifyYTiframeseektime('672')">0:11:12</a> hebrew and the greek  
<a onclick="modifyYTiframeseektime('673')">0:11:13</a> that the the jews of that time changed  
<a onclick="modifyYTiframeseektime('675')">0:11:15</a> the bible to make it accommodate to make  
<a onclick="modifyYTiframeseektime('677')">0:11:17</a> it conform to make it fit in with the  
<a onclick="modifyYTiframeseektime('680')">0:11:20</a> culture of the hellenistic world the  
<a onclick="modifyYTiframeseektime('683')">0:11:23</a> world of alexandra the great greek  
<a onclick="modifyYTiframeseektime('685')">0:11:25</a> thought greek philosophy greek customs  
<a onclick="modifyYTiframeseektime('687')">0:11:27</a> greek understandings of god the bible  
<a onclick="modifyYTiframeseektime('689')">0:11:29</a> has literally changed and it's that  
<a onclick="modifyYTiframeseektime('691')">0:11:31</a> bible is that as i say used by the new  
<a onclick="modifyYTiframeseektime('693')">0:11:33</a> testament writers  
<a onclick="modifyYTiframeseektime('696')">0:11:36</a> and then he goes on and again with an  
<a onclick="modifyYTiframeseektime('698')">0:11:38</a> eye to the contemporary issues in modern  
<a onclick="modifyYTiframeseektime('700')">0:11:40</a> america all this reminds me of a recent  
<a onclick="modifyYTiframeseektime('703')">0:11:43</a> controversy he writes among some  
<a onclick="modifyYTiframeseektime('705')">0:11:45</a> christians namely whether bible  
<a onclick="modifyYTiframeseektime('708')">0:11:48</a> translations today  
<a onclick="modifyYTiframeseektime('710')">0:11:50</a> should use gender inclusive language in  
<a onclick="modifyYTiframeseektime('713')">0:11:53</a> other words to to use language refers to  
<a onclick="modifyYTiframeseektime('716')">0:11:56</a> male and female rather than just male  
<a onclick="modifyYTiframeseektime('718')">0:11:58</a> because often  
<a onclick="modifyYTiframeseektime('719')">0:11:59</a> in the greek  
<a onclick="modifyYTiframeseektime('720')">0:12:00</a> uh it refers to um uses the male term  
<a onclick="modifyYTiframeseektime('723')">0:12:03</a> and so gender inclusive language refers  
<a onclick="modifyYTiframeseektime('725')">0:12:05</a> to male and female  
<a onclick="modifyYTiframeseektime('728')">0:12:08</a> talk about a food fight he says  
<a onclick="modifyYTiframeseektime('730')">0:12:10</a> whatever might we might one might think  
<a onclick="modifyYTiframeseektime('733')">0:12:13</a> of it the argument that gender inclusive  
<a onclick="modifyYTiframeseektime('736')">0:12:16</a> language is simply compromising the  
<a onclick="modifyYTiframeseektime('738')">0:12:18</a> bible for the sake of culture  
<a onclick="modifyYTiframeseektime('741')">0:12:21</a> rings rather hollow  
<a onclick="modifyYTiframeseektime('743')">0:12:23</a> he says when we look at what the jews  
<a onclick="modifyYTiframeseektime('745')">0:12:25</a> were doing about 2300 years ago  
<a onclick="modifyYTiframeseektime('749')">0:12:29</a> they produced a culturally influenced  
<a onclick="modifyYTiframeseektime('752')">0:12:32</a> bible translation  
<a onclick="modifyYTiframeseektime('754')">0:12:34</a> the translation that oh sweet irony  
<a onclick="modifyYTiframeseektime('758')">0:12:38</a> became the bible of the new testament  
<a onclick="modifyYTiframeseektime('761')">0:12:41</a> writers  
<a onclick="modifyYTiframeseektime('763')">0:12:43</a> i'll leave it there so  
<a onclick="modifyYTiframeseektime('764')">0:12:44</a> here's a he is a writer who is a fairly  
<a onclick="modifyYTiframeseektime('767')">0:12:47</a> progressive fairly liberal evangelical  
<a onclick="modifyYTiframeseektime('770')">0:12:50</a> christian  
<a onclick="modifyYTiframeseektime('771')">0:12:51</a> and so he you know he's making a virtue  
<a onclick="modifyYTiframeseektime('773')">0:12:53</a> out of necessity necessity is we've got  
<a onclick="modifyYTiframeseektime('775')">0:12:55</a> to face the facts that the uh the new  
<a onclick="modifyYTiframeseektime('777')">0:12:57</a> testament writers were quoting from a  
<a onclick="modifyYTiframeseektime('779')">0:12:59</a> translation which has substantially  
<a onclick="modifyYTiframeseektime('781')">0:13:01</a> altered the hebrew bible  
<a onclick="modifyYTiframeseektime('784')">0:13:04</a> so  
<a onclick="modifyYTiframeseektime('785')">0:13:05</a> we can kind of do the same again we can  
<a onclick="modifyYTiframeseektime('788')">0:13:08</a> introduce gender inclusive language he  
<a onclick="modifyYTiframeseektime('790')">0:13:10</a> goes on later to talk about other things  
<a onclick="modifyYTiframeseektime('792')">0:13:12</a> uh to do with homosexuality and gay  
<a onclick="modifyYTiframeseektime('794')">0:13:14</a> marriage and he is allowing these  
<a onclick="modifyYTiframeseektime('796')">0:13:16</a> changes to justify further changes to uh  
<a onclick="modifyYTiframeseektime('801')">0:13:21</a> the biblical uh text and our  
<a onclick="modifyYTiframeseektime('803')">0:13:23</a> understanding of what god's word is to  
<a onclick="modifyYTiframeseektime('806')">0:13:26</a> us today  
<a onclick="modifyYTiframeseektime('807')">0:13:27</a> so um i'm obviously not focusing on that  
<a onclick="modifyYTiframeseektime('810')">0:13:30</a> so much but just on how the new  
<a onclick="modifyYTiframeseektime('812')">0:13:32</a> testament writers quoted from a  
<a onclick="modifyYTiframeseektime('814')">0:13:34</a> translation that had already altered and  
<a onclick="modifyYTiframeseektime('817')">0:13:37</a> changed the text of the hebrew bible  
<a onclick="modifyYTiframeseektime('820')">0:13:40</a> itself  
<a onclick="modifyYTiframeseektime('821')">0:13:41</a> and then of course  
<a onclick="modifyYTiframeseektime('823')">0:13:43</a> we mustn't forget that we read the new  
<a onclick="modifyYTiframeseektime('825')">0:13:45</a> testament in english so we have the  
<a onclick="modifyYTiframeseektime('828')">0:13:48</a> hebrew original  
<a onclick="modifyYTiframeseektime('829')">0:13:49</a> we have the greek new testament which  
<a onclick="modifyYTiframeseektime('832')">0:13:52</a> quotes from a translation of the hebrew  
<a onclick="modifyYTiframeseektime('835')">0:13:55</a> and then it's translated again  
<a onclick="modifyYTiframeseektime('837')">0:13:57</a> into english you have this layer upon  
<a onclick="modifyYTiframeseektime('839')">0:13:59</a> layer upon layer  
<a onclick="modifyYTiframeseektime('841')">0:14:01</a> of every act of translation by the way  
<a onclick="modifyYTiframeseektime('843')">0:14:03</a> isn't just a mechanical process it's an  
<a onclick="modifyYTiframeseektime('846')">0:14:06</a> act of interpretation  
<a onclick="modifyYTiframeseektime('848')">0:14:08</a> it's not a simple word for word  
<a onclick="modifyYTiframeseektime('851')">0:14:11</a> translation is every act  
<a onclick="modifyYTiframeseektime('853')">0:14:13</a> of translation is an interpretation  
<a onclick="modifyYTiframeseektime('856')">0:14:16</a> itself  
<a onclick="modifyYTiframeseektime('857')">0:14:17</a> anyway that's um what i wanted to say  
<a onclick="modifyYTiframeseektime('859')">0:14:19</a> and i do recommend this book it's  
<a onclick="modifyYTiframeseektime('861')">0:14:21</a> written in a quite a tabloidy way to a  
<a onclick="modifyYTiframeseektime('864')">0:14:24</a> popular american audience and even  
<a onclick="modifyYTiframeseektime('866')">0:14:26</a> though this style is very american in  
<a onclick="modifyYTiframeseektime('868')">0:14:28</a> places um i think there are a lot of  
<a onclick="modifyYTiframeseektime('871')">0:14:31</a> hard  
<a onclick="modifyYTiframeseektime('872')">0:14:32</a> nuggets of facts in here which are worth  
<a onclick="modifyYTiframeseektime('875')">0:14:35</a> getting to know about if you want to  
<a onclick="modifyYTiframeseektime('877')">0:14:37</a> understand how the bible actually works  
<a onclick="modifyYTiframeseektime('880')">0:14:40</a> until next time  

</details>
