# Prophet Muhammad in the Bible? A personal view. (2021-04-19)

<iframe loading='lazy' src='https://www.youtube.com/embed/JbH7lO06z6o'></iframe>

## Description

Filmed at Speakers' Corner last weekend.

## Summary of [Prophet Muhammad in the Bible? A personal view.](https://www.youtube.com/watch?v=JbH7lO06z6o)


*<span style="color:red; font-size:125%">This summary is AI generated - there may be inaccuracies</span>. [](/)*

### <a onclick="modifyYTiframeseektime('0')">00:00:00</a> - <a onclick="modifyYTiframeseektime('300')">00:05:00</a>

 discusses the idea that the figure of the "paracletos" in the Bible could be interpreted as Muhammad, despite the objections of Christians. It is argued that this is possible with the understanding that God has sent other prophets.

**<a onclick="modifyYTiframeseektime('0')">00:00:00</a>** This individual believes that the scriptures can be read in a way that references Muhammad, despite the objections of Christians. They state that this is done with the understanding that God has sent other prophets.
* **<a onclick="modifyYTiframeseektime('300')">00:05:00</a>** discusses the idea that there will be a human figure who comes after Jesus in the Bible, known as the "paracletos." Scholars from both Christianity and Islam agree that this figure is not Muhammad, but instead another figure from early Christianity.

<details><summary><h2>Full transcript with timestamps: CLICK TO EXPAND</h2></summary>

<a onclick="modifyYTiframeseektime('6')">0:00:06</a> [Music]  
<a onclick="modifyYTiframeseektime('7')">0:00:07</a> we've  
<a onclick="modifyYTiframeseektime('7')">0:00:07</a> been in discussions with people before  
<a onclick="modifyYTiframeseektime('10')">0:00:10</a> and they referred to  
<a onclick="modifyYTiframeseektime('12')">0:00:12</a> scriptures in  
<a onclick="modifyYTiframeseektime('20')">0:00:20</a> [Laughter]  
<a onclick="modifyYTiframeseektime('29')">0:00:29</a> i like to look at religious texts both  
<a onclick="modifyYTiframeseektime('31')">0:00:31</a> historically and academically as well as  
<a onclick="modifyYTiframeseektime('33')">0:00:33</a> from a religious point of view  
<a onclick="modifyYTiframeseektime('35')">0:00:35</a> i need to be consistent so i will say  
<a onclick="modifyYTiframeseektime('39')">0:00:39</a> i would say two things on one level the  
<a onclick="modifyYTiframeseektime('41')">0:00:41</a> level of historical exegesis  
<a onclick="modifyYTiframeseektime('43')">0:00:43</a> isaiah 42 is not about muhammad  
<a onclick="modifyYTiframeseektime('48')">0:00:48</a> it's about events in isaiah's day  
<a onclick="modifyYTiframeseektime('52')">0:00:52</a> but and so that's on one level and same  
<a onclick="modifyYTiframeseektime('55')">0:00:55</a> with deuteronomy 18 18  
<a onclick="modifyYTiframeseektime('57')">0:00:57</a> it's not obviously about muhammad it  
<a onclick="modifyYTiframeseektime('58')">0:00:58</a> could be about other other people it  
<a onclick="modifyYTiframeseektime('59')">0:00:59</a> could be about joshua for example and  
<a onclick="modifyYTiframeseektime('61')">0:01:01</a> jesus  
<a onclick="modifyYTiframeseektime('61')">0:01:01</a> will say it's about other people that's  
<a onclick="modifyYTiframeseektime('63')">0:01:03</a> fine but and this is another view here  
<a onclick="modifyYTiframeseektime('66')">0:01:06</a> and this is why  
<a onclick="modifyYTiframeseektime('67')">0:01:07</a> i can say it is about them as well  
<a onclick="modifyYTiframeseektime('69')">0:01:09</a> because  
<a onclick="modifyYTiframeseektime('70')">0:01:10</a> if you know that muhammad if you believe  
<a onclick="modifyYTiframeseektime('72')">0:01:12</a> that muhammad is a prophet of god  
<a onclick="modifyYTiframeseektime('74')">0:01:14</a> a man sent by god himself and that part  
<a onclick="modifyYTiframeseektime('77')">0:01:17</a> of his message  
<a onclick="modifyYTiframeseektime('78')">0:01:18</a> is that the previous scriptures mention  
<a onclick="modifyYTiframeseektime('80')">0:01:20</a> him  
<a onclick="modifyYTiframeseektime('81')">0:01:21</a> then it is legitimate theologically to  
<a onclick="modifyYTiframeseektime('84')">0:01:24</a> read those scriptures  
<a onclick="modifyYTiframeseektime('86')">0:01:26</a> in the light of the revelation that  
<a onclick="modifyYTiframeseektime('88')">0:01:28</a> mohammed bought  
<a onclick="modifyYTiframeseektime('89')">0:01:29</a> brought yeah but what about what you  
<a onclick="modifyYTiframeseektime('91')">0:01:31</a> know like so so  
<a onclick="modifyYTiframeseektime('92')">0:01:32</a> that you can say this is how my cake and  
<a onclick="modifyYTiframeseektime('93')">0:01:33</a> eat it in a sense it is but christians  
<a onclick="modifyYTiframeseektime('96')">0:01:36</a> do this as well when they read  
<a onclick="modifyYTiframeseektime('97')">0:01:37</a> all these old testament texts in the  
<a onclick="modifyYTiframeseektime('98')">0:01:38</a> light of christ when they have nothing  
<a onclick="modifyYTiframeseektime('100')">0:01:40</a> to do with jesus  
<a onclick="modifyYTiframeseektime('101')">0:01:41</a> as they could yeah but if you believe  
<a onclick="modifyYTiframeseektime('104')">0:01:44</a> that jesus said by god  
<a onclick="modifyYTiframeseektime('105')">0:01:45</a> uh then you can do that theologically i  
<a onclick="modifyYTiframeseektime('108')">0:01:48</a> don't see that as invalid  
<a onclick="modifyYTiframeseektime('109')">0:01:49</a> but at the level of historical exegesis  
<a onclick="modifyYTiframeseektime('112')">0:01:52</a> i couldn't  
<a onclick="modifyYTiframeseektime('113')">0:01:53</a> it's like pulling myself up by my own  
<a onclick="modifyYTiframeseektime('114')">0:01:54</a> bootstraps i couldn't say well just like  
<a onclick="modifyYTiframeseektime('116')">0:01:56</a> 8080 must be about muhammad  
<a onclick="modifyYTiframeseektime('118')">0:01:58</a> because you've got to start from the  
<a onclick="modifyYTiframeseektime('119')">0:01:59</a> belief that muhammad is a prophet of god  
<a onclick="modifyYTiframeseektime('121')">0:02:01</a> then you look back and say  
<a onclick="modifyYTiframeseektime('122')">0:02:02</a> well who best fits this description one  
<a onclick="modifyYTiframeseektime('124')">0:02:04</a> like moses who is one like moses is it  
<a onclick="modifyYTiframeseektime('127')">0:02:07</a> jesus not really  
<a onclick="modifyYTiframeseektime('128')">0:02:08</a> is it muhammad yeah he's a really good  
<a onclick="modifyYTiframeseektime('130')">0:02:10</a> candidate for this description then you  
<a onclick="modifyYTiframeseektime('132')">0:02:12</a> can say  
<a onclick="modifyYTiframeseektime('132')">0:02:12</a> yeah it is about muhammad but the level  
<a onclick="modifyYTiframeseektime('134')">0:02:14</a> of historical exegesis the kind of thing  
<a onclick="modifyYTiframeseektime('136')">0:02:16</a> you do at university  
<a onclick="modifyYTiframeseektime('137')">0:02:17</a> you would not get that conclusion so  
<a onclick="modifyYTiframeseektime('154')">0:02:34</a> moses is talking to the tribe of the  
<a onclick="modifyYTiframeseektime('155')">0:02:35</a> leader he's not talking to the whole of  
<a onclick="modifyYTiframeseektime('157')">0:02:37</a> israel  
<a onclick="modifyYTiframeseektime('158')">0:02:38</a> he's only talking to one tribe so when  
<a onclick="modifyYTiframeseektime('160')">0:02:40</a> he says your brethren he's talking about  
<a onclick="modifyYTiframeseektime('161')">0:02:41</a> the  
<a onclick="modifyYTiframeseektime('162')">0:02:42</a> other christians yeah indeed  
<a onclick="modifyYTiframeseektime('165')">0:02:45</a> at that level of understanding you're  
<a onclick="modifyYTiframeseektime('166')">0:02:46</a> right yeah but if you also know that in  
<a onclick="modifyYTiframeseektime('169')">0:02:49</a> salvation history  
<a onclick="modifyYTiframeseektime('170')">0:02:50</a> that god has sent other prophets jesus  
<a onclick="modifyYTiframeseektime('171')">0:02:51</a> and muhammad then  
<a onclick="modifyYTiframeseektime('173')">0:02:53</a> you can look for that fuller meaning uh  
<a onclick="modifyYTiframeseektime('175')">0:02:55</a> theologically  
<a onclick="modifyYTiframeseektime('177')">0:02:57</a> and that's a valid movement it's not  
<a onclick="modifyYTiframeseektime('179')">0:02:59</a> just the immediate horizon of  
<a onclick="modifyYTiframeseektime('180')">0:03:00</a> understanding  
<a onclick="modifyYTiframeseektime('181')">0:03:01</a> you can look at other horizons in  
<a onclick="modifyYTiframeseektime('182')">0:03:02</a> catholicism it's called the census  
<a onclick="modifyYTiframeseektime('184')">0:03:04</a> plenum  
<a onclick="modifyYTiframeseektime('184')">0:03:04</a> the fullest sense and they use it to  
<a onclick="modifyYTiframeseektime('186')">0:03:06</a> justify their doctrines but  
<a onclick="modifyYTiframeseektime('188')">0:03:08</a> if you look at that bigger context i  
<a onclick="modifyYTiframeseektime('190')">0:03:10</a> don't have a problem with people saying  
<a onclick="modifyYTiframeseektime('191')">0:03:11</a> yes muhammad is prophesied in  
<a onclick="modifyYTiframeseektime('193')">0:03:13</a> general 1818 and in isaiah 42.  
<a onclick="modifyYTiframeseektime('195')">0:03:15</a> christians will object  
<a onclick="modifyYTiframeseektime('196')">0:03:16</a> because they don't believe in muhammad  
<a onclick="modifyYTiframeseektime('198')">0:03:18</a> anyway if they believed in muhammad they  
<a onclick="modifyYTiframeseektime('200')">0:03:20</a> wouldn't object  
<a onclick="modifyYTiframeseektime('201')">0:03:21</a> so it's a question of chicken and egg  
<a onclick="modifyYTiframeseektime('204')">0:03:24</a> where you're coming from  
<a onclick="modifyYTiframeseektime('205')">0:03:25</a> there's no neutral space here there's no  
<a onclick="modifyYTiframeseektime('206')">0:03:26</a> like i'm going to step outside of all  
<a onclick="modifyYTiframeseektime('208')">0:03:28</a> this because the historical critical  
<a onclick="modifyYTiframeseektime('209')">0:03:29</a> method is not neutral either  
<a onclick="modifyYTiframeseektime('211')">0:03:31</a> because it excludes theological readings  
<a onclick="modifyYTiframeseektime('213')">0:03:33</a> it assumes  
<a onclick="modifyYTiframeseektime('215')">0:03:35</a> as a matter of methodology that god  
<a onclick="modifyYTiframeseektime('216')">0:03:36</a> doesn't send profits  
<a onclick="modifyYTiframeseektime('218')">0:03:38</a> he's just looking at the immediate  
<a onclick="modifyYTiframeseektime('219')">0:03:39</a> historical context and that's a choice  
<a onclick="modifyYTiframeseektime('221')">0:03:41</a> to  
<a onclick="modifyYTiframeseektime('222')">0:03:42</a> really restrict your vision to a  
<a onclick="modifyYTiframeseektime('224')">0:03:44</a> particular  
<a onclick="modifyYTiframeseektime('238')">0:03:58</a> the holy spirit in islam of course is  
<a onclick="modifyYTiframeseektime('240')">0:04:00</a> not the third person of the trinity  
<a onclick="modifyYTiframeseektime('242')">0:04:02</a> it is gabriel so did the holy spirit uh  
<a onclick="modifyYTiframeseektime('246')">0:04:06</a> go to muhammad in in the cave initially  
<a onclick="modifyYTiframeseektime('250')">0:04:10</a> uh you know say recite yeah but he says  
<a onclick="modifyYTiframeseektime('253')">0:04:13</a> [Laughter]  
<a onclick="modifyYTiframeseektime('259')">0:04:19</a> well we need to look at the original  
<a onclick="modifyYTiframeseektime('261')">0:04:21</a> hebrew and how that can be interpreted  
<a onclick="modifyYTiframeseektime('263')">0:04:23</a> the semitic languages are not as  
<a onclick="modifyYTiframeseektime('266')">0:04:26</a> simplistic and binary as modern  
<a onclick="modifyYTiframeseektime('268')">0:04:28</a> englishes  
<a onclick="modifyYTiframeseektime('270')">0:04:30</a> so you know how about the one in the  
<a onclick="modifyYTiframeseektime('271')">0:04:31</a> crossbow though  
<a onclick="modifyYTiframeseektime('275')">0:04:35</a> well that's interesting that's actually  
<a onclick="modifyYTiframeseektime('277')">0:04:37</a> a more credible one actually  
<a onclick="modifyYTiframeseektime('279')">0:04:39</a> uh from a historical critical point of  
<a onclick="modifyYTiframeseektime('280')">0:04:40</a> view than all the others  
<a onclick="modifyYTiframeseektime('282')">0:04:42</a> um a whole raft of really seriously  
<a onclick="modifyYTiframeseektime('286')">0:04:46</a> top biblical scholars in the world  
<a onclick="modifyYTiframeseektime('288')">0:04:48</a> people i don't even know them but people  
<a onclick="modifyYTiframeseektime('290')">0:04:50</a> like rudolph bolton for example  
<a onclick="modifyYTiframeseektime('292')">0:04:52</a> who are is probably the greatest new  
<a onclick="modifyYTiframeseektime('294')">0:04:54</a> testament scholar 20th century from  
<a onclick="modifyYTiframeseektime('296')">0:04:56</a> germany  
<a onclick="modifyYTiframeseektime('297')">0:04:57</a> um he was a lutheran but he was a  
<a onclick="modifyYTiframeseektime('299')">0:04:59</a> christian  
<a onclick="modifyYTiframeseektime('301')">0:05:01</a> he said and there's about i mean there's  
<a onclick="modifyYTiframeseektime('303')">0:05:03</a> a whole bibliography in raymond brown's  
<a onclick="modifyYTiframeseektime('305')">0:05:05</a> excellent commentary  
<a onclick="modifyYTiframeseektime('306')">0:05:06</a> uh in the anchor bible series and  
<a onclick="modifyYTiframeseektime('308')">0:05:08</a> raymond brown himself is a brilliant  
<a onclick="modifyYTiframeseektime('309')">0:05:09</a> scholar  
<a onclick="modifyYTiframeseektime('311')">0:05:11</a> and he makes the point that many many  
<a onclick="modifyYTiframeseektime('314')">0:05:14</a> scholars believe the parakletos  
<a onclick="modifyYTiframeseektime('316')">0:05:16</a> to use a greek word um is it referring  
<a onclick="modifyYTiframeseektime('320')">0:05:20</a> originally to another figure a human  
<a onclick="modifyYTiframeseektime('324')">0:05:24</a> figure he who will come after jesus  
<a onclick="modifyYTiframeseektime('327')">0:05:27</a> and bring a message of salvation  
<a onclick="modifyYTiframeseektime('331')">0:05:31</a> so now a lot of scholars who wouldn't  
<a onclick="modifyYTiframeseektime('333')">0:05:33</a> agree with that but a lot of scholars  
<a onclick="modifyYTiframeseektime('334')">0:05:34</a> who do say that it's not just a muslim  
<a onclick="modifyYTiframeseektime('336')">0:05:36</a> idea  
<a onclick="modifyYTiframeseektime('337')">0:05:37</a> this is also something that has been  
<a onclick="modifyYTiframeseektime('339')">0:05:39</a> proposed by academics as well  
<a onclick="modifyYTiframeseektime('341')">0:05:41</a> and in christian history uh if you look  
<a onclick="modifyYTiframeseektime('344')">0:05:44</a> at the early church for example  
<a onclick="modifyYTiframeseektime('346')">0:05:46</a> uh the montanists i don't know if you  
<a onclick="modifyYTiframeseektime('348')">0:05:48</a> know about church history okay the man  
<a onclick="modifyYTiframeseektime('350')">0:05:50</a> you know about montanus  
<a onclick="modifyYTiframeseektime('355')">0:05:55</a> identified himself with this figure that  
<a onclick="modifyYTiframeseektime('358')">0:05:58</a> was later on identified with muhammad so  
<a onclick="modifyYTiframeseektime('360')">0:06:00</a> even in christian history uh that there  
<a onclick="modifyYTiframeseektime('363')">0:06:03</a> have been people who have been  
<a onclick="modifyYTiframeseektime('364')">0:06:04</a> identified as  
<a onclick="modifyYTiframeseektime('366')">0:06:06</a> his prophet who was to come after jesus  
<a onclick="modifyYTiframeseektime('368')">0:06:08</a> and who wasn't muhammad  
<a onclick="modifyYTiframeseektime('369')">0:06:09</a> so it's not actually just a muslim idea  
<a onclick="modifyYTiframeseektime('371')">0:06:11</a> it's been there in christianity before  
<a onclick="modifyYTiframeseektime('373')">0:06:13</a> so the idea is actually supported by a  
<a onclick="modifyYTiframeseektime('375')">0:06:15</a> lot of western  
<a onclick="modifyYTiframeseektime('376')">0:06:16</a> christian scholarship that there will be  
<a onclick="modifyYTiframeseektime('378')">0:06:18</a> a figure like muhammad who would come  
<a onclick="modifyYTiframeseektime('380')">0:06:20</a> now they wouldn't they didn't say it was  
<a onclick="modifyYTiframeseektime('381')">0:06:21</a> muhammad by the way but the the uh  
<a onclick="modifyYTiframeseektime('383')">0:06:23</a> the uh the job description uh fits  
<a onclick="modifyYTiframeseektime('387')">0:06:27</a> that prophecy was that that spirit will  
<a onclick="modifyYTiframeseektime('389')">0:06:29</a> abide  
<a onclick="modifyYTiframeseektime('390')">0:06:30</a> forever it'd be with the believers  
<a onclick="modifyYTiframeseektime('393')">0:06:33</a> forever  
<a onclick="modifyYTiframeseektime('394')">0:06:34</a> so how would you interpret that in the  
<a onclick="modifyYTiframeseektime('395')">0:06:35</a> life it was mohammed because you know  
<a onclick="modifyYTiframeseektime('397')">0:06:37</a> what was what he must have done  
<a onclick="modifyYTiframeseektime('398')">0:06:38</a> the the the revelation that he bought uh  
<a onclick="modifyYTiframeseektime('401')">0:06:41</a> is the quran is there for uh speaking to  
<a onclick="modifyYTiframeseektime('405')">0:06:45</a> the  
<a onclick="modifyYTiframeseektime('405')">0:06:45</a> he's speaking to the the disciples of  
<a onclick="modifyYTiframeseektime('407')">0:06:47</a> jesus the disciples were waiting for him  
<a onclick="modifyYTiframeseektime('410')">0:06:50</a> after jesus so i don't need to  
<a onclick="modifyYTiframeseektime('412')">0:06:52</a> understand what's being said here it's  
<a onclick="modifyYTiframeseektime('414')">0:06:54</a> not that  
<a onclick="modifyYTiframeseektime('414')">0:06:54</a> baltman and others are saying on the  
<a onclick="modifyYTiframeseektime('416')">0:06:56</a> surface reading of it is referring to  
<a onclick="modifyYTiframeseektime('418')">0:06:58</a> they are saying that but they're saying  
<a onclick="modifyYTiframeseektime('420')">0:07:00</a> that john's gospel  
<a onclick="modifyYTiframeseektime('422')">0:07:02</a> has gone through several editions uh  
<a onclick="modifyYTiframeseektime('425')">0:07:05</a> before it reached the final form we have  
<a onclick="modifyYTiframeseektime('426')">0:07:06</a> it today if you look at john 21  
<a onclick="modifyYTiframeseektime('429')">0:07:09</a> it actually says not the author of the  
<a onclick="modifyYTiframeseektime('431')">0:07:11</a> gospel he says we testify  
<a onclick="modifyYTiframeseektime('433')">0:07:13</a> that he the author of this gospel this  
<a onclick="modifyYTiframeseektime('435')">0:07:15</a> is in john 21 itself  
<a onclick="modifyYTiframeseektime('436')">0:07:16</a> has said these things and he is true or  
<a onclick="modifyYTiframeseektime('438')">0:07:18</a> he's a true witness or something yeah  
<a onclick="modifyYTiframeseektime('440')">0:07:20</a> so even in the gospel itself is talking  
<a onclick="modifyYTiframeseektime('441')">0:07:21</a> about someone else who is the author of  
<a onclick="modifyYTiframeseektime('442')">0:07:22</a> the gospel  
<a onclick="modifyYTiframeseektime('443')">0:07:23</a> so there's two there's two authors of  
<a onclick="modifyYTiframeseektime('445')">0:07:25</a> john  
<a onclick="modifyYTiframeseektime('446')">0:07:26</a> even in the gospel itself but even more  
<a onclick="modifyYTiframeseektime('448')">0:07:28</a> than that raymond brown has  
<a onclick="modifyYTiframeseektime('450')">0:07:30</a> posited that the gospel has been through  
<a onclick="modifyYTiframeseektime('452')">0:07:32</a> five editorial  
<a onclick="modifyYTiframeseektime('454')">0:07:34</a> phases five redactions um given what you  
<a onclick="modifyYTiframeseektime('457')">0:07:37</a> can see  
<a onclick="modifyYTiframeseektime('458')">0:07:38</a> of the you can see the scenes where bits  
<a onclick="modifyYTiframeseektime('460')">0:07:40</a> of the text have been put together  
<a onclick="modifyYTiframeseektime('462')">0:07:42</a> and there's something that scholars have  
<a onclick="modifyYTiframeseektime('463')">0:07:43</a> uncovered so he he suggests there have  
<a onclick="modifyYTiframeseektime('465')">0:07:45</a> been various redactions or various  
<a onclick="modifyYTiframeseektime('466')">0:07:46</a> additions  
<a onclick="modifyYTiframeseektime('467')">0:07:47</a> now what's this got to do with the  
<a onclick="modifyYTiframeseektime('468')">0:07:48</a> paracletos because it looks like in an  
<a onclick="modifyYTiframeseektime('470')">0:07:50</a> earlier edition  
<a onclick="modifyYTiframeseektime('471')">0:07:51</a> of um the gospel what we call the gospel  
<a onclick="modifyYTiframeseektime('474')">0:07:54</a> of john  
<a onclick="modifyYTiframeseektime('476')">0:07:56</a> this siblific figure was an independent  
<a onclick="modifyYTiframeseektime('478')">0:07:58</a> figure with a pacific  
<a onclick="modifyYTiframeseektime('479')">0:07:59</a> characterization as a man because the  
<a onclick="modifyYTiframeseektime('481')">0:08:01</a> pronoun  
<a onclick="modifyYTiframeseektime('482')">0:08:02</a> is used in greek of he and is not  
<a onclick="modifyYTiframeseektime('484')">0:08:04</a> normally used in that way of the holy  
<a onclick="modifyYTiframeseektime('486')">0:08:06</a> spirit  
<a onclick="modifyYTiframeseektime('487')">0:08:07</a> uh is specifically genderized  
<a onclick="modifyYTiframeseektime('491')">0:08:11</a> but here he is referred to as a gendered  
<a onclick="modifyYTiframeseektime('494')">0:08:14</a> entity  
<a onclick="modifyYTiframeseektime('495')">0:08:15</a> a person who comes after jesus so  
<a onclick="modifyYTiframeseektime('498')">0:08:18</a> um if you have this kind of fairly  
<a onclick="modifyYTiframeseektime('500')">0:08:20</a> sophisticated understanding of the  
<a onclick="modifyYTiframeseektime('501')">0:08:21</a> history of the  
<a onclick="modifyYTiframeseektime('502')">0:08:22</a> gospel the way it's rejected and you  
<a onclick="modifyYTiframeseektime('504')">0:08:24</a> look at the unusual features of the  
<a onclick="modifyYTiframeseektime('507')">0:08:27</a> parakletos  
<a onclick="modifyYTiframeseektime('508')">0:08:28</a> it being an actual pronoun gendered  
<a onclick="modifyYTiframeseektime('510')">0:08:30</a> person  
<a onclick="modifyYTiframeseektime('512')">0:08:32</a> then that invites the question maybe  
<a onclick="modifyYTiframeseektime('513')">0:08:33</a> there was someone who has to come after  
<a onclick="modifyYTiframeseektime('515')">0:08:35</a> jesus who was expected  
<a onclick="modifyYTiframeseektime('516')">0:08:36</a> to also preach the truth and this uh  
<a onclick="modifyYTiframeseektime('519')">0:08:39</a> again if you believe having profit of  
<a onclick="modifyYTiframeseektime('521')">0:08:41</a> god  
<a onclick="modifyYTiframeseektime('521')">0:08:41</a> he fits the bill perfectly but in the  
<a onclick="modifyYTiframeseektime('524')">0:08:44</a> early church other people  
<a onclick="modifyYTiframeseektime('525')">0:08:45</a> also thought to have fitted that bill so  
<a onclick="modifyYTiframeseektime('527')">0:08:47</a> it's not just a a wacky muslim idea  
<a onclick="modifyYTiframeseektime('530')">0:08:50</a> christians also had this idea themselves  
<a onclick="modifyYTiframeseektime('531')">0:08:51</a> when they read the gospel in the early  
<a onclick="modifyYTiframeseektime('533')">0:08:53</a> church they thought  
<a onclick="modifyYTiframeseektime('534')">0:08:54</a> it was referring to someone else as well  
<a onclick="modifyYTiframeseektime('537')">0:08:57</a> now you may think they're wrong and  
<a onclick="modifyYTiframeseektime('538')">0:08:58</a> that's fine yeah because  
<a onclick="modifyYTiframeseektime('539')">0:08:59</a> it says that that holy spirit who you're  
<a onclick="modifyYTiframeseektime('542')">0:09:02</a> talking about  
<a onclick="modifyYTiframeseektime('543')">0:09:03</a> he said he lives in you and he will be  
<a onclick="modifyYTiframeseektime('545')">0:09:05</a> with you and be with you and he'll be in  
<a onclick="modifyYTiframeseektime('548')">0:09:08</a> i get what you're saying and there is an  
<a onclick="modifyYTiframeseektime('549')">0:09:09</a> answer to that but you need to read the  
<a onclick="modifyYTiframeseektime('550')">0:09:10</a> uh  
<a onclick="modifyYTiframeseektime('551')">0:09:11</a> the academic work of these top biblical  
<a onclick="modifyYTiframeseektime('553')">0:09:13</a> scholars  
<a onclick="modifyYTiframeseektime('554')">0:09:14</a> uh to understand why they're saying this  
<a onclick="modifyYTiframeseektime('556')">0:09:16</a> yeah um but they are saying this and  
<a onclick="modifyYTiframeseektime('558')">0:09:18</a> there are a lot of them who are saying  
<a onclick="modifyYTiframeseektime('560')">0:09:20</a> this  
<a onclick="modifyYTiframeseektime('560')">0:09:20</a> and it has nothing to do with islam for  
<a onclick="modifyYTiframeseektime('561')">0:09:21</a> them this is just someone was to come a  
<a onclick="modifyYTiframeseektime('563')">0:09:23</a> human being a man was to come after  
<a onclick="modifyYTiframeseektime('565')">0:09:25</a> jesus  
<a onclick="modifyYTiframeseektime('566')">0:09:26</a> who would be a prophet  

</details>
