# The First Council of Constantinople - and why Jesus would have wept. (2020-12-11)

<iframe loading='lazy' src='https://www.youtube.com/embed/Uei51koTiQU'></iframe>

## Description

The First Council of Constantinople was a council of Christian bishops convened in Constantinople in AD 381 by the Roman Emperor Theodosius I. This second ecumenical council confirmed the Nicene Creed, expanding its teaching to produce the Niceno-Constantinopolitan Creed, and defined the Holy Spirit (along with Jesus) as a deity worthy of worship. 

I explain why Jesus - had he observed the proceedings of the council - would have wept.

## Summary of [The First Council of Constantinople - and why Jesus would have wept.](https://www.youtube.com/watch?v=Uei51koTiQU)


*<span style="color:red; font-size:125%">This summary is AI generated - there may be inaccuracies</span>. [](/)*

### <a onclick="modifyYTiframeseektime('0')">00:00:00</a> - <a onclick="modifyYTiframeseektime('600')">00:10:00</a>

The First Council of Constantinople was held in 381 AD in order to condemn the heresy of Apollinarianism. The Council expanded on the Nicene Creed, affirming that Jesus is fully God and that the Holy Spirit is also God. This doctrine was later expanded upon in the Nicene Creed. The video describes the development of the doctrine of the Trinity, which goes from monotheism to tritheism. Christianity began as a monotheistic religion, but over time it became polytheistic, with three gods worshiped alongside the Father. This was a significant change from Jesus' teachings, which centered around one God.

**<a onclick="modifyYTiframeseektime('0')">00:00:00</a>** The Council of Constantinople (381 AD), which condemned Apollinarianism, expanded on the Nicene Creed. It is the creed of orthodoxy, used by all major churches in the East and West.
* **<a onclick="modifyYTiframeseektime('300')">00:05:00</a>** The First Council of Constantinople affirmed that Jesus is fully God, and that the Holy Spirit is also God. This doctrine is later expanded upon in the Nicene Creed.
* **<a onclick="modifyYTiframeseektime('600')">00:10:00</a>** The video describes the development of the doctrine of the Trinity, which goes from monotheism to tritheism. Christianity began as a monotheistic religion, but over time it became polytheistic, with three gods worshiped alongside the Father. This was a significant change from Jesus' teachings, which centered around one God.

<details><summary><h2>Full transcript with timestamps: CLICK TO EXPAND</h2></summary>

<a onclick="modifyYTiframeseektime('1')">0:00:01</a> well in this uh second  
<a onclick="modifyYTiframeseektime('3')">0:00:03</a> video in the series of seven about the  
<a onclick="modifyYTiframeseektime('5')">0:00:05</a> seven  
<a onclick="modifyYTiframeseektime('6')">0:00:06</a> uh ecumenical councils the church that  
<a onclick="modifyYTiframeseektime('9')">0:00:09</a> is universal councils  
<a onclick="modifyYTiframeseektime('11')">0:00:11</a> that were called um gatherings of  
<a onclick="modifyYTiframeseektime('13')">0:00:13</a> bishops usually under an emperor  
<a onclick="modifyYTiframeseektime('15')">0:00:15</a> to thrash out christian doctrine to  
<a onclick="modifyYTiframeseektime('17')">0:00:17</a> denounce heretics  
<a onclick="modifyYTiframeseektime('18')">0:00:18</a> i want to talk about the council of  
<a onclick="modifyYTiframeseektime('22')">0:00:22</a> constantinople which was called by the  
<a onclick="modifyYTiframeseektime('24')">0:00:24</a> emperor  
<a onclick="modifyYTiframeseektime('25')">0:00:25</a> theodosius in 381 a.d  
<a onclick="modifyYTiframeseektime('29')">0:00:29</a> but before i get into that i just want  
<a onclick="modifyYTiframeseektime('30')">0:00:30</a> to go back to the  
<a onclick="modifyYTiframeseektime('33')">0:00:33</a> nicene creed to the council of nicaea  
<a onclick="modifyYTiframeseektime('36')">0:00:36</a> called by the emperor constantine who  
<a onclick="modifyYTiframeseektime('38')">0:00:38</a> was the first  
<a onclick="modifyYTiframeseektime('39')">0:00:39</a> christian emperor of the roman empire  
<a onclick="modifyYTiframeseektime('42')">0:00:42</a> and  
<a onclick="modifyYTiframeseektime('43')">0:00:43</a> when he passed away and his son  
<a onclick="modifyYTiframeseektime('46')">0:00:46</a> constantine  
<a onclick="modifyYTiframeseektime('47')">0:00:47</a> uh the second uh took over and his son  
<a onclick="modifyYTiframeseektime('50')">0:00:50</a> after him  
<a onclick="modifyYTiframeseektime('51')">0:00:51</a> and they were aryan emperors in other  
<a onclick="modifyYTiframeseektime('54')">0:00:54</a> words they rejected their fathers or  
<a onclick="modifyYTiframeseektime('56')">0:00:56</a> grandfather's views about  
<a onclick="modifyYTiframeseektime('58')">0:00:58</a> uh jesus being as  
<a onclick="modifyYTiframeseektime('61')">0:01:01</a> god as divine as the father being equal  
<a onclick="modifyYTiframeseektime('65')">0:01:05</a> in deity both being of the same  
<a onclick="modifyYTiframeseektime('68')">0:01:08</a> substance of the same being  
<a onclick="modifyYTiframeseektime('69')">0:01:09</a> as each other of one being and uh  
<a onclick="modifyYTiframeseektime('73')">0:01:13</a> the the aryans rejected this uh  
<a onclick="modifyYTiframeseektime('75')">0:01:15</a> believing that  
<a onclick="modifyYTiframeseektime('76')">0:01:16</a> christ had a beginning he was created by  
<a onclick="modifyYTiframeseektime('79')">0:01:19</a> the father  
<a onclick="modifyYTiframeseektime('80')">0:01:20</a> so even though you could use divine  
<a onclick="modifyYTiframeseektime('81')">0:01:21</a> language of him uh you could call him  
<a onclick="modifyYTiframeseektime('84')">0:01:24</a> divine  
<a onclick="modifyYTiframeseektime('85')">0:01:25</a> he was not god in the ultimate sense so  
<a onclick="modifyYTiframeseektime('88')">0:01:28</a> the people who succeeded constantine his  
<a onclick="modifyYTiframeseektime('90')">0:01:30</a> son  
<a onclick="modifyYTiframeseektime('90')">0:01:30</a> uh and and his son uh were aryans  
<a onclick="modifyYTiframeseektime('94')">0:01:34</a> and also other um so-called heresies  
<a onclick="modifyYTiframeseektime('98')">0:01:38</a> came about i call them so-called because  
<a onclick="modifyYTiframeseektime('100')">0:01:40</a> obviously this is from the point of view  
<a onclick="modifyYTiframeseektime('101')">0:01:41</a> of the  
<a onclick="modifyYTiframeseektime('102')">0:01:42</a> of what became the traditional orthodox  
<a onclick="modifyYTiframeseektime('104')">0:01:44</a> catholic church  
<a onclick="modifyYTiframeseektime('105')">0:01:45</a> uh you may think the so-called heresies  
<a onclick="modifyYTiframeseektime('108')">0:01:48</a> were actually true  
<a onclick="modifyYTiframeseektime('109')">0:01:49</a> uh uh and accurate in in what in their  
<a onclick="modifyYTiframeseektime('111')">0:01:51</a> views  
<a onclick="modifyYTiframeseektime('112')">0:01:52</a> uh one of the views um was um  
<a onclick="modifyYTiframeseektime('115')">0:01:55</a> popularly uh is popularly known as  
<a onclick="modifyYTiframeseektime('117')">0:01:57</a> apollinarianism  
<a onclick="modifyYTiframeseektime('118')">0:01:58</a> and this came about by a chap called  
<a onclick="modifyYTiframeseektime('120')">0:02:00</a> apollinarius  
<a onclick="modifyYTiframeseektime('122')">0:02:02</a> um and he was a supporter of the council  
<a onclick="modifyYTiframeseektime('124')">0:02:04</a> of nicaea the nicene creed  
<a onclick="modifyYTiframeseektime('126')">0:02:06</a> but he kind of pushed it a bit too far  
<a onclick="modifyYTiframeseektime('128')">0:02:08</a> and he ended up saying  
<a onclick="modifyYTiframeseektime('130')">0:02:10</a> perhaps in spite of himself he didn't  
<a onclick="modifyYTiframeseektime('132')">0:02:12</a> want to be a heretic  
<a onclick="modifyYTiframeseektime('134')">0:02:14</a> uh because he was condemned uh he ended  
<a onclick="modifyYTiframeseektime('136')">0:02:16</a> up saying that yeah jesus had a human  
<a onclick="modifyYTiframeseektime('138')">0:02:18</a> body but his mind his soul was divine  
<a onclick="modifyYTiframeseektime('141')">0:02:21</a> so it's kind of like you know god  
<a onclick="modifyYTiframeseektime('142')">0:02:22</a> dressed in a suit of  
<a onclick="modifyYTiframeseektime('144')">0:02:24</a> human flesh if you like he wasn't fully  
<a onclick="modifyYTiframeseektime('146')">0:02:26</a> human jesus  
<a onclick="modifyYTiframeseektime('148')">0:02:28</a> and he uh he was just his uh body that  
<a onclick="modifyYTiframeseektime('150')">0:02:30</a> was obviously human  
<a onclick="modifyYTiframeseektime('152')">0:02:32</a> but his soul his mind was completely  
<a onclick="modifyYTiframeseektime('155')">0:02:35</a> divine and this was um an understanding  
<a onclick="modifyYTiframeseektime('158')">0:02:38</a> of the incarnation that was subsequently  
<a onclick="modifyYTiframeseektime('160')">0:02:40</a> condemned  
<a onclick="modifyYTiframeseektime('161')">0:02:41</a> at the council of constantinople  
<a onclick="modifyYTiframeseektime('166')">0:02:46</a> now the other really important thing  
<a onclick="modifyYTiframeseektime('168')">0:02:48</a> about the council  
<a onclick="modifyYTiframeseektime('169')">0:02:49</a> um is to do with the holy spirit which  
<a onclick="modifyYTiframeseektime('172')">0:02:52</a> had not been mentioned before  
<a onclick="modifyYTiframeseektime('173')">0:02:53</a> very much at all at the council of  
<a onclick="modifyYTiframeseektime('175')">0:02:55</a> nicaea at the council of nicaea if  
<a onclick="modifyYTiframeseektime('177')">0:02:57</a> you've not  
<a onclick="modifyYTiframeseektime('178')">0:02:58</a> come across it before um it mentions  
<a onclick="modifyYTiframeseektime('181')">0:03:01</a> very briefly the holy spirit it says  
<a onclick="modifyYTiframeseektime('183')">0:03:03</a> you know we believe in one god the  
<a onclick="modifyYTiframeseektime('185')">0:03:05</a> father almighty the maker  
<a onclick="modifyYTiframeseektime('187')">0:03:07</a> of all things we believe in jesus and it  
<a onclick="modifyYTiframeseektime('188')">0:03:08</a> talks about how jesus one being  
<a onclick="modifyYTiframeseektime('191')">0:03:11</a> um homo eusion or consubstantial with  
<a onclick="modifyYTiframeseektime('194')">0:03:14</a> god the father  
<a onclick="modifyYTiframeseektime('195')">0:03:15</a> um how jesus died and rose again and  
<a onclick="modifyYTiframeseektime('198')">0:03:18</a> then it says  
<a onclick="modifyYTiframeseektime('199')">0:03:19</a> we believe in the holy spirit full stop  
<a onclick="modifyYTiframeseektime('202')">0:03:22</a> and that's it  
<a onclick="modifyYTiframeseektime('203')">0:03:23</a> and that is all that nice here says  
<a onclick="modifyYTiframeseektime('205')">0:03:25</a> about the holy spirit so who is the holy  
<a onclick="modifyYTiframeseektime('207')">0:03:27</a> spirit  
<a onclick="modifyYTiframeseektime('208')">0:03:28</a> what's his relationship between uh to  
<a onclick="modifyYTiframeseektime('210')">0:03:30</a> the father and to the son  
<a onclick="modifyYTiframeseektime('212')">0:03:32</a> doesn't really go into that so the  
<a onclick="modifyYTiframeseektime('214')">0:03:34</a> another thing that the council  
<a onclick="modifyYTiframeseektime('215')">0:03:35</a> did was to really expand on this and  
<a onclick="modifyYTiframeseektime('220')">0:03:40</a> revise the nicene creed  
<a onclick="modifyYTiframeseektime('223')">0:03:43</a> in such a way in fact the nicene creed  
<a onclick="modifyYTiframeseektime('226')">0:03:46</a> as it's called today  
<a onclick="modifyYTiframeseektime('227')">0:03:47</a> is really the nicene constantinople  
<a onclick="modifyYTiframeseektime('230')">0:03:50</a> creed  
<a onclick="modifyYTiframeseektime('231')">0:03:51</a> that's actually the creed that's read in  
<a onclick="modifyYTiframeseektime('234')">0:03:54</a> all the major  
<a onclick="modifyYTiframeseektime('235')">0:03:55</a> churches of the east to the orthodox  
<a onclick="modifyYTiframeseektime('237')">0:03:57</a> churches and the west in  
<a onclick="modifyYTiframeseektime('239')">0:03:59</a> the catholic churches the anglican  
<a onclick="modifyYTiframeseektime('240')">0:04:00</a> church and so on is the revised nicene  
<a onclick="modifyYTiframeseektime('243')">0:04:03</a> creed that's really  
<a onclick="modifyYTiframeseektime('244')">0:04:04</a> the orthodox touchstone uh of  
<a onclick="modifyYTiframeseektime('247')">0:04:07</a> of orthodoxy and truth um  
<a onclick="modifyYTiframeseektime('251')">0:04:11</a> for christians um and why was the ho why  
<a onclick="modifyYTiframeseektime('254')">0:04:14</a> did this become an issue because  
<a onclick="modifyYTiframeseektime('256')">0:04:16</a> prominent churchmen were saying look the  
<a onclick="modifyYTiframeseektime('259')">0:04:19</a> holy spirit  
<a onclick="modifyYTiframeseektime('260')">0:04:20</a> isn't god he's not fully god only the  
<a onclick="modifyYTiframeseektime('263')">0:04:23</a> father is fully god  
<a onclick="modifyYTiframeseektime('264')">0:04:24</a> and as we saw in the first video the  
<a onclick="modifyYTiframeseektime('267')">0:04:27</a> verses in the bible  
<a onclick="modifyYTiframeseektime('268')">0:04:28</a> that say that where jesus says in in  
<a onclick="modifyYTiframeseektime('271')">0:04:31</a> john's gospel  
<a onclick="modifyYTiframeseektime('273')">0:04:33</a> um that he prays and he prays that  
<a onclick="modifyYTiframeseektime('276')">0:04:36</a> this is eternal life that they may know  
<a onclick="modifyYTiframeseektime('278')">0:04:38</a> you the only true god  
<a onclick="modifyYTiframeseektime('281')">0:04:41</a> and jesus christ whom you have sent  
<a onclick="modifyYTiframeseektime('284')">0:04:44</a> so jesus himself refers to the father  
<a onclick="modifyYTiframeseektime('287')">0:04:47</a> as the only true god he's not including  
<a onclick="modifyYTiframeseektime('291')">0:04:51</a> himself  
<a onclick="modifyYTiframeseektime('292')">0:04:52</a> in the godhead as divine at all  
<a onclick="modifyYTiframeseektime('295')">0:04:55</a> and there are other verses all over the  
<a onclick="modifyYTiframeseektime('297')">0:04:57</a> place in the bible where  
<a onclick="modifyYTiframeseektime('298')">0:04:58</a> jesus is clearly distinguished from god  
<a onclick="modifyYTiframeseektime('300')">0:05:00</a> you know jesus prays to god  
<a onclick="modifyYTiframeseektime('302')">0:05:02</a> he feels abandoned by god on the cross  
<a onclick="modifyYTiframeseektime('304')">0:05:04</a> my god my god why have you abandoned me  
<a onclick="modifyYTiframeseektime('306')">0:05:06</a> i mean it says that in mark's gospel of  
<a onclick="modifyYTiframeseektime('308')">0:05:08</a> matthew's gospel um he doesn't know  
<a onclick="modifyYTiframeseektime('310')">0:05:10</a> things  
<a onclick="modifyYTiframeseektime('311')">0:05:11</a> though he's not omniscient and and so on  
<a onclick="modifyYTiframeseektime('314')">0:05:14</a> so clearly he's not exhibiting  
<a onclick="modifyYTiframeseektime('316')">0:05:16</a> any of these uh divine characteristics  
<a onclick="modifyYTiframeseektime('318')">0:05:18</a> that we would normally expect of god  
<a onclick="modifyYTiframeseektime('321')">0:05:21</a> um so um  
<a onclick="modifyYTiframeseektime('325')">0:05:25</a> some people were denying some church  
<a onclick="modifyYTiframeseektime('327')">0:05:27</a> women denying the holy spirit was god  
<a onclick="modifyYTiframeseektime('328')">0:05:28</a> why because only if the father is god  
<a onclick="modifyYTiframeseektime('331')">0:05:31</a> if you start having other people other  
<a onclick="modifyYTiframeseektime('332')">0:05:32</a> forces other entities that are also god  
<a onclick="modifyYTiframeseektime('335')">0:05:35</a> so you've got jesus also god the holy  
<a onclick="modifyYTiframeseektime('337')">0:05:37</a> spirit is also god  
<a onclick="modifyYTiframeseektime('338')">0:05:38</a> how many gods are there um so  
<a onclick="modifyYTiframeseektime('342')">0:05:42</a> these people were after nicaea were  
<a onclick="modifyYTiframeseektime('345')">0:05:45</a> quite  
<a onclick="modifyYTiframeseektime('345')">0:05:45</a> emphatic about that now this was  
<a onclick="modifyYTiframeseektime('348')">0:05:48</a> condemned by  
<a onclick="modifyYTiframeseektime('349')">0:05:49</a> for example the pope pope damascus the  
<a onclick="modifyYTiframeseektime('351')">0:05:51</a> first at that time he said no no  
<a onclick="modifyYTiframeseektime('353')">0:05:53</a> no the holy spirit is fully god he's a  
<a onclick="modifyYTiframeseektime('355')">0:05:55</a> person  
<a onclick="modifyYTiframeseektime('356')">0:05:56</a> alongside god the father who's also a  
<a onclick="modifyYTiframeseektime('358')">0:05:58</a> person alongside jesus was also a person  
<a onclick="modifyYTiframeseektime('360')">0:06:00</a> um and theodosius the roman empire up  
<a onclick="modifyYTiframeseektime('363')">0:06:03</a> roman emperor  
<a onclick="modifyYTiframeseektime('364')">0:06:04</a> called this council the first council of  
<a onclick="modifyYTiframeseektime('366')">0:06:06</a> constantinople  
<a onclick="modifyYTiframeseektime('368')">0:06:08</a> in 381 to settle a whole bunch of these  
<a onclick="modifyYTiframeseektime('370')">0:06:10</a> issues and to reinforce to restate  
<a onclick="modifyYTiframeseektime('373')">0:06:13</a> that the truth was the council of nicaea  
<a onclick="modifyYTiframeseektime('376')">0:06:16</a> he revised it to add bits in  
<a onclick="modifyYTiframeseektime('378')">0:06:18</a> to condemn these people who were saying  
<a onclick="modifyYTiframeseektime('381')">0:06:21</a> the holy spirit  
<a onclick="modifyYTiframeseektime('382')">0:06:22</a> also wasn't god um and so he expanded it  
<a onclick="modifyYTiframeseektime('386')">0:06:26</a> and revised it  
<a onclick="modifyYTiframeseektime('387')">0:06:27</a> there were some cannons as they're  
<a onclick="modifyYTiframeseektime('389')">0:06:29</a> called that these are doctrinal  
<a onclick="modifyYTiframeseektime('391')">0:06:31</a> statements from the council that um  
<a onclick="modifyYTiframeseektime('395')">0:06:35</a> they're called cannons they are  
<a onclick="modifyYTiframeseektime('398')">0:06:38</a> doctrinal decrees  
<a onclick="modifyYTiframeseektime('400')">0:06:40</a> stating uh in this case uh that the  
<a onclick="modifyYTiframeseektime('403')">0:06:43</a> heresies were  
<a onclick="modifyYTiframeseektime('404')">0:06:44</a> outlawed so the aryans who said that  
<a onclick="modifyYTiframeseektime('408')">0:06:48</a> jesus was a created being  
<a onclick="modifyYTiframeseektime('409')">0:06:49</a> these were outlawed uh by the state  
<a onclick="modifyYTiframeseektime('413')">0:06:53</a> by this decree um the  
<a onclick="modifyYTiframeseektime('416')">0:06:56</a> the other canon of firm nicaea as the  
<a onclick="modifyYTiframeseektime('419')">0:06:59</a> truth and also the bishop of  
<a onclick="modifyYTiframeseektime('420')">0:07:00</a> constantinople  
<a onclick="modifyYTiframeseektime('422')">0:07:02</a> who was until then subordinate to the  
<a onclick="modifyYTiframeseektime('424')">0:07:04</a> pope  
<a onclick="modifyYTiframeseektime('425')">0:07:05</a> it was decided to raise his status to  
<a onclick="modifyYTiframeseektime('427')">0:07:07</a> equal to the pope  
<a onclick="modifyYTiframeseektime('429')">0:07:09</a> um so these were come  
<a onclick="modifyYTiframeseektime('432')">0:07:12</a> some of the issues but principally it  
<a onclick="modifyYTiframeseektime('434')">0:07:14</a> was to reassert  
<a onclick="modifyYTiframeseektime('436')">0:07:16</a> the truth of nicaea  
<a onclick="modifyYTiframeseektime('439')">0:07:19</a> even though theodosi is his predecessors  
<a onclick="modifyYTiframeseektime('444')">0:07:24</a> constantine won constantine too and many  
<a onclick="modifyYTiframeseektime('446')">0:07:26</a> bishops  
<a onclick="modifyYTiframeseektime('447')">0:07:27</a> had decided actually jesus was not god  
<a onclick="modifyYTiframeseektime('449')">0:07:29</a> and that he was created  
<a onclick="modifyYTiframeseektime('451')">0:07:31</a> so you had this thing you know in the  
<a onclick="modifyYTiframeseektime('454')">0:07:34</a> council of nicaea you had by majority  
<a onclick="modifyYTiframeseektime('456')">0:07:36</a> vote deciding that jesus was fully god  
<a onclick="modifyYTiframeseektime('459')">0:07:39</a> and then after that constantine dies and  
<a onclick="modifyYTiframeseektime('461')">0:07:41</a> you get kind of differing views coming  
<a onclick="modifyYTiframeseektime('463')">0:07:43</a> back saying well actually no he's not  
<a onclick="modifyYTiframeseektime('464')">0:07:44</a> really god because let me look at these  
<a onclick="modifyYTiframeseektime('465')">0:07:45</a> passages in scripture jesus says  
<a onclick="modifyYTiframeseektime('467')">0:07:47</a> the father is greater than i you know he  
<a onclick="modifyYTiframeseektime('469')">0:07:49</a> prays to god he's how can he be god  
<a onclick="modifyYTiframeseektime('471')">0:07:51</a> that there are so many pastors in the  
<a onclick="modifyYTiframeseektime('472')">0:07:52</a> bible that do not sit uh comfortably at  
<a onclick="modifyYTiframeseektime('475')">0:07:55</a> all with this idea  
<a onclick="modifyYTiframeseektime('476')">0:07:56</a> so many people were persuaded by that  
<a onclick="modifyYTiframeseektime('478')">0:07:58</a> and then theodosius comes along and he's  
<a onclick="modifyYTiframeseektime('480')">0:08:00</a> very violent actually  
<a onclick="modifyYTiframeseektime('481')">0:08:01</a> i mean his father was executed and he he  
<a onclick="modifyYTiframeseektime('484')">0:08:04</a> was very a very violent man himself  
<a onclick="modifyYTiframeseektime('486')">0:08:06</a> and he enforced this on the roman empire  
<a onclick="modifyYTiframeseektime('488')">0:08:08</a> and it became an offense  
<a onclick="modifyYTiframeseektime('490')">0:08:10</a> against the state to uh to be a heretic  
<a onclick="modifyYTiframeseektime('493')">0:08:13</a> to to disagree with what his views were  
<a onclick="modifyYTiframeseektime('497')">0:08:17</a> so um and you see here the beginnings of  
<a onclick="modifyYTiframeseektime('499')">0:08:19</a> the medieval period don't you where  
<a onclick="modifyYTiframeseektime('500')">0:08:20</a> the church really uh has a massive  
<a onclick="modifyYTiframeseektime('503')">0:08:23</a> social role  
<a onclick="modifyYTiframeseektime('504')">0:08:24</a> in enforcing uh its views on the people  
<a onclick="modifyYTiframeseektime('507')">0:08:27</a> and lower behind if you  
<a onclick="modifyYTiframeseektime('508')">0:08:28</a> disagree you will be uh you could be uh  
<a onclick="modifyYTiframeseektime('511')">0:08:31</a> punished uh even executed if you  
<a onclick="modifyYTiframeseektime('513')">0:08:33</a> publicly deny the trinity  
<a onclick="modifyYTiframeseektime('516')">0:08:36</a> so uh these are some of the issues uh  
<a onclick="modifyYTiframeseektime('519')">0:08:39</a> that  
<a onclick="modifyYTiframeseektime('519')">0:08:39</a> came about the holy spirit now uh let me  
<a onclick="modifyYTiframeseektime('523')">0:08:43</a> just get this  
<a onclick="modifyYTiframeseektime('524')">0:08:44</a> so in the first council of  
<a onclick="modifyYTiframeseektime('526')">0:08:46</a> constantinople in 381  
<a onclick="modifyYTiframeseektime('530')">0:08:50</a> whereas at nicaea you had the mention of  
<a onclick="modifyYTiframeseektime('532')">0:08:52</a> the holy spirit  
<a onclick="modifyYTiframeseektime('533')">0:08:53</a> nothing more in the constantinople creed  
<a onclick="modifyYTiframeseektime('536')">0:08:56</a> you have this  
<a onclick="modifyYTiframeseektime('537')">0:08:57</a> that we believe in one holy catholic and  
<a onclick="modifyYTiframeseektime('539')">0:08:59</a> apostolic church  
<a onclick="modifyYTiframeseektime('541')">0:09:01</a> we acknowledge one baptism for the  
<a onclick="modifyYTiframeseektime('543')">0:09:03</a> forgiveness of sins  
<a onclick="modifyYTiframeseektime('544')">0:09:04</a> we look for the resurrection of the dead  
<a onclick="modifyYTiframeseektime('546')">0:09:06</a> and the life of the world to come  
<a onclick="modifyYTiframeseektime('548')">0:09:08</a> and we believe in the holy spirit the  
<a onclick="modifyYTiframeseektime('550')">0:09:10</a> lord  
<a onclick="modifyYTiframeseektime('551')">0:09:11</a> and giver of life who proceeds from the  
<a onclick="modifyYTiframeseektime('554')">0:09:14</a> father  
<a onclick="modifyYTiframeseektime('554')">0:09:14</a> with the father and the son together is  
<a onclick="modifyYTiframeseektime('557')">0:09:17</a> worshiped and glorified  
<a onclick="modifyYTiframeseektime('559')">0:09:19</a> who spoke by the prophets now everything  
<a onclick="modifyYTiframeseektime('562')">0:09:22</a> i've just read there  
<a onclick="modifyYTiframeseektime('563')">0:09:23</a> has been added in to the nicene creed so  
<a onclick="modifyYTiframeseektime('566')">0:09:26</a> the idea for example we acknowledge one  
<a onclick="modifyYTiframeseektime('569')">0:09:29</a> baptism for the remission of sins the  
<a onclick="modifyYTiframeseektime('570')">0:09:30</a> idea that baptism as it as  
<a onclick="modifyYTiframeseektime('572')">0:09:32</a> such forgives your sins  
<a onclick="modifyYTiframeseektime('577')">0:09:37</a> is added in is that extraordinary did  
<a onclick="modifyYTiframeseektime('579')">0:09:39</a> jesus  
<a onclick="modifyYTiframeseektime('580')">0:09:40</a> preach did he go around saying you know  
<a onclick="modifyYTiframeseektime('582')">0:09:42</a> have have some baptism and you will be  
<a onclick="modifyYTiframeseektime('584')">0:09:44</a> saved  
<a onclick="modifyYTiframeseektime('584')">0:09:44</a> so baptism itself uh remits  
<a onclick="modifyYTiframeseektime('587')">0:09:47</a> sin um the what the idea the one holy  
<a onclick="modifyYTiframeseektime('591')">0:09:51</a> catholic apostolic church that's the  
<a onclick="modifyYTiframeseektime('593')">0:09:53</a> first time that's in the creed  
<a onclick="modifyYTiframeseektime('595')">0:09:55</a> and then to the holy spirit the holy  
<a onclick="modifyYTiframeseektime('597')">0:09:57</a> spirit is now the lord  
<a onclick="modifyYTiframeseektime('598')">0:09:58</a> the giver of life who proceeds from the  
<a onclick="modifyYTiframeseektime('600')">0:10:00</a> father  
<a onclick="modifyYTiframeseektime('601')">0:10:01</a> with the father and the son is worshiped  
<a onclick="modifyYTiframeseektime('603')">0:10:03</a> and glorified  
<a onclick="modifyYTiframeseektime('605')">0:10:05</a> so you have three beings now  
<a onclick="modifyYTiframeseektime('608')">0:10:08</a> who are worshiped you have the father  
<a onclick="modifyYTiframeseektime('610')">0:10:10</a> who has got his worship the son who is  
<a onclick="modifyYTiframeseektime('612')">0:10:12</a> god who's worshipped  
<a onclick="modifyYTiframeseektime('613')">0:10:13</a> and clearly the holy spirit who is also  
<a onclick="modifyYTiframeseektime('617')">0:10:17</a> worshiped so each is fully god  
<a onclick="modifyYTiframeseektime('620')">0:10:20</a> and my mass isn't great but i make that  
<a onclick="modifyYTiframeseektime('623')">0:10:23</a> three  
<a onclick="modifyYTiframeseektime('624')">0:10:24</a> beings who are fully god all of whom  
<a onclick="modifyYTiframeseektime('627')">0:10:27</a> are together it says are to be  
<a onclick="modifyYTiframeseektime('629')">0:10:29</a> worshipped and  
<a onclick="modifyYTiframeseektime('630')">0:10:30</a> all of them are to be worshipped and  
<a onclick="modifyYTiframeseektime('632')">0:10:32</a> glorified  
<a onclick="modifyYTiframeseektime('634')">0:10:34</a> wow now that wasn't in nicaea uh he was  
<a onclick="modifyYTiframeseektime('636')">0:10:36</a> added to the nicen creed  
<a onclick="modifyYTiframeseektime('638')">0:10:38</a> and so as i said before today when  
<a onclick="modifyYTiframeseektime('640')">0:10:40</a> christians uh  
<a onclick="modifyYTiframeseektime('641')">0:10:41</a> recite which they do the nice and creed  
<a onclick="modifyYTiframeseektime('644')">0:10:44</a> they mean this revised creed which  
<a onclick="modifyYTiframeseektime('646')">0:10:46</a> includes the bit about how baptism saves  
<a onclick="modifyYTiframeseektime('648')">0:10:48</a> you  
<a onclick="modifyYTiframeseektime('649')">0:10:49</a> and a bit about the three entities that  
<a onclick="modifyYTiframeseektime('651')">0:10:51</a> are now worshipped  
<a onclick="modifyYTiframeseektime('652')">0:10:52</a> together the word together is in the  
<a onclick="modifyYTiframeseektime('655')">0:10:55</a> creed  
<a onclick="modifyYTiframeseektime('655')">0:10:55</a> so you get a collective is a group of  
<a onclick="modifyYTiframeseektime('658')">0:10:58</a> group of beings group of individuals  
<a onclick="modifyYTiframeseektime('660')">0:11:00</a> who are all worshiped together  
<a onclick="modifyYTiframeseektime('664')">0:11:04</a> as god of course so although the word  
<a onclick="modifyYTiframeseektime('667')">0:11:07</a> trinity is not mentioned clearly this is  
<a onclick="modifyYTiframeseektime('669')">0:11:09</a> trinitarian trinity  
<a onclick="modifyYTiframeseektime('670')">0:11:10</a> the doctrine of the trinity as such will  
<a onclick="modifyYTiframeseektime('672')">0:11:12</a> be addressed in a later council  
<a onclick="modifyYTiframeseektime('674')">0:11:14</a> which god willing i'll make a video on  
<a onclick="modifyYTiframeseektime('677')">0:11:17</a> but you can see  
<a onclick="modifyYTiframeseektime('678')">0:11:18</a> how uh the development i mean how far we  
<a onclick="modifyYTiframeseektime('681')">0:11:21</a> have moved from  
<a onclick="modifyYTiframeseektime('682')">0:11:22</a> jesus in in uh in galilee  
<a onclick="modifyYTiframeseektime('685')">0:11:25</a> preaching god and his kingdom  
<a onclick="modifyYTiframeseektime('688')">0:11:28</a> and now we have three entities who are  
<a onclick="modifyYTiframeseektime('691')">0:11:31</a> now proclaimed and worshipped  
<a onclick="modifyYTiframeseektime('693')">0:11:33</a> as god is this trini is this tritheism  
<a onclick="modifyYTiframeseektime('697')">0:11:37</a> um i think i think it is actually  
<a onclick="modifyYTiframeseektime('701')">0:11:41</a> many people say it's not because  
<a onclick="modifyYTiframeseektime('702')">0:11:42</a> christians still profess belief in one  
<a onclick="modifyYTiframeseektime('704')">0:11:44</a> god  
<a onclick="modifyYTiframeseektime('705')">0:11:45</a> but it the the the this is stretched to  
<a onclick="modifyYTiframeseektime('708')">0:11:48</a> such an extent  
<a onclick="modifyYTiframeseektime('709')">0:11:49</a> that it breaks i think that if if each  
<a onclick="modifyYTiframeseektime('712')">0:11:52</a> of the constituent  
<a onclick="modifyYTiframeseektime('714')">0:11:54</a> deities each of which is named and  
<a onclick="modifyYTiframeseektime('717')">0:11:57</a> worshiped and glorified individually  
<a onclick="modifyYTiframeseektime('720')">0:12:00</a> uh this stretches the definition and  
<a onclick="modifyYTiframeseektime('722')">0:12:02</a> it's kind of like a polytheistic  
<a onclick="modifyYTiframeseektime('724')">0:12:04</a> monotheism as a a paradox of course  
<a onclick="modifyYTiframeseektime('727')">0:12:07</a> or monotheistic polytheism it's a  
<a onclick="modifyYTiframeseektime('729')">0:12:09</a> politic it's a monotheism that is  
<a onclick="modifyYTiframeseektime('731')">0:12:11</a> polytheistic it's kind of a  
<a onclick="modifyYTiframeseektime('732')">0:12:12</a> contradiction  
<a onclick="modifyYTiframeseektime('733')">0:12:13</a> it both affirms and denies what it  
<a onclick="modifyYTiframeseektime('735')">0:12:15</a> claims to believe  
<a onclick="modifyYTiframeseektime('736')">0:12:16</a> um so um so  
<a onclick="modifyYTiframeseektime('740')">0:12:20</a> as i say that council uh uh issued this  
<a onclick="modifyYTiframeseektime('743')">0:12:23</a> creed  
<a onclick="modifyYTiframeseektime('744')">0:12:24</a> and it was enforced with state power  
<a onclick="modifyYTiframeseektime('748')">0:12:28</a> if you disagreed with this if you're an  
<a onclick="modifyYTiframeseektime('750')">0:12:30</a> aryan if you said jesus  
<a onclick="modifyYTiframeseektime('751')">0:12:31</a> is not god you were punished it also  
<a onclick="modifyYTiframeseektime('754')">0:12:34</a> outlawed  
<a onclick="modifyYTiframeseektime('755')">0:12:35</a> uh by the by all pagan practices the  
<a onclick="modifyYTiframeseektime('758')">0:12:38</a> temples were closed they were more than  
<a onclick="modifyYTiframeseektime('760')">0:12:40</a> closed they were ransacked burnt down  
<a onclick="modifyYTiframeseektime('762')">0:12:42</a> uh violence was committed against pagans  
<a onclick="modifyYTiframeseektime('765')">0:12:45</a> this state the christian state did  
<a onclick="modifyYTiframeseektime('766')">0:12:46</a> nothing  
<a onclick="modifyYTiframeseektime('767')">0:12:47</a> took no action against the attackers  
<a onclick="modifyYTiframeseektime('769')">0:12:49</a> they were allowed to get away with it  
<a onclick="modifyYTiframeseektime('772')">0:12:52</a> and so i guess in my view you have a  
<a onclick="modifyYTiframeseektime('773')">0:12:53</a> kind of really beginning of the  
<a onclick="modifyYTiframeseektime('775')">0:12:55</a> totalitarian catholic state  
<a onclick="modifyYTiframeseektime('777')">0:12:57</a> where one particular view reigns supreme  
<a onclick="modifyYTiframeseektime('780')">0:13:00</a> and i think we lose we have now lost  
<a onclick="modifyYTiframeseektime('784')">0:13:04</a> very clearly in this uh any sense of the  
<a onclick="modifyYTiframeseektime('787')">0:13:07</a> pure monotheism the tao heed  
<a onclick="modifyYTiframeseektime('790')">0:13:10</a> which is preached by moses all the  
<a onclick="modifyYTiframeseektime('793')">0:13:13</a> prophets in the jewish bible whether it  
<a onclick="modifyYTiframeseektime('795')">0:13:15</a> be  
<a onclick="modifyYTiframeseektime('795')">0:13:15</a> isaiah isaiah jeremiah micah  
<a onclick="modifyYTiframeseektime('798')">0:13:18</a> and so on all of those who are very  
<a onclick="modifyYTiframeseektime('801')">0:13:21</a> clearly  
<a onclick="modifyYTiframeseektime('802')">0:13:22</a> monotheistic jesus himself of course who  
<a onclick="modifyYTiframeseektime('805')">0:13:25</a> prayed to god and worshiped god here we  
<a onclick="modifyYTiframeseektime('807')">0:13:27</a> have  
<a onclick="modifyYTiframeseektime('808')">0:13:28</a> a a mutation we have a bidder we have an  
<a onclick="modifyYTiframeseektime('811')">0:13:31</a> innovation where two other entities  
<a onclick="modifyYTiframeseektime('814')">0:13:34</a> are now worshiped and glorified  
<a onclick="modifyYTiframeseektime('816')">0:13:36</a> alongside  
<a onclick="modifyYTiframeseektime('818')">0:13:38</a> the father this is not something that  
<a onclick="modifyYTiframeseektime('820')">0:13:40</a> jesus knew anything about it's not  
<a onclick="modifyYTiframeseektime('822')">0:13:42</a> something you'll find  
<a onclick="modifyYTiframeseektime('823')">0:13:43</a> in the bible taught in that way at all  
<a onclick="modifyYTiframeseektime('826')">0:13:46</a> um  
<a onclick="modifyYTiframeseektime('827')">0:13:47</a> the holy spirit is not defined as fully  
<a onclick="modifyYTiframeseektime('829')">0:13:49</a> god as the son is not defined as fully  
<a onclick="modifyYTiframeseektime('831')">0:13:51</a> god  
<a onclick="modifyYTiframeseektime('831')">0:13:51</a> in a trinitarian way uh with three  
<a onclick="modifyYTiframeseektime('834')">0:13:54</a> beings in one god  
<a onclick="modifyYTiframeseektime('835')">0:13:55</a> so this is uh this is a very uh  
<a onclick="modifyYTiframeseektime('839')">0:13:59</a> innovative revolutionary development  
<a onclick="modifyYTiframeseektime('842')">0:14:02</a> um proceeding from nicaea with the holy  
<a onclick="modifyYTiframeseektime('845')">0:14:05</a> spirit added on as  
<a onclick="modifyYTiframeseektime('847')">0:14:07</a> another person who is god  
<a onclick="modifyYTiframeseektime('851')">0:14:11</a> um so there we have it i i think um  
<a onclick="modifyYTiframeseektime('854')">0:14:14</a> i think if jesus uh had attended that  
<a onclick="modifyYTiframeseektime('857')">0:14:17</a> council  
<a onclick="modifyYTiframeseektime('858')">0:14:18</a> as an observer uh he would have been  
<a onclick="modifyYTiframeseektime('861')">0:14:21</a> horrified  
<a onclick="modifyYTiframeseektime('862')">0:14:22</a> he would have looked in disbelief at the  
<a onclick="modifyYTiframeseektime('865')">0:14:25</a> piety that he had as a jewish rabbi as a  
<a onclick="modifyYTiframeseektime('869')">0:14:29</a> prophet  
<a onclick="modifyYTiframeseektime('870')">0:14:30</a> had been so distorted and undermined  
<a onclick="modifyYTiframeseektime('873')">0:14:33</a> and betrayed by  
<a onclick="modifyYTiframeseektime('876')">0:14:36</a> gentiles centuries later who thought  
<a onclick="modifyYTiframeseektime('879')">0:14:39</a> they knew the mind of god  
<a onclick="modifyYTiframeseektime('882')">0:14:42</a> but i i think jesus would have uh would  
<a onclick="modifyYTiframeseektime('885')">0:14:45</a> have  
<a onclick="modifyYTiframeseektime('886')">0:14:46</a> jesus would have wept um that's just my  
<a onclick="modifyYTiframeseektime('889')">0:14:49</a> opinion  
<a onclick="modifyYTiframeseektime('889')">0:14:49</a> so until next time um i hope that was  
<a onclick="modifyYTiframeseektime('892')">0:14:52</a> not too confusing  

</details>
