#!/bin/bash

directories=(massari hijab sapience blogging_theology thought_adventure)
titles=("Video summaries generated by AI technology, plus Natural Language Processing (NLP) machine learning transcripts, of Prof. Dr. Muhammad Al-Massari" "Video summaries generated by AI technology, plus Natural Language Processing (NLP) machine learning transcripts, of Mohammed Hijab" "Video summaries generated by AI technology, plus Natural Language Processing (NLP) machine learning transcripts, of Hamza Tzortzis and other eminent speakers" "Video summaries generated by AI technology, plus Natural Language Processing (NLP) machine learning transcripts, of Paul Williams Blogging Theology podcast" "Video summaries generated by AI technology, plus Natural Language Processing (NLP) machine learning transcripts, of The Thought Adventure podcasts")

for i in "${!directories[@]}"; do
  dir=${directories[$i]}
  title=${titles[$i]}

  # Change into the directory
  cd "$dir"

  # Create the index.md file
  echo "# $title <br><br>" > README.md

  # Iterate over all .md files in the directory
  n=1
  for f in *.md; do
    # Skip the index.md file
    if [ "$f" != "README.md" ]; then
      # Get the first line of the file as the link text
      link_text=$(head -n 1 "$f")
      echo "$n. [$link_text]($dir/$f)" >> README.md
      n=$((n+1))
    fi
  done
  
  # lint recent files
  find . -name "*.md" -type f -mtime 1 -exec remark {} --use remark-preset-lint-consistent --use remark-preset-lint-recommended -o \;

  # Change back to the parent directory
  cd ..
done
